M7R0
I/ListOfMatrices7(7%7$7%"""""!F(X,%)anythingG6"6"[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F
(F(F(F(F(F(F(F(F(7$7%F(F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F(F(F(F(F(F(F(F
(F(7$7%F(F(F'X,F*6"F,[gl!"%!!!#1"%"%F(,$*$%"rG#!"$""#!""F(F(F(F(F(F(F(F(F(F(F(F
(F(F(7(7$7%F:F(F(X,F*6"F,[gl!"%!!!#1"%"%,$*(,&F7F:F9F'F',&F7F'F9F'F;F7F9#F'F:F(
F(,$**FD#F;F:,&F7F'!"#F'FEF7F9*$FDF;FEF8F(F(F(F(F(F(,$*$F7F9#F;""'F(,$FGFEF(F(,
$*&FDF;F7FJFN7$7%F'F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,$FM#F'FOF(F(FWF(F(F(
F(F(F(7$7%F'F(F'X,F*6"F,[gl!"%!!!#1"%"%F(,$FG#""$F:F(F(,$FGFHF(F(,$FRFXF(F(F(F(
F(F[oF(F(7$7%F(F:F(X,F*6"F,[gl!"%!!!#1"%"%,$FRFHF(F(FgnF(FLF(F(F(F(F(F(FjnF(F(,
$FBFX7$7%F(F'F'X,F*6"F,[gl!"%!!!#1"%"%F(F(FFF(F(F(F(F(FPF(F(,$FBFNF(F(FfoF(7$7%
F(F(F:X,F*6"F,[gl!"%!!!#1"%"%,$FMFHF(F(F(F(FQF(F(F(F(FaoF(F(F(F(F(7,7$7%FinF(F(
X,F*6"F,[gl!"%!!!#1"%"%,$***&FIF'F7F;FEFCF'FDF;F7!"%FHF(F(,$*,FKFEF7FdpFIFEFcpF
EFDFHFhnF(F(F(F(F(F(,$*&FcpFEF7Fdp#F'""%F(,$Ffp#F9FjpF(F(,$*(FDF;F7F9FcpFEFip7$
7%F:F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,$Fhp#F;FjpF(F(FcqF(F(F(F(F(F(7$7%F:
F(F'X,F*6"F,[gl!"%!!!#1"%"%F(,$FfpF8F(F(,$Ffp#FinFjpF(F(,$F^qFdqF(F(F(F(F(F\rF(
F(7$7%F'F:F(X,F*6"F,[gl!"%!!!#1"%"%,&**F7!"&,(*$F7F:F'F7F9F:F'F'FDF;FcpFHF'F^qF
EF(F(,&*,FDFHFIFhnF7FcrFKFEFcpFHFJFfpF8F(FgpF(F(F(F(F(F(,&FgrF'FfpF[rF(F(,&FbrF
HFbpFdq7$7%F'F'F'X,F*6"F,[gl!"%!!!#1"%"%F(F(,(FfpF:*$F7#!"*F:FNFgrF'F(F(F(F(F(,
&FgrFHFfpF;F(F(,(FbrFip**FDF;FIF'F7FdpFcpFEFipFbpFipF(F(FcsF(7$7%F'F(F:X,F*6"F,
[gl!"%!!!#1"%"%,*FdsFE**FDFHFIFEF7F`sFKFEFE**FDF;FIF:F7FcrFcpFHFEFhpFEF(F(,&Ffp
FH*&FDF;F7#!"(F:FNF(F]qF(F(F(F(,&FdsFHFbpFdqF(,$FgrFipF(F(F(7$7%F(FinF(X,F*6"F,
[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(7$7%F(F:F'X,F*6"F,[gl!"%!!!#1"%"
%F(,&FgrFEF_sFXF(F(,$FfpFdqF(F(,&FdsFdq**F7FdpFcpFE,&F7F'F;F'F'FDF;FipF(F(F(F(F
(,&F[tFdqFbrFipF(F(7$7%F(F'F:X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,&FdsFipF]uFdqF
(F(,&F[tFipFbrFdqF(F(F(F(F(F(7$7%F(F(FinX,F*6"F,[gl!"%!!!#1"%"%F(,&FfpFEF]tFXF(
F(F[uF(F(F(F(F(F(F(F(F(F(F(717$7%FjpF(F(X,F*6"F,[gl!"%!!!#1"%"%,(*(F7!"',(Fer""
)F7!#I"#FF'F'FDF;#F'Fdv*(FCF:FDFJF7Fbv#F'"#C*(FDFJFIF'F7Fbv#F9FdvF(F(,(*,FIFEF7
FbvFKFE,&F7FjpFasF'F'FDFHF\w*,FCF'FDF8F7FbvFIFEFKFE#F;Fdv**FDF8FIFEF7FcrFKFEFgv
F(F(F(F(F(F(,&*&F_wF'F7Fbv#F9"#S*$F7Fbv#F'"$?"F(,(F^w#""*FfwF`w#F'FfwFbw#F;FfwF
(F(,(*(F7FcrFDF;F_wF'FewF[wFew*&FDFJF7FdpFhw7$7%FinF'F(X,F*6"F,[gl!"%!!!#1"%"%F
(F(F(F(F(F(,&Fgw#F;FiwFdw#FinFfwF(F(FfxF(F(F(F(F(F(7$7%FinF(F'X,F*6"F,[gl!"%!!!
#1"%"%F(,(F^w#FinFdvF`wFgvFbwFawF(F(,(F`wF^xFbwF]xF^w#FasFfwF(F(,(F[wFhxFaxFgxF
`xFhxF(F(F(F(F(FayF(F(7$7%F:F:F(X,F*6"F,[gl!"%!!!#1"%"%,.*(F7Fbv,(FerFjpF7!#8"#
5F'F'FDF;Faw*(FCF'FDFJF7Fcr#F;"#7F[wF[r*(F7FbvFdrF'FDF;F;**F7FbvF^uF'F_wF'FDF;F
dqF`xFawF(F(,&**FDFHFIFhnF7FbvFKFE#"#BFdvF^w#""(FdvF(FcwF(F(F(F(,&*&FIF'F7FbvFh
xFgwFhwF(,&Faz#!#pFfwF^w#!#@FfwF(F(,.*(F7Fbv,(FerFinF7!")FjpF'F'FDF;FhxF[z#F;"#
gF[w#Fin"#?F^z#Fin""&*(F7Fbv,(FerFjpF7FiyF\xF'F'FDF;Fc[lFavFhx7$7%F:F'F'X,F*6"F
,[gl!"%!!!#1"%"%F(F(,,*,FKFEFIFEF^uF'F7FbvFDFHFawFaz#FiyFdv**FKFEFIFEF7FbvFDFHF
ip*&FcpFEF7#!#6F:FipF^wF\qF(F(F(F(F(,*F^\lFhxFaz#"#RFfwF^w#F\xFd[lF`\l#F;Fd[lF(
F(,6*(,(Ff[lF'FerF'F7FdpF'F7FbvFDF;FewF[wFewF[zFhw*(FDF;FIF:F7FbvF\wF^z#F9FjyFg
[lFew*&F7FcrFDF;Fhw**FIF'F7FbvFDF;F_wF'FewFavFew*(F7FbvFCF'FDF;FhwF(F(Fi\lF(7$7
%F:F(F:X,F*6"F,[gl!"%!!!#1"%"%,0*(,(FerFjpF7Fc\lFezF'F'F7FbvFDF;FawF`]lF\zF\]lF
;*,FKFEF7Fb\lFIFEFcpFEFDFHF\qF_]lFdqF[wF\wFdwFawF(F(,.*,,(F7!#;F]zF'FerFf[lF'FK
FEF7FbvFIFHFDFHFgvF`\lFgvFazFE*(FDF;F7F`sFcpFEFipF^wFgvFbwFgvF(F_xF(F(F(F(,,*(,
("#6F'FerFinF7!#7F'F7FbvFDF;FhxF`]lFa[lF\]lFe[lF_]lFc[lFavFhxF(,,*,,&FbvF'F7Ff[
lF'FIFEFKFEF7FbvFDFHFewFbwF^xFazF]]lF^wFewF`\lF^xF(F(,&*(,(FerF'F7F'FdpF'F'F7Fb
vFDF;FhxFaxFhw7$7%F'FinF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,&FgzFewFgwFgxF(F(F
]_lF(F(F(F(F(F(7$7%F'F:F'X,F*6"F,[gl!"%!!!#1"%"%F(,,F^\lFgvFaz#FcrFjpF`\lFdqFa
\lFdqF^wFawF(F(,*F^\lFewFazF[rF`\l#F'Fd[lF^wFhxF(F(,6Fj\lFhxF\]lF^yF^[lFewF^]lF
gxF[wFewF[zFhwF_]lFhx**F7FbvFIF'F^uF'FDF;F]]lF`]lFgxFg[lFewF(F(F(F(F(,6Fj\lFhxF
\]lF^yF`]lFgxF_]lFhxF^]lFgxF^[lFewF[wFewF[zFhwF^zF]]lFg[lFewF(F(7$7%F'F'F:X,F*6
"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,6F_^lFewF^]lFgxFj\lFhxF\]lF`yF[zFgxF[wFhxF_]lFew
Fg_l#FinFjyF`]lFhwFg[lFhxF(F(,6F_^lFewF`]lFhwF\]lF`yF_]lFewFj\lFhxF[zFgxF[wFhxF
^zF^`lFg[lFhxF^]lFgxF(F(F(F(F(F(7$7%F'F(FinX,F*6"F,[gl!"%!!!#1"%"%F(,.Fj]lFawF`
\lFawFazFHF]^lFdqF^wFawFbwFawF(F(,,Fj]lFhxFbwF]xFazF^`lF`\lF]xF^wFhxF(F(,&Fg^lF
ewFaxFgxF(F(F(F(F(Ff`lF(F(7$7%F(FjpF(X,F*6"F,[gl!"%!!!#1"%"%,(F^[lFgvF[wF\wFaxF
ivF(F(,(Faz#F_tFdvF`wFgvFbwFawF(FfzF(F(F(F(F(F(,(Faz#"#@FfwF`wF^xFbwF]xF(F(,(Fg
yFewFhvFhwF[wFew7$7%F(FinF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,(FazFdzF`wFawFbwFgvF(F(F
(F(F(,(F`wF]xFbwF^xFazF[[lF(F(,(F[wFhxFhvFgxFgyFhxF(F(FhalF(7$7%F(F:F:X,F*6"F,[
gl!"%!!!#1"%"%,0Fg^lFgvF^]l#F'F]zFh]lFipFj\lFipF\]lFipF[wF\wFgzFgvF(F(,0Fj]lFaw
F`\lFaw**FDF;FIF'F7Fb\lFcpFEFipF^\lFaw**F7Fb\lFcpFEF^uF'FDF;FdqFazFawF`wFgvF(,,
F_^lFhxF^]l#F'Fb[lFj\l#F9Fd[lF\]lFdblF^[lFhxF(F(F(F(FaalF(,,Fd^lFhxF`wF^xF^\lFh
xFazFhxF`\lF]xF(F(,&Ff]lFewFhvFhw7$7%F(F'FinX,F*6"F,[gl!"%!!!#1"%"%F(F(,0Fj]lFg
vF`\lFgvF`blFdqF^\lFgvFablFipFazFgvF`wFawF(F(F(F(F(,,Fd^lFewF`wF]xF^\lFewF`\lF^
xFazFewF(F(,&Ff]lFhxFhvFgxF(F(F]clF(7$7%F(F(FjpX,F*6"F,[gl!"%!!!#1"%"%,(F_^lFgv
FgwFivFh]lFipF(F(F(F(Ff^lF(F(F(F(FfblF(F(F(F(F(777$7%Ff[lF(F(X,F*6"F,[gl!"%!!!#
1"%"%,(**FcpFEF7F_t,(FerFd[lF7!#%)"#")F'F'FDF;Fh\l**FCF:FDFJF7F_tFcpFE#F;Fjy**F
DFJFIF'F7F_tFcpFE#F\xFjyF(F(,(*.FcpFEFIFEF7F_tFKFE,&F7Fjy!#FF'F'FDFHFc[l*.FCF'F
DF8F7F_tFKFEFIFEFcpFEF^`l*,FDF8FIFEF7FbvFKFEFcpFEF]]lF(F(F(F(F(F(,&*(FcpFEFcdlF
'F7F_t#F'"#I*&F7F_tFcpFEF^xF(,(FbdlF^dlFedlFewFfdlFhxF(F(,(**FDF;F7FbvFcdlF'Fcp
FEFidlF_dlF[x*(FDFJF7FcrFcpFEF^x7$7%FjpF'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,
&F[elF]xFhdl#F;FjdlF(F(FdelF(F(F(F(F(F(7$7%FjpF(F'X,F*6"F,[gl!"%!!!#1"%"%F(,(Fb
dlFdblFedlF]]lFfdlF^`lF(F(,(FedlFhxFfdlFewFbdl#F'FjyF(F(,(F_dlF`yF_elF]xF^elFee
lF(F(F(F(F(F]flF(F(7$7%FinF:F(X,F*6"F,[gl!"%!!!#1"%"%,8**F7F_tFcpFE,(FerFd[lF7!
#n"#`F'F'FDF;F]x*,FCF'FDFJF7F`[lFdrF'FcpFH#F'Ff[l**FDFJFIF:F7F`[lFcpFH#FbvFf[l*
*FcpFEFCF'FDFJF7FbvFhflF_dl#FasFf[l**F7F_tFcpFE,(FerFd[lF7Fjz"#bF'F'FDF;F]x**Fc
pFEF7F_t,(FerFd[lF7!#tFb[lF'F'FDF;F]x*,F7F_tFcpFEF^uF',&F7Ff[lFc\lF'F'FDF;Fhfl*
,FcpFEF7F_tF^uF',&F7Ff[lFb^lF'F'FDF;Fhfl*,FcpFEF7F_tF^uF'FcdlF'FDF;F\flF^elFe_l
F(F(,0*.F7F_tFcpFEFKFEFIFE,&F7"#NFbglF'F'FDFHF^x*.FDF8FIFEF7F`[lFKFEFdrF'FcpFHF
^`l*,FDF8F7F_tFIFhnFKFEFcpFHF\fl*.FDFHFIFEF7F_tFcpFEFKFEFdglF'#!#BFfw*.FcpFEFKF
EF7F_tFIFEFfglF'FDFHF_hlFbdl#F_tFd[l*.FCF'FDF8F7F`[lFIFhnFKFEFcpFHF]]lF(FgdlF(F
(F(F(,(*(F7F_tFcpFEFdglF'Feel*(FcpFEFfglF'F7F_tFa[lF[elF^xF(,0FiglFcblFchlFidlF
^hl#FczFb[lFahlFhhlFbdl#FezFjdlF]hl#F;"#:F\hlFe_lF(F(,8**F7F_tFcpFE,(FerF[ilF7!
#TFd[lF'F'FDF;Fa[lFiflF]]l**FDFJF7F_tFdrF'FcpFHFe_lF[glFe_lF_dl#FasFd[l**F7F_tF
cpFE,(FerF[ilF7!#V"#AF'F'FDF;Fa[l**FcpFEF7F_t,(FerF[ilF7!#YFjvF'F'FDF;Fa[l**F7F
_tFcpFE,(FerFf[lF7F\^lFa^lF'F'FDF;#FJF[il**FcpFEF7F_t,(FerFf[lF7!#<F]zF'F'FDF;F
[jl**FcpFEF7F_t,(FerFjyF7!#PFfvF'F'FDF;FjhlFiclFeel7$7%FinF'F'X,F*6"F,[gl!"%!!!
#1"%"%F(F(,@*.FIFhnFKFEFe^lF'FcpFHF7F`[lFDFHF]x*,F7F_tFKFEFIFEFcpFEFDFH#FcrFdv*
$F7#!#:F:Fhw*.F7F`[lFIFhnFKFE,&FasF'F7Ff[lF'FcpFHFDFHF]x*.FKFEFIFE,(F7F^jl"#9F'
FerFf[lF'FcpFHF7F`[lFDFHF]x*.FcpFEFIFEFKFEFe^lF'FDFHF7F_tF]xF^hl#"#8Ffw*,FKFEFc
pFHF7F`[lFIFhnFDFHFh\lFahlFc[m*&F_wF'F7F[[mFewFbdlF^`lFedlFhx*,FDF8FIFhnF7F_tFK
FEFcpFEF`yFchlFc[lF\hlF`yF(F(F(F(F(,<FgjlFa[lF][mFa[lFchlFa[lF\hlF]xF_[mFa[lFed
lFgxFg[mF]xFb[mFa[lF^hl#FiyFb[lFahlFi[mFhjlFXFbdl#F;Ff[lFe[mFidlF(F(,J**,*F7"#k
!#[F'*$F7FinFf[lFerFevF'F7F`[lFDF;FcpFHFcblF_dlFipF[glF^x**F7F`[l,*F7"#h!#UF'F`
\mFf[lFerFevF'FDF;FcpFHFcblFiflFe_lF`ilFgx**,*F7"#o!#_F'F`\mFf[lFer!#JF'F7F`[lF
DF;FcpFHFcbl**FDFJF7FbvFIF'FcpFEFgx**FcpFE,(FjdlF'FerFf[lF7!#AF'F7F_tFDF;Fcbl*,
FDF;FIF'F7F_tFcpFEFdglF'F^bl*,FcpFEFDF;FIF'F7F_tFfglF'F^blFiil#F'F[ilF\jlF`]m*(
FcpFEF7FbvFDF;F^xF_jlFidl**FdrF'F7F`[lFDF;FcpFHFa[l*,FcpFEFIF'F7F_tFDF;FcdlF'Fi
dl**F7F_tFDF;FIF'FcpFEFa[lFiclFidl**FcpFEF7F_tFCF'FDF;F^xF(F(,JF\\mFcblFd]mFgxF
a\mFcblFe]mF^xFe\mFcblF[]mFcblF^]mF^blFb]mFgxF_]mF^blFa]mF^xFc]mFidlF_dl#Fa^lFf
wFj\mFa[lFiilF`]mF\jlF`]mF_jlFidlFiflF\flF`ilFa[lFiclFidlF[glF^xF(7$7%FinF(F:X,
F*6"F,[gl!"%!!!#1"%"%,>**,*F`\mFd[lFer!#(*F7"$_"!#wF'F'F7F`[lFDF;FcpFHF]x*,FCF'
FDFJF7F_tFIF'FcpFEF\flF_dl#"#LFfwFe]mFhfl*&,&F`wF9FbwFinF'F7F8Fgx**,*F`\mFd[lFe
r!#**F7"$g"F[dlF'F'F7F`[lFDF;FcpFHF]x*,FCF'FDFJF7F`[lFIF:FcpFHF\fl**FcpFE,*F`\m
Fd[lFer!$B"F7"$E#!$E"F'F'FDFJF7F_tF]xF^]mFhfl*,FIFEF7F[[mFKFEF_wF'FDFHF[xF_]mFh
flFc]mF\flFiflF`yFhdlFe_lF(F(,<*.,(Fer"#DF7!#$)"#mF'F'FIFEFKFEF7F`[lFDFHFcpFHF^
xFg[mFewFfdl#Fc\lFfwFhjlF]]l*&,&F[wF\xFaxF;F'F7F8Fgx*.,(FerFe_mF7F[dlFg\mF'F'FI
FEFKFEF7F`[lFDFHFcpFHF^x*,FDF8FI#Ff[lF:F7F`[lFKFEFcpFHFew*.FcpFEFKFE,*!$;#F'Fer
!$m"F`\mFe_mF7"$S$F'FIFHF7F_tFDF8F^xF^hlF^dl*(F7#FiyF:FDF;F_wF'FewFahlF^dlFbdlF
h\lFedlFewF(F]elF(F(F(F(,4**,*F7"$!=F`\mF[ilFer!#"*!$;"F'F'F7F`[lFDF;FcpFHFa[lF
d]mFe_lFe]mFe_l**,*F7"$)=!$C"F'F`\mF[ilFer!#$*F'F7F`[lFDF;FcpFHFa[l**FcpFE,(Fei
lF'FerFf[lF7F]]mF'F7F_tFDF;Fh\lF^]mF[jlF_]mF[jlFc]mFjhlFiclFeelF(,:*.,&F7Fe_m!#
LF'F'FKFEFIFhnF7F`[lFDFHFcpFHFcbl*.,&F7Fe_m!#MF'F'FKFEFIFhnF7F`[lFDFHFcpFHFcblF
chlFhw*.FcpFEFIFEFKFE,(F7F[am"$3"F'FerFe_mF'FDF8F7F_tFcblFfdlFhxFg[mFe_lF^hlF`]
mFahlF`]mFbdlFidlF]`mFe_lF]hlFa[lFhjlFhxF(F(,,*,,(FerFf[lF7Fjp!#?F'F'FIF'F7F`[l
FDF;FcpFHFeelFiflF^x**FcpFE,*F7!#Q"#sF'F`\mFf[lFerFb^lF'FDFJF7F_tFa[lF_elF^xF_d
lFh\l7$7%F:FinF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,(FehlFidlF[elF]xFfhlFcblF(F
(FibmF(F(F(F(F(F(7$7%F:F:F'X,F*6"F,[gl!"%!!!#1"%"%F(,BFgjlF^xFhjl#Ff[lFdvFjjlFg
xF][mF^xF_[mF^xFb[mF^xF^hlFipFe[mFe_lFahlFipFf[mFhxFbdlFe_lFchlFhxF]`mF[xFiglF]
xF\hlFewF]hlF^dlF(F(,@FedlFgxFg[mF^x*.FDF8FIFEF7F_tFKFEFcpFEF^uF'F]xFgjlFcblF][
mFcblF_[mFcblF\hlF^dlF]hlF`]mFb[mFcblF^hlFNFahlFN*.F7F_tFcpFEFKFE,(FerF[hlF7!$V
""$Y"F'F'FDFHFIFHFa[lFhjlFNFe[mFeelFbdlFeelF(F(,PF_dlFipFj\mFhw**FDFJF7FbvFcpFE
F^uF'FgxF\\mFa[lFa\mFa[lFe\mFa[lFiflFhflF`ilFeelF[]mFa[lF^]mF\zF_]mF\zF]ilFcblF
a]mF]xFbilFcblFb]mFcblFfilFcblFd]mFcblF[glF^xFc]mFeelFiilF`]mFe]mF]xF\jlF`]mF_j
lFidlF(F(F(F(F(,NF\\mFa[lFd]mFhwFa\mFa[lFe]mF]xFe\mFa[lF[]mFa[lF^]mF\zFb]mFhwF_
]mF\zFa]mF]xFc]mFeel**FDFJFIF:F7F_tFcpFHFcblF]ilFcblF`ilFeelF_dlF[xF[glF^xFbilF
cblFiflFc[lFfilFcblFiilF`]mF\jlF`]mF_jlFidlF(F(7$7%F:F'F:X,F*6"F,[gl!"%!!!#1"%"
%F(F(F(F(F(F(,NFd]m#F;Fjv**F7F_tFcpFEF^uF'FDF;FhwFg`mFcblFa]mF]xF\amFcblF_dlFh_
mFj\mFcblFaamFe_lF\\mFa[lFa\mFa[lFe\mFa[lF[]mFa[lF^]mFe_lF_]mFe_lFiflF^dlF`ilFc
blF[glF]xFc]mFidlFiilFjhlFe]mF^xF\jlFjhlF_jlFeelF(F(,PFg`mFcblFd]mFa[lFe]mF^xF
\amFcblFaamFe_lF^]mFe_lF_]mFe_lFc]mFidl**FIF:F7F`[lFDF;FcpFHFa[lF\\mFa[lF_dlFdq
F[glF]xFa\mFa[lFiflFh\lF`ilFhwFe\mFa[lFj\mFhwF[]mFa[lFiilFjhlF\jlFjhlFa]mF]xF_j
lFeelFb]mFcblF(F(F(F(F(F(7$7%F:F(FinX,F*6"F,[gl!"%!!!#1"%"%F(,<Fc_mF]xFg[mFhxFf
dlFg]mFhjlF^`l*&,&F[wFasFaxF'F'F7F8FgxF[`mF]xF]`mFhxF_`mF]xF^hlF\flFd`mFhxFahlF
\flFbdlFe_lFedlFhxF(F(,:FedlFgxFc_mFa[lFfdlFewF[`mFa[lFg[mFh\lF_`mFa[lF]`mFh\lF
]hlFcblF^hlFjhlFhjlFewFahlFjhlFbdlFeelF(F(,*F_dlFhxF^bmFidlF_elF]xFabmFcblF(F(F
(F(F(,,F^bmFidlFiflF]xFabmFcblF_elF]xF_dlFe_lF(F(7$7%F'FjpF(X,F*6"F,[gl!"%!!!#1
"%"%,2*,F7F`[l,&F7F[ilFi\mF'F'FdrF'FDF;FcpFHFh\lFifl#FOFf[lF`ilFj[mF]ilF^xF_dlF
`dlF_elF^dlFbilF^xFfilF^xF(F(,4*.F7F`[lFKFEFcpFHFIFhnFDFHFcemF'F\flF\hlF]]lF]hl
F^`lFiglF]xFchlF^dlFfdlF^`lFedlF]]lF^hl#FezFfwFahlFgemF(FdhlF(F(F(F(F(F(,4FfemF
jhlFchlF`]mF\hlFh\lFiglFa[lF]hlFeelFfdlFewFedlFhxF^hl#F_tFb[lFahlFiemF(F(,2*.F7
F`[lFIF'FcemF'F^uF'FDF;FcpFHFidlFiflF^`lFgflFh\lFcflFcblF_dlF[xF]dlF^xF]glFcblF
`glFcbl7$7%F'FinF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,B*.FIFhnFKFE,&F`[lF'F7Ff[lF'FcpFH
F7F`[lFDFHF^xFe[mF]x*&FIF'F7F[[mFhxFjjlFhwF][mF^xF^hlF^xFg[mF[xFfdlF\wFfemFh\lF
]hlFdblF\hlFhxFiglF^xFchlF\flFedlF^`l*.F7F_tFcpFEFKFEFDFHFIFH,(FerFf[lF7F\[lFei
lF'F'#F_tFfw*.FcpFEF7F_tFKFEFDFHFIFH,(FerFf[lF7F]]mFjvF'F'FffmF(F(F(F(F(,<F\hlF
hxFchlFjhlFfemFidlFafmFcblF][mFcblF^hl#F:F[ilFfdlF^blFedlFewF]hlFcblFg[mF^xFhjl
Fa[lFiglFcblFahl#FezFb[lF(F(,>FiflFdqFgflFivF[fmFa[l**,*F7"#i!#WF'F`\mFf[lFerFe
vF'F7F`[lFDF;FcpFHFa[lFa\mFa[lF^]mFa[lF_dlFdqF]dlF]xFb^mFhwFd]mFa[lFcflFa[lF]gl
Fa[lF`glFa[lF`dmFcblF(F(,>F]gmFa[lFbdmFgxFa\mFa[lF^]mFa[lFb]mFhwFb^mFcblF_dlFh_
mF[fmFa[lFiflFj[mFgflFidlFcflFa[lF]dlF]xF]glFa[lF`glFa[lF(7$7%F'F:F:X,F*6"F,[gl
!"%!!!#1"%"%,V*,FKFEFIFEF^uF'F7F[[mFDFHFhxFfhlF^x**FDFHFIFhnF7F[[mFKFEF\qF[]mFh
\l**FKFEFIFEF7F[[mFDFHFh\lF^]mFew**FcpFEFDF;F7F_tFhfmF'F^xFj\mF^dlFa\mF^dlFb]mF
j[m**,*F`\mFf[lFerF`bmF7FjvF`[lF'F'F7F`[lFDF;FcpFHFh\l*,F7F`[lFDF;FIF:FcpFHFdgl
F'F^xFe\mFh\lFehlFh\lF_dl#F`alFd[lFa]mFj[mFa_mFewF\\mFh\lFiflF[rF]gmFh\lF_]mF^x
**,*F`\mFf[lFerF\[lF7"#GFb^lF'F'F7F`[lFDF;FcpFHFh\l**F7F`[l,*F`\mFf[lFerF`bmF7F
czFbvF'F'FDF;FcpFHFh\lFabmF^xFicmF^dlF^bmFh\lF(F(,hn*(F[]lF'F7F[[mFDF;FewF_`mF]
xF^hlFe_lF_[mFhxFfdlFhx*(FDF;FIF:F7F[[mF\wFahlF]xF[`mF]xFchlFh\lF\hlF`yFedlFbhl
Fe[mF^`l**F7F[[mFIF'F^uF'FDF;F^`lF][mFe_l*.F^uF'FKFEFIFhnF7F`[lFDFHFcpFHFE*&,&F
[wFasF[zF'F'F7F8FgxFc_mF]xFgjlFgem*(F7F[[mF_[lF'FDF;FhxFafmF]x*(F7F[[mFCF'FDF;F
hw*&F7Fe`mFDF;FhwF]`mFhxFhjlF^`lFg[mF\wFb[mF]xFacmF[x*(F7F[[mFh[lF'FDF;FhxF]hlF
]x**FIF'F7F[[mFDF;F_wF'FewF(,PFd]mFhwF`dmFgxFg`mFa[lFa]mFh\lF\amFa[lFiflFh\lFic
mFa[lFaamFh\lF\\mFidlFa\mFidlFe\mFidlF[]mFidlF^]mFidlFbdmFcblF_]mFidlFj\mFgxF_d
lF^xFgcmFhwF`ilFcblF]ilFa[lFbilFa[lFb]mFa[lFfilFa[lF(F(F(F(,@FbdmFhwF_dlF^`lFb^
mF^xFb]mFgxF]gmFidlFa\mFidlF^]mFidlFiflFc[lFgflF^xF]dlF^xFd]mFcblFcflFcblF]glFc
blF`glFcblF`dmFa[lF(,JFhhm#F;FinFgjlFiemF]`mF^xFchlFe_lFg[mF^xF_[mFh\lFedl#Fa^l
FiwFdamFa[lFgamFa[lF]hlFgxFjamFa[lFfdlFa[lFafmFa[lF][mFeel*.F7F`[lFIFhnFKFEFdgl
F'FDFHFcpFHFa[lFb[mFa[lF^hlFa[lFahlFa[lFe[mFeelFhjlFewF(F(,@*,,(FerFf[lF7Fc\lFO
F'F'FIF'F7F`[lFDF;FcpFHFidl*,,(FerFf[lF7!#5FjpF'F'FIF'F7F`[lFDF;FcpFHFidl*,F7F`
[l,(FerFf[lF7F[jmFinF'F'FIF'FcpFHFDF;FidlFicmFgxFgflF^xF`ilFhwF_dlFe_lFb^mF^xF]
^mFcblFg^mFcblFiflF]xF\_mFcblFj\mFa[lF]dlF^xFgcmFcbl7$7%F'F'FinX,F*6"F,[gl!"%!!
!#1"%"%F(F(,ZFehmFewF_`mF^xF^hlF^xF_[mF^xFfhmF[xFahlF^xFchlFe_lFedl#FezFd[l*.,*
F`\mFe_mFer!$M"F7"$O#!$O"F'F'FKFEFIFHF7F`[lFDFHFcpFHF^xFe[mF]]l*(F`^lF'F7F[[mFD
F;FhxFghmF]]lF][mF^xFhhmFdq*.,&F7F[il!#>F'F'FKFEFIFhnF7F`[lFDFHFcpFHF^xFgjlFewF
\imFgx*&,&F[wF\xF[zF;F'F7F8Fgx*.,*F`\mF'FerFcrF7FdvFdpF'F'FKFEFIFHF7F`[lFDFHFcp
FHFdqF]imFhwF]`mFewFhjlFbhlFg[mFe[lFb[mF^xFacmF`yF^imFewF_imFhx*.,*F`\mFe_mFer!
$L"F7"$K#!$K"F'F'FKFEFIFHF7F`[lFDFHFcpFHF^xF(F(F(F(F(,DFhhm#F'FinF]`mF]xFchlFh
\lFgjlFe_lF\hlF]xFjjmFcblFedl#Fc\lFiwFdamFcblFgamFcblFjamFcblFe[mF[gmFhjlF`]mF]
[mFcblF_[mFcblFb[mFcblF^hlFcblFahlFcblF(F(,<FgimFa[lFicmFhwFgflFcblFiimFa[lF_dl
Fh\lF\jmFa[lF`ilFgx*,,&F7F[ilF\^lF'F'FIF:F7F`[lFDF;FcpFHFa[lFb^mFidlF]^mFa[lF]d
lF]xFg^mFa[lF\_mFa[lF(F(,<Fj[nFa[lFb^mFivF_hmFa[lFiimFa[lF\jmFa[lF]^mFa[lFg^mFa
[lFiflF^xF\_mFa[lFj\mFcblF]dlF]xFgcmFa[lFgflFhwF(7$7%F'F(FjpX,F*6"F,[gl!"%!!!#1
"%"%,>Fj[nF^xF_dlF]]lFd]mF^dl*,F[^lF'FKFEF7F[[mFIFHFDFHFew**FDF8FIFEF7Fe`mFKFEF
^x**,*F`\mF[ilFerFa^mF7"$C"!#kF'F'F7F`[lFDF;FcpFHF^xFbdmF^dlFg`mF^xF[elF^dlFhgm
F]]lFigmF^xF\amF^xFa_mFewFaamFewF(F(,,FjjmF]xFfdlF]xFhjlFhx*(Fh^lF'F7F[[mFDF;Fh
x*&FDFJF7Fb\lFhwF(,*F_dlFewF^bmFeelF_elF^xFabmFa[lF(F(F(F(,.Fj[nFidlFb^mFh\lF]^
mFcblF]dlF^xFg^mFcblF\_mFcblF(,(*.,*F`\mF[ilFer!#zF7"$O"Fa^mF'F'FKFEFIFHF7F`[lF
DFHFcpFHFa[lFe[mFgxFfdlFa[lF(F(F(7$7%F(Ff[lF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F
(F(F(F(F(F(F(F(F(F(F(7$7%F(FjpF'X,F*6"F,[gl!"%!!!#1"%"%F(,6FafmF]xFe[mF^xFcfmFe
wFjjlFgxF][mF]xFeimF]xF]hlFewF]`mF`y*.F7F`[lFKFEFcpFHFDFHFIFE,(FerF[ilF7!#hF_gm
F'F'Fh\lF\hlF[xF(F(,2FafmFa[lFfdlFhwFg[mF]xF][mFa[lFacmF^xF^hlFa[lFhjlFcbl*.FKF
EF7F_tFDFHFIFEFcpFEFcemF'FidlF(F(,4F]gmFcblF_dlF^xFb^mFgxFa\mFcbl*,FCF'FDFJF7F_
tFcpFEF^uF'FhwF^]mFcblFd]mFcbl**F7F_tFcpFE,(FerF[ilF7Fhil"#JF'F'FDF;Fa[lF`dmFa[
lF(F(F(F(F(,4F]gmFcblFbdmFhwFa\mFcblF]hmFcblFb]mFgxFiflFh\lF[_mFa[l**F7F`[l,*Fe
rFa^mF7"$B"!#iF'F`\mF[ilF'FDF;FcpFHFa[lFgflFcblF(F(7$7%F(FinF:X,F*6"F,[gl!"%!!!
#1"%"%F(F(F(F(F(F(,4F]gmFa[lF_dlF]xFb^mFhwFa\mFa[lFa^nFgxF^]mFa[lFd]mFa[lFb^nFc
blF`dmFcblF(F(,4FbdmFgxFiflFe_lF[_mFcblFb]mFhwF]gmFa[lFa\mFa[lF]hmFa[lFgflFa[lF
f^nFcblF(F(F(F(F(F(7$7%F(F:FinX,F*6"F,[gl!"%!!!#1"%"%F(,F*.,(FerF[ilF7!#\"#QF'F
'FIFEFKFEF7F`[lFDFHFcpFHF]xFhjlF^xFe[mFhxFijmFewF]imFa[lFehmFc[lFfhmFc[lF]`mF`y
*.FKFE,*FerFddlF7"#[!#GF'F`\mFf[lF'FcpFHF7F`[lFDFHFIFHFh\lFgjlFh\l*.F[^lF'FIFEF
KFEF7F`[lFDFHFcpFHFh\lFafmF^xF]hlF^xF[imFewF][mF^xF\hlF[xF^hlF^xFfdlFewF(F(,8Fj
jmFa[lFfdlF]x*.,&F_tF'F7Ff[lF'FKFEFIFhnFcpFHFDFHF7F`[lFidlFgjlF`]mFg[mF]xFacmF^
xFe[mF^dlFafmFcblFhjlF]xF][mFcblF^hlFcblF(F(,4Fj[nFcblF_dlF^xFj\mFcblF_hmFa[lFg
cmFa[lF[hmFa[lFb^mFgxFbhmFa[lFa^nFhwF(F(F(F(F(,4*,,(FerF[ilF7Fhil"#KF'F'FIF'F7F
`[lFDF;FcpFHFcblF[_mFa[lF_hmFa[lFiimFa[lF\jmFa[lFicmFhwFgflFcblF`ilFgxF_dlFh\lF
(F(7$7%F(F'FjpX,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,4Fj[nFa[lF_dlF]xFj\mFa[lF_hmF
cblFgcmFcblF[hmFcblFb^mFhwFbhmFcblFa^nFgxF(F(,4Fc`nFa[lF[_mFcblF_hmFcblFicmFgxF
gflFa[lFiimFcblF_dlFe_lF\jmFcblF`ilFhwF(F(F(F(F(F(7$7%F(F(Ff[lX,F*6"F,[gl!"%!!!
#1"%"%F(,,FjjmF^xFfdlF^xFhjlFewFi\nFewFj\nFgxF(F(,(FjjmFcblFhjlFhwFfdlFcblF(F(F
(F(F(F(F(F(F(F(F(7>7$7%FOF(F(X,F*6"F,[gl!"%!!!#1"%"%,0*(F7Fas,*F`\mFiwFer!$=)F7
"%n<!%:7F'F'FDF;Fhw**FCF'FDFJF7FasFcvF'#Fez"$S#**FDFJFIF'F7FasF_wF'#F\[l"#!)**F
IF'F7FasFCF:FDFJFe_l*(FDFJF7FasFIF:Fail**,&F[wFasFhvF'F'FCF'FDF;F7F9#F'"$?(*,,&
FbwF9F`wFinF'FDFHFIFEF7F9FKFE#F;F_bnF(F(,2*,FIFEF7FasFKFE,(FerFb[lF7!$>$"$0%F'F
'FDFHF^x*,FDF8FIFEF7FasFKFEFcvF'#F;Fbbn*,FDF8FIFEF7F`[lFKFEF_wF'#FezFbbn*,FIFhn
F7FasFCF'FDF8FKFEFdbl**FKFEFIFhnF7F`[lFDF8Fc[l*.FCF'FDF8F7FasFIFEFKFEF_wF'Few**
Ff^mF'FCF'FDF;F7F9Fgbn*,FidmF'FDFHFIFEF7F9FKFEF[cnF(F(F(F(F(F(,**&F7FasF^cnF'#F
;"$o"*&F7FasF_wF'#Fd[m"%!o"*&FIF'F7Fas#F'"#c*$F7Fas#F;"%S]F(,2F]cnFbdnFgcn#Fin"
$g&Fccn#FiyFidnFecn#FinFcdnFfcn#F9FcdnFacnFbdn*,FfbnF'FDFHFIFEF7F9FKFE#F'F`dn*(
FjbnF'FDF;F7FJFednF(F(,0*(F7F`[lFDF;F^cnF'F\dnF`bn#!#RFidn*(FDFJF7F_tF_wF'F_dnF
dbn#FasFcdn*(FDFJF7F_tFIF'Fbdn*,Ff^mF'FDFHFIFEF7F9FKFEF^en*(FidmF'FDF;F7FJFedn7
$7%Ff[lF'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,*F^dn#FiyF`dnFddn#F'FfdnFadn#F;F
cdnF[dn#F'F]dnF(F(F]fnF(F(F(F(F(F(7$7%Ff[lF(F'X,F*6"F,[gl!"%!!!#1"%"%F(,2F]cnF]
xFacn#F'FbbnFccn#F_tFbbnFecnFc[lFfcnFdblFgcnFhx**FjbnF'FCF'FDF;F7F9Fgbn*,Fj_mF'
FDFHFIFEF7F9FKFEF[cnF(F(,2FacnF`fnFccn#Fd[mFidnF]en#F;F`dnF_enF_fnFecnF\enFfcnF
[enFgcn#F9FidnF]cnF`fnF(F(,0F`bn#Ff\lFidnFdenF^fnFgenF]gnFhenF_fnFdbn#F\xFcdnFf
enF`fnFaenFafnF(F(F(F(F(,0FaenFafnF`bnF`gnFdenF^fnFdbnFagnFfenF`fnFibnF^en*(Fj_
mF'FDF;F7FJFednF(F(7$7%FjpF:F(X,F*6"F,[gl!"%!!!#1"%"%,N**F7FasFIF',(FerFb[lF7Fa
`m"$z"F'F'FDF;Fgx**FCF'FDFJF7FasFhyF'#F_tF_bnFdbn#"$H$Fbbn**FCF'FDFJF7FasFdrF'#
FiyFjdl*(F7F`[lFcvF'FDFJF]hnF`bnFdz*(FfbnF'FDF;F7FJ#F;FhbnFibn#F'F_bn**F7FasFIF
',(FerFiwF7!$W%"$r$F'F'FDF;F[cn*(F7Fas,*F`\mFiwFer!$/(F7"%E8!$&zF'F'FDF;F[cn*,F
CF'FDFJF7FasF^uF'F_wF'#F_tFiw**FIF'F7F`[lFCF'FDFJF^dl**F7FasFIF',(FerFiwF7!$e%"
$&QF'F'FDF;F[cn*(F7Fas,*F`\mFiwFer!$=(F7"%q8!$D)F'F'FDF;F[cn*(F7Fas,*F`\mFiwFer
!$Y(F7"%l9!$+*F'F'FDF;F[cn**F7F`[lFDFJF_wF'FCF'F]hn**F^[nF'FCF'FDF;F7F9#F'"$g$*
,F7FasFIF'F^uF',&F7Fjdl!#xF'F'FDF;Feel**F7FasF^uF',(FerFjdlF7!$U""$l"F'F'FDF;Fe
el**F7FasF^uF',(FerFjdlF7!$\"Fi`mF'F'FDF;Feel**F7FasF^uF'F^cnF'FDF;Fa[lFaenFgxF
(F(,J*,F7FasFIFhnFKFE,&F7"$0"!$W#F'F'FDFHFhw*,FDF8FIFEF7FasFKFEFhyF'FgfnFfcn#!#
rF_bn*,FKFEF7FasFIFEFDF8FdrF'FH*(Ff^mF'FDF;F7FJFdhnFicnFehn*,F7FasFIFhnFKFE,&F7
FjdlFbglF'F'FDFHF^bn*,FIFEF7FasFKFE,(Fer"#qF7!$A$"$l$F'F'FDFHFgfn*.FDF8FIFEF7Fa
sFKFEF^uF'F_wF'F]xFccnFa[l*,F7FasFIFhnFKFEFejnF'FDFH#FczF_bn*,FIFEF7FasFKFEFhjn
F'FDFHFb\o*,FIFEF7FasFKFEF\[oF'FDFHFb\oFecn#Fd^nFfw*,FDF8FIFEF7FasFKFEF_[lF'Few
*,F^[nF'FDFHFIFEF7F9FKFEFgxF]cn#FezFiwFgcn#Fd[mFbbn*,FDF8FIFEF7FasFKFEFh[lF'Fdb
lFacn#F;"#;F(FjcnF(F(F(F(,0*(F7FasFIF',&F7F[ilFcbmF'F'FafnFadn#"#<F`dn*(F7FasFI
F'FejnF'Fafn*&F7FasFhjnF'FafnFddn#F;"%?D*&F7FasF\[oF'#F'"$O$F^dnF_dnF(,JF`[oF\d
nFecn#FasFbbnFf\oFhdnFg[oF^dlFacnFbcnFgcnFhdnF]enF]gnFifnF_fnFi[o#F;F[`nF[\o#F;
"$7"Fj\o#Fin"$!GFa\o#F`hlFh]oFc\oF`^oFd\oF`^oFd[oF`fnFfcn#Ff[lFjvFg\o#F'"$S)F]c
nF_dmF`\o#F;FahmFccn#F'"#UF(F(,N**F7FasFIF',(Fer"#XF7Fc[n"#lF'F'FDF;FafnFdbn#"$
>(Fidn*(FDFJF7F`[lF_[lF'F^fn*(FDFJF7F`[lFdrF'F[jlF`bn#Fd[mFcdnF`jnF^fnFgenF]gn*
*FidmF'FCF'FDF;F7F9F_fn**F7FasFIF',(Fer"#!*F7!$x#"$S"F'F'FDF;Fg]o*(F7Fas,*F`\mF
d_oFer!$s%F7"$N(!$+$F'F'FDF;Fg]o*(FDFJF7F`[lFh[lF'#FiyFc^oFainFd^o**F7FasFIF',(
FerFd_oF7!$"H"$a"F'F'FDF;Fg]o*(F7Fas,*F`\mFd_oFer!$'[F7"$z(!$I$F'F'FDF;Fg]o*(F7
Fas,*F`\mFd_oFer!$2&F7"$Q)!$g$F'F'FDF;Fg]oFbhnF^fn*(F^[nF'FDF;F7FJFd]o**F7FasFI
F',(FerFjdlF7!$2""#xF'F'FDF;Fe^o*(F7Fas,*F`\mFjdlFer!$s"F7"$2$!$l"F'F'FDF;Fe^o*
(F7Fas,*F`\mFjdlFer!$z"F7F_hn!$!=F'F'FDF;Fe^o*(F7Fas,*F`\mFb[lFer!$z$F7"$C(!$0%
F'F'FDF;#F'"#%)FhanFafn7$7%FjpF'F'X,F*6"F,[gl!"%!!!#1"%"%F(F(,hn**F7F`[lFDF8FIF
EFKFEF[cnFd\o#FiyF_bnFgcn#Fc\lFbbnF]cnFh\l*,F7FasFKFEFIFE,(FerFjyF7F_ilFf^oF'F'
FDFHFbcn*(FcpFEFcdlF'F7#F^jlF:Fidl*,FDF8FIFhnF7FasFKFEF_wF'Fhx**F7FasFDFHFIFhnF
KFE#"$@"F_bnFc\oFgbo*&F7F\coFcpFEF^xFg[oFg\l*,FIFEFKFE,(F7!$<""$5"F'FerFjdlF'F7
FasFDFHF[cn*,FKFEFIFEF7FasFDF8FCF'Fehn*,F7FasFKFEFIFhn,&F\[nF'F7FjyF'FDFHFbcn*,
FKFE,*Fer!#eF7"$6"!#qF'F`\mFjyF'F7FasFDFHFIFHFbcn*,FIFEFKFE,(F7F_aoFd_oF'FerFjd
lF'F7FasFDFHFgx*,F7FasFKFEFIFE,(F7!$G""$N"F'FerFjdlF'FDFHF[cn**FIFEFKFEFDFHF7Fa
sFgx*.FCF'FDF8F7FasFKFEFIFEF^uF'F^x*,F_wF'F7FasFDFHFIFEFKFE#FinF\]o*,FjhmF'FDFH
FIFEF7F9FKFEF[cnFa\oFgbo**FDF8FIF^`mF7FasFKFEF_al*,FIFEFKFE,(F7!#bF[`nF'FerF[il
F'F7FasFDFHFgx*,FIFEFKFE,(F7!#N"#HF'FerFjyF'F7FasFDFHFbcnFj\oFhxFacn#F'F\]oFecn
#F\[nFfw*,FDF8FIFEF7FasFKFEF[]lF'Fhx*,F7FasFKFEFIFEF^uF'FDFHFehnF(F(F(F(F(,ZFd
\o#Fd[mFh]oFgcn#F;Ff_oF]cn#F'FahmFibo#F'F]^oF]coF^gnF^co#FcrF`alFc\oFfeoFg[oFew
FbcoFg]oFgcoFieoFicoFieoF^doFafnF`doFg]oFddoFb^oFedo#F'FidnFifnFednFfdo#FasFf_o
Fa\oFfeoFido#FasF]^oFjdoFafn*&Ff^mF'F7F9F_fnF]eoFieoFj\oF^gnFacnFgfnFecn#"#VFid
nF]enF^enFceoF^gnFdeoF\dnF(F(,fp**F_wF'F7FasFCF'FDF;F[fo*(F7Fas,*F7"$F%!$:$F'F`
\mFjdlFer!$&>F'FDF;#F;Fh]o**FDFJF7F`[lFIF'F_wF'F[fo*(FdrF'FDF;F7FasFiv*(,*F7"$5
#!$i"F'F`\mF[ilFer!#&*F'FDF;F7FasF\dn*(F7FasFDF;FIF:#F'F`al**F7FasFIF'F_wF'FDF;
FafnF`bn#F9F[hl*(FDFJF7F`[lF[]lF'F[fo*(F7FasF[]lF'FDF;Fafn**FDFJFIF'F7FasF^uF'F
^gnF]ao#F;F`bo*(F7FasFcvF'FDF;Fafn**FIF'F7FasFDF;F\[oF'#FcrFh]oFfaoFggo*(F7Fas,
*F7"$2%!$%HF'F`\mFjdlFer!$!>F'FDF;FhfoF\`oF[fo**FIF'F7FasFDF;F^cnF'F\dn**F7FasF
IF:FDF;FejnF'FjgoFjaoF\dnFhanF\dn**FIF'F7FasFDF;FhjnF'Fjgo*(,*F7"$[%F[aoF'F`\mF
jdlFerFgfoF'F7FasFDF;Fhfo*&FjhmF'F7F9Fedn*(,*F7"$x%!$!RF'F`\mFjdlFer!$-#F'F7Fas
FDF;FhfoFainFbdn*(FIF'F7F`[lFDF;Fbdn**FIF'F7FasFCF'FDF;Fbdn*(F_wF'F7F`[lFDF;F_d
n*(F7FasFCF'FDF;Fedn*(,*F7Feho!$_$F'F`\mFjdlFer!$(>F'FDF;F7FasFhfo*(F7FasFh[lF'
FDF;Fafn*(FDFJF7F`[lFIF:#FinF]^oFa_oFedn*&Fj_mF'F7F9F_fnFdbn#!$>#FidnF__oF]xF`j
nFafn*(F7Fas,*F7"$?&!$]%F'F`\mFjdlFer!$4#F'FDF;Fhfo*(F7Fas,*F7"$)Q!$w#F'F`\mFjd
lFer!$&=F'FDF;FhfoFbhnF[fo*(,*F7"$+%!$.$F'F`\mFjdlFerFcjoF'FDF;F7FasFhfo*&F7F`[
lFDF;FednFgenF^enFaaoFggoF(F(,fpFbfoFafnFcfoFhfoFifoFafnFjfoF]xF[goF\dnF`goFfio
FbgoF[foF`bn#FjzFidnFdgoFafnFegoF[foFfgoF`fnF]aoFggoFhgoF[foFigoFjgoFfaoFggoF[h
oFhfo*(FDFJFIF'F7Fas#F'F_^oF\`oFafnF`hoF\dn*(FjhmF'FDF;F7FJFednFahoFjgoFjaoF\dn
FhanF\dnFbhoFjgoFchoFhfo*(F7F`[lFCF'FDFJFednFghoFhfoFainFbdnF\ioFbdnF]ioFbdnF^i
oF_dnF_ioFedn*&F7F_tFDFJFednF`ioFhfoFdioF[foFeioFagoFdbn#Fi\mFcdnF__oFivF`jnF[f
oFjioFhfoF_joFhfoFbhnFafnFdjoFhfoFhjoFednFaaoFggoF(7$7%FjpF(F:X,F*6"F,[gl!"%!!!
#1"%"%,fnFbfoF]hn*(F7Fas,,Fer"%2KF7!%KT"%!*=F'*$F7FjpFiwF`\m!%Y5F'FDFJF[cn*.Fcp
FEFIFEF7F\coFKFEFcdlF'FDFHF^dl**FDF9FIF'F7FasFCF'FbcnF`bnFffmFhgoF]hn*(FDF9FIF'
F7F`[lFgfn*(,,Fer"%)*HF7!%$z$"%5<F'F[\pFiwF`\m!%/5F'FDFJF7FasF[cn*&FfbnF'F7F9Fd
hnFigoFeel*,FCF'FDFJF7FasFIF'F_wF'F`inF[[pFgfnF`hoFa[lFahoFeelFbhoFeel*(,,Fer"%
)4$F7!%FSFj[pF'F[\pFiwF`\m!%=5F'FDFJF7FasF[cnF]ioF^dl*(F7FasFCF:FDFJ#F;Fcjn*(,*
F`\mFb[lFer!$1$F7"$-&!$j#F'F'FDF;F7FasFgx**FCF'FDFJF7FasFg]lF'F]hn**FDFJFIF'F7F
asFe^lF'Fhx**FIF:F7FasFCF'FDFJFahn*&,&FedlF\xFfdlFasF'F7F8FgxFdbnFhfl*(FDFJF7Fa
sF[^lF'Fgfn*(,,Fer"%8HF7!%)o$F`dnF'F[\pFiwF`\m!$%)*F'FDFJF7FasF[cnF[dnFgx*(,,Fe
r"%6IF7!%7R"%[=F'F`\m!$)**F[\pFiwF'FDFJF7FasF[cnFgenFehnF(F(,fn*,FIFEFKFE,*Fer!
%05F7"%W@!%_9F'F`\m"$]"F'FDF8F7FasFehn**FD#FcrF:FIFEF7F_tFKFEF[cn*,FIFEFKFE,*Fe
rFd^pF7"%4@!%59F'F`\mF[_pF'FDF8F7FasFehnFd\oFcblFgcnF]x*,FDF]_pFIFEF7F`[lFKFEFC
F'Fehn*,FDF8FIFEF7FasFKFEFh^lF'Few*,FDF8FIFEF7FasFKFEFg]lF'Fgfn*,FDF8F7F`[lF[^l
F'FKFEFIFHF[cnF]cnFhwF]coF]xF^coFc[lFc\oFcblFjfnFehnFfcnF^bl*.F[^lF'FKFEF7FasFI
FHFDF8FCF'F]xFfcoFehn*,FIFEFKFE,*Fer!%J5F7"%8A!%&["F'F`\mF[_pF'FDF8F7FasFehn*,F
IFEFKFE,*Fer!%Q5F7"%\A!%I:F'F`\mF[_pF'FDF8F7FasFehn*,FIFEF7FasFKFE,*Fer!%(3"F7"
%'R#!%?;F'F`\mF[_pF'FDF8Fehn**FDF;F7F[[mFcdlF'FcpFEFidl*,,*F`\mF[_pFer!$O)F7"%B
:!$-*F'F'FKFEFIFHF7FasFDFHFehnFfdoFdcnFa\oFcblFido#F:Ff[l*&,&F_dlFddlF_elFinF'F
7F8FgxF^foFdhnFccnF^blFecnFc[lF(,0F`bnFbenFdenF_dnFibnF]gnFcgnF_fnFdbnFeenFfenF
bdnFaenF\dnF(F(F(F(,F*(,*!$*QF'F7"$#eF`\mFj^oFer!$$GF'FDF;F7FasFafn*(F7FasF`^lF
'FDF;F^fnF`goF[jlFbfoF^fnF_ioF^en*(,*F7"%37!$C)F'F`\mFd_oFer!$x&F'FDF;F7FasFg]o
*(,*F7"%h7!$q)F'F`\mFd_oFer!$#fF'FDF;F7FasFg]oFbgoF]`oF]ioFd^o*(,*F7"%k7!$!))F'
F`\mFd_oFer!$"fF'FDF;F7FasFg]o*(,*F7"%>8!$I*F'F`\mFd_oFer!$1'F'FDF;F7FasFg]o*(F
7Fas,*F7"$k%Ff`oF'F`\mFjdlFerF^joF'FDF;FieoFhgoF^fnFahoFe^oFbhoFe^oFigoFe^oF`ho
F_boFhanFafnF(,XFf^pFhfo**FDF]_pFIFhnF7FasFKFEF^gnF\_pF^enFfboF^enF^_pFhfoFd\oF
ggoFgcn#F;FidnFc_pFhdnFd_pF`fnF]cnF\dn*,Fe^lF'FIFEFKFEF7F`[lFDF8FafnF]coFd^oF^c
oF\enFc\oFggoFfcnFggoFfco#F;Fc^o*.FCF'FDF8F7FasFe^lF'FIFEFKFEF`cpFg_pFhfoF\`pFh
foFa`pFhfoFg`pFhfoFfdoFjdnFa\oFggoFidoFdqFh[oF_fnFccn#!#HF`dnFecnF^xF(F(,@*(,*F
`\mF[ilFerF`hlF7!#!)"$E"F'F'FDF;F7FasFafnFe]pFhdn*(FDFJF7F`[lFh^lF'F^fn*(,,Fer!
#EF7"$g(!$#zF'F[\pFjdlF`\m!$P"F'FDFJF7FasFafnFdbnFhfl*(,,FerFcenF7"$g)F_jnF'F[
\pFjdlF`\mFijnF'FDFJF7FasFafnFcgnF_fnF`bnF\gn*(F7Fas,,Fer!#mF7"%M5!%!3"F'F[\pFj
dlF`\mF][oF'FDFJFg]oFi]pFbdnF[[pF[foFdenF_dnFfenFbdnF_\pF[fo*&FDF9F7FbvFedn7$7%
FinFinF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,0Fadn#F^jlF`dnFddn#F'Fe]oF^]oF\dnF^
dnF^fnFb]oF\dnFc]oF\dnFf]oFhfoF(F(F_epF(F(F(F(F(F(7$7%FinF:F'X,F*6"F,[gl!"%!!!#
1"%"%F(,joF`[oFgxF`\oF^xFfboFehnFd\oF_dmFgcnF^xF]cnFgxFiboFgfnF[coFeelF]coFewF^
co#!$@"F_bnFc\oF_dmF[\oFbcnFacoF]xFi[oF]hnFjfnFehnFf\oFhxFd[oFbcnFg[oFe_lFfcn#"
#rF_bnFbcoFehnFfcoF[cnFgcoFgfnFicoFgfnF^doFhwF`doFehnFddoFhwFedoF]xFfdo#F9F\]oF
hdoF[cnFa\oF_dmFidoF[[lFjdoFhwF_enFdhnF]eoFgfnFj\oFhxFccnFcblFecnF]]lFceoFewFde
oF[cnF(F(,boFg\oFbcpF`\oFheoFd\o#Ff[lF]dnFgcnF[foF]cnFafn*,FKFEF7FasFIFhnFDF8F^
uF'FewFiboF\^oF]coFhdnF^co#Ff[lF`alFc\oF]fpFf\oF^gnFd[oFbdnFg[oFipFfcn#FcrFjvFb
coFhfo*,F7FasFIFEFKFE,(FerFjdlF7Fc[nFecmF'F'FDFH#F'F[`nFgcoF\^oFicoF\^oF^doF\dn
F`doFhfoFddoFbcp*,FIFHF7FasFKFE,*F`\mF]\oFer!$i%F7"%45!$I(F'F'FDFHFieoFedoF`cpF
fdo#F\xFf_oFa\oF]fpFido#F\xF]^oFjdoF\dnF^foFedn*,F7FasFIFEFKFE,(FerFb[oF7!$a%"$
)[F'F'FDFHFafnF]eoF\^oFj\oF^gnFccn#F;Ff^oFecnFheoFceoFhdnFdeoFafnF(F(,bqFbfoF`c
pFcfoFg]oFifoF`cpFjfoF_dmF[goFafnF`go#F;F`alFbgoF\dnF`bn#F_ilF_^oFdgoF`cpFegoF
\dnFfgoFhdnF]aoFggoFhgoF\dnFigo#Ff[lFh]oFfaoFggoF[hoFg]o**FDFJF7F`[lFIF'F^uF'F]
xF\`o#FczF`dnF`hoFafnFahoFcgpFjaoF\dnFbhoFcgpFchoFg]oFfhoF_fnFghoFg]oFainFbdnFg
_oFhfoF\ioF`fnF]ioF`fnF^ioF^fnF_ioF_fnF\aoFaepF`ioFg]oF^_oF_dnFdioF\dnFeio#F9F]
^oFb_oFhfoFb`oFhfoFg`oFhfoF^`oFhfoFgioFednFdbn#!#DFahmF__oF^blF`jnF[foFjioFg]oF
_joFg]oFbhnFafnFdjoFg]oFhjoF_fnFaaoFggoFh^oF\dnF(F(F(F(F(,fqFbfoF\dnFcfoFg]oFif
oF\dnFjfoF^xF[goFafnF`goFfgpFbgoF`cpF`bn#F]^nFidnFdgoF\dnFegoF`cpFfgoFbdnF]aoFg
goFhgoF`cpFigoFcgpFfaoFggoF[hoFg]oF[[p#F;F_^oF\`o#F'Fb[oF`hoFafnF][pFednFahoFcg
pFjaoF\dnFbhoFcgpFchoFg]oF^[pF_fnFghoFg]oFainFbdnFg_oFhfoF\ioF`fnF]ioF`fnF^ioF^
fnF_ioF_fnF_[pF_fnF`ioFg]oF^_oF_dnFdioF`cpFeioFagp**Fj_mF'FCF'FDF;F7F9F_fnFb_oF
hfoFb`oFhfoFg`oFhfoF^`oFhfoFdbn#!$4%FidnF__oFdimF`jnFafnFjioFg]oF_joFg]oFbhnF[f
oFdjoFg]oFhjoF_fnFibnF]gnFaaoFggoFh^oF\dnF(F(7$7%FinF'F:X,F*6"F,[gl!"%!!!#1"%"%
F(F(F(F(F(F(,bqFbfoF[foFcfoFg]oFifoF\dnF[goFafnF`go#F[hnF`dnFbgoFegpF`bn#"#pFid
nFdgoF\dnFegoF`cpFfgoFbdnF]aoF_boFhgoFafnF[cpF\^oFigoF\^oFfaoF_boF[hoFg]oF[[pF[
hpF\`oF\dnF`hoF\dnF][pF_fnFahoF\^oFjaoFafnFbhoF\^oFchoFg]oF^[pF_fnFghoFg]oFainF
`fnF\ioF`fnFfbpFhfoF]ioFbdnF^ioF^fnF_ioFd]oF_[pF_fnF`ioFg]oFdioF`cpFabpFhfoF\bp
FhfoFfapF_dnFeioFagpFgapFhfoFdbn#Fd^nFcdn**FIF'F7FasF^uF'FDF;F^xF__oF_dmF`jnF`c
pFjioFg]oFaapF\dnF_joFg]oFbhnF\dnFdjoFg]oFhjoF_fnFaaoF_boF(F(,bqFbfoFafnFcfoFg]
oFifoF`cpFjfoF_dmF[goFafnF`go#FinF[hlFbgoF\hpF`bnF[ipFdgoF`cpFegoF\dnFfgoFhdnF]
aoF_boFhgoF[foF[cpF\^o*&FidmF'F7F9F_fnFigoF\^oFfaoF_boF[hoFg]oF\`oF`cpF`hoF\dnF
ahoF\^oFjaoFafnFbhoF\^oFchoFg]oFghoFg]oFainF`fnF\ioF`fnFfbpFhfoF]ioFbdnF^ioF^fn
F_ioFd]oF`ioFg]oFdioF\dnFabpFhfoF\bpFhfoFfapF_dnFeioFfgpF]hpFednFgapFhfoFdbn#"$
>#FidnF__oF^xF`jnF\dnFjioFg]oFaapF\dnF_joFg]oFbhnF`cpFdjoFg]oFhjoF_fnFibnF^en*&
F^[nF'F7F9FednFaaoF_boF(F(F(F(F(F(7$7%FinF(FinX,F*6"F,[gl!"%!!!#1"%"%F(,fnFf^pF
[cnF\_pFehnF^_pF[cnFd\oFa[lFgcnF^xFb_pF[cnFc_pFhxFd_pFbcnFe_pFehnF]cnFgxF]coF^x
F^coFdbl*&,&F_dlFfvF_elF9F'F7F8FgxFc\oFa[l*&FjbnF'F7F9FdhnFfcnF\zFf_pF^xFfcoF[c
nFg_pF[cnF\`pF[cnFa`pF[cnFf`pFeelFg`pF[cnFfdoFhfnFa\oFa[lFido#FJFf[lFccnF\zFecn
FdblFicnFehnF(F(,X*,FIFHF7FasFKFE,,Fer"%qXF7!%7k"%SKF'F`\m!%(Q"F[\pF[_pF'FDF8Fg
]oF_cpFhdnF\_pF]gnFfboF]gnF^_pFg]oFd\oF_boFgcnF[foFc_pF^gnFd_pFbdnF]cnFafnFacpF
\dnF]coFheoF^coF[enFc\oF_bo*,FKFE,,Fer"%aTF7!%Sd"%/HF'F`\m!%08F[\pF[_pF'FDF8F7F
asFIFHFg]oFfcnF_boFf_pF[foFfcoFb^oFg_pFg]oFg`pFg]oFfdoF\gnFa\oF_boFidoFipFh[oFe
dn*,FKFE,,Fer"%DVF7!%Gg"%gIF'F`\m!%Q8F[\pF[_pF'FDF8F7FasFIFHFg]oFccn#F`eoF`dnFe
cnF]xF(F(,>Fi]pFjdnF[dpF_dnFdbnFj[mFcgnFednF[[pF`cpF`bnFjdnFgcpF\dnFdenF^fnF\dp
F\dnFbdpF\dnFfenF`fnF_\pF`cpFjdpF_fnFedpFhfoF(F(F(F(F(,@FgcpF\dnFe]pF^gnF[dpF_d
nF\dpF\dnFdbnFj[mFbdpF\dnFhenF_fnF`bnFjdnFedpFhfoFi]pF`fnF[[pF`cpFdenF^fnFfenF`
fnF_\pF`cpFjdpF_fnF(F(7$7%F:FjpF(X,F*6"F,[gl!"%!!!#1"%"%,P**F7FasFIF',(FerFd_oF
7!$,$"$I#F'F'FDF;Fehn**FCF'FDFJF7FasF_[lF'F^bnFdbn#!$.#Ffw*(FDFJF7F`[lFhyF'F^bn
F\aoF^]p**F7Fas,&F7Fj^o!#)*F'F'FdrF'FDF;FcblF__o#Fd[mFjdl**F7Fas,&F7Fj^o!$."F'F
'FdrF'FDF;Fcbl**F7FasFdrF:FDFJFIF;Fhfl**F7F`[lF^uF'F_wF'FDFJFh\oF`bn#Fg_nFbbn**
F7Fas,&F7Fd_o!$<#F'F'FdrF'FDF;Fhw**F7FasF^uF',(FerFd_oF7!$7%"$l%F'F'FDF;FhwFh^o
FhwFdenF^bnFb_oFehnFg_oFehnFfenFe_lF^`oFehnFb`oFehnFg`oFehnFa_oFgbnFgenF[cnF(F(
,R*,F7FasFKFEFIFhn,&F7Fjjn!$e$F'F'FDFHF[cnFf\oFaeoFfcn#FdilF[`nFg\oFhw*,F7FasFK
FEFIFhnFDFHF]\qF'FeelFg[oFE*,FKFEF7FasFDFHFIFhnFa\qF'FeelFccnF[fpFj\oFc[l*,F7Fa
sFKFEFIFhnFDFHFg\qF'Fa[l*,F7FasFKFEFIFEFDFHFj\qF'Fa[lF`[oFgxFecn#Fd[mF[`nFd[oFa
eoFacnFhxFi[oF]hnF[\oFbcnF`\oF^xFgcnF^bnFa\oF]hnFc\oF]hnFd\oF]hnFifnFgbnF]enF[c
nF(F]]oF(F(F(F(,(*(F7FasFIF',&F7F[ilFiamF'F'FhfoFadnF^fnFddnFednF(,RF^]qFg]oFec
n#!$>%F`dnFd[oFgfnFg\oFbcpFb]qFe^oFg[oF\flFc]qFe^oF`\oFheoFgcnF_dmFd]qF_boFe]qF
_boF`[oFafnFf\oFgfnFfcn#"$4#F`dnFccn#Fa]oFidnFi[oFcfpF[\oFieoFj\o#F9F_^oFa\oFcf
pFc\oFcfpFd\oFcfpFacnF^gnFicnF^enFh[oFednF(F(,P**F7FasFIF',(Fer"#vF7!$A#"$G"F'F
'FDF;FhfoFdbn#Fc\lFezF[\qF_dnFh[qF_dnFajnFaep*,F7FasFIF'F]\qF'F^uF'FDF;FggoF`hn
Fjfm*,F7FasFIF'Fa\qF'F^uF'FDF;FggoFc\q#F'Fa[mF`bn#FiyFbbn**F7FasFh[lF'FDFJFCF'#
Fd[mFc^o*,F7FasFIF'Fg\qF'F^uF'FDF;F\dn*(F7Fas,*F`\mFd_oFer!$-&F7"$x)!$l%F'F'FDF
;F\dnFignF\dnF]bnF_dnFfhnFhfoFjhnFhfoFcbnFbdnFbinFhfoFfinFhfoF[jnFhfoFibnF^enFc
hnFedn7$7%F:FinF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,`q*,FKFEFIFEF^uF'F7F`[lFDF8F]x*,F7
FasFKFEFIFhnFdglF'FDFHF]xF`\oF]xFfboF[cn*(FcpFEFfglF'F7F\coFa[l*,FIFEFKFE,(F7Fh
epFiwF'FerFjdlF'F7FasFDFHFehnFd\oF^bnFgcnF]hn*,FIFEFKFE,(F7!#g"#fF'FerF[ilF'F7F
asFDFHFhwFb]qFcblFiboFgfn*,F7FasFKFEFDFHFIFE,(FerFd_oF7!$(R"$M%F'F'FhwF]coFew*,
F7FasFKFEFDFHFIFE,(FerFj^oF7!$$>"$1#F'F'FcblF^co#FiyF[`nFhcnFgbn*,F7FasFKFEFIFh
nF``nF'FDFHFgfnFc\oFidl*,F7FasFIFhnFKFEFbfmF'FDFHFgfnF[\oFgfnFacoF^xFd[oF[]oFg[
oFe_lFfcnF_cm*,F7FasFKFEFIFhn,&FecpF'F7F[ilF'FDFHFhwFafpF^bnFfcoFehnF`doFehnFdd
oFgx*,,&F[wF\xFhvF;F'FDFHFIFEF7F9FKFEF[cn*,FIFEFKFE,(F7!$:""$4"F'FerFjdlF'F7Fas
FDFHFehnFfdoF[cnFhdoFehnFa\oFehn*,F7FasFIFEFKFEFDFH,(FerFjdlF7FadpFa`oF'F'F^bnF
ido#FecpFfw*(F7F\coFcpFEFdglF'Feel*,F7FasFKFEFIFhn,&!#fF'F7FjdlF'FDFHFehn*,F7Fa
sFDFHFIFhnFKFEFi]qF'FehnFe]qFhwF[gpFhwFj\oFew*,FIFhnFKFEF^[mF'F7FasFDFHF]xFccnF
i\oFacnFewFecnFj`qFceoFewFdeoFehn*.FKFEFIFEFcemF'F^uF'F7FasFDFHFehn*,F7FasFIFhn
FKFEF_]oF'FDFHFhwF(F(F(F(F(,bpFg\oFb^oFi_qF`cpFd]qF\dnFj_qF`fnF`[oF\dnFc]qFggoF
`\oFd^oF\`qFhfoFd\oF[^oFgcnFivF^`qF\dnFb]qFggoFiboF\^oF]coFhdnF^co#FdaqFc^oF[aq
F\^oFc\oF_gpF\aqF\^oF[\oF\^oFi[oF[^oFgipFednFd[oFbcnFg[o#F[bqF_^oFfcn#FbglFidnF
]aqF\dnF`doFhfoFddoFb^oFaaqFhfoFfdoFafnFa\oF_gpFido#Fa]oF]^oFiaqFhfoF\bqFhfoFe]
qF\dnFj\oFhdnF]bqF`fnFccn#F;F[hlFacnFhdnFecn#"$>%F`dnFceoFhdnFdeoF\dnF^bqFhfoF_
bqF\dnF(F(,hqFcfoFg]oFignFafnFjhnFg]oFcbnF`fnF`goFago*(,*F7"$0#!$^"F'F`\mF[ilFe
rF_goF'FDF;F7FasFafnFbgoFafnFc\qFd^oF]bnF^fnF`bn#Fa^lF]\oF__qFg]oFegoFafnFfgoFh
dn**F7FasFdrF'FDFJFIF'Fd^o*&F`aqF'F7F9FednF[jnFg]oF^_qFg]o*(F7Fas,*F7"$%>!$W"F'
F`\mF[ilFerFj`mF'FDF;Fg]o*(F7Fas,*F7"$">FfjmF'F`\mF[ilFer!##*F'FDF;FafnF[hoFg]o
*(F7Fas,*F7"$'Q!$s#F'F`\mFjdlFerFcjoF'FDF;Fg]oFg\pF`cp**F[]lF'F7FasFDFJFCF'F`cp
FahoFg]oFbhoFg]oFfhoF_fn*(,*F7Fe`qFf`oF'F`\mFjdlFerFgfoF'F7FasFDF;Fg]oF\ioF`cp*
(F7FasFhyF'FDF;F\dnFh[qF\dnF[\qF`cpF]ioF`cp*(F7Fas,*F7"$(>!$Q"F'F`\mF[ilFer!#%*
F'FDF;Fafn*(F7Fas,*F7"$'>FccqF'F`\mF[ilFerFgcqF'FDF;Fg]oFi^qFafn**F7FasFIF:FDF;
F_]oF'FafnF_ioFednFajnFd]o*(,*F7"$$>FcdqF'F`\mF[ilFerFgcqF'FDF;F7FasFafnFdioF\d
n*(,*F7"$*>!$b"F'F`\mF[ilFerFj`mF'FDF;F7FasFg]oFf]pFfgp**F7FasFDF;FIF:Fi]qF'Fg]
oFh^qFafnFdbn#FjepFcdnFihpF_dmF`hn#FiyFiwFbinFg]oFfinFg]oFhjoFednFfhnFg]o*(F7Fa
sF_[lF'FDF;F\dn*(,*F7"$!R!$"GF'F`\mFjdlFerFcjoF'FDF;F7FasFg]oF\_q#F`hlF`dnF(F(,
^rFcfoFg]oFignFafnFjhnFg]o*(F7Fas,*Fer!$([F7"$J)!$M%F'F`\mFd_oF'FDF;Fg]oFcbnF`f
nFjfoF^xF`goFfioFibqFafnFbgoF[foFc\qFd^oF]bnF^fnF`bn#F\dlFidnF__qFg]oFegoF[foFf
goFbdnF^cqFd^oF[jnFg]oF`cqFg]oFdcqFafnF[hoFg]oFhcqFg]oFg\pF\dnF\dqF\dnF[[pF[hpF
ahoFg]oFbhoFg]o*(F7Fas,*Fer!$Q#F7"$*R!$1#F'F`\mFj^oF'FDF;FafnF^[pF_fnF]dqFg]oF
\ioF\dnF_dqF`cpFh[qF`cpF[\qF\dnF]ioF\dn*(F`aqF'FDF;F7FJFednF`dqFafnFedqFg]oFhdq
FafnF_ioFednF]]pF_fnFidqFafnFdioF`cpF\eqFg]oFf]pFagpF`eqFg]oFh^qFafn**FjhmF'FCF
'FDF;F7F9F_fnFdbn#"$*oFidnF`hnFh[nFbinFg]oFfinFg]oFhjoFednFfhnFg]oFgenF^enFceqF
`cpFdeqFg]oF\_q#F;Fb[oF(7$7%F:F:F:X,F*6"F,[gl!"%!!!#1"%"%,jt*.FIFhnFKFEFe^lF'Fc
pFHF7#F\[nF:FDFHFa[l*&,&FedlFinFg[mFasF'F7F8F^]p*.F7F\coFcpFEFKFEFccmF'FDFHFIFH
FcblFcfoFcblF]\pFidl*,FKFEFcpFHF7F`gqFIFhnFDFHFidl*&,&F\hlFasF]hlFOF'F7F8#F;Fd_
oFifoFh\oFjfoF_\qF[goFcblFibqFcblF`bnF[[l**FDF;FIF'F7FasFfaqF'FhwFfgoFabnF^cqF
\ap*(F7Fas,,Fer"$m&F7!$Q&FcdoF'F[\pFjdlF`\m!$D#F'FDFJFhwFedpFehnFgcpFhw*(,*F`\m
F[ilFer!#lF7"#&)!#KF'F'FDF;F7FasFcblFigoFhwFdcqFcblF[hoFcblFhcqFhwF\dqFh\oF[[pF
]x*(F7Fas,*F`\mFjdlFer!$D"F7"$c"Fh\mF'F'FDF;Fhw*(,*F`\mF[ilFerFg\nF7"#')!#OF'F'
FDF;F7FasFcbl*(,*F`\mFjdlFer!$R"F7Fi`qF_^mF'F'FDF;F7FasFhwFahoFhwF^]oFhw*(,*F`
\mFjdlFerFdcmF7"$<#!$/"F'F'FDF;F7FasFehn*(,,Fer"$B'F7!$"p"$q#F'F[\pFjdlF`\m!$K#
F'FDFJF7FasFhwFc]oFhw**F7Fas,(FerFjdlF7F`]n"#]F'F'FIF'FDF;FhwFbhoFcblFchoFhw**F
CF'FDFJF7FasFh^lF'F^bn*(FDFJF7F`[lFg]lF'F^bnF^[p#F'Fi`mFghoFhwF]dqFhw*.FDFHFIFE
F7F\coFcpFEFKFEFdglF'FXF\ioF\fl*.F7F`gqFIFhnFKFEF^[mF'FcpFHFDFHFa[lF_dqF^bnF]io
F^bnF`dqFcbl*(,*F`\mF[ilFerFi^nF7"#yF\`nF'F'FDF;F7FasFcbl*(F7Fas,,Fer"$T&F7!$0&
FjcpF'F[\pFjdlF`\m!$?#F'FDFJFhwFhdqFcblF^ioFh\o*(,*F`\mF[ilFer!#oF7"#%*FcenF'F'
FDF;F7FasFcbl*.FcpFEFKFEF7F\coFIFEFfglF'FDFHFX*(,,Fer"$t&F7!$u&Fi`mF'F[\pFjdlF`
\mF]hqF'FDFJF7FasFhw*.FcpFEFIFEFKFEFe^lF'FDFHF7F\coFa[lFidqFcblF`ioFhw**F7FasF^
uF'F_wF'FDF;Fh\o*.FKFEFIFEF`[mF'FcpFHF7F`gqFDFHFa[l*,F7F\coFKFEFIFEFcpFEFDFHFXF
b]oFhwF\dpFhwFe]pFdblFf]pFh\oFeioF_\q**F7FasFIF',*FccqF'F7"$#HF`\mFjdlFer!$t"F'
FDFJFehn*(,*F`\mFjdlFerFadpF7"$)>FgcqF'F'FDF;F7FasFhwFdbn#FecpFjyFjioFhw*&,&Fed
lFbvFacmF\xF'F7F8F^]pFi]pF^xF_joFhw*(,*F`\mFjdlFerFehqF7Fj^mF]^nF'F'FDF;F7FasFh
wFdjoFhwFbdpFhwF_ipF^]pFdeqFhw*(F7Fas,*F`\mF[ilFerFi^nF7"#w!#CF'F'FDF;FcblFf]oF
ehnF(F(,\v*&,&F_dlFasFj\mFinF'F7F8F^]pFi_qFhwFj_qF^x*,,(FerFj^oF7!$Y""$2"F'F'FI
FEFKFEF7FasFDFHF[cnFf^pF[cn*,,&F7FinFdpF'F'FKFEFIFhnF7FasFDFHFN**F7F\coFcpFEFji
lF'FDF;Fjhl*&,&Fifl"#=F`ilF9F'F7F8Fggq**FcpFEF7F\coF`jlF'FDF;FeelFfboFbcnF^_pF[
cnF\`qF[cn*,F7FasFIFEFKFE,*!#sF'FerF[doF`\mF\xF7"$;"F'FDF8F[^o*,,(FerF[ilF7!#cF
jiqF'F'FKFEFIFEF7FasFDFHFa[lFd\oF[cn*&,&F_dlFfvF[glF9F'F7F8FgxFgcnF^bnFc_pFaeoF
d_pFaeoFe_pF[^oF^`qFgx*,FIFEFKFE,*F7F`ao!#XF'F`\mFOFerFcenF'FDF8F7FasF\z*(FcpFE
F7F[[mFDF;F^x*,,&F7F[ilF]]mF'F'FKFEFIFhnF7FasFDFHFa[lF^fpFailFiboF^x**FdrF'F7F`
gqFDF;FcpFHFa[lF]coFgvF^co#F\[mF\]o*,,(FerFjdlF7!$0"FihqF'F'FKFEFIFEF7FasFDFHFg
x**FcpFEF7F\coFgilF'FDF;Fa[lFc\oFgx*,,&F7F[ilF^jlF'F'FKFEFIFhnF7FasFDFHFeelFf\o
FewFg[oFe[lFfcn#F\[nFbbnFf_pF[^oFbcoF[cn**FcpFEF7F\coF]jlF'FDF;FjhlF]aqFgxFfcoF
bcn**FcpFEF7F\coFCF'FDF;F^x*,,*F`\mFj^oFer!$N#F7"$'R!$7#F'F'FKFEFIFHF7FasFDFHF[
cn**F]\mF'F7F`gqFDF;FcpFHFcbl*,FKFE,,F`\m!$p#Fer"$v)F7!%H7"$I'F'F[\pFjdlF'FDF8F
7FasFIFHFgxFgcoFbcn*,,*F`\mFjdlFerF^goF7"$"G!$a"F'F'FKFEFIFHF7FasFDFHFgxFg_pF[c
nFicoFbcnF^doFgxF`doFgx**F7F\coFcpFEF^ilF'FDF;Fa[l**F7F\coFcpFEFcilF'FDF;Fa[lF
\`pF[cn**F7F`gqFb\mF'FDF;FcpFHFcblFaaqF[cn**Ff\mF'F7F`gqFDF;FcpFHFcblFa`pF[cnFe
doF[^o**F7F\coFDF;FIF'FcpFEFa[l*,,(FerFj^oF7Fj\rF]^oF'F'FKFEFIFEFDFHF7FasF[cnFg
`pF[cnFfdoF[fpFa\oFgxFidoF^y*,,*F`\mFjdlFerFcaoF7"$@$!$%>F'F'FKFEFIFHF7FasFDFHF
gxFjdoFgxFiaqF[cn*,,&F7FjyFiyF'F'FIFhnFKFEFDFHF7FasF^x*,Ff_nF'FKFEFIFEFDFHF7Fas
F]hn*,,(FerFj^oF7!$_""$9"F'F'FKFEFIFEF7FasFDFHF[cn*,,(FerFOF7F`bmF[ilF'F'FKFEFI
FEF7FasFDFHF\zF]eoFbcn*,,(FerFjdlF7F_goFghpF'F'FKFEFIFEF7FasFDFHFgx**FcpFEF\]mF
'F7F\coFDF;Fcbl*&,&F_dlFa]rFgcmF9F'F7F8F^]p*,FDF;FIF'F7F\coFcpFEFdglF'F^bl*,F7F
asFIFEFKFE,*FerF[ioF7"$@%!$q#F'F`\mFjdlF'FDF8F^xF]bqF^xFccnF]hnFacnFhxFecn#"#>F
[`n*,,(FerFinF7F[jmFdvF'F'FKFEFIFEFDFHF7FasFNFceoFgv*,FcpFEFIF'F7F\coFDF;FcdlF'
Fidl*,FcpFEFDF;FIF'F7F\coFfglF'F^bl*,F7FasFIFhnFKFE,(F7FadpFjcpF'FerFjdlF'FDF8F
a[lF_bqFgxF(,bqFcfoF\dnFifoF_dnFjfoFivF[goFggoF`go#FfamFidnFbgoF^fnF`bnF\gnFdgo
F_dnFegoF_dnFfgoFjdnF[cpFieoF\ipFednFigoF\dnF[hoF\dnFdgpF^xF[[pF\[pF\`oF^fnF][p
F_fnFahoF\dnFbhoF\dnFchoF\dnF^[pFednFghoF\dnFg_oFg]oF\ioFheoFfbpFg]oF^ioF]_qF_i
oF_fnF_[pFednF`ioF\dnF^_oF^fnFdioF_dnFabpFg]oF\bpFg]oFfapF^fnFeio#Fe_mFh]oFb_oF
g]oFb`oFg]oFg`oFg]oF^`oFg]oFgapFg]oFdbn#F\brFcdnFihpF]xF__oF_dmFjioF\dnFaapFafn
F_joF\dnFdjoF\dnFhjoFd]oF_ipF_fnFh^oFafnF(F(F(F(,hqFcfoF\dnFignF\dnFjhnFhfo*(F7
FasFh`mF'FDF;FhfoFcbnFbdnFjfoF]xF`goFdbrFibqFggoFbgoF^fnFc\qFbdnF]bnF_dnF`bn#Fc
enF_^oFegoF_dnFfgoFjdn*(,*F7"$(=FhepF'F`\mF[ilFerF`amF'FDF;F7FasFhfoF^cqFheoFf
\pFedn*(FDFJFIFinF7FasFbdnF[jnFhfoFdcqFggoF[hoF\dn*(F7Fas,*F`\mFf[lFerFbhqF7Fg_
mF`gmF'F'FDF;F\^oFhcqF\dnFg\pF_dnF\dqF_dnF[[pF\[pFahoF\dnFbhoF\dnF^[pFednF]dqF
\dnF_dqF_dnF]ioF_dn*(F7FasF]amF'FDF;FhfoF`dqFggoFhdqFggoF_ioFaepF]]pFedn*(,*F`
\mF[ilFerFj`mF7F[hn!$6"F'F'F7FasFDF;FhfoFidqFggoFdioF_dnFfapF^fnFf]pFebrFffqFed
nFdbn#!$H&FidnFihpFivF`hnF`]m*(,*F`\mF[ilFerFgcqF7"$$=!$7"F'F'F7FasFDF;FhfoFbin
FhfoFfinFhfoFhjoFednFfhnFhfoF_ipF_fnFdeqF\dnF\_qF_dnF(,dsFi_qFggoFj_qFbdnFh\rFg
]oFf^pFg]oF\]r#Ff[lFf^oFfboF[foF^_pFg]oF\`qFg]oFg]rF_boFd\oFg]oFgcnF_dmFc_pFgfn
Fd_pFgfnF^`qFafnF\^r#Ff[lF`boF`^rF_boFiboFbdn*,,&F7Fj^oFi]rF'F'FIFhnFKFEFDFHF7F
asFg]oFacpF[cnF]coF]xF^co#"$."FidnFd^rFafnFc\oFafnFh^rFe^oFf\oFhdnFg[oF\enFfcn#
FfvF_^oFbcoFg]o*,F7FasFKFEFIFE,(F7!$>""$="F'FerFjdlF'FDFHFg]o*,F[[nF'FIFhnFKFEF
DFHF7FasFieoF]aqFafnFfcoF[foFc_rFafnFgcoFieoFi_rFafnFccpF[cnFg_pFg]oFicoFieoF^d
oFafnF`doFafnF\`pFg]oFaaqFg]oFa`pFg]oFedoF[cn*,F7FasFIFhnFKFE,(F7!#S"#OF'FerF\x
F'FDF8FcgpFg`pFg]oFfdoF_^qFa\oFg]oFeaqFg]oFido#FinFa[mFd`rFafnFjdoFafnFh`rFbdnF
j`rF_boF[arFg]oF_arF\drF]eoFieoFaarFafn*,,(FerFj^oF7!$X""$1"F'F'FKFEFIFEF7FasFD
FHFg]oFgarFbdnF]bqFbdnFccnF_dnFacnF^gnFecn#!$x$F`dnF]brF[drFceoF]xFabrF_boF_bqF
afnF(F(,`rFf[pFhfo**F7FasFIF',*F7"$@#!#jF'F`\mFjdlFer!$g"F'FDFJF\dnFifoF_dnFcbn
FbdnF^\pF[foFc\qFbdnF]bnF_dnF`bnFjdnFdgoF_dnFfgoFjdnF^cqFheoFigqF\dn*(,*F`\mF[i
lFerF_\mF7FfvFa[mF'F'F7FasFDF;FhfoF_\pF`cpF`\pFhfoF^hqFggoF]crFbdn*(FCF:FDF9F7F
`[lFedn**F7Fas,(FerF[ilF7!#=F`[lF'F'FIF'FDF;FhfoFg\pF_dnFdgpF_dm*(,*F`\mF[ilFer
FhilF7F\brFjvF'F'FDF;F7FasFhfoF\dqF_dnF[[pF[hpF\`oF^fnF][pF_fn**F7FasFIF',*F7Fa
hm"#aF'F`\mF[ilFerFi^nF'FDFJFhfoFbiqF\dnF[jqF_dnF\jqF_dnF^[pFd]o**F7Fas,(FerFjd
lF7F`hq"#EF'F'FIF'FDF;F\dnFh\pFhfo**,(FerF[ilF7FiamFa]rF'F'FIF'F7FasFDF;FggoFhj
qFggoF]]pFednF_[pFednF][rF\dnF^_oF^fnF_]pF\dn**F7Fas,(FerF[ilF7F\^lFb^lF'F'FIF'
FDF;Fhfo**F7Fas,(FerF[ilF7FbhqF]zF'F'FIF'FDF;FggoFe]pF`^qFf]pFebrFeioFebr**,(Fe
rF[ilF7FbhqFa[mF'F'FIF'F7FasFDF;FggoFi[rF\dnFffqFednFdbn#F_ilF]^oF`hnF`]mF__oF^
xFi]pFd^oFj]pFhfoF_\rF\dn*(,*F`\mF[ilFer!#^F7"#MFdvF'F'FDF;F7FasFhfoF_^pFhfo*(F
DF9F7F_tFCF'F_fnF\_qF_dn7$7%F:F'FinX,F*6"F,[gl!"%!!!#1"%"%F(F(,ht*,FKFE,,Fer"%0
TF7!%Gc"%?GF'F`\m!%)H"F[\pF[_pF'FDF8F7FasFIFHFehnFf\r#F;Fi`mFg\oFehn*&,&F_dlFdd
lF[glFinF'F7F8Fgx*,,*F`\mF[ilFerFfjnF7Ff^qFjjqF'F'FKFEFIFHF7FasFDFHFidl*,FKFE,*
F`\mFOFerFbhqF7F_glFevF'F'FDFHF7FasFIFHF^blFjipFehn*,FKFE,,Fer"%vUF7!%6f"%qHF'F
`\m!%J8F[\pF[_pF'FDF8F7FasFIFHFehnF^]rF`]mFb]rFidl*,F`^lF'F7FasFDF8FIFEFKFEFdbl
*,F7FasF[^lF'FKFEFIFHFDFHFgx*,,*F`\mFjyFer!#`F7"##*Fh\mF'F'FKFEFIFHFDFHF7FasF]x
FfboF[cnFd\oFehnFgcnF]hn*,F_]nF'FKFEFIFHFDFHF7FasFcbl*,,*F`\mFd_oFer!$#\F7"$"))
!$9&F'F'FKFEFIFHF7FasFDFHFehnFd_pF[]o*&,&FiflF]frF`ilFinF'F7F8F_hrF_^rF^x*,FIFE
FKFE,*Fer!$%fF7"%P7!$5)F'F`\mFd_oF'FDF8F7FasFehnF^fpFg\lFiboFgfn*,,(FerF[ilF7Fd
\mF`eoF'F'FKFEFIFEF7FasFDFHFehnF]coFj[mF^co#FfcqF_bn**F7F\coFcpFEF^uF'FDF;FgxFc
\oFehn*,FDFHFIFEF7FasFKFE,&F7FezF\[mF'F'F]xF`jpFehnFg[oFh\lFf_pFcfpFbcoFehnF[_r
F`]mFfdrFehn*,FKFE,,Fer"$D)F7!%76"$S&F'F`\m!$i#F[\pFjdlF'FDF8F7FasFIFHFhwFfcoFc
blF\_rF]x*,,*F`\mFjdlFerF_eqF7"$f#FcdqF'F'FKFEFIFHF7FasFDFHFhwFb_rFcbl*,,&F7Fj^
oFi^nF'F'FKFEFIFhnF7FasFDFHFhwFgcoFgfnFi_rFhw**F]amF'F7F`gqFDF;FcpFHFa[lFicoFgf
n*,FDFHFIFEF7FasFKFEFdglF'FcblF^doFhwF`doFehnFddoFgx*,FIFEFKFE,&F7F]zFhgpF'F'F7
FasFDFHFhwF_`rFcblF``rFcblFedoFcfpFa`rFivFg`pFehnFfdo#F\brFiw*,FIFEFKFE,*Fer!$8
'F7"%*H"!$b)F'F`\mFd_oF'FDF8F7FasFehnFa\oFehnFido#FajlFfw**FcpFEFbamF'F7F\coFDF
;Fh\lFjdoFhw*,F7FasFKFE,,Fer"$%zF7!%_5"$/&F'F`\m!$d#F[\pFjdlF'FDF8FIFHFhw**Fh`m
F'F7F`gqFDF;FcpFHFa[lFfjpFehn*,,(FerF[ilF7FjhqFeilF'F'FKFEFIFEF7FasFDFHFehnF]eo
FgfnFcarFcblFj\oFhxFfarFh\l*,FKFE,*F`\mF[ilFerF[doF7FghpF^dpF'F'FDFHF7FasFIFHFe
hnFacnFewFecn#F\[nF[`nFceoFhxFdeoFcfpF_brFeel*,FKFE,,Fer"$b"F7!$*>Fd_oF'F[\pFOF
`\mFagrF'F7FasFDF8FIFHF^blF`brFh\lF(F(F(F(F(,brFf^pFhfoF\irF^^oF]irFafnF_cpF^gn
FfboF^enF^_pFhfoFd\oFhfoFgcnFivFb_pF^enFcirFhfoFd_pFbcnF\^r#FcrF`boFjirFhfoFibo
F\^oF_jrFhfoF]co#Fc\lFidnF^co#FdcmFidnFc\oFhfoFcjrF`fnFh^rF_gpFg[o#FJF[hlFbcoFh
foFfdrFhfoFfco#F;"$?%F^[sF\dnFgcoF\^oFi_rF\dnFccpFehnFg_pFhfoFicoF\^oFa[sFggoF^
doF\dnF`doFhfoFddoFb^oF\`pFhfoFb[sF\dn*,,(FerF[ilF7F\`nFd[mF'F'FKFEFIFEF7FasFDF
HFhfoFa`pFhfoFedoFehnFg`pFhfoFfdo#F\[nFc^oFe[sFhfoFa\oFhfoFidoFbcnFjdoF\dnFh`rF
`fnFj`rFggoF_arF]]sFc\sFhfoF]eoF\^oFaarF\dnFj\oF^gnFgarF\dnFacnFhdnFecn#"$x$F`d
nFceoF^gnFdeoFehn*,Fe^lF'FIFEFKFEF7FasFDFHFafnFabrF\dnF(F(,`rFf[pFg]oFcerFg]oFi
foF`cpFcbnF`fnF]bnF^fnF`bnFbdnFdgoF[foFfgoFhdn*(F7FasFg]lF'FDF;F\dnF^cqFd^oFigq
Fg]o**,(FerFj^oF7FdcmF_erF'F'FIF'FDF;F7FasFafnF_\pF[foF`\pFg]oF^hqFafnF]crFd^oF
g\pFifqF\dqF\dn*(,*F`\mF[ilFerFa^mF7"$H"F]doF'F'FDF;F7FasFg]oF[[pF[foF\`oF[foFb
iqFg]o**FIF',*F7"%">"!$?(F'F`\mFd_oFerF`bpF'FDFJF7FasFg]oF[jqF\dnF\jqF`cpF^[pF_
fnFcfrFg]o*(,*F`\mF[ilFerFfjnF7"$Q"FicpF'F'FDF;F7FasFg]oFh\pFg]oFffrFafnFhjqFaf
nF]]pFaepF_[pFednF][rFg]oF_]pFafnFjfrFafnFe]pFhdnFf]p#F_ilFb]sFeioFjdn*(F`^lF'F
7F`[lFDFJF`cp*(,*F`\mFj^oFerFbfqF7"$3%!$C#F'F'FDF;F7FasFafnF\grFafnFi[rFg]oFffq
F_fn*(F7FasFh^lF'FDF;F\dnFdbnF_drF`hnF_dmF__oF]x*(,*F`\mF[ilFerF`]nF7Fa`oF^\qF'
F'FDF;F7FasFg]oFi]pFbdnFj]pFg]oF_\rFg]o**F`^lF'F7FasFDFJFCF'F`cp**FIF',*F7"%]6!
$-(F'F`\mFd_oFerF[bpF'FDFJF7FasFg]oF_^pFg]oFcgrFedn**F7FasF[\nF'FIF:FDF;Fg]oF\_
qF\dnF(F(,`rFf[pFg]oFifoF\dnFcbnF`fnF^\pF`cpF]bnF^fnF`bnFhdnFdgoFafnFfgoFbdnFj]
sF`cpF^cqFd^oFigqFg]oF[^sFafnF`\pFg]oF^hqFafnF]crFd^oFjerF_fnFg\pFheqFdgpFivF\d
qF`cpF]^sFg]oF[[pF[foF\`oFafnFchqFg]oFghqFafnFbiqFg]oF`^sFg]oF[jqF`cpF\jqF\dnF^
[pF_fnFd^sFg]oFh\pFg]oF`jqFafnFcjqFg]oFhjqFafnF\aoF_fnF]]pFaepF_[pFednF][rFg]oF
_]pFafnFe]pFhdnFf]p#FajlFh]oFeioFd^oFh^sF\dnFi^sFafnFi[rFg]oF]_sF`cpFdbn#"#TF_^
oF`hnF^xF^_sFg]oFi]pFbdnFj]pFg]oF_\rFg]oF`_sF\dnFa_sFg]oF_^pFg]oFa\rFafnFe_sFg]
oF\_qF`cpF(7$7%F:F(FjpX,F*6"F,[gl!"%!!!#1"%"%,hoF]\pFidlF`goF_\qFbgoFh\oF`bnFdc
nFj]sF^bnF[^sFhwF[cpFgfn*(,,F[\pFd_oF`\m!$J'Fer"%N:F7!%_:"$e&F'F'FDFJF7FasFehnF
_\pFgfnF]crFhfl*(,,Fer"%vBF7!%-J"%S9F'F[\pFd_oF`\m!$s(F'FDFJF7FasFehn*(,,Fer"%/
BF7!%-I"%/9F'F[\pFd_oF`\m!$d(F'FDFJF7FasFehnF[[pF]x*.FcpFEFKFEF``mF'FIFHF7F\coF
DF8Fcbl*.F\`mF'FIFEFKFEF7F`gqFDFHFcpFHFcblF`^sFehnF^jqF`]m*.Fd_mF'FIFEFKFEF7F`g
qFDFHFcpFHFcblFfbpFehnF_ioFehnF\[rF`]m*.FCF'FDF8F7F\coFKFEFIFEFcpFEFhwFadnFe_lF
d[rFhx*,FDF8FIFhnF7F\coFKFEFcpFEFe_lFabpFehn*&,&F]`mFasF]hlFinF'F7F8F_hrF\bpFeh
nFi^sFcbl*,FDF8FIFEF7F[[mFKFEFcpFEFhxFgapFehnFdbnFe[lFi]pFdcnFaapFhwF^dnF^bnF`_
sF^bnFa_sFehn*(,*F`\mFj^oFer!$L#F7"$#RFa_rF'F'FDF;F7FasFhwF(F(,L*,FKFE,,F[\pFb[
oF`\m!$)yFer"%*3#F7!%GB"$C*F'F'FDF8F7FasFIFHF[cnF\irFbcnF]irF^xFddoF[cn**FDFJFI
F'F7F\coFcpFEFewF^[sFgxFfcnFjhlF^coFdbl*,F_bmF'FIF'F7F`gqFDF;FcpFHFeel*(FDFJF7F
e`mFcpFEF^xFcirF[cnFe_pF[cnFidoF^dlFfdoF^xFfboF[cnFjirF[cn**FcpFEFbbmF'FDFJF7F
\coFa[lFe[sF[cnFccnF[cnFc_pFewF\_pF[cnF(,>Fi]pF\gnF[dpF^fnFdbnFhflFhenFednF[[pF
[foF`bnF\gnFgcpFafnFdenF_dnF\dpFafnFbdpFafnFfenFbdnF_\pF[foFjdpFednFedpFg]oF(F(
F(F(,H*(,*F`\mFd^qFer!$(QF7Fh_r!$E$F'F'F7FasFDF;FhfoFj]sF_dnF`_sF_dnF]]pF]gnF[^
sFggoFf]pFjfmFi^sFggoF]crFj^qFg\pF]_qFa_sF\dnF`^sF\dnF_]pF\dnF]bnF_dnFj]pFhfoF`
\pFhfoFcbnFbdnF_^pFhfoFh\pFhfoFf[pFhfoF(,D*,,*F`\mFb[oFer!$y&F7"$L*FffpF'F'FKFE
FIFEF7FasFDF8Fg]oFc_pFhdnFidoFheoFe_pFafnF\_pF^en*,,*F`\mFj^oFer!$U#F7"$G%!$[#F
'F'FKFEFIFHF7FasFDFHFafnFcirFg]o*,FKFE,,Fer"%DCF7!%%G$"%?;F'F`\m!$u(F[\pFd_oF'F
DF8F7FasFIFHFg]o*,FKFE,,Fer"%DDF7!%`MFd\pF'F`\m!$$zF[\pFd_oF'FDF8F7FasFIFHFg]oF
h]sF[foF^coF]xFfcnFivFfboF^enFfdoF[foFccnFafnF\irFbdnFddoF^enF(F(,**(,,F[\pF[il
F`\mF\[nFer!$c#F7"$k'!$?%F'F'FDFJF7FasFhfoF[dpF^fnFdbnF`fnFjdpFedn7$7%F'Ff[lF(X
,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,(Fh]qFg]oFadnF_dnFddnF_fnF(F(F]esF(F(F(F(F(F
(7$7%F'FjpF'X,F*6"F,[gl!"%!!!#1"%"%F(,\p*,FKFE,*Fer!#!*F7F[hn!$="F'F`\mF[ilF'F7
FasFDFHFIFHFgxFi_qF^xFj_qF^xFfboFehnF[`qFcblFb`qFhwF]coFhxFf`qFcblF^coFf]qF[aqF
bcnFc\oF[cnF\aqFbcnFacoF]xFf\oF[]oFg[o#Fc\lFd[lFfcnFf]qF]aqFgxFfcoF[cnFddoFhwFf
doFehnFhdoFehnFa\oF[cnFido#F`eoFfwFhaqFidlFiaqF[cnF\bqF[cnFe]qFhw*,F7FasFKFE,*F
er!$)=F7"$"RFjarF'F`\mFjdlF'FDFHFIFHF[cn*,F7FasFKFEFIFE,(FerFjjnF7!$)o"$;(F'F'F
DFHFehn*,F7FasFKFEFDFHFIFE,(FerFj^oF7F[fsFgdqF'F'Fcbl*,F7FasFIFhnFKFE,&F7FjyF\[
lF'F'FDFHFbcnFj\oFewF]bqF^xFccnF]x*,FKFE,*Fer!$v"F7"$R$!$=#F'F`\mFjdlF'F7FasFDF
HFIFHF[cn*,FKFE,*Fer!$"=F7"$i$!$S#F'F`\mFjdlF'F7FasFDFHFIFHF[cnFceoFhxFdeoF[cnF
^bqF[cnF_bqFgxF(F(,hoFi_qF[foFd]qF\dnFj_qFbdnFc]qFggoF\`qFg]oF^`qFafnFb]qFggoF^
fpFh_sFiboFieoF]coF^gnF^co#!$4"Fc^oF[aqFieoFc\oFg]oF\aqFieoFgipF_fnFf\oFbcnFg[o
Fd^oFfcnFafnF]aqFafnF`doFg]oFddoFbcpFaaqFg]oFfdoF\dnFa\oFg]oFido#F^jlF]^oFh[oF_
fnFiaqFg]oF\bqFg]oFe]qF\dnF]fsFhfoFj\oFhdnF]bqFbdnFccnF`cpFicnF]gnFceoF^gnFdeoF
afnF^bqFg]oF_bqFafnF(F(,\qFcfoFhfoF`goFagpFibqF\dnFbgoF\dnF`bnFhdnF__qFg]oFegoF
\dnFfgoF^gnF^cqFheoF_cqF_fn*,FIF'F7FasFCF'FDFJF^uF'F^xF`cqFhfoFdcqF\dnF[hoFhfoF
hcqFhfoFg\pF[foF\dqF[foFahoFhfoFbhoFhfoFfhoFednF]dqFhfoF\ioF[foF_dqFafnFh[qF`cp
F[\qF\dnF]ioF[foF`dqF\dnFedqFhfoFhdqF\dnFb^qFg]oF_ioF_fnFidqF\dnFdioFafn**F7Fas
FdrF'FDFJF^uF'Fd^oF\eqFhfoFf]pFfio**F7FasFIF',(FerFj^oF7!$["F`drF'F'FDF;FafnF`e
qFhfo**F7FasFIF',(FerFj^oF7Fdcm"#)*F'F'FDF;FafnFdbn#Fa]oFcdnFihpFiv**F7FasFIF',
(FerFd_oF7!$2$F`iqF'F'FDF;Fg]oFchnF_fnFhjoF_fnFibnF]gnFceqFafnFdeqFhfoF\_qF`cpF
(F(F(F(F(,\qFcfoFhfoFjeqFg]oFjfoF]xF`goFfgpFibqF\dnFbgoF`cpFc\qFd^oF`bnFbdnF__q
Fg]oFegoF`cpFfgoF`fnF^cqFheoF`cqFhfoFdcqF\dnF[hoFhfoFhcqFhfoFg\pFafnF\dqFafnF[[
pF\[pFahoFhfoFbhoFhfoF`fqFafnF^[pFednF]dqFhfoF\ioFafnF_dqF[foFh[qF\dnF[\qF`cpF]
ioFafnF`dqF\dnFedqFhfoFhdqF\dnF_ioF_fnF]]pFednFidqF\dnFdioF[foF\eqFhfoFf]pFagoF
`eqFhfoFffqF_fn*(F7Fas,*Fer!$s$F7"$s&FfdsF'F`\mFd^qF'FDF;Fg]oFdbn#FfcqFidnF`hnF
_dm*(F7Fas,*FerF[bsF7"$%Q!$'>F'F`\mFj^oF'FDF;FafnFhjoF_fnFceqF[foFdeqFhfoF\_qF
\dnF(F(7$7%F'FinF:X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,\rFcfoFg]oFhbrFg]oF`go#F
\xF_^oFibqFafnFbgoFafnF`bnF^gnF__qFhfoFegoFifqFfgoFhdnFjbrFg]oF^cqF`fnFf\pF_fnF
]crF`fnFdgsF]xF`cqFhfoFdcqFafnF[hoFg]oF^crFieoFhcqFg]oFg\pF`cpF\dqF`cp**FDFJFIF
:F7FasF^uF'FbdnFahoFg]oFbhoFg]oF]dqFg]oF\ioFafnF_dqF\dnFh[qF[foF[\qFafnF]ioF`cp
FefqF_fnF`crFg]oF`dqFafnFedqFhfoFhdqFafnF_ioFednFacrFg]oFidqFafnFdioF\dnFegsFbd
nF\eqFhfoFfapF_dnFf]pFfgpFfgsF\dnF`eqFhfoFigsF\dnFdbn#FJFezFihpF_dmFfcrFg]oF]hs
FhfoFhjoFaepFgenF]gnF_ipFednFceqF[foFdeqFg]oF\_qF[foF(F(,hqFcfoFg]oFhbrFg]oFjeq
FhfoFjfoF^xF`go#F\brF`dnFibqFafnFbgoF[foFc\qFbdnF`bnF`fnF__qFhfoFegoFheqFfgoFbd
nFjbrFg]oF]crF`fnF`cqFhfoFdcqFafnF[hoFg]oF^crFieoFhcqFg]oFg\pF\dnF\dqF\dnF[[pF[
hpFahoFg]oFbhoFg]oF`fqF\dnF^[pF_fnF]dqFg]oF\ioF[foF_dqF`cpFh[qFafnF[\qF[foF]ioF
\dnF`crFg]oF`dqFafnFedqFhfoFhdqFafnF_ioFednF]]pF_fnFacrFg]oFidqFafnFdioF`cpF\eq
FhfoFfapF_dnFf]pFagpF`eqFhfoFffqFednFdbn#F\gsFidnF`hnFivFfcrFg]oFfhsF\dnFhjoFae
pFceqFafnFdeqFg]oF\_qFafnF(F(F(F(F(F(7$7%F'F:FinX,F*6"F,[gl!"%!!!#1"%"%F(,htFg
\oF[cn*&,&FiflF\xFicmF9F'F7F8F_hrFi_qFgxFj_qF]xF\irFc[lF]irFhwFfboFcblF\`qFehn*
,,*F`\mFj^oFerFecsF7"$=%!$G#F'F'FKFEFIFHF7FasFDFHFehnFbirFgfnFcirF[cnFc_pF[]oFe
_pFcfpF^`qFhw*&,&Fj\mF9F_dlF\xF'F7F8F^]pFhirF_hrF_^rFe_lFjirF[cnFiboFgfnFb^rFcb
lF_jrF[cnF]coFhxF^co#Fa]oFiwFbjrFhwFg^rFcblFc\oFehnFcjrF^x*,F7FasFKFE,,FerFd[nF
7!$/$"$W"F'F`\mFa^mF[\pF\xF'FIFHFDF8Fcfp**FIF:F7F`gqFDF;FcpFHFa[lFf\oFhxFg[oFge
sFfcn#F\brFbbn*,,*F`\mF[ilFer!##)F7"$["!#))F'F'FKFEFIFHF7FasFDFHFcblFfdrF[cnF]a
qFhwFfcoF[cnF]_rFehnFb_rFeelF^[sFgxFc_rFhwF`[sFcblFa[sFa[lF`doFehnF^dsF[cnFddoF
hw*&,&F_dlF]frFgcmFinF'F7F8F^]pF]`rFcblF^`rFcblFb[sFgxF_`rFeelFaaqFehnF``rFeel*
,,*F`\mFj^oFer!$O#F7Fcfq!$9#F'F'FKFEFIFHF7FasFDFHFehnFa`rFgxFfdoF^bnFa\oFehnFid
o#Fa^lFd[lFd`rFhwF[\sFe_lF\\sFhwFiaqFehnFb\sFcbl*,,*F`\mFinFerF\^lF7FahmF\^lF'F
'FKFEFIFHF7FasFDFHFg[nFc\sF[cnFcarFeelFj\oFew*,,*F`\mFjdlFerFeaoF7"$'HFcaoF'F'F
KFEFIFHF7FasFDFHFhwFfarFeelFgarFcblF]bqF]x*,,*F`\mFj^oFerFb[tF7"$/%F\_sF'F'FKFE
FIFHFDFHF7FasFehnFe\sF[cn*,,*F`\mF[ilFer!#')F7"$i"!$+"F'F'FKFEFIFHF7FasFDFHFcbl
FccnF^bnFceoFj[mFdeoF[^oF`brFeelF_bqFhwF(F(,hrFi_qF_boFj_qF`fnF\]r#FcrFf^oF\irF
`^qF]irF\dnF_cpFhdnFfboFa]sF\`qFhfoFc]rFjgoF\jsFhfoFg]rFggoFb_pF]gnFcirFg]oFc_p
FbcnFe_pF`cpF^`qF\dnFjirFg]o*,FKFEFIFE,*FerF^joF7"$d%FffoF'F`\mFjdlF'FDF8F7FasF
\dnF`^rFggoF^fpFh_sFiboF\^oF_jrFg]oFacpFafnF]coF^gnF^coFj^qFd^rF\dnFc\oFhfoFcjr
FbdnFf\oF^gnFg[oFd^oFfcn#FddlF_^oFfdrFg]oF]aqF\dnFfcoF^enF]_rFhfoF^[sFafnFa[sF_
boF`doFhfoFddoFbcpFb[sFafnFc]sFg]oFaaqFhfoF`[tFhfoFb`rFhfoFfdoF^fnFe[sFg]oFa\oF
hfoFido#!$8"FidnFd`rF\dnFiaqFhfoFj`rF\^oFc\sFg]oFj\oFhdnFgarFggoF]bqF`fnFccnF^f
nF]brFc\tFceoF^]sFdeoF[cnFh]sF\dnFabrF\dnF_bqF\dnF(F(,`rFifoF\dnF^\pF`cpF`bnFhd
nFdgoFifqFfgoFbdnFj]sFafnF^cqFbdnFigqFg]oFherFg]oF[^sF\dnF^hqFafnF]crFbdnFjerF_
fnFdgsF^xF[frFg]oFg\pF[foFdgpFivF^frFg]oF\dqF`cpF]^sFhfoF`isF`fnF[[pF[foF\`oFaf
nFchqFg]oFghqFafnF][pFednF`frFg]oFbiqFg]oF`^sFhfoF[jqF`cpF\jqF\dnF^[pF_fnFd^sFh
foF`jqFafnFcjqFg]oFhjqFafnF]]pFednF_[pFaepF][rFg]oF^_oF_dnFegsF`fnFhfrFg]oFf]pF
\gnFeio#FdilFc^oFh^sF[foFi^sF\dnFi[rFg]oF]_sFafnFdbn#"#^F_^oF^_sFhfoFi]pF\gnF_
\rFg]oF_grFg]oF`_sF[foFa_sFhfoFa\rFafnFe_sFhfoF\_qF`cpF(F(F(F(F(,^rFifoF`cpFc\q
F`fnF`bnFbdnFdgoFheqFfgoFhdnFj]sF[foFigqFg]oFherFg]oF[^sF\dnF_\pF[foF^hqFafnF]c
rFbdnFg\pFafnFe`sFhfoF^frFg]oF\dqF\dnF]^sFhfoF[[pF[foF\`oF[foFchqFg]oFghqFafnFb
iqFg]oF[jqF\dnF\jqF`cpF^[pF_fnFd^sFhfoF`jqFafnFcjqFg]oFhjqFafnFajnFednF]]pFednF
_[pFaepF][rFg]oF^_oF_dn*(F7Fas,*F`\mF[ilFerFhilF7Fd[lFjvF'F'FDF;Fg]oFe]pFhdnFf]
pFheoFeio#FiyFh]oFh^sFafn*(F7Fas,,F[\pF[ilF`\mFgcqFerF`^mF7FJ!$3"F'F'FDFJFg]oFi
^sF\dnFi[rFg]oF]_sF[fo*(F7Fas,*F`\mF[ilFerF_\mF7FahmF\]oF'F'FDF;Fg]oFdbn#Fh^nFi
dnF`hnF_dmF__oF]xF^_sFhfoFi]pFbdnF_\rFg]oF_grFg]oF`_sFafnFa_sFhfoFcgrFednFa\rFa
fnFe_sFhfoF\_qF\dnF(F(7$7%F'F'FjpX,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,`qFifoFafn
F^\pF[foF`bnF^gnFdgoF\dnFfgoF`fnFj]sF\dnFigqFhfoF[^sFafnF^hqF\dnF]crFd^oFjerFed
nFdgsF]xFg\pF`cpFdgpF_dmF\dqF[foF]^sFhfoFjbsFg]oF`isFheoF[[pF`cpF\`oF\dnFchqFhf
oFghqF\dnFbiqFhfoF`^sFg]oF[jqF[foF\jqFafnF^[pFednFd^sFhfoF`jqF\dnFcjqFhfoFhjqF
\dnF\aoFednF]]pF_fnF_[pF_fnF][rFhfoFf]pFjdnFeioFheoFh^sFafnFi^sFafnFi[rFhfoF]_s
F[foFdbnFbgpF^_sFhfoFi]pFjdnF_\rFhfoF`_sF`cpFa_sFg]oFa\rF\dnFe_sFhfoF\_qF[foF(F
(,bqFifoF[foF`bnF`fnFdgoF`cpFfgoF^gnFj]sF`cpF^cqFheoFigqFhfoF[^sFafnF_\pF`cpF^h
qF\dnF]crFd^oFg\pF\dnFe`sFg]oF\dqFafnF]^sFhfoFjbsFg]oF[[pF`cpF\`oF`cpFchqFhfoFg
hqF\dnFbiqFhfoF[jqFafnF\jqF[foF^[pFednFd^sFhfoF`jqF\dnFcjqFhfoFhjqF\dnFajnF_fnF
]]pF_fnF_[pF_fnF][rFhfoFe]pF^gnFf]pFd^oFeioF\gnFh^sF[foFi^sFafnFi[rFhfoF]_sFafn
Fdbn#Fb\qFidnF`hnFivF__oF^xF^_sFhfoFi]pF`fnF_\rFhfoF`_sF\dnFa_sFg]oFcgrF_fnFa\r
F\dnFe_sFhfoF\_qFafnF(F(F(F(F(F(7$7%F'F(Ff[lX,F*6"F,[gl!"%!!!#1"%"%F(,LF^bsFehn
F\irFgfnF]irF]xFddoFehnFdbsFhx*,,(FerFj^oF7F]arFf\nF'F'FKFEFIFEF7FasFDFHFhwFfcn
F`]mF^coFc[lFebsFidlFfbsF]xFcirFehnFe_pFehnFidoF\flFfdoF]xFfboFehnFjirFehnFgbsF
cblFe[sFehnFccnFehnFc_pFhxF\_pFehnF(F(,DF^bsFhfoFc_pF^gnFidoFd^oFe_pF\dnF\_pF]g
nF^[sF\dnF]irF`cpF^coF^xFfcnF_dmFfboF]gnFcirFhfoFccnF\dnFjirFhfoF\irF`fnFddoF]g
nFe[sFhfoFfdoF`cpF(F(,*FddsFg]oF[dpF_dnFdbnFbdnFjdpF_fnF(F(F(F(F(Fg^tF(F(7$7%F(
FOF(X,F*6"F,[gl!"%!!!#1"%"%,,Fb^qF[cnF^_oF]hnFdbn#"#\FbbnFhenFdhnFgenFehnF(F(,0
F^]qFehnFf\oFgfnFecnF]hnFfcnFgemFd[oFewF_enFdhnF]enFehnF(Fg]qF(F(F(F(F(F(,0F^]q
FhfoFfcnFbcnFd[oFhdnFf\oF`fnFecnFivFicnF]gnFhcnF_fnF(F(,,Fd[qFg]oFdbnFi\oF\hnF^
fnFibnF]gnFebnF_fn7$7%F(Ff[lF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,0F]fsF[cnFf\oFbcnFecn
F^bnFfcnFffmFd[oFhxFh[oFdhnF_aqFehnF(F(F(F(F(,0Ff\oFbdnFecnF_dmFicnF^enFhcnFedn
FfcnFgfnFd[oF^gnF^]qFg]oF(F(,,FdbnF[_qF\hnF_dnFibnF^enFebnFednFd[qFhfoF(F(,,*(F
7Fas,*F`\mFd_oFer!$"[F7"$K)!$g%F'F'FDF;FhfoFdbnF[_qF\hnF_dnFgenF]gn**F`aqF'FCF'
FDF;F7F9F_fnF(7$7%F(FjpF:X,F*6"F,[gl!"%!!!#1"%"%,`o*&,&FfdlF9Fg[mF\xF'F7F8F^]pF
^\pFbcnFdgoF`inFfgoFdcnFherF[cn*&,&FfdlFOFacmFasF'F7F8F^]pF_\pFgfnF\ipFdhn**F7F
asFDF;FIF',(FerF[ilF7Fg\nFg\mF'F'F[cnF[frF[cnF`cqFgxF^frF[cnF[[pFgfnF`frF[cn*.F
IFhnFKFEFbfmF'FcpFHF7F`gqFDFHFcblF^jqFcbl*.FKFEF7F\coFDFHFIFEFcpFEFcemF'FeelF\i
oF]hnF_jqFcblFedqFgx*&F7FasFj`tF'F[cnF_[pF^]pFd[rFa[lF\eqFgxFhfrF[cnF[dpF]hnFe]
pFhxFeioF`inF`eqF[cnFdbn#Fd[mFd[lFi]pFgfnF_grF[cnFibnF[cnFceqF]hnF(F(,do*&,&F_d
lF\xFb^mF9F'F7F8F^]pFi_qF]x**F7F\coFcpFEFc^nF'FDF;Fcbl*,FCF:FDF]_pF7FasFIFEFKFE
FehnFfboFehnFc]rFcfpF\jsFehnFb_pF[cnFc_pFgfnFd_pFewFe_pF]x*&,&F_dlF]frFa^nFinF'
F7F8F^]p**F^gmF'F7F`gqFDF;FcpFHFa[lF^fpFe_lF^coFgdoFbjrFcblF[aqFgfnF\aqFgfnFgip
FdhnFd[oFewFfcnF]xFf_pF[cnF]_rFehnF_aqF[cnF_`rFa[lF`[tFehnFedoF[cnFa`rFa[lFb`rF
ehnFidoF^xF\bqFehnFj`rFgfnFfarFa[lFecnFeelFceoF]xF^bqFehnF(,NFfcrFhfoFfapF^fnF
\ioF^fnFhjoF]gnFacrFhfoFegoF]_qFhbrFhfoF`goF]_qFjbrFhfoFdbnF`fnF]crFbdnF`crFhfo
F`isF`fnF^crF\^oFceqF^fnF\eqFafnF`cqFafnFedqFafnF`eqFafnF^cqF`fnFegsFbdnFahsFhf
oF(F(F(F(,,FdbnFi\oF\hnF^fnFgenF^enF_`tFednFj_tFg]oF(,ZFi_qF`cpFcatF]gnF_cpFhdn
FfboFbcpF\jsFhfoFc_pF`fnFd_pFhdnF]drFhfoFacpF`cpF^co#F^jlFidn*,F7FasFKFEFIFEF`[
mF'FDFHF\^oFd[oFhdnFg[oF`fnFfcnF`cp*,F7FasFKFEFDFHFIFEFj`tF'FhfoFfdrF\^oFfcoF^e
n*,F7FasFKFEFIFE,(F7F]frF\]oF'FerFf[lF'FDFHF\^oFccpFafnF`[tFhfoFedoFafnFgdrFjgo
FifnFedn*,FIFEFKFEFc^nF'F7FasFDFHFhfoFidoF`fnF\erFhfoFecnFagoFceoFd^oF(F(,FF^iq
Fg]oFe]pFhdnFd]pF^fnF[iqFafnFhiqFafnF_`tFednFfgoF\gnF]crFbdnFdbnF\gnFe[rFg]oF^c
qF`fnFi]pFbdnF[[pF[foF`isF`fnF\hnF^fnFegsFbdnF^\pF`cp*(FCFinFDF9F7FasF_fn7$7%F(
FinFinX,F*6"F,[gl!"%!!!#1"%"%F(F(,doFi_qF^xFbatFa[lFcatF[cnFfboF[cnF\jsF[cnFb_p
FehnFbirFbcnFc_pFbcnFd_pFhxFe_pF^x*&,&F_dlFasFb^mFinF'F7F8F^]pFfatFcblF^fpFh\l*
&,&F_dlFa]rFa^nF9F'F7F8F^]pF^coF[fpFbjrFa[lF[aqFbcnF\aqFbcnFcjsF[^oFd[oFhxFfcnF
^xFf_pFehnF]_rF[cnF_`rFcblF`[tF[cnFedoFehnFa`rFcblFidoF]xF\bqF[cnF^foFdhnFfarFc
blFj[tF[cnFecnFidlF]enF[cnFceoF^xF^bqF[cnF(F(F(F(F(,ZFi_qF[foFcatF^enF_cpF^gnFf
boFb^oF\jsFg]oFc_pFbdnFd_pF^gnF]drFg]oFacpF[foF^coF_^qF[btFieoFd[oF^gnFg[oFbdnF
fcnF[foF\btFg]oFfdrFieoFfcoF]gnF]btFieoFccpF\dnF`[tFg]oFedoF\dnFgdrFcgpFifnF_fn
F_btFg]oFidoFbdnF\erFg]oFecnFagpFceoFheoF(F(,FFe]pF^gnFd]pF_dnF_`tF_fnF]crF`fnF
fgoFjdnFi]pF`fnF[[pF`cpFdbnFjdnF^cqFbdnF^iqFhfoF`isFbdnF\hnF_dnF[iqF\dnFhiqF\dn
FegsF`fnF^\pF[foFabtFednFe[rFhfoF(F(,FF^iqFhfoFe]pF^gnFd]pF_dnF[iqF\dn*(F7Fas,*
F`\mFjdlFerF]iqF7"$3#Fa\tF'F'FDF;F\dnFebnFednFfgoFjdnF]crF`fnFdbnFjdn*(F7Fas,,F
er"$Q'F7!$G("$)GF'F[\pFjdlF`\mF[bsF'FDFJFhfoF^cqFbdnFi]pF`fnF[[pF`cpF`isFbdnF\h
nF_dnFegsF`fnF^\pF[foFabtFednF(7$7%F(F:FjpX,F*6"F,[gl!"%!!!#1"%"%,boF_gqFjhl*(F
7FasFe\nF'FDF;F[cnFdgqF\flFhbrF[cnF^\pFbcnF`goF`inFegoF`inFfgoFdcnFjbrF[cn*.FDF
8FIFEF7F\coFKFEFcpFEF^uF'F]xF^crFbcnF]^sFgxF[[pF]xF[atFa[lF^jqFa[lF_jqFa[lFd^sF
gxF`crF[cnFacrF[cnFadnF]hnFd[rF^xFeasF^xFe]pFhxFh^sF]hn*.F``nF'FKFEFIFhnFcpFHFD
FHF7F`gqFeelF]_sF]hnFhasF^x*.F[[nF'FKFEFIFhnF7F`gqFDFHFcpFHFcblFdbnFbcnFfcrF[cn
F^_sFgxFi]pFgfnFhjoF[cnFddsF[cnFe_sF[cnF(F(,X*,FCF'FDFJF7F\coFcpFEF^uF'FgxFcatF
ehnF\irFgfnF]irF]x**F7F`gqFchmF'FDF;FcpFHFcblFd_pFewFdbsF]xF^fpFe_lF_jrFehn**F`
hmF'F7F`gqFDF;FcpFHFcblF^coF]x*,FCF'FDFJF7F\coFIF'FcpFEFhw*,F[\nF'FIF:F7F`gqFDF
;FcpFHFa[l**FDFJF7F[[mFIF'FcpFEFa[lFf_pF[cnF^bsFehnFfdrFehnFfcoF[cn**FDFJF7F[[m
FcpFEF^uF'FcblFddoFehnFc]sFehnFedoF[cnFidoFh\lFc\sFehnFecnF[cn**F\hmF'F7F`gqFDF
;FcpFHFcblFdeoF]xF(,NFjbsFhfoF]_sF^fnFh^sF^fnF_[pF]gnF^_sFafnFdgoF]_qFd^sFafnFe
ioF]_qF]^sFafnF]crFbdnFe_sFafnF`isF`fnF_grFhfoF^_oF^fnFherFhfoF^cqF`fnFe]tFhfoF
egsFbdnF^frFhfoF_]tFhfoFdbnFd^oFb]tFhfoF(F(F(F(,FFe]pFhdnFd]pF^fnFebnF_fnF]crFb
dnFfgoF\gnFi]pFbdnF[[pF[foFdbnF\gnF^cqF`fnF^iqFg]oF`isF`fnF\hnF^fnF[iqFafnF^ctF
afnFegsFbdnF^\pF`cpFabtF_fnFactFg]oF(,FF_csFhfoFd_pFhdnFccpFafnFcatF]gnFe\sFhfo
Fc\sFhfoF_jrFhfoFbirFhfoFh]sF`cpFedoFafnFfcoF^enFdeoF`cpFidoFbdnF^coF`cpFecnFaf
nFg[oF`fnF\irF`fnFddoF]gnF(F(,(F_`sFg]oFd]pF^fnFabtF_fn7$7%F(F'Ff[lX,F*6"F,[gl!
"%!!!#1"%"%F(F(,XF`dtFhwFcatF[cnF\irFbcnF]irF^xFadtFa[lFd_pFhxFdbsF^xF^fpFh\lF_
jrF[cnFbdtFa[lF^coF^xFcdtFgxFddtFcblFedtFcblFf_pFehnF^bsF[cnFfdrF[cnFfcoFehnFfd
tFa[lFddoF[cnFc]sF[cnFedoFehnFidoFe_lFc\sF[cnFecnFehnFgdtFa[lFdeoF^xF(F(F(F(F(,
FF_csFg]oFd_pF^gnFccpF\dnFcatF^enFe\sFg]oFh]sF[foFedoF\dnFfcoF]gnFc\sFg]oFidoF`
fnFecnF\dnF_jrFg]oFdeoF[foF\irFbdnFddoF^enFbirFg]oF^coF[foFg[oFbdnF(F(,(F_`sFhf
oFd]pF_dnFabtFednF(F(FbetF(7$7%F(F(FOX,F*6"F,[gl!"%!!!#1"%"%,0FjbsF[cnFfapF]hnF
dbnFh\lF^dtFa[lFddnFdhnFd[rFgxFhasFa[lF(F(F(F(FcdsF(F(F(F(F[etF(F(F(F(F(F,
