M7R0
I-ListOfMetric7(7%7$7%"""""!F(X,%)anythingG6"6"[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F(F
(F(F(F(F(F(F(F(7$7%F(F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F
(7$7%F(F(F'X,F*6"F,[gl!"%!!!#1"%"%F(*$%"rG#!"$""#F(F(F5F(F(F(F(F(F(F(F(F(F(F(7(
7$7%F9F(F(X,F*6"F,[gl!"%!!!#1"%"%*(,&F6F9F8F'F',&F6F'F8F'!""F6F8F(F(,$**FA#FBF9
,&F6F'!"#F'#F'F9F6F8*$FAFBFHF9F(F(F(F(F(F(,$*$F6F8#F'""$F(FCF(F(,$*&FAFBF6FGFL7
$7%F'F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,$FK#FBFMF(F(FTF(F(F(F(F(F(7$7%F'F(
F'X,F*6"F,[gl!"%!!!#1"%"%F(,$FDFGF(F(FZF(F(,$FOFUF(F(F(F(F(FenF(F(7$7%F(F9F(X,F
*6"F,[gl!"%!!!#1"%"%,$FOFBF(F(FZF(FJF(F(F(F(F(F(FZF(F(,$F?FU7$7%F(F'F'X,F*6"F,[
gl!"%!!!#1"%"%F(F(FCF(F(F(F(F(FCF(F(,$F?FLF(F(F`oF(7$7%F(F(F9X,F*6"F,[gl!"%!!!#
1"%"%,$FKFGF(F(F(F(FNF(F(F(F(F[oF(F(F(F(F(7,7$7%FMF(F(X,F*6"F,[gl!"%!!!#1"%"%,$
***&FFF'F6FBFHF@F'FAFBF6!"%FBF(F(,$*,FIFHF6F^pFFFHF]pFHFAFE#!"*""%F(F(F(F(F(F(,
$*&F]pFHF6F^pFEF(F_pF(F(,$*(FAFBF6F8F]pFHFE7$7%F9F'F(X,F*6"F,[gl!"%!!!#1"%"%F(F
(F(F(F(F(,$FepFHF(F(F\qF(F(F(F(F(F(7$7%F9F(F'X,F*6"F,[gl!"%!!!#1"%"%F(,$F`p#""*
FcpF(F(FaqF(F(,$FgpFHF(F(F(F(F(FdqF(F(7$7%F'F9F(X,F*6"F,[gl!"%!!!#1"%"%,&**F6!"
&,(*$F6F9F'F6F8F9F'F'FAFBF]pFEF9FgpF'F(F(,&*,FAFEFF#FMF9F6F[rFIFHF]pFEFMF`pFbqF
(FdpF(F(F(F(F(F(F^rF(F(,&FjqF'F\pFH7$7%F'F'F'X,F*6"F,[gl!"%!!!#1"%"%F(F(,(F`pF8
*$F6#FbpF9FLF_rF7F(F(F(F(F(FfrF(F(,(FjqFE**FAFBFFF'F6F^pF]pFHFEF\pFEF(F(FirF(7$
7%F'F(F9X,F*6"F,[gl!"%!!!#1"%"%,*FjrF'**FAFEFFFHF6FhrFIFHFcp**FAFBFFF9F6F[rF]pF
EF'FepF'F(F(,(F`pFH*&FAFBF6#!"(F9FLF_r#F'FcpF(FfpF(F(F(F(,&FjrF'F\pFHF(FbsF(F(F
(7$7%F(FMF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(7$7%F(F9F'X,F
*6"F,[gl!"%!!!#1"%"%F(,(F_rFEFgrFUF`p#FBFcpF(F(F`tF(F(,*FjrFfs**F6F^pF]pFH,&F6F
'FBF'F'FAFBFatFasFfsFjqFatF(F(F(F(F(FbtF(F(7$7%F(F'F9X,F*6"F,[gl!"%!!!#1"%"%F(F
(F(F(F(F(,*FjrFatFctFfsFasFatFjqFfsF(F(FitF(F(F(F(F(F(7$7%F(F(FMX,F*6"F,[gl!"%!
!!#1"%"%F(,&F`p#F8FcpFcsFUF(F(F^uF(F(F(F(F(F(F(F(F(F(F(717$7%FcpF(F(X,F*6"F,[gl
!"%!!!#1"%"%,(*(F6!"',(F]r"")F6!#I"#FF'F'FAFBFfs*(F@F9FAFGF6FguFL*(FAFGFFF'F6Fg
uF8F(F(,(*,FFFHF6FguFIFH,&F6FcpFbpF'F'FAFE#FM""&*,F@F'FAF7F6FguFFFHFIFH#F9Fbv**
FAF7FFFHF6F[rFIFH#FGFbvF(F(F(F(F(F(,&*$F6Fgu#FG"#X*&F`vF'F6Fgu#FM"#?F(F^vF(F(,(
F]vFdv*&FAFGF6F^pFiv*(F6F[rFAFBF`vF'F\w7$7%FMF'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F
(F(F(,&F[w#F8F]wFhv#F9FjvF(F(FewF(F(F(F(F(F(7$7%FMF(F'X,F*6"F,[gl!"%!!!#1"%"%F(
,(F_v#F8FbvFcvFfvFevFdvF(F(F\xF(F(,(F`wFfwF]vFfvF_wFgwF(F(F(F(F(F^xF(F(7$7%F9F9
F(X,F*6"F,[gl!"%!!!#1"%"%,.*(F6Fgu,(F]rFcpF6!#8"#5F'F'FAFBFat*(F@F'FAFGF6F[r#FG
FMF]v""'*(F6FguF\rF'FAFBFG**F6FguFdtF'F`vF'FAFBFEF`wFatF(F(,&**FAFEFFF`rF6FguFI
FH#!#BFbvF_v#FesFbvF(FgvF(F(F(F(,&*&FFF'F6FguFfwFhvFivF(F]yF(F(,.*(F6Fgu,(F]rFM
F6!")FcpF'F'FAFBFfwFhx#FcpFjvF]v#F^pFbvF[y#FguFbv*(F6Fgu,(F]rFcpF6FfxFcqF'F'FAF
B#F8FgxFfuFfw7$7%F9F'F'X,F*6"F,[gl!"%!!!#1"%"%F(F(,,*,FIFHFFFHFdtF'F6FguFAFE#F'
FbvF^y#"#8Fbv**FIFHFFFHF6FguFAFEFiy*&F]pFHF6#!#6F9FEF_v#FjxFbvF(F(F(F(F(FbzF(F(
,6*(,(FbvF'F]rF'F6F^pF'F6FguFAFBF\wF]vFdvFhxFiv*(FAFBFFF9F6Fgu#FMFcpF[yFavF[zF
\w*&F6F[rFAFBFiv**FFF'F6FguFAFBF`vF'F\wFfuF\w*(F6FguF@F'FAFBFivF(F(F\[lF(7$7%F9
F(F9X,F*6"F,[gl!"%!!!#1"%"%,0*(,(F]rFcpF6Fjz""(F'F'F6FguFAFBFatFc[lFixF_[lFG*,F
IFHF6FizFFFHF]pFHFAFEFhrFb[lFEF]vF8F[wFatF(F(,0*,,(F6!#;"#7F'F]rFbvF'FIFHF6FguF
FFEFAFE#FBFiuFgzFfvF^yFiy*(FAFBF6FhrF]pFHFEF_v#FBFbvFevFfv*,,&FguF'F6FbvF'FFFHF
IFHF6FguFAFE#F8"#SF(F^wF(F(F(F(,,*(,("#6F'F]rFMF6!#7F'F6FguFAFBFfwFc[lFhyF_[lFj
yFb[lF]zFfuFfwF(F]\lF(F(,&*(,(F]rF'F6F'F^pF'F'F6FguFAFBFfwF_wFiv7$7%F'FMF(X,F*6
"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,&FcyF\wFhvFgwF(F(Fe]lF(F(F(F(F(F(7$7%F'F9F'X,F*6
"F,[gl!"%!!!#1"%"%F(,,FczFd\lF^yF9Fgz#FcpFbvFhzFHF_vFdzF(F(Fj]lF(F(,8F][lFfwF_[
lF_uFeyF\wFa[lFgwF]vFdvFhxFivFb[lFfw**F6FguFFF'FdtF'FAFB#FMFgxFc[lFgwF[zF\wF[yF
^^lF(F(F(F(F(F\^lF(F(7$7%F'F'F9X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,8Fj\lF\wFa[l
FgwF][lFfwF_[l#FcqF]wFhxFgwF]vFfvFb[lF\wF]^lF]zFc[lFivF[zFfwF[yF]zF(F(Fc^lF(F(F
(F(F(F(7$7%F'F(FMX,F*6"F,[gl!"%!!!#1"%"%F(,.F^\lFdzFgzFdvF^yF[^lFc\lFHF_vFdzFev
FdvF(F(Fi^lF(F(,&F_]lF\wF_wFgwF(F(F(F(F(Fj^lF(F(7$7%F(FcpF(X,F*6"F,[gl!"%!!!#1"
%"%,(FeyFfsF]vF8F_wFLF(F(,(F^y#F[\lFbvFcvFfvFevFdvF(FbyF(F(F(F(F(F(F`_lF(F(,(F]
vFdvF\vFivFdxF\w7$7%F(FMF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,(F^yFayFcvFdvFevFfvF(F(F(
F(F(Fg_lF(F(,(FdxFfwF\vFgwF]vFfvF(F(Fh_lF(7$7%F(F9F9X,F*6"F,[gl!"%!!!#1"%"%,4F_
]lFfsFa[l#F9FMF\\lFHF][lFHF_[lFHF]vF8FcyFfs*&,&F_rFEFgr#FBFjxF'F6F7FB*&F6F7,&F_
rFHFgr#F'FjxF'F'F(F(,4Fe\l#FMFh\lFcvFfvFczFdzF^yFdzFgzFdv*&,&FasFfsFjqFatF'F6F7
FBF^\l#F'Fiu**FAFBFFF'F6FizF]pFHFat**F6FizF]pFHFdtF'FAFBFfsF(,,Fj\lFfwFa[l#F^pF
jvF][lF^^lF_[lF^^lFeyFfwF(F(F(F(Fb_lF(,4F^\lFi`lFgzFdvFj`lFatFczFdzF[alFfsF^yFd
zFcvFfv*&F6F7,&FasFatFjqFfsF'F'Fe\lFf`lF(F(,&Fi[lF\wF\vFiv7$7%F(F'FMX,F*6"F,[gl
!"%!!!#1"%"%F(F(,4Fe\lFg\lFcvFdvFczFd\lFgzFfvF^yFd\lF_alFBF^\lFb\lFj`lFfsF[alFa
tF(F(F(F(F(,4F^\lFb\lFgzFfvFj`lFfsFczFd\lF[alFatF^yFd\lFcvFdvFg`lF'Fe\lFg\lF(F(
,&Fi[lFfwF\vFgwF(F(FhalF(7$7%F(F(FcpX,F*6"F,[gl!"%!!!#1"%"%,,Fj\lFfsFhvFLF\\lFH
*&,&F`pFEFcsFa`lF'F6F7FB*&F6F7,&F`pFHFcsFd`lF'F'F(F(F(F(F^]lF(F(F(F(FaalF(F(F(F
(F(777$7%FbvF(F(X,F*6"F,[gl!"%!!!#1"%"%,(**F]pFHF6Fes,(F]rF]wF6!#%)"#")F'F'FAFB
#FBFgx**F@F9FAFGF6FesF]pFH#FesFgx**FAFGFFF'F6FesF]pFH#"#jFgxF(F(,(*.F]pFHFFFHF6
FesFIFH,&F6Fgx!#FF'F'FAFEFat*.F@F'FAF7F6FesFIFHFFFHF]pFHFB*,FAF7FFFHF6FguFIFHF]
pFHF'F(F(F(F(F(F(,&*&F6FesF]pFH#F9"#:*(F]pFHFdclF'F6Fes#FBF[dlF(FbclF(F(,(F_clF
jy*(FAFGF6F[rF]pFHFjcl**FAFBF6FguFdclF'F]pFHF]dl7$7%FcpF'F(X,F*6"F,[gl!"%!!!#1"
%"%F(F(F(F(F(F(,&F\dl#F'F[dlFicl#FGF[dlF(F(FedlF(F(F(F(F(F(7$7%FcpF(F'X,F*6"F,[
gl!"%!!!#1"%"%F(,(FcclFfsFfclF'FgclFBF(F(F\elF(F(,(F`dlFfdlF_clF[[lF_dlFgdlF(F(
F(F(F(F]elF(F(7$7%FMF9F(X,F*6"F,[gl!"%!!!#1"%"%,>F`dl#F'Fgx*,F]pFHF6FesFdtF'Fdc
lF'FAFBFdz**F6FesF]pFH,(F]rF]wF6!#n"#`F'F'FAFB#F'F]w*,F6FesF]pFHFdtF',&F6FbvFjz
F'F'FAFBFdv**F]pFHF6Fes,(F]rF]wF6!#t"#gF'F'FAFBFielF_cl#!#")Fgx**F@F'FAFBF6F8,&
FjqF'FgpFHF'F'**F6FesF]pFH,(F]rF]wF6!#p"#bF'F'FAFBFiel*,F]pFHF6FesFdtF',&F6FbvF
]]lF'F'FAFBFdv**FAFGFFF9F6FgyF]pFE#F]]lFbv*,FAFEFFFHF6F8FIFH,&F_rFGF`pF7F'F`r*,
,&F_rF9F`pF`rF'FAFEFFFHF6F8FIFHF7**F]pFHF@F'FAFGF6Fgu#FcqFgx*,F@F'FAFGF6FgyF\rF
'F]pFEFdvF(F(,8*.F6FesF]pFHFIFHFFFH,&F6"#NF^flF'F'FAFE#F'"#C*.F@F'FAF7F6FgyFFF`
rFIFHF]pFEFL*.FAFEFFFHF6FesF]pFHFIFHF[flF'#"#BFhgl*.F]pFHFIFHF6FesFFFHFiflF'FAF
EF[hlFccl#F[\lFa\l*,FAF7F6FesFFF`rFIFHF]pFEFa`l*.FAF7FFFHF6FgyFIFHF\rF'F]pFEFat
*,FAFEFFFHF6F8FIFHFcflF'FH*(FAFBF6FGF]glF'Fd`l**F@F'FAFBF6F8,&F_rF'F`pF`[lF'FH*
,,&FjqFHF\pFfsF'FAFEFFFHF6F8FIFHF7F(FhclF(F(F(F(,(*(F6FesF]pFHF[flF'FfdlFiclFjc
l*(F]pFHFiflF'F6Fes#F'"#IF(,8FdglFgglF`hlFatF_hlFa`lFjglF[hlF]hlF[hlFcclF^hlFig
lFLFchlFH*,FAFEFFFHF6F8FIFH,&FjqFEF\pFatF'F`rFahlFH*(F_glF'FAFBF6FGFa`lF(F(,>**
F]pFHF6Fes,(F]rF[dlF6!#YFhglF'F'FAFBFjhl**F]pFHF6Fes,(F]rFbvF6!#<Fa\lF'F'FAFB#F
cpF[dl**F6FesF]pFH,(F]rF[dlF6!#TF]wF'F'FAFBFjhl**F]pFHF6Fes,(F]rFgxF6!#PF[vF'F'
FAFBFjcl*(FAFBF6FGF^ilF'Fd`l*(FfhlF'FAFBF6FGFa`lF_cl#"#LF]w**F6FesF]pFH,(F]rFbv
F6F`\lF\]lF'F'FAFBFgilFjflFav**F6FesF]pFH,(F]rF[dlF6!#V"#AF'F'FAFBFjhl*,FAFEFFF
HF6F8FIFHFdhlF'F'**FAFGF6FesF\rF'F]pFEF\clF`gl#FjzF_flFhblFfdl7$7%FMF'F'X,F*6"F
,[gl!"%!!!#1"%"%F(F(,HFjgl#FfxFhgl*.FIFHFFFH,(F6Ffil"#9F'F]rFbvF'F]pFEF6FgyFAFE
#FBFhglF]hlF`[mFiglFa`lF`hlFfsFfcl#FBFa\l*,,(FjqFatFjrFatF\pFatF'FAFEFFFHF6F8FI
FHF7*,FIFHF]pFEF6FgyFFF`rFAFE#F'Fa\l*.F6FgyFFF`rFIFH,&FbpF'F6FbvF'F]pFEFAFEFd[m
*&F`vF'F6#!#:F9Ff`l*.FFF`rFIFHFf\lF'F]pFEF6FgyFAFEFd[m*&,&F[wFg\lFhv#F'"$?"F'F6
F7FBFcclFE*,F6FesFIFHFFFHF]pFHFAFE#"#VFhgl*,FAF7FFF`rF6FesFIFHF]pFHFfs*.F]pFHFF
FHFIFHFf\lF'FAFEF6FesFd[m**F@F'FAFBF6F8,&F_rFEF`pFBF'FH*&F6F8,(F`pF9FgrFa`lF_rF
'F'Fd`l*$F6F]\m#FBFc\mF(F(F(F(F(,HFjglF`[mFa[mFd[mF]hlF`[mFiglFa`lF`hlFfs*&,(F`
pFGFgrFd`lF_rFBF'F6F8Fa`lFfclFe[m*,FAFEFFFHF6F8FIFH,(FjqFfsFjrFfsF\pFfsF'F`rFh[
mFi[mFj[mFd[mF\\mFf`lF_\mFd[m*&F6F7,&FhvF^]mF[wFf`lF'F'FcclFEFd\mFe\mFg\mFfsFh
\mFd[mFi\mFHF]]mF^]mF(F(,P**F]pFH,(F[ilF'F]rFbvF6!#AF'F6FesFAFB#FBF[il*&Fg[mF'F
6F8Fa`lFdilFgdl*,FAFEFFFHF6F8FIFHFj\mF'FH*,FAFBFFF'F6FesF]pFHF[flF'Fa`l**FAFGF6
FguFFF'F]pFH#F'Fh\l**F6Fgy,*F6"#h!#UF'*$F6FMFbvF]rFjuF'FAFBF]pFEFj]m**F\rF'F6Fg
yFAFBF]pFEF_^mF[jlF]dl**,*F6"#o!#_F'Fd^mFbvF]r!#JF'F6FgyFAFBF]pFEFj]m*,F]pFHFFF
'F6FesFAFBFdclF'F]dlF_cl#FbpFgx*(F]pFHF6FguFAFBFjcl**,*F6"#k!#[F'Fd^mFbvF]rFjuF
'F6FgyFAFBF]pFEFj]mFbjlFgdlFjflFfw**F6FesFAFBFFF'F]pFHF_^m*,F]pFHFAFBFFF'F6FesF
iflF'Fa`lFijlF_^mF`gl#F\]lFc\mFhblF]dl*(FAFBF6FGFc]mF'Fd`l**F]pFHF6FesF@F'FAFBF
d_mF(F(,PFg]mFj]mFdilFgdlF\^mFHF]^mFa`lF^^mF_^mF`^mFj]mFe^mF_^mF[jlF]dlFf^mFj]m
F[_mF]dlF_clF\_mF]_mFjclF^_mFj]mFbjlFgdlFjflFfw*(Fg[mF'FAFBF6FGFa`lFb_mF_^mFc_m
Fa`lFijlF_^mF`glFd_mFhblF]dl*&F6F8Fc]mF'Fd`lFf_mFd_mF(7$7%FMF(F9X,F*6"F,[gl!"%!
!!#1"%"%,H*,FAFEFFFHF6F8FIFHF_blF'F`r*,FablF'FAFEFFFHF6F8FIFHF7F\dlFcel*,F@F'FA
FGF6FesFFF'F]pFHFdzF]^mFdv**,*Fd^mF]wF]r!#(*F6"$_"!#wF'F'F6FgyFAFBF]pFEFiel**F@
F'FAFBF6F8,*FjrFHF`sFHFasFHFepFHF'F'*,F@F'FAFGF6FgyFFF9F]pFEFdzF[_mFdzF_cl#"$B"
F]w**F]pFH,*Fd^mF]wF]r!$B"F6"$E#!$E"F'F'FAFGF6FesFiel*,FFFHF6F]\mFIFHF`vF'FAFEF
d^l*&F6F7,(F_v#FMFiuFcvFi`lFevFb\lF'F'Fjfl#FbpF]w**,*Fd^mF]wF]r!#**F6"$g"FjblF'
F'F6FgyFAFBF]pFEFiel*&,&FcvF8FevFMF'F6F7#FBF_flFc_mFdv*&,(F_v#F8FiuFcvFb\lFevFi
`lF'F6F7FBFf_mFaglF(F(,L*.F]pFHFIFH,*!$;#F'F]r!$m"Fd^m"#DF6"$S$F'FFFEF6FesFAF7F
_^mFjglFd`l*,FAFEFFFHF6F8FIFHFh`mF'FHFgcl#"#RFh\lF]hlFd`l*.,(F]rFebmF6FjblFh^mF
'F'FFFHFIFHF6FgyFAFEF]pFEF_^mFiglFjclFfclFf`l*(FAFBF6FGF_blF'Fd`l*.,&F6Febm!#LF
'F'FIFHFFF`rF6FgyFAFEF]pFE#F'F_fl*.,(F]rFebmF6!#$)"#mF'F'FFFHFIFHF6FgyFAFEF]pFE
F_^m*.F]pFHFFFHFIFH,(F6!$;""$3"F'F]rFebmF'FAF7F6FesF`cmFcclFi[m*&,(F`wFg\lF]vFg
\lF_wFb\mF'F6F7FB*.,&F6Febm!#MF'F'FIFHFFF`rF6FgyFAFEF]pFEF`cm*,FAF7FF#FbvF9F6Fg
yFIFHF]pFEFi`lFd\mF`[lFg\mFi`l*&,&F]vFcqF_wFBF'F6F7Fb\m*(F6#FfxF9FAFBF`vF'Ff`lF
_hlF\bmF(F^dlF(F(F(F(,8**,*F6"$!=Fd^mF[dlF]r!#"*FgcmF'F'F6FgyFAFBF]pFEFjhlFb_mF
\clFf_mFjjl**,*F6"$)=!$C"F'Fd^mF[dlF]r!#$*F'F6FgyFAFBF]pFEFjhl**F]pFH,(FgjlF'F]
rFbvF6Fi]mF'F6FesFAFBFcelF]^mFgilFc_mFgilF[_mFjclFhblFfdl*&F6F8,&FjrFEF\pFatF'F
d`l*&,&FjrFHF\pFfsF'F6F8Fa`lF(,LFabmF_^mFjglFd`lFgbmFHFgclFhbmF]hlFd`lFjbmF_^mF
iglFjclFfclFf`l*&F6F7,(F]vFf`lF_wF^]mF`wFf`lF'F'*(FablF'FAFBF6FGFa`lF]cmF`cmFac
mF_^mFecmF`cmFcclFi[mF[dmF`cmF^dmFi`lFd\mF`[lFg\mFi`lF`dmFb\mFbdmFf`lF_hlF\bmF(
F(,,*,,(F]rFbvF6Fcp!#?F'F'FFF'F6FgyFAFBF]pFEFfdlFjflF^^l**F]pFH,*F6!#Q"#sF'Fd^m
FbvF]rF]]lF'FAFGF6FesFjhlF_dlFjclF_clFcel7$7%F9FMF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F
(F(F(F(,(FhhlF]dlFihlFj]mFiclFgdlF(F(FdfmF(F(F(F(F(F(7$7%F9F9F'X,F*6"F,[gl!"%!!
!#1"%"%F(,TFjgl#F[rFa\lFa[mFgglF]hlFjfmFiglFg\lF`hl#FBFh\lFfclFgdlFh[mFe[mFj[mF
gglF\\mFg\lFbhlFa`lF_\mFgglFd]mFBFcclFe[m*.F6FesF]pFHFIFH,(F]rFfglF6!$V""$Y"F'F
'FAFEFFFEF\bmFahlFEF^dm#FbpFh\lFd\m#FfjlFhglFg\mF[gmFh\mFgglFdglF[gm*.FAF7FFFHF
6FesFIFHF]pFHFdtF'F_^mF[]mFa`l*,,&FjrFfsFctFatF'FAFEFFFHF6F8FIFHF7F]]mFb\mF_hlF
d`lF(F(,TFjglFjfmFa[mFgglF]hlFjfmFiglFg\lF`hlF[gmF`]mFd`lFfclFgdlFh[mFe[mFj[mFg
glF\\mFg\lF_ilFd`lF_\mFgglF`\mF'FcclFe[mF\gmF\bmFahlFEF^dmF`gmFd\mFagmFg\mF[gmF
h\mFgglFdglF[gmFbgmF_^m*,FAFEFFFHF6F8FIFH,&FjrFatFctFfsF'F`rF]]mFb\mF_hlFd`lF(F
(,ZFg]mFjhlFailFj]mF[^mFd`lFdilFgdlF]^mFd`lFhilFj]mF^^mF^]mF`^mFjhlFe^mF[gmF[jl
F]dlFf^mFjhlF_jlFd`lF[_mFfdl*(FAFBF6FGFggmF'Fd`lF_cl#!#RFh\lF]_mFgdlF^_mFjhl**F
AFGF6FguF]pFHFdtF'Fb\mFbjlFgdlFjfl#FesF]wFdjlFj]mFhjlFEFb_mF[gmFc_mFd`lFijlFfdl
F`glFd_mFf_m#FjzFc\m**FAFGFFF9F6FesF]pFEF\bmF(F(F(F(F(,ZFg]mFjhlFailFj]mFdilFgd
lF]^mFd`l*(FdgmF'FAFBF6FGFa`lFhilFj]mF^^mF^]mF`^mFjhlFe^mF[gmF[jlF]dlFf^mFjhlF^
jlFa`lF[_mFfdlF_clFjgmF]_mFgdlF^_mFjhlF\hmFb\mFbjlFgdlFjflF]hmFdjlFj]mFhjlFEFb_
mF[gmFc_mFd`lFijlFfdlF`glFd_mFi_mFa`lFf_mF^hmF_hmF\bmF(F(7$7%F9F'F9X,F*6"F,[gl!
"%!!!#1"%"%F(F(F(F(F(F(,ZFg]mFjhlFdilFjclF\^mFEF]^mF\clF^^mF[gmF`^mFjhlFe^mF\bm
F^emF\clF[jlFfdlFf^mFjhlF[_mF]dlF_clFaglF]_mFgdl**F6FesF]pFHFdtF'FAFBF^]mF^_mFj
hlFbjlFjclFjflF\w*&F6F8FdgmF'Fd`lFidmFj]mFedmFj]mFh_mFd`lFb_m#F[\lFc\mFc_mF\clF
ijlF[gmF`glF^hm**FFF9F6FgyFAFBF]pFEF`cmFbemFd`lFf_mFd_mF(F(,ZFg]mFjhlFdilFjclF
\^mFEF]^mF\cl*&FggmF'F6F8Fa`lF^^mF[gmF`^mFjhlFe^mF\bmF^emF\clF[jlFfdlFf^mFjhlF[
_mF]dlF_clFaglF]_mFgdlFghmF^]mF^_mFjhlFbjlFjclFjflF\wFidmFj]mFedmFj]mFb_mFihmFc
_mF\clFijlF[gmF`glF^hmFjhmF`cmFe_mFa`lFf_mFd_mF`emFa`lF(F(F(F(F(F(7$7%F9F(FMX,F
*6"F,[gl!"%!!!#1"%"%F(,DFabmFd[mFjglFa`lFgbmFEFgclFjgmF]hlFa`lFjbmFd[mFfcl#F[rF
hglFeemFBF\cmFa`l*&,&F]vFbpF_wF'F'F6F7Fb\mFacmFd[mFcclFe[mF^dmFb\lFd\mF_uFg\mFb
\lFbdmFg\lF_hlF`cmF(F(,DFabmFd[mFjglFa`lFgbmFEFgclFjgmF]hlFa`lFjbmFd[mFfclFbimF
gemFd`lFcimFb\mFacmFd[mFcclFe[mFicmF'F^dmFb\lFd\mF_uFg\mFb\lFbdmFg\lF_hlF`cmF(F
(,,F_clFatFiemF]dlF_dlFgdlF\fmFj]mFjflFfwF(F(F(F(F(FfimF(F(7$7%F'FcpF(X,F*6"F,[
gl!"%!!!#1"%"%,8*,F6Fgy,&F6F[dlFj^mF'F'F\rF'FAFBF]pFEF\clFjfl#Fa\lFbvFijlFfvFhi
l#FBF]wF_cl#FcqFbvF_dlFd\lFdjlF_jmFailF_jm*(FcflF'FAFBF6FGFBF^glF`rF\glF7F(F(,<
*.F6FgyFIFHF]pFEFFF`rFAFEF]jmF'Fa`lFiglFd`lF`hlFfsFdglFd[mF_hlFUFgclF_bmFfclFda
mFjgl#FesFhglF]hlFdjm*(FdhlF'FAFBF6FGFEFehlF`rFahlFE**F@F'FAFBF6F8F]glF'Fa`lF(F
ghlF(F(F(F(F(F(,<FcjmFa`lF`hlFfsF_hlFUFdglFd[mFiglFd`lFgclF_bmFfclFdamFjglFdjmF
]hlFdjmFahlFE**F_glF'F@F'FAFBF6F8Fd`lFejmFEF]ilF7F(F(,8*.F6FgyFFF'F]jmF'FdtF'FA
FBF]pFEF]dlFjflF]xFbglFcelFeelFj]mF_clFeamF]clFielFdflFj]mF\flFj]mFhjlFB**FfhlF
'F@F'FAFBF6F8Fd`l**F@F'FAFBF6F8F^ilF'Fa`l7$7%F'FMF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,
PFjgl#"#>Fc\mFgcl#F\]lFhglF]hl#F[\lF_flFiglFa`lFfclF_bmFf[mF`rFh[mF[gm*(Fj\mF'F
AFBF6FGFEFj[mFggl*.F]pFHF6FesFIFHFAFEFFFE,(F]rFbvF6Fi]mFhglF'F'#F[\lFh\lFfjmFd`
l*&,&FcyFf`lFhvFb\mF'F6F7FB*.FFF`rFIFH,&FgyF'F6FbvF'F]pFEF6FgyFAFEFggl*&F6F8Fc`
lF'Fa`lFahlFHFd\mF\bmFg\mFatFdglFgglFcjmFi[m*&FFF'F6F]\mFg\lF]]mF^]mF_hlFd`l*.F
6FesF]pFHFIFHFAFEFFFE,(F]rFbvF6!#@FgjlF'F'Fi[nF(F(F(F(F(,PFjglFb[nFgclFd[nF]hlF
e[nFiglFa`lFfclF_bmFb]mF7Fh[mF[gm*&F6F7,&FcyFg\lFhvF^]mF'F'*&F``lF'F6F8Fd`lFf[n
FEFj[mFgglFhjmFa`lFg[nFi[nF\\nFgglFahlFHFd\mF\bmFg\mFatFdglFgglFcjmFi[mF_\nFg\l
F]]mF^]mF_hlFd`lF`\nFi[nF(F(,LFeelFjhlFa`mF[gmF\^mFEF]^mFjhl*&Fh`lF'F6F8Fd`lF\f
lFjhlF`^mFjhlFe^mF^]m**F@F'FAFBF6F8Fc]mF'Fa`lFjjmFjhlF]clF_jmF_cl#"#@Fh\lFghmF
\bmFdflFjhlFjflFd^lFhjlFHF[[nFa`l**,*F6"#i!#WF'Fd^mFbvF]rFjuF'F6FgyFAFBF]pFEFjh
lFb_mF`cmFjhmFb\mFbglFg\lF(F(,LFeelFjhlFa`mF[gmF\^mFEF]^mFjhlF\flFjhl**Fg[mF'F@
F'FAFBF6F8Fd`lF`^mFjhlFe^mF^]mF\[nFd`lFjjmFjhlF]clF_jmF_clFj\nFghmF\bmFdflFjhl*
&F6F8F`alF'Fa`lFjflFd^lFhjlFHF\]nFjhlFb_mF`cmFjhmFb\mFbglFg\lF(7$7%F'F9F9X,F*6"
F,[gl!"%!!!#1"%"%,do*&F6F7,,FczFi`lF^y#F[rFcpFgzFatFhzFatF_vFb\lF'F'F_`mF7F``mF
`r*,FIFHFFFHFdtF'F6F]\mFAFEF\wFihlF_jm**FAFEFFF`rF6F]\mFIFHF7Fg]mF\cl**FIFHFFFH
F6F]\mFAFEF\clF]^mFfw**F]pFHFAFBF6FesFh[nF'F_jmF^^mFd\lF`^mFd\l*&FcflF'F6F8FBFe
^mFfv**,*Fd^mFbvF]rF[fmF6FhglFgyF'F'F6FgyFAFBF]pFEF\cl*,F6FgyFAFBFFF9F]pFEF[flF
'F_jmFf^mF\cl*&,,FczFb\lF^y#FbvFcpFgzFfsFhzFfsF_vFi`lF'F6F7FBFhhlF\clF_cl#F[]nF
gx*(Fh`mF'FAFBF6FGFBF]_mFfvFaamFfw*,F``lF'FAFEFFFHF6F8FIFHF`r*,FAFEFFFHF6F8FIFH
F\]mF'F`rF^_mF\cl*,Fa]mF'FAFEFFFHF6F8FIFHF7*,FAFEFFFHF6F8FIFHFc`lF'F7FjflF`rF\]
nF\clFc_mF_jm**,*Fd^mFbvF]rFb\nF6"#GF]]lF'F'F6FgyFAFBF]pFEF\cl**F6Fgy,*Fd^mFbvF
]rF[fmF6F\hlFguF'F'FAFBF]pFEF\clF\fmF_jmF_hmFd\lFiemF\clF(F(,`p*(F^[lF'F6F]\mFA
FBFf`lFabmF[gmFjglF]dlFa[mFb\lFgbmFEFgclF^hm*(FAFBFFF9F6F]\mFdamF]hlFd[mFjbmF[g
mFiglFcelF`hl#FcqFh\lFfcl#FhelFc\mFf[mF7Fh[mFU*.F6FgyFFF`rFIFHF[flF'FAFEF]pFEF
\bm**F6F]\mFFF'FdtF'FAFBF]zFj[mFe[m*&FdhlF'F6F8FE*.FdtF'FIFHFFF`rF6FgyFAFEF]pFE
#F[rFjxF]cmF\bm*&,6F][lFg\lF_[lF_bmFc[lFb\mFb[lFg\lFa[lFb\mFeyFf`lF]vFf`lFhxF^]
mF[yF^^lF[zFf`lF'F6F7FB*&,&F]vFbpFhxF'F'F6F7Fb\mFacmF[gmF_\mFdjmFecmF\bm*(F6F]
\mFfyF'FAFBFg\lF\\nFd[mF[dmF\bm*,Fh`lF'FAFEFFFHF6F8FIFHF`r*(F6F]\mF@F'FAFBF^]m*
&F6FcdmFAFBF^]mF^dmF\cl**F@F'FAFBF6F8F\]mF'Fd`lFd\mF_bmFg\m#F[\lF]wFh\mFd[mFbgm
F`gm*(F6F]\mF\zF'FAFBFg\l*(FAFBF6FGFc`lF'Fa`l**F@F'FAFBF6F8F_blF'Fa`lF_hl#!#>Fc
\m**FFF'F6F]\mFAFBF`vF'Ff`lF(,XFg]mF]dlFailFjhlF]^mF]dlFahmFd`lFhilFjhlF\imFd`l
F^^mF`cmF`^mF]dlFe^mFjhlF^emFcelFf^mF]dlFigmFa`lF_clF^^lF]_mFgilFghmF`cmF^_mF]d
lF\hmF\bmFjflFcelFdjlFjhlFhhmFa`lFidmFjhlFedmFjhlFb_mF\bmFc_mF]dlFijlFj]mFjhmFj
]mF_hmFjhlF(F(F(F(,JFeelFj]mFa`mFielF\^mF'F]^mF]dlFh\nFa`lF\flFj]mFa]nFa`lF`^mF
]dlFe^mF`cmFi\nFd`lF]clFielF_clF]xFghmFjhlFdflFj]mFb]nFd`lFjflF]zF\]nF]dlFb_mFj
]mFjhmF\bmFbglFielF(,`pFb_nFf`lFabmF[gmFjglF]dlFa[mFb\lFgbmFEFgclF^hmFc_nFdamF]
hlFd[mFjbmF[gmFiglFcelF`hlFd_nFfclFe_nFb]mF`rFh[mFUFf_nF\bm**Fa]mF'F@F'FAFBF6F8
Fa`lFg_nF]zFj[mFe[mFh_nFEFi_nFj_nF]cmF\bmF]`nFb\mFacmF[gmF_\mFdjm**FablF'F@F'FA
FBF6F8Fd`lFecmF\bmF_`nFg\lF\\nFd[mF[dmF\bmFa`nF^]m*,FAFEFFFHF6F8FIFHF`alF'F7Fb`
nF^]mF^dmF\clFd\mF_bmFg\mFd`nFh\mFd[mFbgmF`gm*&F6F7,6F][lFf`lF_[lFdamFc[lF^]mFb
[lFf`lFa[lF^]mFeyFg\lF]vFg\lFhxFb\mF[yF]zF[zFg\lF'F'Fe`nFg\l*(F``lF'FAFBF6FGFd`
lF_hlFh`nFj`nFf`lF(F(,HFa`mFielFa]nFa`lFb`mFj]mF^^mFjhl*,,(F]rFbvF6!#5FcpF'F'FF
F'F6FgyFAFBF]pFEF]dlFi\nFd`l*,F6Fgy,(F]rFbvF6FganFMF'F'FFF'F]pFEFAFBF]dlF]clFie
lF_clF\clF\amFj]mF\hmFj]mFjflF]zFfamFj]mFijlF\bmF_hmF`cm*(FAFBF6FGF`alF'Fa`l*(F
h`lF'FAFBF6FGFd`lFbglFiel*,,(F]rFbvF6FjzFjxF'F'FFF'F6FgyFAFBF]pFEF]dl7$7%F'F'FM
X,F*6"F,[gl!"%!!!#1"%"%F(F(,\pFb_nFf`lFabmF_^mFjglFgglFa[mFgglFgbmFHFc_nF`gmF]h
lFgglFiglF\clF`hlF_^mFfcl#!#`Fc\m*.,*Fd^mFebmF]r!$M"F6"$O#!$O"F'F'FIFHFFFEF6Fgy
FAFEF]pFEF_^m*,FcemF'FAFEFFFHF6F8FIFHF7*&F6F8FablF'Fa`lFh[m#FbvFa\l*&Fj\mF'F6F8
FE*(F[]lF'F6F]\mFAFBFg\lFg_nF^^lFj[mFgglFi_nF^hl*.,&F6F[dlFi`nF'F'FIFHFFF`rF6Fg
yFAFEF]pFEFgglF]cmF`cmF_\mFi`lFecmF`cmF[dmF`cmFa`nFb\m*&,&F]vFcqFhxFBF'F6F7Fb\m
F`anF`r*.,*Fd^mF'F]rF[rF6FiuF^pF'F'FIFHFFFEF6FgyFAFEF]pFEFfsFb`nF^]mF^dmFcelFc`
nFa`lFd\mF\cnFg\mF]xFh\mFgglFbgmFd_n*&,6Fj\lFf`lFc[lF^]mF_[lFd_nFb[lFf`lF][lFg
\lFhxFb\mF]vFg\lF[yF]zF[zFg\lFa[lFb\mF'F6F7FBFe`nFf`lFg`nFd`lFj`nFg\l*.,*Fd^mFe
bmF]r!$L"F6"$K#!$K"F'F'FIFHFFFEF6FgyFAFEF]pFEF_^mF(F(F(F(F(,\pFb_nFf`lFabmF_^mF
jglFgglFa[mFgglFgbmFHFc_nF`gmF]hlFgglFiglF\clF`hlF_^mFfclFcbnFebnF_^m*,FAFEFFFH
F6F8FIFHFaemF'F`rFh[mF\cnF]cnFEF^cnFg\lF^anFd`lFg_nF^^lFj[mFgglFi_nF^hlF_cnFggl
F]cmF`cmF_\mFi`l*&F6F7,6Fj\lFg\lFc[lFb\mF_[lF`gmFb[lFg\lF][lFf`lFhxF^]mF]vFf`lF
[yF^^lF[zFf`lFa[lF^]mF'F'F_anFa`lFecmF`cm*&F_blF'F6F8Fd`lF[dmF`cmF``nF7Fa`nFb\m
FacnFb\mFccnFfsFb`nF^]mF^dmFcelFd\mF\cnFg\mF]xFh\mFgglFbgmFd_nFe`nFf`lFj`nFg\lF
gcnF_^mF(F(,JFa`mFg\lFa]nFd`lFb`mFjhlF^^mF\bmFeanFjhlFhanFjhlF]clF_jmF_clFielF
\amFjhlF\hmF`cmFjflF\wFfamFjhl**F@F'FAFBF6F8FaemF'Fd`l*,,&F6F[dlF`\lF'F'FFF9F6F
gyFAFBF]pFEFjhlFijlFb\mF\_nF`cmF_hmF^]mF[bnFa`lFbglF[gmF\bnF`cmF(F(,J**FcemF'F@
F'FAFBF6F8Fa`lFa`mFg\lFb`mFjhlF^^mF\bmFeanFjhlFi\nFa`lFhanFjhlF]clF_jmF_clFielF
\amFjhlF\hmF`cmFjflF\wFfamFjhlFcdnFjhlFijlFb\mF\_nF`cmF_hmF^]mFjanFd`lFbglF[gmF
\bnF`cmF(7$7%F'F(FcpX,F*6"F,[gl!"%!!!#1"%"%,HF_`mF`rF``mF7F\^nF]xF]^nF_jm**,*Fd
^mF[dlF]rFf`mF6"$C"!#kF'F'F6FgyFAFBF]pFEF_jmF^emFfwF_clF]xFaamFfwFiclFd\l**FAF7
FFFHF6FcdmFIFHF_jm*,F_\lF'FIFHF6F]\mFFFEFAFEFfwFidmF_jmFedmF_jm*&F6F7,.F^\lFb\l
FgzFb\lF^yFEFc\lFatF_vFb\lFevFb\lF'F'*&Fh`mF'F6F8FB*&,.F^\lFi`lFgzFi`lF^yFHFc\l
FfsF_vFi`lFevFi`lF'F6F7FBFb_mFd\lFcdnF_jmFjhmFd\lF(F(,4*.,*Fd^mF[dlF]r!#zF6"$O"
Ff`mF'F'FIFHFFFEF6FgyFAFEF]pFEF\bmFh[mFgdlFgclFd[m*&,&F_]lFf`lF_wFb\mF'F6F7FBFg
emFa`lF_cnF[gmFd\mFg\l*(F`]lF'F6F]\mFAFBFg\l*&FAFGF6FizF^]mF(,*F_clFdvFiemFfdlF
_dlFjclF\fmFjhlF(F(F(F(,2FcdnF]dlFa`mFcelFb`mFj]mF]clFielFfamFj]mF\amFj]mFfdnFd
`lFbdnFa`lF(,4F_cnF[gmFgclFd[mFd\mFg\lF^fnFg\lF_fnF^]mF\cmFd`lFh[mFgdl*&F6F7,&F
_]lFg\lF_wF^]mF'F'FhenF\bmF(F(F(7$7%F(FbvF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(F
(F(F(F(F(F(F(F(F(F(7$7%F(FcpF'X,F*6"F,[gl!"%!!!#1"%"%F(,HF\\nFd[mFgclFjclFg\mF_
^mFj[mFd[mFbgmF[gmFjglF\bmFd\mF`cm*.FIFHF6FesFAFEFFFHF]pFHF]jmF'FjhlFd\nFBFcgmF
`rF^\nFd`lFh[mF_^mF_\nFf`lF]]mFb\mFf_nF[gmF_hlFf`lF^dmFd_n*.F6FgyFIFHF]pFEFAFEF
FFH,(F]rF[dlF6!#hF^]nF'F'FielF`hlF`gmF(F(,HF\\nFd[mFh[mF_^mF_\nFf`lF]]mFb\mFj[m
Fd[mFf_nF[gmF_hlFf`lF^dmFd_nF_gnFielF`hlF`gmFf\nFa`lFgclFjclFfgmF7Fj[nF'Fg\mF_^
mFbgmF[gmFjglF\bmFd\mF`cmF^gnFjhlF(F(,FFjhmF^]mFjflFielFi`mF`cmFe^mFb\mF\]nFj]m
F`^mFj]mFb^nF\bmFbglF\bm**F6Fgy,*F]rFf`mF6F[am!#iF'Fd^mF[dlF'FAFBF]pFEF`cmFh\nF
a`lF_clF\w**F@F'FAFBF6F8FggmF'Fa`lFa`mFb\m*,F@F'FAFGF6FesF]pFHFdtF'F^]mF]^mF\bm
Fb_mF\bm**F6FesF]pFH,(F]rF[dlF6Fcil"#JF'F'FAFBF`cmFghmF`cmF(F(F(F(F(,FF\]nFj]mF
_clF\wFa`mFb\mF`^mFj]mFhgnF^]mF]^mF\bmFb_mF\bmFignF`cmFghmF`cm**FdgmF'F@F'FAFBF
6F8Fd`lFb]nFd`lFjhmF^]mFjflFielFi`mF`cmFe^mFb\mFb^nF\bmFbglF\bmFdgnF`cmF(F(7$7%
F(FMF9X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,FF\]nFjhlFjhmFb\mF`^mFjhlFb^nF`cmFe^m
F^]mFjflF_jmFi`mF\bmFdgnF\bmFbglF`cmFb]nFa`lF_clFfwFggnFd`lFa`mF^]mFhgnFb\mF]^m
F`cmFb_mF`cmFignF\bmFghmF\bmF(F(,FF\]nFjhlF_clFfwFa`mF^]mF`^mFjhlFhgnFb\mF]^mF`
cmFb_mF`cmFignF\bmFghmF\bmF]hnFa`lFh\nFd`lFjhmFb\mFb^nF`cmFe^mF^]mFjflF_jmFi`mF
\bmFdgnF\bmFbglF`cmF(F(F(F(F(F(7$7%F(F9FMX,F*6"F,[gl!"%!!!#1"%"%F(,VFb_nFfwFjgl
FgglFgclFd_nFc_nFfwF`hlF`gm*.,&FesF'F6FbvF'FIFHFFF`rF]pFEFAFEF6FgyFjhlF[cnFd`lF
h[m#FesFh\lF^cnFf`lFj[mFgglF_cnF\bmF_\mFe[n*.F_\lF'FFFHFIFHF6FgyFAFEF]pFEFiel*.
FIFH,*F]rFeclF6"#[!#GF'Fd^mFbvF'F]pFEF6FgyFAFEFFFEFielF_`nFf`lF\\nFgglFb`nF`cmF
^dmFd_nFd\mFi[nFg\mF_^mFbgmF[gm*.,(F]rF[dlF6!#\"#QF'F'FFFHFIFHF6FgyFAFEF]pFEF[g
mFfgmF7Ff`nFd`lF_hlF_^m*&,,Fj\lFg\lFa[lF\bmF][lF\wF_[lF\wFeyFg\lF'F6F7FBF(F(,VF
b_nFfwFjglFgglFgclFd_nFc_nFfwF`hlF`gm*&F6F7,,Fj\lFf`lFa[lF`cmF][lFfwF_[lFfwFeyF
f`lF'F'FihnFjhlFh[mF[inF^cnFf`lFj[mFgglF_cnF\bmF_\mFe[nF\inFielF]inFielF_`nFf`l
F\\nFgglF`dnFa`lFb`nF`cmF^dmFd_nFd\mFi[nFg\mF_^mFbgmF[gmFainF[gmFcgmF`rFcanFa`l
F_hlF_^mF(F(,F*,,(F]rF[dlF6Fcil"#KF'F'FFF'F6FgyFAFBF]pFEF\bmFi`mF`cmF\_nFjhlF_h
mF^]mFbglF\bmFeanF`cmF_clFdzFhanF`cmFijlFb\mF[bnFa`lF]hnFd`lFcdnF\bmF^^mF\bmF\h
mF`cmF`^nF`cmFa`mFb\mF__nF`cmFhgnF^]mF(F(F(F(F(,FFcdnF\bmF_clFdzF^^mF\bmF\_nFjh
lF\hmF`cmF`^nF`cmFa`mFb\mF__nF`cmFhgnF^]mFggnFa`lFjanFd`lF[jnF\bmFi`mF`cmF_hmF^
]mFbglF\bmFeanF`cmFhanF`cmFijlFb\mF(F(7$7%F(F'FcpX,F*6"F,[gl!"%!!!#1"%"%F(F(F(F
(F(F(,FF[jnF`cmFi`mF\bmF\_nFj]mFeanF\bmFhanF\bmF_hmFb\mFbglF`cmFijlF^]mF_clFd\l
FjanFa`lF]hnFa`lFcdnF`cmF^^mF`cmF\hmF\bmF`^nF\bmFa`mF^]mF__nF\bmFhgnFb\mF(F(,FF
cdnF`cmF_clFd\lF^^mF`cmF\_nFj]mF\hmF\bmF`^nF\bmFa`mF^]mF__nF\bmFhgnFb\mFggnFd`l
F[bnFd`lF[jnF`cmFi`mF\bmFeanF\bmFhanF\bmF_hmFb\mFbglF`cmFijlF^]mF(F(F(F(F(F(7$7
%F(F(FbvX,F*6"F,[gl!"%!!!#1"%"%F(,0F_cnFgglFd\m#FbvFhglFgclFgglFcfnFBFgemFd`lF^
fnFf`lF_fnFb\mF(F(,0F_cnFgglFgclFgglFd\mFjjnF^fnFf`lF_fnFb\mF\cmFa`lF\fnF'F(F(F
(F(F(F(F(F(F(F(F(7>7$7%FjxF(F(X,F*6"F,[gl!"%!!!#1"%"%,6*(F6Fbp,*Fd^mFc\mF]r!$=)
F6"%n<!%:7F'F'FAFBF`cm**F@F'FAFGF6FbpFhuF'Fihm**FAFGFFF'F6FbpF`vF'#Fb\nFh\l**FF
F'F6FbpF@F9FAFGFd`n*(FAFGF6FbpFFF9#!#jF]w**,&F]vFbpF\vF'F'F@F'FAFBF6F8#F'"$g$*,
,&FevF8FcvFMF'FAFEFFFHF6F8FIFHF^]m**,(FfuFi`lF\vFgglF]vF_bmF'F@F'FAFBF6F8F'*,Fc
amF'FAFEFFFHF6F8FIFHF7*,FAFEFFFHF6F8FIFHF^bmF'F`rF(F(,>*,FFFHF6FbpFIFH,(F]rF_fl
F6!$>$"$0%F'F'FAFE#FM"#q*.F@F'FAF7F6FbpFFFHFIFHF`vF'#Fcq"$7"*,FAF7FFFHF6FgyFIFH
F`vF'#Fj^m"$!G*,FFF`rF6FbpF@F'FAF7FIFH#F[cl"$S"**FIFHFFF`rF6FgyFAF7#FaflFg]o*,F
AF7FFFHF6FbpFIFHFhuF'#"#<"$g&*,F_\oF'FAFEFFFHF6F8FIFH#F'"%!o"*(Fc\oF'FAFBF6FG#F
B"%S]**,(F_vFd_nFcvF_^mFevF[gmF'F@F'FAFBF6F8FH*,FfemF'FAFEFFFHF6F8FIFHF7*,Fe\oF
'FAFEFFFHF6F8FIFHFH*(FAFBF6FGF^bmF'Fd`l**F[bmF'F@F'FAFBF6F8#FB"$?(*,FdimF'FAFEF
FFHF6F8FIFH#F'"$S#F(F(F(F(F(F(,.*&F6FbpF`vF'#Ffx"$S)*$F6Fbp#F'"%?D*&FFF'F6Fbp#F
jzFa]o*&F6FbpFj\oF'#F'"#%)*&Fe]mF'F6F8Fa`l*&F6F8Fa\mF'Fd`lF(,>Fi\oF]]oFj]oF[^oF
b]oFc]oFe]oFf]oFh]oFi]oF_]oF`]oFi^oFj^oF\_oF]_oFg^oFH*(FcamF'FAFBF6FGFa`lFd^oFH
*,FAFEFFFHF6F8FIFHFjcmF'F`rF^^oF_^oFa^oFb^oF(F(,6Fh[o#FibmFd]o*(FAFGF6FesF`vF'F
a_o*,F[bmF'FAFEFFFHF6F8FIFH#FBFb_o*(FdimF'FAFBF6FGFd_oF[\o#"#**Fa]o*(FAFGF6FesF
FF'Fg_o*(F6FgyFAFBFj\oF'Fi_o*,Fe^oF'FAFEFFFHF6F8FIFHF'*(FfemF'FAFBF6FGFa`l*(FAF
BF6FGFjcmF'Fd`l7$7%FbvF'F(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,,Fh_o#FBFj_oF`_o#
FfzFb_oFf_o#F\]lFa]oFc_o#FBFe_oF[`oFLF(F(,,Fh_oFbaoF`_oFcaoFf_oFdaoFc_oFeaoF\`o
FUF(F(F(F(F(F(7$7%FbvF(F'X,F*6"F,[gl!"%!!!#1"%"%F(,>Fj]o#FfilF]^oFb]o#F[hnFd]oF
^^o#FBF`^oFa^o#F'Fc^oFe]oFi]oFh]oFf]oF_]o#FbpFa]oFi\o#F8F^]o**,(FcvF[gmFevF_^mF
_vF`gmF'F@F'FAFBF6F8FHF_`oF7Fg^oFEFh^oFa`l**Fc\oF'F@F'FAFBF6F8Fj^o*,FadmF'FAFEF
FFHF6F8FIFHF]_oF(F(,>Fi\oFaboFj]oF\boFb]oF]boFe]oFi]oFh]oFf]oF_]oF`boFdboFj^oFe
boF]_oFg^oFEF^`oFd`lFbboFHFf^oF`rF^^oF^boFa^oF_boF(F(,:Fh[o#F[hmFd]oFb`oFcaoFb
\oF^bo*(FadmF'FAFBF6FGF_boF[\o#FhamFa]oFh`oFdaoFi`oFbaoFj`oFEF[aoFL*,FcboF'FAFE
FFFHF6F8FIFHFHFc`oF_^oFe`oFb^oF(F(F(F(F(,:Fi`oFbaoFh[oFhboFb`oFcaoF[\oFjboFh`oF
daoFc`oF_^oFe`oFb^oF[coFHF\aoFUFj`oFEFb\oF^boFiboF_boF(F(7$7%FcpF9F(X,F*6"F,[gl
!"%!!!#1"%"%,jn**F6FbpFFF',(F]rF_flF6Fcbm"$z"F'F'FAFBF\bm*(F6Fbp,*Fd^mFc\mF]r!$
/(F6"%E8!$&zF'F'FAFBF^]mFh[o#F[\lFcp*,F6FbpFFF'FdtF',&F6F[il!#xF'F'FAFBF]dl**F6
FbpFdtF',(F]rF[ilF6!$\"FgdmF'F'FAFBF]dl*.F_glF'FIFHF6F^pFFFHF]pFHFAFEF`r**F6Fbp
FdtF',(F]rF[ilF6!$U""$l"F'F'FAFBF]dl*(F6Fbp,*Fd^mFc\mF]r!$Y(F6"%l9!$+*F'F'FAFBF
^]m*,F]pFHF@F'FAFBF6F^pFcflF'FB*,,&F^y#F`yFiuF_v#FesFiuF'FAFEFFFHF6F8FIFHF7*,FA
FEFFFHF6F8FIFH,&F^y#F\hlFiuF_v#F[\lFiuF'F`r**FFF'F6FgyF@F'FAFGFd\l*(Fe\oF'FAFBF
6FGFB**,.FdxFb\lFhxFe[mF]vF`[lF[yFBF\yFatF`wFb\lF'F@F'FAFBF6F8F'**FbcnF'F@F'FAF
BF6F8#F'FgdmFf\oF`rFg\oF7**F@F'FAFGF6FbpFexF'#FesFc\m**F6FbpFdtF'Fj\oF'FAFBFj]m
F[\o#"$H$Fh\l**F@F'FAFGF6FbpF\rF'#FfxF[dl**F6FgyFAFGF`vF'F@F'F[fo**F6FbpFFF',(F
]rFc\mF6!$e%"$&QF'F'FAFBF^]m*(F6Fbp,*Fd^mFc\mF]r!$=(F6"%q8!$D)F'F'FAFBF^]m*.FIF
HF6F^pFFFHF]pFHFAFEF]glF'F7*,F@F'FAFGF6FbpFdtF'F`vF'#FesF_fl*(F6FgyFhuF'FAFGF[f
o*(F_\oF'FAFBF6FG#FBFa\o**F6FbpFFF',(F]rFc\mF6!$W%"$r$F'F'FAFBF^]mFi`oF\bmFb\oF
b\mF(F(,`o*,FbcnF'FAFEFFFHF6F8FIFH#F'"$0"*(Fe^oF'FAFBF6FGFE*,F6FbpFFF`rFIFH,&F6
Fhgo!$W#F'F'FAFE#FBF^]o*.FAF7FFFHF6FbpFIFHFdtF'F`vF'#FfilFd]o*,FFFHF6FbpFIFHF_d
oF'FAFE#F`yFg]oF_]o#FjzF^]oFi\oF\cl**F@F'FAFBF6F8F^bmF'Fa`l*.FfhlF'FIFHF6F^pFFF
HF]pFHFAFEF`r*,FFFHF6FbpFIFHFcdoF'FAFEFaho*,F]pFHF@F'FAFBF6F^pFdhlF'FE*,,.FeyFg
\lFhxF`cmF]vFfwF[yF]xF[zFfwFfuFg\lF'FAFEFFFHF6F8FIFHF7*,FFFHF6FbpFIFH,(F]rF^]oF
6!$A$"$l$F'F'FAFE#F8Fg]o**,&F^y#FfflFh\lF_vFi[oF'F@F'FAFBF6F8FH*(FAFBF6FGFaeoF'
Fd`l*,F6FbpFFF`rFIFH,&F6F[ilF^flF'F'FAFEF_jm*,FAF7FFFHF6FbpFIFHFfyF'F`]o*,FAF7F
FFHF6FbpFIFHFexF'F\bo*,FIFHF6FbpFFFHFAF7F\rF'FdvFh]o#"$@"F^_o**FAFBF6F8F]pFHF]g
lF'FatFg^oFEFf^oF`rFdboF_bo*,F6FbpFFF`rFIFHF\doF'FAFEFaho*,FgeoF'FAFEFFFHF6F8FI
FHFH*(F[bmF'FAFBF6FG#F'F[_o*.FIFHF6F^pFFFHF]pFHFAFEFcflF'F_u*,FAF7FFFHF6FbpFIFH
F\zF'#Fcq"#cFb]o#F\^o"$?%Fj]oFielFe]o#!#r"#!)F^^oF^boF\_o#FBF^_oF(F__oF(F(F(F(,
8Ff_o#!$R"F`^oFc_o#F'"%g7*(F6FbpFFF',&F6F[dlF^fmF'F'FbaoF`_oFa_o*(F6FbpFFF'F\do
F'Fbao*&F6FbpFcdoF'Fbao*&F6FbpF_doF'#FB"$o"F\`oFd`l*&Fe\nF'F6F8Fa`l*&F6F8F[\nF'
Fd`lF[`oFa`lF(,`oFfgoFggo**FcamF'F@F'FAFBF6F8Fd`lFigoFEFjgoF]hoF^hoF_ho**F_glF'
FAFBF6F8F]pFHFfsF`hoFahoF_]oFbhoFi\oF\clFehoFahoFfhoFE*,FAFEFFFHF6F8FIFH,.FeyFf
`lFhxF\bmF]vF\wF[yFavF[zF\wFfuFf`lF'F`rFihoF]ioF^ioFHFbioF_jmFdioF`]oFeioF\boFf
ioFdvFh]oFgio*(F]eoF'FAFBF6FGFa`lFg^oFEF_`oF7FdboF_boFjioFahoF[joFHF\joF]joF^jo
F_u*.FIFHF6F^pFFFHF]pFHFAFEF^ilF'F7F_joF`joFb]oFbjoFj]oFielFe]oFdjoF^^oF^boF\_o
FgjoF(F(,jn**FfemF'F@F'FAFBF6F8Fd`lFh[o#FfxF^_n**FfhlF'FAFBF6F8F]pFHFfs*.FIFHF6
F^pFFFHF]pFHFAFEFdhlF'F7**F6FbpFFF',(F]rF[ilF6!$2""#xF'F'FAFB#FBF[]n**F@F'FAFBF
6F8FjcmF'Fa`l*(F6Fbp,*Fd^mF[ilF]r!$z"F6F^fo!$!=F'F'FAFBFf\p*(FAFGF6FgyF\zF'#Ffz
Fcjo*(F6Fbp,*Fd^mF_flF]r!$z$F6"$C(!$0%F'F'FAFB#FB"#U*(FhhoF'FAFBF6FGFa`l*(FAFBF
6FGFj[pF'Fd`lFb[oFbaoFdeo#F'Fc[m*(F6Fbp,*Fd^m"#!*F]r!$s%F6"$N(!$+$F'F'FAFBFb[p*
*FAFBF6F8F]pFHF^ilF'Fat*(FbcnF'FAFBF6FGF[[pFj`oFB*(FAFGF6FgyFfyF'Fcao*,F_ioF'FA
FEFFFHF6F8FIFHF'**FdimF'F@F'FAFBF6F8Feao**F6FbpFFF',(F]rFj]pF6!$x#Fg]oF'F'FAFBF
b[p*(F6Fbp,*Fd^mFj]pF]r!$'[F6"$z(!$I$F'F'FAFBFb[p*(F6Fbp,*Fd^mFj]pF]r!$2&F6"$Q)
!$g$F'F'FAFBFb[p**F6FbpFFF',(F]rFj]pF6!$"H"$a"F'F'FAFBFb[pF[\o#!$>(Fd]o*(FAFGF6
FgyF\rF'FgilFafoFcaoF^goFcaoFc`o#F'Fb_o*(F6Fbp,*Fd^mF[ilF]r!$s"F6"$2$!$l"F'F'FA
FBFf\p**F6FbpFFF',(F]rFjvF6Ficn"#lF'F'FAFBFbao7$7%FcpF'F'X,F*6"F,[gl!"%!!!#1"%"
%F(F(,fp*,F]pFHF@F'FAFBF6F^pFj\mF'FE*,,6F][lFf`lF]vFf`lFhxF^]mF_[lFdamF[yF^^lF[
zFf`lFa[lF^]mFb[lFf`lFfuFf`lFc[lF^]mF'FAFEFFFHF6F8FIFHF7**F6FgyFAF7FFFHFIFHF]_o
*&,&F\dlFjhlFiclF[gmF'F6F7FBF`ho#FfzFg]oF_]o#"#tF]^oFi\o#FMFfglFchoFd`l*,F6FbpF
IFHFFFH,(F]rFgxF6FjilFd]pF'F'FAFE#FMFg]o*(F]pFHFdclF'F6#FfilF9Fj]m*,FAF7FFF`rF6
FbpFIFHF`vF'F`bo**F6FbpFAFEFFF`rFIFH#!%x=F`^o*(F]pFHF6F^pF\]mF'FatFehoF[ap*&F6F
capF]pFHF_^mFfioFi[o*,FFFHFIFH,(F6!$<""$5"F'F]rF[ilF'F6FbpFAFE#F'Fg]o*,FIFHFFFH
F6FbpFAF7F@F'Fgjo*&F6F8,,FczFb\lF^y#FfxFiuFgzFfsFhzFfsF_vF_uF'Fd`l*,F6FbpFIFHFF
F`r,&Fi`nF'F6FgxF'FAFEFaapFg^oFH*,FIFH,*F]r!#eF6"$6"!#qF'Fd^mFgxF'F6FbpFAFEFFFE
Faap*,FFFHFIFH,(F6Fd\pFj]pF'F]rF[ilF'F6FbpFAFE#F'F^]o*,F6FbpFIFHFFFH,(F6!$G""$N
"F'F]rF[ilF'FAFEF^bp**FFFHFIFHFAFEF6FbpFggo*.F@F'FAF7F6FbpFIFHFFFHFdtF'#FMFa]oF
dboFb^o*,F`vF'F6FbpFAFEFFFHFIFH#!$T"F]^o*,F^`nF'FAFEFFFHF6F8FIFHF]_oFjioF[ap*&F
6F8FcamF'Fa`l*,Fe]mF'FAFEFFFHF6F8FIFHF7*,Fa\mF'FAFEFFFHF6F8FIFHF`r**FAF7FFF_dmF
6FbpFIFH#!$R$F]^o**,*FczFf`lF^yFhbmF_vFd^lFgzF_jmF'F@F'FAFBF6F8FH*,FFFHFIFH,(F6
!#bF_inF'F]rF[dlF'F6FbpFAFEF\cp*.Fg[mF'FIFHF6F^pFFFHF]pFHFAFEF`r*&F[bmF'F6F8F_b
o*,FFFHFIFH,(F6!#N"#HF'F]rFgxF'F6FbpFAFEFaapF_joF`boFj]oF_jmFe]o#"$4$F]^oF^^oF_
^o*,FAF7FFFHF6FbpFIFHF^[lF'F`bo*,F6FbpFIFHFFFHFdtF'FAFE#FfilF`^oF(F(F(F(F(,fpFe
`pFE*,FAFEFFFHF6F8FIFH,6F][lFg\lF]vFg\lFhxFb\mF_[lF_bmF[yF]zF[zFg\lFa[lFb\mFb[l
Fg\lFfuFg\lFc[lFb\mF'F`r*(Fa]mF'F]pFHF6F^pFfsFg[pFa`l*&F6F7,&FiclF_^mF\dlFj]mF'
F'Fh`pF]_oF`hoF[apF_]oF\ap*&F^bmF'F6F8Fd`lFi\oF^apF_apFaapFbapFj]mFdapF`boFeapF
fapFehoF[apFiapF_^mFfioFi[oFjapF^bpF_bpFgjoFcbpFaapFg^oFHFebpFaapFjbpF\cpF]cpF^
bpFacpFggoFbcpFccpFdboFb^oFdcpFecpFgcpF]_oFjioF[apFicpF7FjcpF`rF[dpF\dpF^dpFHF`
dpF\cp*.FIFHF6F^pFFFHF]pFHFAFEFc]mF'F7FddpF_boFedpFaap*&,,FczFi`lF^y#FfzFiuFgzF
atFhzFatF_vF`[lF'F6F8Fa`lF_joF`boFj]oF_jmFe]oFidpF^^oF_^oF[epF`boF\epF]epF(F(,d
r*,F_dpF'FAFEFFFHF6F8FIFHFH*(Fg[mF'F]pFHF6F^pFfsF^\pFa`l**F`vF'F6FbpF@F'FAFB#Ff
xF`^o*(F6Fbp,*F6"$F%!$:$F'Fd^mF[ilF]r!$&>F'FAFB#F'Fc[p**FAFGF6FgyFFF'F`vF'F]fp*
(F\rF'FAFBF6FbpF]dl*(,*F6"$5#!$i"F'Fd^mF[dlF]r!#&*F'FAFBF6FbpFi_o*(F6FbpFAFBFFF
9#!#D"$O$**F6FbpFFF'F`vF'FAFBF]fpFh[o#"$<"F]^o*(FAFGF6FgyF^[lF'F]fp*(F6FbpF^[lF
'FAFBF]fp**FAFGFFF'F6FbpFdtF'#FfzF]^o*(FAFBF6FGFe]mF'Fa`l**F@F'FAFBF6F8Fa\mF'Fd
`lFb\p#F'Fd]p*(F6FbpFhuF'FAFBF]fp*(FAFBF6FGF`epF'Fd`l**FFF'F6FbpFAFBF_doF'#FbvF
c[pFh\pFhgp*(F6Fbp,*F6"$2%!$%HF'Fd^mF[ilF]r!$!>F'FAFBFcfp*(FAFGFFF'F6Fbp#FBFd]o
F\]pF]fp**FFF'F6FbpFAFBFj\oF'Fi_o*&FjcmF'F6F8Fd`l*(F^`nF'FAFBF6FGF_bo**F6FbpFFF
9FAFBF\doF'F\hpF^]pFi_oFb[oFi_o**FFF'F6FbpFAFBFcdoF'F\hp*(,*F6"$[%F__pF'Fd^mF[i
lF]rFbfpF'F6FbpFAFBFcfp*&F^`nF'F6F8F_bo*(F6FgyF@F'FAFGF_bo*(,*F6"$x%!$!RF'Fd^mF
[ilF]r!$-#F'F6FbpFAFBFcfpFdeo#FBF^_n*(FFF'F6FgyFAFBFg_o**FFF'F6FbpF@F'FAFBFcip*
(F`vF'F6FgyFAFBFa_o*(F6FbpF@F'FAFBFd_oFj`oFH*&F6FesFAFGF_bo*(,*F6F[ip!$_$F'Fd^m
F[ilF]r!$(>F'FAFBF6FbpFcfp*(F6FbpF\zF'FAFBF]fp*(FAFGF6FgyFFF9F\gpFb^pF_bo**FAFB
F6F8F]pFHFc]mF'Fat*.FIFHF6F^pFFFHF]pFHFAFEFj\mF'F_u*&FadmF'F6F8Fb^oF[\o#"$H&F]^
oFf_pF]dlFafoF]fp*&Fg`pF'F6F8Fa`l*(F6Fbp,*F6"$?&!$]%F'Fd^mF[ilF]r!$4#F'FAFBFcfp
*(F6Fbp,*F6"$)Q!$w#F'Fd^mF[ilF]r!$&=F'FAFBFcfpF^goF]fp*(,*F6"$+%!$.$F'Fd^mF[ilF
]rF^[qF'FAFBF6FbpFcfp*&F6FgyFAFBFd_oFc`oF^boFh_pFhgpF(F(,drFjepFHF\fpF]fpF^fpFc
fpFdfpF]fpFefpF]dlFffpFi_oF[gpF\gpF_gpF]fpFh[oF`gpFbgpF]fpFcgpF]fpFdgpFegpFb\pF
hgpFigpF]fp**Fg[mF'FAFBF6F8F]pFHFfsFg\pFd`lF[hpF\hpFh\pFhgpF]hpFcfpFbhpFchpF\]p
F]fpFdhpFi_o*(Fa\mF'FAFBF6FGFd`l*(F]pFHF6F^pFc]mF'FatFfhpF_boFghpF\hpF^]pFi_oFb
[oFi_oFhhpF\hpFihpFcfp**Fe]mF'F@F'FAFBF6F8Fa`lF\ipF_boF]ipF_boF^ipFcfpFdeoFcipF
dipFg_oFeipFcipFfipFa_o*&F6F8F`epF'Fd`lFgipFd_oFj`oFHFhipF_boFiipFcfpF]jpF]fp*&
F6F8FfemF'Fa`lF^jpF\gpFb^pF_bo*(Fg`pF'FAFBF6FGFa`lF`jpF_uFajpFb^oF[\oFbjpFf_pF]
dlFafoF]fpFejpFcfpFjjpFcfpF^goF]fpF_[qFcfpFc[qFd_oFc`oF^boFh_pFhgpF(7$7%FcpF(F9
X,F*6"F,[gl!"%!!!#1"%"%,\p**,0Fi[lFb\lFc[lFe[mF_[lFBF\\lF_uFb[lFatF]vF_bmF[wFb
\lF'F@F'FAFBF6F8F'F\fpF[fo*(F6Fbp,,F]r"%2KF6!%KT"%!*=F'*$F6FcpFc\mFd^m!%Y5F'FAF
GF^]m*.F]pFHFFFHF6FcapFIFHFdclF'FAFEFd\l**FAF8FFF'F6FbpF@F'F[gmFh[oF]hmFigpF[fo
*(FAF8FFF'F6FgyF_^m*(,,F]r"%)*HF6!%$z$"%5<F'Fh\qFc\mFd^m!%/5F'FAFGF6FbpF^]m*&F_
\oF'F6F8F`goF[hpF]dl*,F@F'FAFGF6FbpFFF'F`vF'F]goFbhpF_^mFdhpFj]mFghpF]dl*&Fe\oF
'F6F8FBFhhpF]dl*.FIFHF6F^pFFFHF]pFHFAFEF_blF'F7*.FablF'FIFHF6F^pFFFHF]pFHFAFEF`
r*,F]pFHF@F'FAFBF6F^pFh`mF'FB*,FcenF'FAFEFFFHF6F8FIFHF7*,FAFEFFFHF6F8FIFHFfenF'
F`r*(,,F]r"%)4$F6!%FSFg\qF'Fh\qFc\mFd^m!%=5F'FAFGF6FbpF^]mFeipFd\l*(F6FbpF@F9FA
FG#FBFgdmFf\oF7Fg\oF`r*(,*Fd^mF_flF]r!$1$F6"$-&!$j#F'F'FAFBF6FbpF\bm**F@F'FAFGF
6FbpFj[lF'F[fo**FAFGFFF'F6FbpFf\lF'F\w**FFF9F6FbpF@F'FAFGF`fo*&,&FfclFcqFgclFbp
F'F6F7F\bm*&F6F7,(FcclFfwFfclF]zFgclF^^lF'F'F[\o#F]jlF]w*&,(FcclF\wFfclF^^lFgcl
F]zF'F6F7FB*(FAFGF6FbpF_\lF'F_^m*(,,F]r"%8HF6!%)o$F`^oF'Fh\qFc\mFd^m!$%)*F'FAFG
F6FbpF^]mFh_oF\bm*(,,F]r"%6IF6!%7R"%[=F'Fd^m!$)**Fh\qFc\mF'FAFGF6FbpF^]mFc`oFb
\mF(F(,dpF^`oFa`l*,FFFHFIFH,*F]r!%05F6"%W@!%_9F'Fd^m"$]"F'FAF7F6Fbp#FBFg]o*,Fb
\qF'FAFEFFFHF6F8FIFHFH*&,(F`dlFjhlF_clFd_nF_dlF[gmF'F6F7FB**FA#F[rF9FFF`rF6FbpF
IFH#F8F]^o**FAFi`qFFFHF6FesFIFH#F'FhfpFh`pF_^o*,FFFHFIFH,*F]rF\`qF6"%4@!%59F'Fd
^mFc`qF'FAF7F6FbpFd`qF`ho#FBFfglF_]o#F8Fa]o*,FAFi`qFFFHF6FgyFIFHF@F'Fgjo*,FAF7F
FFHF6FbpFIFHF`]lF'F`]o*,FAF7FFFHF6FbpFIFHFj[lF'F\bo*,FAF7F6FgyF_\lF'FIFHFFFEF]_
oFi\oF]ho*,Ff\lF'FFFHFIFHF6FgyFAF7FcfpFdapF_hoFeap#!#dFd]oFehoFaaq*.FIFHF6F^pFF
FHF]pFHFAFEFh`mF'F_uFeboFgjoFh]o#FjenFc[p*.F_\lF'FIFHF6FbpFFFEFAF7F@F'F[gm*,Fdf
nF'FAFEFFFHF6F8FIFHF7F_bpFj`q*.F@F'FAF7F6FbpFf\lF'FFFHFIFH#FBF]^o*,FFFHFIFH,*F]
r!%J5F6"%8A!%&["F'Fd^mFc`qF'FAF7F6FbpFd`qF_`oF`r*,FFFHFIFH,*F]r!%Q5F6"%\A!%I:F'
Fd^mFc`qF'FAF7F6FbpFd`q*,FFFHF6FbpFIFH,*F]r!%(3"F6"%'R#!%?;F'Fd^mFc`qF'FAF7Fd`q
**FAFBF6F]\mFdclF'F]pFHFj]m*,,*Fd^mFc`qF]r!$O)F6"%B:!$-*F'F'FIFHFFFEF6FbpFAFEFd
`qFdcpFc]oFjioFaaq**FAFBF6F8F]pFHF_blF'FatF[dp#FfxF]wF\joF_bo*&Fe^oF'F6F8FE*&,&
F_clFeclF_dlFMF'F6F7Fb\mFddpF]joFb]o#!$p"F`^oFe]oF]z**,,Fe\lFg\lFevF[gmF^yF]zF_
vFg\lFgzF[gmF'F@F'FAFBF6F8FH*(FAFBF6FGFfenF'Fd`lF(,6Fi`oFi_oFh[oFa`oFb`oFa_oF[
\oFf`oFh`oFg_oFb\oFg_pFiboFeaoF[coFBF\aoFd`lF[aoFa`lF(F(F(F(,RF\fpFcaoF[gpFgilF
_gpF]]pFggpFa`lFigpFcao*(F6Fbp,*F6"$k%Fj^pF'Fd^mF[ilF]rFijpF'FAFB#FBFajoF[hpFf
\pFdhpFc]pFghpFf\pFb[oFbaoFhhpFf\pFh[qFd`l*(,*F6"%>8!$I*F'Fd^mFj]pF]r!$1'F'FAFB
F6FbpFb[pFeipFg]pFgipFd`o*&F6F8,,Fj\lFf`lFc[lF\bmF_[lFavFb[lF\wFfuFf`lF'Fd`l*(,
*F6"%k7!$!))F'Fd^mFj]pF]r!$"fF'FAFBF6FbpFb[p*(,*F6"%h7!$q)F'Fd^mFj]pF]r!$#fF'FA
FBF6FbpFb[p*(F6FbpF[]lF'FAFBFcao*(F]pFHF6F^pFaemF'Fat*(,*F6"%37!$C)F'Fd^mFj]pF]
r!$x&F'FAFBF6FbpFb[p*(,*!$*QF'F6"$#eFd^mFjvF]r!$$GF'FAFBF6FbpFbao*&,,Fj\lFg\lFc
[lF`cmF_[lF]xFb[lFfwFfuFg\lF'F6F8Fa`l*(FcemF'F]pFHF6F^pFfsF(,dpFh^oFd`lF^`qFd`q
Fe`qFH*&F6F7,(F_clF`gmF_dlF_^mF`dlFj]mF'F'Fh`qFj`qF[aqF\aqFh`pF_^oF]aqFd`qF`hoF
aaqF_]oFbaqFcaqFgjoFdaqF`]oFeaqF\boFfaqF]_oFi\oF]hoFgaqFcfpFdapF_hoFeapFhaqFeho
FaaqFjaqF_uFeboFgjoFh]oF[bqF\bqF[gm*,FAFEFFFHF6F8FIFHF]fnF'F`rF_bpFj`q*(FcenF'F
AFBF6FGFa`lF^bqF_bqF`bqFd`qFf^oF7FebqFd`qFjbqFd`qF_cqFj]mF`cqFd`qFdcpFc]oFjioFa
aqF[dpFfcqF\joF_boFgcqFEFhcqFb\mFddpF]joFb]oFjcqFe]oF]zF\dqFH**FablF'FAFBF6F8F]
pFHFfsF(F(,JF[aoFa`lF\aoFd`lFh`oFg_oFh[o#FfxFd]oFb`oFa_o*(F6Fbp,,F]r!#mF6"%M5!%
!3"F'Fh\qF[ilFd^mF`doF'FAFGFb[pF\]qFchp*(,*Fd^mF[dlF]rF`yF6!#!)"$E"F'F'FAFBF6Fb
pFbaoFbhpFchp*,F]dqF'FAFEFFFHF6F8FIFHF'*(FAFBF6FGF]fnF'Fd`lFiboFeao*(,,F]r!#EF6
"$g(!$#zF'Fh\qF[ilFd^m!$P"F'FAFGF6FbpFbao*(FAFGF6FgyF`]lF'FcaoFh^q#F8Fd]o*&FAF8
F6FguFd_oF[\o#Fj^mFh\lFa_qFcip*(,,F]rF[hmF6"$g)FjdoF'Fh\qF[ilFd^mFddoF'FAFGF6Fb
pFbao*(FdfnF'FAFBF6FGFa`l7$7%FMFMF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,4F][pFi_
oFf_o#"$R"F`^oF_[pFi_oF`[pFi_oFc_o#FBF\[pFa[pFcfpF`_oFcaoF\`oFUFd[pFLF(F(,4F][p
Fi_oFf_oF[iqF_[pFi_oF`[pFi_oFc_oF]iqFa[pFcfpF`_oFcaoF[`oFLFe[pFUF(F(F(F(F(F(7$7
%FMF9F'X,F*6"F,[gl!"%!!!#1"%"%F(,drFfgoFd`oFbepFBFjgoFb\mF^ho#F\^oFd]oFh`pFgjoF
`hoFg]pF_]oFccpFi\oF\cp*,FIFHF6FbpFFF`rFAF7FdtF'Fg\lF_apF]ioFbapFjhlFdapF`]oFea
p#"%x=F`^o*,,6F][lFg\lF_[lF_bmFeyFf`lFa[lFb\mF]vFf`lFhxF^]mFb[lFg\lF]^lF^^lFc[l
Fb\mF[zFf`lF'FAFEFFFHF6F8FIFHF7FhapFfsFehoFg]pFiho#F'FfjoFiapF[gmFaioFa`lFbio#F
[\lF^_oFeboFgjoFdioF`boFeioF[^oFfioFdzFh]o#!$@"F^_oFjapFd`q*,F6FbpFFFHFIFH,(F]r
F[ilF6FicnF_gmF'F'FAFE#F'F_inF_bpF]_oFiioFfsF`bpFa`lFcbpF]ioF_`oF`rFebpF]ioFjbp
F]hoF]cpFd`qFacp#FBFhgo*,FFFEF6FbpFIFH,*Fd^mF^]oF]r!$i%F6"%45!$I(F'F'FAFE#F'Fa]
oFbcpFbaqFdcp#"$T"F]^oFgcpF]_oFjioFg]pFhcpFd`lFicpF`rFjcpF7F[dp#"$R$F]^oF[joFEF
`dpF]ho*.FdgmF'FIFHF6F^pFFFHF]pFHFAFEF`rFa^oF]joFddpFb^o*(FcboF'FAFBF6FGFE*,F6F
bpFFFHFIFH,(F]rFhgoF6!$a%"$)[F'F'FAFEFcfpFedpF]ioF^joF`[lF_joF`boFb]o#FfilFcjoF
e]o#"$H"Fd]oF[epF`]oF\ep#F\^oF`^o**F@F'FAFBF6F8,*FczFg\lF^yF`[lFgzFielF_vFf`lF'
FHF(F(,drFfgoFd`oFaepFatFjgoFb\mF^hoFdiqFh`pFgjoFi`pF'Fh[pFatF`hoFg]pF_]oFccpFd
epFa`lFi\oF\cpFeiqFg\lF_apF]io*.FIFHF6F^pFFFHF]pFHFAFEFggmF'F7FbapFjhlFdapF`]oF
eapFfiq*,FAFEFFFHF6F8FIFH,6F][lFf`lF_[lFdamFeyFg\lFa[lF^]mF]vFg\lFhxFb\mFb[lFf`
lF]^lF]zFc[lF^]mF[zFg\lF'F`rFehoFg]pFihoFjiqFiapF[gmFbioF[jqFeboFgjoFdioF`boFei
oF[^oFfioFdzFh]oF\jqFjapFd`qF[\pFd`lF^jqF`jqF_bpF]_oFcbpF]ioFf^oF7FebpF]ioFjbpF
]hoF]cpFd`qFacpFajqFbjqFgjqFbcpFbaqFdcpFhjqFgcpF]_oFjioFg]pFicpF`rFjcpF7F[dpFjj
qF[joFEF`dpF]hoFa^oF]joFddpFb^oF][rFEF^[rFcfpFedpF]ioFfepFd`lF^joF`[lF_joF`boFb
]oFb[rFe]oFc[rF[epF`]oF\epFe[rFf[rFHF(F(,jsF[fpFatF^\pFa`lF\fp#FfzF`^oF^fpFb[pF
dfpF]\rFefpFfdlFffpFbaoF[gp#FebmF^gpF_gpF]\rFh[o#"$V"F]^oFbgpF]\rFcgpF]\rFdgp#F
fxF]^oF`\pFatFa\pF`[lFb\pFhgpFigpF]\rF[hp#F[rFc[pFh\pFhgpF]hpFb[p**FAFGF6FgyFFF
'FdtF'F[gmFbhp#F'Fd]oF\]pFa\r*,FAFEFFFHF6F8FIFHFg[rF'FHFdhpFbaoFf[qFa`lFehpFa`l
FfhpF_boFghpFb\rF^]pFi_oFe]pFd`lFhhpFb\rFihpFb[pFh[qFd`lF\ipFb^oF]ipFb^oF^ipFb[
pFdeoFcipFh]pFcfpFdipFdaoF[coFEFeip#F'F^_nFfipFcaoFgipFeaoF_^pFeaoFhipFb^oFiipF
b[pF`^pFa_oF]jpF]\r**FAFBF6F8F]pFHFggmF'FatF^jpF^\rFa^pFE**FadmF'F@F'FAFBF6F8Fb
^oFc^pFcfpFf^pFcfpF[_pFcfpF`_pFcfpFajpF_boF[\o#"$2&Fd]oFf_pF[inFafoF]fpFdjpFd`l
FejpFb[pFjjpFb[pF^goF]fpF_[qFb[pFc[qFeaoFb\oF_^oFh_pFhgpF]`pFi_o*(FAFBF6FGF[\rF
'Fd`lF(F(F(F(F(,jsF\fpF]\rF^fpFb[pFdfpF]\rFefpFfdlFffpFbaoF[gpF^\rF_gpF]\rFh[oF
_\rFbgpF]\rFcgpF]\rFdgpFa\rFfgpFd`lFggpFa`lFa\pF`[lFb\pFhgpFigpF]\rFg\pFd`lF[hp
Fb\rFh\pFhgpF]hpFb[pFc\rF[gmFbhpFd\rF\]pFa\rFe\rFHFdhpFbaoFg[qFfsFfhpF_boFghpFb
\rF^]pFi_oFf]pFa`lFhhpFb\rFihpFb[pF\ipFb^oF]ipFb^oF^ipFb[pFdeoFcipFh]pFcfpFdipF
daoF[coFEFeipFf\rF^^pFfsFfipFcaoFi[qFa`lFgipFeaoF_^pFeaoFhipFb^oFiipFb[pF`^pFa_
oF]jpF]\rFj[qFd`lF^jpF^\rFa^pFEFh\rFb^oFc^pFcfpFf^pFcfpF[_pFcfpF`_pFcfpFajpF_bo
F[\oFi\rFf_pF[inFafoF]fp*(FiiqF'FAFBF6FGFa`lFejpFb[pFjjpFb[pF^goF]fpF_[qFb[pFc[
qFeaoFb\oF_^o**FdgmF'FAFBF6F8F]pFHFfsFh_pFhgpF]`pFi_oF(F(7$7%FMF'F9X,F*6"F,[gl!
"%!!!#1"%"%F(F(F(F(F(F(,fsFjepFEF^\pFd`lF\fpF]fpF^fpFb[pFdfpF]\rFefpFgglFffpFba
oF[gp#!$B$F`^oF_gpFa\rFh[o#F\bpF]^oFbgpF]\rFcgpF]\rFdgpFa\r*&F6F8,6Fj\lFg\lFa[l
F^]mF][lFf`lF_[lF`gmFhxF^]mF]vFf`lFb[lFg\lF]^lF^^lFc[lFb\mF[zFf`lF'Fd`lFb\pFc]p
FigpF]fpFe[qFatFadq#F'Fajo*&FdimF'F6F8Fb^oF[hpFi]rFh\pFc]pF]hpFb[pFbhpFd\rF\]pF
]\rFdhpFi_oFf[qFa`lFehpFa`lFfhpFb^oFghpFi]rF^]pFbaoFhhpFi]rFihpFb[pFh[qFa`lF]ip
Fb^oF^ipFb[pFdeoFf\rFdipFdaoF[coFHFedqFcfpFeipFcipFfipFcaoFgipF[[pFhipFb^oFiipF
b[pF]jpF]\r*(F]pFHF6F^pFdgmF'FatF\eqFcfpFaeqFcfpFfeqFa_oF^jpF^\rFh\rF_boF[\qFd`
lF`jpF`[lFheqFcfpF[\o#!$H&F]^o**FFF'F6FbpFdtF'FAFBF_^mFf_pFfdlFafoF]\rFejpFb[pF
]fqFi_oFjjpFb[pF^goF]\rF_[qFb[pFc[qFeaoFb\oF^bo*&FbcnF'F6F8F_boFh_pFc]pFbfqFd`l
FdfqFatF(F(,fsFjepFEF\fpF]fpF^fpFb[p*&,6Fj\lFf`lFa[lFb\mF][lFg\lF_[lFd_nFhxFb\m
F]vFg\lFb[lFf`lF]^lF]zFc[lF^]mF[zFg\lF'F6F8Fa`lFdfpF]\rFefpFgglFffpFbaoF[gpFd]r
F_gpFa\r*(FggmF'F]pFHF6F^pFfsFh[oFf]rFbgpF]\rFcgpF]\rFdgpFa\rFfgpFd`lFggpFd`lFb
\pFc]pFigpF]fpFjgpFa`lFg\pFa`lFadqFi]rFj]rFb^oF[hpFi]rFh\pFc]pF]hpFb[pFbhpFd\rF
\]pF]\rFdhpFi_oFfhpFb^oFghpFi]rF^]pFbaoFhhpFi]rFihpFb[pF]ipFb^oF^ipFb[pFdeoFf\r
FdipFdaoF[coFHFedqFcfpFeipFcipFfipFcaoFgipF[[pFhipFb^oFjdqFa`lFiipFb[pF]jpF]\rF
\eqFcfpFaeqFcfpFfeqFa_oFj[qFd`lFgeqFfsF^jpF^\rFh\rF_boF_jpFfsF`jpF`[lFheqFcfpF[
\oF\^rF^^rF_^mFf_pFfdlFafoF]\rFejpFb[pF]fqFi_oFjjpFb[pF^goF]\rF_[qFb[pFc[qFeaoF
b\oF^boF_^rF_boFh_pFc]pF(F(F(F(F(F(7$7%FMF(FMX,F*6"F,[gl!"%!!!#1"%"%F(,hp*,FFFE
F6FbpFIFH,,F]r"%qXF6!%7k"%SKF'Fd^m!%(Q"Fh\qFc`qF'FAF7#F'F^gpF^`oFd`lF^`qF]_oFe`
qFEFffqFBFh`q#FMF]^oF[aq#FBFhfpFh`pF^boF]aqF^bpF`ho#F'FfglF_]oFccpFcaqF]_oFdaqF
`boFeaqF[^oFfaqFgjoFi\oF\cpFgaqFb[pFdapFdiqFeap#"#dFd]o*&,&F_clF[vF_dlF8F'F6F7F
b\mFehoFb_r*,FIFH,,F]r"%aTF6!%Sd"%/HF'Fd^m!%08Fh\qFc`qF'FAF7F6FbpFFFEF__rFjaqF`
[l*&Fc\oF'F6F8F]joFh]o#"#zFc[pF\bqFccpFhfqF7F_bpF`_rF`bqF^bpFf^oF`rFebqF]_oFjbq
F]_oF_cqFjhlF`cqF^bpFdcpF]boFjioFb_rFecqFfsF[dp#FfzF]wF\joFb^o**F@F'FAFBF6F8,,F
^\lFf`lFevF_^mF^yF^^lFgzF_^mF_vFf`lF'FH*,FIFH,,F]r"%DVF6!%Gg"%gIF'Fd^m!%Q8Fh\qF
c`qF'FAF7F6FbpFFFEF__r*&FcboF'F6F8FEFb]o#"$p"F`^oFe]oF^^lF\_oFgjoF^dqFa`lF(F(,h
pFi^rF__rFh^oFa`lF^`qF]_oFe`qFEFf`qF'Fh`qF`_rF[aqFa_rFh`pF^boF]aqF^bpF`hoFb_rF_
]oFccpFcaqF]_oFdaqF`boFeaqF[^oFfaqFgjoFi\oF\cpFgaqFb[pFdapFdiqFeapFc_rFe_rFb\mF
ehoFb_rFg_rF__rFjaqF`[lF]`rF]joFh]oF^`rF\bqFccpF]bqF`rF_bpF`_rFifqFd`lF`bqF^bpF
_`oF7FebqF]_oFjbqF]_oF_cqFjhlF`cqF^bpFdcpF]boFjioFb_rF[dpF``rF\joFb^oFa`rFHFc`r
F__rFi`rFEFb]oFj`rFe]oF^^lF\_oFgjoFjfqFatF(F(,JF\aoFUFh`oFdaoFh[o#FfzFd]oFb`oFc
aoF]gqFcfp*,FAFEFFFHF6F8FIFHFb`rF'FHF\]qFd\rFbgqFi_oFe`oFb^oFbhpFd\rFfgqFEFiboF
_boFhgqFi_oF^hqFa_oFh^qF`_rF`hqFeaoF[\o#F[hnFh\lFa_q#F\hlF]^oFbhqFi_oFehqFLF(F(
F(F(F(,JF[aoFLFh`oFdaoFh[oF^arFb`oFcaoF]gqFcfpF_arFHF\]qFd\rFbgqFi_oFe`oFb^oFbh
pFd\rFfgqFEFggqFUFiboF_boFhgqFi_oF^hqFa_oFh^qF`_rF`hqFeaoF[\oF`arFa_qFaarFbhqFi
_oF(F(7$7%F9FcpF(X,F*6"F,[gl!"%!!!#1"%"%,jnFh`oFcel**F6FbpF\rF9FAFGFFFBFdvFh[o#
FcinFh\lFb`oFihm**F6Fbp,&F6Fj]p!$<#F'F'F\rF'FAFBF`cm**F6Fbp,&F6Fjv!#)*F'F'F\rF'
FAFBFjhlF\eoF`rF`eoF7**F6Fbp,&F6Fjv!$."F'F'F\rF'FAFBFjhlFh]pFb\m**F@F'FAFGF6Fbp
FfyF'Fihm*(FAFGF6FgyFexF'FihmF_^pFa^q*,FAFEFFFHF6F8FIFH,(F^yF_eoFcvFi`lFevFb\lF
'F`r**F6FgyFdtF'F`vF'FAFGFe[n*,,(F^yFceoFcvFb\lFevFi`lF'FAFEFFFHF6F8FIFHF7*$Fcf
lF9F'*&F_glF'F]glF'F'**F6FbpFFF',(F]rFj]pF6!$,$"$I#F'F'FAFBFb\mFb^pF`\oFc^pFb\m
Ff^pFb\mF[_pFb\mF`_pFb\mF[\o#!$.#F]w**F6FbpFdtF',(F]rFj]pF6!$7%"$l%F'F'FAFBF`cm
Ff_p#FfzF[dlFc`oF^]mF]`pF`cm*(FgeoF'FAFBF6FGFB**F@F'FAFBF6F8,(FeyFi`lF]vF_bmF_w
FgglF'F'F(F(,doFfgoFajq*,F6FbpFIFHFFF`rFAFEF[brF'Fb_rFjgoF\cp*,FIFHF6FbpFAFEFFF
`rFabrF'#F9FfglF^hoFdiq*,F6FbpFIFHFFF`r,&F6Fedo!$e$F'F'FAFEF^bp*(FAFBF6FGFfbrF'
Fd`lF`hoFielF_]o#FfilF^_o*,F6FbpFIFHFFF`rFAFEF^brF'F]drFehoFielFghoF`rFihoFaap*
*F@F'FAFBF6F8FaeoF'Fa`lFbioFielFdioF_jmFeioF_jmFfioFfvFh]o#"$d)Fb_o*,FAFEFFFHF6
F8FIFHFicrF'FHFdboFj^o*,,(F]vFf`lF\vF^]mFdxFf`lF'FAFEFFFHF6F8FIFHF7*&FcflF'Fdhl
F'F'*&FfhlF'F]glF'F'FjioFielF[joFEF\joFb^o*,F6FbpFIFHFFFHFAFEFccrF'Fb_rF_jo#Fbp
FajoFb]o#Fb^mFd]oFj]oF`boFe]o#!$P%Fb_oF^^oF]_oF\_oF_^o*(F_ioF'FAFBF6FGFE**F@F'F
AFBF6F8,(F^yFj\nFcvF[gmFevF_^mF'FHF(FhjoF(F(F(F(,,*(F6FbpFFF',&F6F[dlF]dmF'F'Fc
fpFf_oFcaoFc_oFd_oFe[pFd`lFd[pFa`lF(,doFfgoFajqF[drFb_rFjgoF\cpF\drF]drF^hoFdiq
F^drF^bpF`hoFielF_]oFbdrFcdrF]drFehoFielFi[pF7FihoFaapFbioFielFdioF_jmFeioF_jmF
fioFfvFh]oFedr*,FAFEFFFHF6F8FIFH,(FdxFg\lF\vFb\mF]vFg\lF'F`rFgdrFHFdboFj^oFjdrF
'*&F_glF'F^ilF'F'FjioFielF[joFEF\joFb^oF\erFb_r*(FibrF'FAFBF6FGFa`lF_joF]erFb]o
F^erFj]oF`boFe]oF_erF^^oF]_oF\_oF_^o**F]eoF'F@F'FAFBF6F8Fd`lFaerFEFberFHF(F(,jn
FbcoFi_oFecoFcfp*(FAFBF6FGFierF'Fd`lFj[oFcipFhar#FBF[\lFg[oFa_oFh[o#FfzFh\l*(F6
Fbp,*Fd^mFj]pF]r!$-&F6"$x)!$l%F'F'FAFBFi_oFfdoFcfp*,F6FbpFFF'F[brF'FdtF'FAFBFi_
o**F@F'FAFBF6F8Fj[pF'Fa`l*,FAFEFFFHF6F8FIFHFcerF'F'FcbrFa_oFdbrFa_o*,F6FbpFFF'F
abrF'FdtF'FAFBFhgp**F6FbpFFF',(F]r"#vF6!$A#"$G"F'F'FAFBFcfpFheoF]iq*$FdhlF9F'*&
FfhlF'F^ilF'F'Fa^pFB*,F6FbpFFF'F^brF'FdtF'FAFBFhgp*(FidrF'FAFBF6FGFa`lF[\o#Fgjl
F[\lF_fo#F^pF[dlFbfoFcfpFffoFcfpF_goFd_oFagoFcfpFb\oFd`o**FhhoF'F@F'FAFBF6F8Fd`
l**F6FbpF\zF'FAFGF@F'#FfxFcjo7$7%F9FMF'X,F*6"F,[gl!"%!!!#1"%"%F(F(,hsFfgoFg_pFf
`pF`r*,FIFHFFFHFdtF'F6FgyFAF7FbaqF[drFb[p*,F6FbpFIFHFFF`rF[flF'FAFEFaboFjgoFb[p
F\drFbaoF^hoF_hoFh`pF]_o*(F_dpF'FAFBF6FGFE*(F]pFHF6F^pFc`lF'Ffs**F@F'FAFBF6F8,(
FcvF_^mFevF[gmF^yFi[oF'FH*&F6F8FibrF'Fd`l*(F]pFHFiflF'F6FcapF`cm*,F[\nF'FAFEFFF
HF6F8FIFHF`r*,FFFHFIFH,(F6F]jqFc\mF'F]rF[ilF'F6FbpFAFEFd`qF`hoF_jmF_]o#F\^oF^_o
*,FFFHFIFH,(F6!#g"#fF'F]rF[dlF'F6FbpFAFEF]hoFcdrFaaq*,Fe\nF'FAFEFFFHF6F8FIFHF7F
_apF]io*,F6FbpFIFHFAFEFFFH,(F]rFj]pF6!$(R"$M%F'F'F^]mFdapF`]o*,F6FbpFIFHFAFEFFF
H,(F]rFjvF6!$$>"$1#F'F'F\bmFeap#"$t'F`^oFi^oFj^o*,F6FbpFIFHFFF`rFjhnF'FAFEF]ioF
eho#FGFfgl*,F6FbpFFF`rFIFHF]\nF'FAFEF]ioFihoF]ioFiapF_^mFddrFd`lFbio#FBF_inF]`r
Fb^oFeioFielFfio#F^flFd]oFh]o#!$B%F]^oFherF7*,F6FbpFIFHFFF`r,&!#HF'F6F[dlF'FAFE
F]hoF^jq#FesF^_oF_bpFgjo*&,(FhhlFj]mFihlF\bmFiclF[gmF'F6F7FBF]cpFd`qFacpFggo*,,
&F]vFcqF\vFBF'FAFEFFFHF6F8FIFHF]_o*&FcflF'Fj\mF'F'*&Fg[mF'F]glF'F'*,FFFHFIFH,(F
6!$:""$4"F'F]rF[ilF'F6FbpFAFEFd`qFdcpFe[rFgcpFgjo*&F6F8Fi]nF'Fa`lFjio#!#ZF`^o*,
F6FbpFFFHFIFHFAFE,(F]rF[ilF6F]hqFc_pF'F'FbjrF[dp#"$"\F]^oF[joFH*(F6FcapF]pFHF[f
lF'Fjhl*,F6FbpFIFHFFF`r,&!#fF'F6F[ilF'FAFEFd`q*,F6FbpFAFEFFF`rFIFHFferF'Fd`qF\e
rF]hoF^[rF^]mF_joF`]o*,FFF`rFIFHF[\mF'F6FbpFAFEFaboFb]o#Fd\pF]^oFj]oF`]oFe]o#"$
P%Fb_oF[epF`]oF\epF]ep*.FIFHFFFHF]jmF'FdtF'F6FbpFAFEFd`q*,F6FbpFFF`rFIFHF^[pF'F
AFEF]hoF(F(F(F(F(,hsFfgoFg_pF_epF7F]hrFbaqF[drFb[pF^hrFaboFjgoFb[pF\drFbaoF^hoF
_hoFh`pF]_oF_hrFEFahrFHFdhrF`cmFehrF`rFfhrFd`qF`hoF_jmF_]oFhhrFihrF]hoFcdrFaaqF
]irF7F_apF]ioF^irF^]mFdapF`]oFbirF\bmFeapFfirFi^oFj^oFhirF]ioFehoFiirFjirF]ioFi
hoF]ioFiapF_^mFbioF[jrF]`rFb^oFeioFielFfioF\jrFh]oF]jrF_jrF]hoF^jqFbjrF_bpFgjoF
]cpFd`qFacpFggoFejrF]_oFgjrF'*&F_glF'Fc]mF'F'FijrFd`qFhdrF`rFdcpFe[rFgcpFgjoFji
oF^[sF`[sFbjr*&Fd^nF'F6F8Fd`lF[dpFb[sF[joFHFd[sFjhlFe[sFd`qFh[sFd`qF\erF]hoF^[r
F^]mF_joF`]o*(F``lF'F]pFHF6F^pFatFi[sFaboFb]oFj[sFj]oF`]oFe]oF[\sF[epF`]oF\epF]
epF]\sFd`q*&FfbrF'F6F8Fa`lF\frFa`l*&F6F7,(FhhlFjhlFiclF_^mFihlF`cmF'F'F^\sF]hoF
(F(,dtFjepFEF^fpFb[pFbcoFbaoFecoFb[p*(F6Fbp,*F]r!$([F6"$J)!$M%F'Fd^mFj]pF'FAFB#
FBF^gpFj[oFf\rFefpF_^mF[gpF\gp*(,*F6"$0#!$^"F'Fd^mF[dlF]rFjfpF'FAFBF6FbpFbaoF_g
pF]fp*,FAFEFFFHF6F8FIFHFbhrF'FHFharFg]pFg[oFcaoFh[o#F[dqF]^oFafrFb[pFcgpF]fpFdg
pFa\r**F6FbpF\rF'FAFGFFF'Fg]p*&FfjrF'F6F8F_boFfdoFb[pFffrF\]s*(F6Fbp,*F6"$%>!$W
"F'Fd^mF[dlF]rFhdmF'FAFBFb[p*(F6Fbp,*F6"$">FgbnF'Fd^mF[dlF]r!##*F'FAFBFbaoF]hpF
b[p*(F6Fbp,*F6"$'Q!$s#F'Fd^mF[ilF]rF^[qF'FAFBFb[pFd]qF]\r**F^[lF'F6FbpFAFGF@F'F
]\rFbhpFd\rFghpFb[pFhhpFb[p*(F6Fbp,*F]r!$Q#F6"$*R!$1#F'Fd^mFjvF'FAFBFb[pF\ipFb^
oF]ipFb^o*(,*F6FairFj^pF'Fd^mF[ilF]rFbfpF'F6FbpFAFBFb[pFdipF]\r*(F6FbpFexF'FAFB
F]\rFcbrF]\rFdbrF]\rFeipF]\r*(FfjrF'FAFBF6FGF_bo*(F6Fbp,*F6"$(>!$Q"F'Fd^mF[dlF]
r!#%*F'FAFBFbao*(F6Fbp,*F6"$'>Fh]sF'Fd^mF[dlF]rF\^sF'FAFBFb[pFifrFb[p**F6FbpFFF
9FAFBF^[pF'FbaoFgipFd_oFheoFd_oF`^qFb^o*&FfhlF'Fc]mF'F'*(,*F6"$$>F^_sF'Fd^mF[dl
F]rF\^sF'FAFBF6FbpFbaoF]jpF]\r**F@F'FAFBF6F8F[\nF'Fd`l*(,*F6"$*>!$b"F'Fd^mF[dlF
]rFhdmF'FAFBF6FbpFb[pFi^qF^\r*&F\`nF'F6F8Fd`lFa^pFH**F6FbpFAFBFFF9FferF'Fb[p*&F
dhlF'Fj\mF'F'*(FAFBF6FGFe\nF'Fa`lFagrFbao**F^`nF'F@F'FAFBF6F8Fb^oFbgrFd`lF[\o#!
%*R"F]^oF^^rFgglF_foFdzFbfoFb[pFffoFb[p*(Fh`lF'F]pFHF6F^pFat**F@F'FAFBF6F8F`epF
'Fa`lFc[qFd_oFagoFb[pFc`oF^bo*(F6FbpFfyF'FAFBF]\r*(,*F6"$!R!$"GF'Fd^mF[ilF]rF^[
qF'FAFBF6FbpFb[p*&FierF'F6F8Fa`lFegrFa`lFfgrFegpF(F(,dtFjepFEF^fpFb[pFbcoFbaoFe
coFb[pFg\sF\]sF^frFa`lFj[oFf\rFefpF_^mF[gpF\gpF]]sFbaoF_gpF]fp**Fg`pF'F@F'FAFBF
6F8Fd`l*(F]pFHF6F^pF`alF'Ffs*&F6F8FidrF'Fd`lFa]sFHFharFg]pFg[oFcaoFh[oFb]sFafrF
b[pFcgpF]fpFdgpFa\rFc]sFg]pFd]sF_boFfdoFb[pFffrF\]sFe]sFb[pFi]sFbaoF]hpFb[pF]^s
Fb[pFd]qF]\rFa^sF]\rFbhpFd\rFgfrFd`lFghpFb[pFhhpFb[pFb^sFb[pF\ipFb^oF]ipFb^oFg^
sFb[pFdipF]\rFi^sF]\rFcbrF]\rFdbrF]\rFeipF]\rFj^sF_boF[_sFbaoF`_sFb[pFifrFb[pFc
_sFbaoFgipFd_oFheoFd_oF`^qFb^o**Fe\nF'F@F'FAFBF6F8Fa`l*&Fg[mF'F^ilF'F'Fe_sFbaoF
]jpF]\rFi_sFb[p*&F6F8FbanF'Fa`lFi^qF^\rFa^pFHF^`sFb[pF_`sF'FagrFbaoFa`sFb^oF[\o
Fb`sF^^rFgglF_foFdzFbfoFb[pFffoFb[pFc[qFd_oFagoFb[pFc`oF^bo*(F[\nF'FAFBF6FGFd`l
Ff`sF]\rFg`sFb[pFfgrFegpF(7$7%F9F9F9X,F*6"F,[gl!"%!!!#1"%"%,`w*(Fb\qF'FAFBF6FGF
B*.FFF`rFIFHFf\lF'F]pFEF6#Fi`nF9FAFEFj]m*&,&FfclFMFg\mFbpF'F6F7Fa^q*.F6FcapF]pF
HFIFHF]gmF'FAFEFFFEFjhlF^fpFjhlFj\qFfdl*,FIFHF]pFEF6F[bsFFF`rFAFEFfdl*&,&F`hlFb
pF_hlFjxF'F6F7#FBFjvFdfpFe[nFefpFfcrFffpFjhlF]]sFjhl*,FgepF'FAFEFFFHF6F8FIFHF7F
h[o#Fb\nF]w**FAFBFFF'F6FbpFa[sF'F`cmFdgpFi[oFc]sF[^l*(F6Fbp,,F]r"$m&F6!$Q&F`cpF
'Fh\qF[ilFd^m!$D#F'FAFGF`cmF]gqFb\mFbgqF`cm*(,*Fd^mF[dlF]r!#lF6"#&)!#KF'F'FAFBF
6FbpFjhlF[hpF`cmFi]sFjhlF]hpFjhlF]^sF`cm*&FablF'F]glF'F'*,,0F^\lFi`lFgzFi`lFj`l
FatFczFi`lF[alFfsF^yFi`lFcvFb\lF'FAFEFFFHF6F8FIFHF7Fa^sFe[nFbhpFiel*(F6Fbp,*Fd^
mF[ilF]r!$D"F6"$c"Fi^mF'F'FAFBF`cm*(,*Fd^mF[dlF]rF_enF6"#')!#OF'F'FAFBF6FbpFjhl
*(,*Fd^mF[ilF]rFjjoF6FeirFd`mF'F'FAFBF6FbpF`cmFghpF`cm**F@F'FAFBF6F8,0F_]lFi`lF
a[lFi[mF\\lFfsF][lFfsF_[lFfsF]vF_bmFcyFi`lF'F'F][pF`cm*(,*Fd^mF[ilF]rF^gmF6"$<#
!$/"F'F'FAFBF6FbpFb\m*(,,F]r"$B'F6!$"p"$q#F'Fh\qF[ilFd^m!$K#F'FAFGF6FbpF`cmF`[p
F`cm**F6Fbp,(F]rF[ilF6Fjen"#]F'F'FFF'FAFBF`cmFhhpFjhlFihpF`cm**F@F'FAFGF6FbpF`]
lF'Fihm*(FAFGF6FgyFj[lF'FihmF]ip#F'Fj]pF^ipF`cmFg^sF`cm*.FAFEFFFHF6FcapF]pFHFIF
HF[flF'FLFdipFdz*.F6F[bsFFF`rFIFHF[\mF'F]pFEFAFEFj]m*,FAFEFFFHF6F8FIFH,0F^\lFb
\lFgzFb\lFj`lFfsFczFb\lF[alFatF^yFb\lFcvFi`lF'F`r*,Fd^nF'FAFEFFFHF6F8FIFHF`r*,F
AFEFFFHF6F8FIFHFi]nF'F7Fi^sFihmFi]qF`rFj]qF7*&Fa]mF'F\]mF'F'FeipFihmF[_sFjhl*(,
*Fd^mF[dlF]rFfgnF6"#yF`inF'F'FAFBF6FbpFjhl*(F6Fbp,,F]r"$T&F6!$0&FegqF'Fh\qF[ilF
d^m!$?#F'FAFGF`cmFc_sFjhl*,FAFEFFFHF6F8FIFHFabpF'F`rFfipFe[n*(,*Fd^mF[dlF]r!#oF
6"#%*F[hmF'F'FAFBF6FbpFjhl*.F]pFHFIFHF6FcapFFFHFiflF'FAFEFL*(,,F]r"$t&F6!$u&Fgd
mF'Fh\qF[ilFd^mFjbsF'FAFGF6FbpF`cm*.F]pFHFFFHFIFHFf\lF'FAFEF6FcapFj]mFe_sFjhlFi
ipF`cm**F6FbpFdtF'F`vF'FAFBFe[n*.FIFHFFFHFb[mF'F]pFEF6F[bsFAFEFj]m*,F6FcapFIFHF
FFHF]pFHFAFEFLF_[pF`cmFhgqF`cmFh^qF]zFi^qFe[nF^jpFfcr**F6FbpFFF',*Fh]sF'F6"$#HF
d^mF[ilF]r!$t"F'FAFGFb\m*(,*Fd^mF[ilF]rF]hqF6"$)>F\^sF'F'FAFBF6FbpF`cmF[\o#Fajr
Fbv*&F6F7,BF_\mF[gmFd\m#FbvFiuF]]mF^]mFj[mF[gmFa[mF[gmFh\mF[gmFjglFfsFh[mFielF]
hlFfsF\\mFf`lFcclFielFiglFf`lF^dmFd_nFdglF_^mF`hlFg\lF_hlF\clF'F'FejpF`cm*&,&Ff
clFguFbgmFcqF'F6F7Fa^qFa_qF_jmFjjpF`cm*(,*Fd^mF[ilF]rFecsF6FiamFagnF'F'FAFBF6Fb
pF`cmF_[qF`cm*.FIFHF6F^pFFFHF]pFHFAFEFc`lF'F`rFbhqF`cmF_^rFa^q*&FgeoF'F6F8FB*&,
BF_\mF_^mFd\m#F[rFiuF]]mFb\mFj[mF_^mFa[mF_^mFh\mF_^mFjglFatFh[mF_jmF]hlFatF\\mF
g\lFcclF_jmFiglFg\lF^dmF`gmFdglF[gmF`hlFf`lF_hlFcelF'F6F7FBFg`sF`cm*(F6Fbp,*Fd^
mF[dlF]rFfgnF6"#w!#CF'F'FAFBFjhl*.F``lF'FIFHF6F^pFFFHF]pFHFAFEF7*&FcflF'Fh`mF'F
9*&F_glF'F_blF'F'Fa[pFb\mF(F(,dy*&,&F_clFbpF^^mFMF'F6F7F`\oFf`pF7F]hr#FfilFb_oF
^hrF]]o*,,(F]rFjvF6!$Y""$2"F'F'FFFHFIFHF6FbpFAFEF^bpF^`qF^bp*,,&F6FMF^pF'F'FIFH
FFF`rF6FbpFAFE#F9F[\lFe`qFE**F@F'FAFBF6F8FfenF'Fa`l**F6FcapF]pFHFcjlF'FAFBFfdl*
&,&Fjfl"#=FijlF8F'F6F7F^es**F]pFHF6FcapF\jlF'FAFBFjhlFh`pF\cpF]aqF^bpFfhrF^bp*,
F6FbpFFFHFIFH,*!#sF'F]rFgbpFd^mFcqF6"$;"F'FAF7F`jq*,,(F]rF[dlF6!#cF[esF'F'FIFHF
FFHF6FbpFAFEFb_r**F@F'FAFBF6F8FabpF'Fd`lF`hoF^bp*&,&F_clF[vF`glF8F'F6F7Fb\mF_]o
FbdrFdaqF_jmFeaqF_jmFfaqF`jqFihrF\cp*,FFFHFIFH,*F6Fe\p!#XF'Fd^mFjxF]rF[hmF'FAF7
F6Fbp#F'F[\l*.Fh`lF'FIFHF6F^pFFFHF]pFHFAFEF7*(F]pFHF6F]\mFAFBF_^m*,,&F6F[dlFi]m
F'F'FIFHFFF`rF6FbpFAFEFb_rFeiqFd^lF_apF]]o**F\rF'F6F[bsFAFBF]pFEF`cm*,,&F6FjvF^
jsF'F'FFF`rFIFHFAFEF6FbpF__rFgaqFgjoFdapF\clFeap#"$d"Fg]o*,,&Fi[lFf`lF\vF^]mF'F
AFEFFFHF6F8FIFHF7*(FAFBF6FGFi]nF'Fa`l*,,(F]rF[ilF6!$0"FicsF'F'FIFHFFFHF6FbpFAFE
F\cp**F]pFHF6FcapFbilF'FAFBF`cmFehoF\cp*,,&F6F[dlFfilF'F'FIFHFFF`rF6FbpFAFEF]dr
**F@F'FAFBF6F8,,Fe\lFf`lFcvF[gmFczFf`lF^yFf`lFgzF_^mF'FH*(FAFBF6FGFbesF'Fd`l**F
AFBF6F8F]pFHFc`lF'FfsFdioF`]oFfio#!$$=Fd]oFh]o#"$(=F]^oF\bqF`jqFjapF^bp**F]pFHF
6FcapFeilF'FAFBFfdl*(F]dqF'FAFBF6FGFE*,FAFEFFFHF6F8FIFHF^dsF'FH*,F\`nF'FAFEFFFH
F6F8FIFHF`rF]bqF`r*,F6FbpFIFHFFFH,(F6!$>""$="F'F]rF[ilF'FAFEF__r*,F`cnF'FFF`rFI
FHFAFEF6FbpFgjqF_jrF\cpF_bpF\cp**F]pFHF6FcapF@F'FAFBF_^m*,,*Fd^mFjvF]r!$N#F6"$'
R!$7#F'F'FIFHFFFEF6FbpFAFEF]_o**F__mF'F6F[bsFAFBF]pFEF\bm*,FIFH,,Fd^m!$p#F]r"$v
)F6!%H7"$I'F'Fh\qF[ilF'FAF7F6FbpFFFEF\cpFcbpFaap*,,*Fd^mF[ilF]rFifpF6"$"G!$a"F'
F'FIFHFFFEF6FbpFAFEF\cpF^bqFgjoF`bqF^bpFebpFaapFjbpF\cpF]cpF\cp**F6FcapF]pFHFii
lF'FAFBF`cm**F6FcapF]pFHFejlF'FAFBF`cmFebqF^bp**F6F[bsFa^mF'FAFBF]pFEF\bmFijrF^
bp**Fg^mF'F6F[bsFAFBF]pFEF\bmFjbqF^bpFbcpF`cm*,F6FbpFFF`rFIFH,(F6!#S"#OF'F]rFcq
F'FAF7#FbvF^gp**F6FcapFAFBFFF'F]pFHF`cm*,,(F]rFjvF6F]isFa]oF'F'FIFHFFFHFAFEF6Fb
pF]_oF`cqF^bpFdcpF^erFjio#Fc[nF`^oF`[sF__rF[dpF]er*,,*Fd^mF[ilF]rFj_pF6"$@$!$%>
F'F'FIFHFFFEF6FbpFAFEF\cpF`dpF\cpFe[sF]_o*,,&F6FgxFfxF'F'FFF`rFIFHFAFEF6FbpF]]o
*,FbinF'FIFHFFFHFAFEF6FbpFaar*,,(F]rFjvF6!$_""$9"F'F'FIFHFFFHF6FbpFAFEF^bp*,,(F
]rFjxF6F[fmF[dlF'F'FIFHFFFHF6FbpFAFEFejsFedpFaap*,,(F]rF[ilF6Fjfp"#pF'F'FIFHFFF
HF6FbpFAFEF\cp*,,(F]rFjvF6!$X""$1"F'F'FIFHFFFHF6FbpFAFEF__r**F]pFHFh]mF'F6FcapF
AFBF\bm*&,&F_clFfisF\hmF8F'F6F7F`\o*,FAFBFFF'F6FcapF]pFHF[flF'Fe[m*,F6FbpFFFHFI
FH,*F]rFbipF6"$@%!$q#F'Fd^mF[ilF'FAF7F]]o*.FcflF'FAFEFFF`rF6F[rFIFHF]pFEFfsFi[s
F]]oFb]o#F[hnFb_oFj]oF`boFe]o#!$@&Fb_o*,,(F]rFMF6FganFiuF'F'FIFHFFFHFAFEF6FbpFa
isF[epF\cl*&Fg[mF'F\]mF'F'*&F_ioF'F6F8FE*&,NF^_mF`cmFb_mF^]mF`^mF`cmFf_mF[gmFf^
mF`cmFg]mF`cmF]^mFi[mFe^mF^]mFc_mFi[mF]_mF[gmF[_mFjhlF_hmF\bmFhilF\bmFijlFjhlF_
clF`gmF`glF_^mFdjlF\bmFjflFfwFailF\bmFbjlF]dlFdilF]dlF[jlFj]mF'F6F7FB*,F]pFHFFF
'F6FcapFAFBFdclF'Fj]m*,F]pFHFAFBFFF'F6FcapFiflF'Fe[m*&FdhlF'Fh`mF'F'*&FfhlF'F_b
lF'F'*,F6FbpFFF`rFIFH,(F6F]hqFegqF'F]rF[ilF'FAF7Fb_rF^\sF\cpF(,\sF^fpFi_oFa^rFd
`lFdfpFa_oFefpFe[mFffpFhgpF[gp#FajlFd]oF_gpFcaoFc^rFatFh[oF\gqFbgpFa_oFcgpFa_oF
dgpF^arFfgpFa`lFg]rFa`lFadqFddqFj]rFd_oF[hpFi_oF]hpFi_oFc\rFielFbhpFd`qF\]pFcao
Fe\rFBFf[qFd`lFehpFd`lFfhpFeaoFghpFi_oFhhpFi_oFihpFi_oF]ipFd_oF^ipFi_oFh]pFb[pF
dip#FjzFajoFedqFb[pFfipFggrFgipFeaoFhipFd_oFiipFi_oF`^pFcaoF]jpFa_oFg\rFfsF[^rF
fsF\eqFb[pFaeqFb[pFfeqFcaoFj[qFa`lF^jp#F]gpFc[pFc^pFb[pFf^pFb[pF[_pFb[pF`_pFb[p
FheqFb[pF[\o#Fg[sFajoF^^rF_jmFf_pFi[mF]]rFd`lFejpFi_oF]fqFbaoFjjpFi_oF_[qFi_oFc
[qF[[pF_^rFeaoF^]rFatF]`pFbaoF[]rFa`lF(F(F(F(,bsFjepF'*&Fg[mF'Fc]mF'F'*$Fj\mF9F
'F^fpFi_oFbcoFi_oFecoFcfp*(F6FbpFfdmF'FAFBFcfpFj[oFcipFefpF_jmF[gpFdatF]]sFhgpF
_gpFcaoF]asFa`lF^asFatF_asFa`lFharFcipFg[oFa_oFh[o#FibmFg]oFcgpFa_oFdgpF^ar*(,*
F6F_\tF]jqF'Fd^mF[dlF]rF]emF'FAFBF6FbpFcfpFc]s#FBFc[mFc]qFd_o*(FAFGFFFMF6FbpFci
pFfdoFcfpFi]sFhgpF]hpFi_o*(F6Fbp,*Fd^mFbvF]rF_csF6FdcmF_]nF'F'FAFBFi]rF]^sFi_oF
d]qFa_oFa^sFa_oFbhpFd`qFghpFi_oFhhpFi_oF]ipFd_oFg^sFi_oFi^sFa_o*&FfcnF'F6F8Fd`l
FeipFa_o*(F6FbpFjdmF'FAFBFcfpF[_sFhgpFc_sFhgpFgipF]iqF`^qFd_oF`asFd`l*(,*Fd^mF[
dlF]rFhdmF6Fdco!$6"F'F'F6FbpFAFBFcfpFe_sFhgp*&F6F8F_dnF'Fa`lF]jpFa_oFh_sFa`lFfe
qFcaoFi^qFfatFa`sFd_oF[\o#FcjpFd]oF^^rFe[mF_foFgdl*(,*Fd^mF[dlF]rF\^sF6"$$=!$7"
F'F'F6FbpFAFBFcfpFbfoFcfpFffoFcfpFd`sFfsFe`sFd`lFc[qFd_oFagoFcfpF_^rFeaoFg`sFi_
oF[asFd`lFfgrFa_oF(,dyFhhsF`\oF_epF`rF]hrFjhsF^hrF]]oF[isF^bpF^`qF^bpF_isFaisFe
`qFE**F``lF'FAFBF6F8F]pFHFatFcisFfdlFdisF^esFgisFjhl*&F6F7,NF^_mF\bmFb_mFb\mF`^
mF\bmFf_mF_^mFf^mF\bmFg]mF\bmF]^mFe[mFe^mFb\mFc_mFe[mF]_mF_^mF[_mFj]mF_hmF`cmFh
ilF`cmFijlFj]mF_clFd_nF`glF[gmFdjlF`cmFjflF\wFailF`cmFbjlFfdlFdilFfdlF[jlFjhlF'
F'Fh`pF\cpF]aqF^bpFfhrF^bpFhisF`jqF\jsFb_rF`hoF^bpF`jsFb\mF_]oFbdrFdaqF_jmFeaqF
_jmFfaqF`jqFihrF\cpFbjsFejsFgjsF_^mFhjsFb_rFeiqFd^lF_apF]]oFjjsF`cmF[[tF__rFgaq
FgjoFdapF\clFeapF][t*&FablF'F^ilF'F'Fb[tF\cpFe[tF`cmFehoF\cpFf[tF]drFh[tFH*(Fd^
nF'FAFBF6FGFd`l**FgepF'F@F'FAFBF6F8Fa`l**FcenF'F@F'FAFBF6F8Fd`lFdioF`]oFfioF\\t
Fh]oF^\tF\bqF`jqFjapF^bpF`\tFfdlFa\tFE*,FAFEFFFHF6F8FIFH,&Fi[lFg\lF\vFb\mF'F`rF
b\tFH*,FAFEFFFHF6F8FIFHFbanF'F7FhfqF7Fd\tF__rFh\tFgjqF_jrF\cpF_bpF\cpFi\tF_^mFj
\tF]_oF_]tF\bmF`]tF\cpFcbpFaapFf]tF\cpF^bqFgjoF`bqF^bpFebpFaapFjbpF\cpF]cpF\cpF
j]tF`cmF[^tF`cmFebqF^bpF\^tF\bmFijrF^bpF]^tF\bmFjbqF^bpFbcpF`cmF^^tFb^tFc^tF`cm
Fd^tF]_oF`cqF^bpFdcpF^erFjioFf^tF`[sF__rF[dpF]erFg^tF\cpF`dpF\cpFe[sF]_oF[_tF]]
oF]_tFaarF^_tF^bpFb_tFejsFedpFaapFd_tF\cpFg_tF__rF[`tF\bmF\`tF`\oF^`tFe[mF_`tF]
]o*.FIFHF6F^pFFFHF]pFHFAFEF`alF'F`rFc`tFfsFi[sF]]oFb]oFd`tFj]oF`boFe]oFe`tFg`tF
aisF[epF\cl*&Fa]mF'Fc]mF'F'Fj`tFE*(FbcsF'FAFBF6FGFa`lF]atFj]mF^atFe[mF_atF'Faat
Fb_rF^\sF\cpF(F(,\t*(F\`nF'FAFBF6FGFd`lFiatF'Fc\qFcfp**Fh`lF'FAFBF6F8F]pFHFat**
F@F'FAFBF6F8F]fnF'Fa`l**F6FbpFFF',*F6"$@#F]\oF'Fd^mF[ilF]r!$g"F'FAFGFi_oFdfpFa_
oFj[oFcipF[]qFchpF]asFa`lFharFcipFg[oFa_oFh[oF^arFbgpFa_oFdgpF^arFc]sF_btFfbsFi
_o*(,*Fd^mF[dlF]rFa_mF6F[vFc[mF'F'F6FbpFAFBFcfpF\]qFd\rF]]qFcfpF[csFhgpF`btFcip
*(F@F9FAF8F6FgyFd_o**F6Fbp,(F]rF[dlF6!#=FgyF'F'FFF'FAFBFcfpFd]qFa_oFc\rFi[m*(,*
Fd^mF[dlF]rFcilF6Fc[nFhglF'F'FAFBF6FbpFcfp*(FAFBF6FGFbanF'Fa`l*(F`[tF'FAFBF6FGF
a`lFa^sFa_oFbhpF^bpF\]pFcaoFfhpFeao**F6FbpFFF',*F6F^_n"#aF'Fd^mF[dlF]rFfgnF'FAF
GFcfp*(FAFBF6FGFgctF'Fd`l**FdfnF'F@F'FAFBF6F8Fd`l**FAFBF6F8F]pFHF`alF'FfsFcdsFi
_oF\esFa_oF]esFa_oF]ipF[[p**F6Fbp,(F]rF[ilF6F]cs"#EF'F'FFF'FAFBFi_o*,FAFEFFFHF6
F8FIFHFi[tF'F'FfgqFBF[^qFcfp**,(F]rF[dlF6F]dmFfisF'F'FFF'F6FbpFAFBFhgpF_fsFhgpF
`^qFd_oFhipFd_oFdfsFi_oF`^pFcaoFb^qFi_o**F6Fbp,(F]rF[dlF6F`\lF]]lF'F'FFF'FAFBFc
fp**F6Fbp,(F]rF[dlF6F_csFa\lF'F'FFF'FAFBFhgpFh^qFaapFi^qFfatF^jpFfat**,(F]rF[dl
F6F_csFc[mF'F'FFF'F6FbpFAFBFhgpF`gsFi_oFa`sFd_oF[\o#"#TFajoF_foFgdlFf_pFielFa_q
Fg]pFb_qFcfpFigsFi_o*(,*Fd^mF[dlF]r!#^F6"#MFiuF'F'FAFBF6FbpFcfpFe`sFd`l*.FdhlF'
FAFEFFF`rF6F[rFIFHF]pFEFHFg_qFcfp*(FAF8F6FesF@F'FeaoFfgrFa_o7$7%F9F'FMX,F*6"F,[
gl!"%!!!#1"%"%F(F(,\y*,FIFH,,F]r"%0TF6!%Gc"%?GF'Fd^m!%)H"Fh\qFc`qF'FAF7F6FbpFFF
EFgjoFhhsFieoFfgoFgjo*&,&F_clFeclF`glFMF'F6F7Fb\m*,,*Fd^mF[dlF]rF]doF6F^grFafsF
'F'FIFHFFFEF6FbpFAFEFj]m*,FIFH,*Fd^mFjxF]rF_csF6FgflFjuF'F'FAFEF6FbpFFFEFe[mFi^
rFgjo*,FIFH,,F]r"%vUF6!%6f"%qHF'Fd^m!%J8Fh\qFc`qF'FAF7F6FbpFFFEFgjo*&F_dpF'F6F8
FEF^`qF\]sFe`qFHFbisFd`lFcisF]dlFgisFj]m*,F[]lF'F6FbpFAF7FFFHFIFHF`jo*,F6FbpF_
\lF'FIFHFFFEFAFEF\cpFh`qFj`q*,,*Fd^mFgxF]rFdbnF6"##*Fi^mF'F'FIFHFFFEFAFEF6FbpF[
gmFh`pF\aqF]aqF\]sF_jsFa`lF`hoFd`qF_]oFhhrFcaqF_^o*,FienF'FIFHFFFEFAFEF6FbpF\bm
*,,*Fd^mFj]pF]r!$#\F6"$"))!$9&F'F'FIFHFFFEF6FbpFAFEFd`q*&F6F8FbcsF'Fd`lFeaqFiel
Fbjs#F[rFj_o*&,&FjflFidtFijlFMF'F6F7FieoFgjsF_^m*,FFFHFIFH,*F]r!$%fF6"%P7!$5)F'
Fd^mFj]pF'FAF7F6FbpFd`q*&F6F8FcenF'Fa`lFeiqFeamF_apF]io*,,(F]rF[dlF6Fc^mFhdpF'F
'FIFHFFFHF6FbpFAFEFd`qFdap#"$,"F]^oFeap#!$$))Fb_o**F6FcapF]pFHFdtF'FAFBFb\m*&Fj
\mF'Fh`mF'F'*&Fg[mF'F_blF'F'**F@F'FAFBF6F8,,Fe\lFg\lFcvF_^mFczFg\lFgzF[gmF^yFg
\lF'FHFehoFd`q*,FAFEFFFHF6FbpFIFH,&F6F[\lF^\mF'F'Fabo*,FfcnF'FAFEFFFHF6F8FIFHF`
rFf[tFc]pFg_rFgjoFfioFd`qF\bqF[jrFjapFd`qF`\tF]dlFfctF7Fh\tFd`q*,FIFH,,F]r"$D)F
6!%76"$S&F'Fd^m!$i#Fh\qF[ilF'FAF7F6FbpFFFEF^]mF_bp#FGFhgoFi\tF[gm*,,*Fd^mF[ilF]
rF\`sF6"$f#F^_sF'F'FIFHFFFEF6FbpFAFEF^]mF_]tF\bm*,,&F6FjvFfgnF'F'FIFHFFF`rF6Fbp
FAFEF]hoFcbpF]ioFf]tF]ho**FjdmF'F6F[bsFAFBF]pFEF`cmF^bqF]_oF`bqF\]sFebpF]io*(F]
pFHF6F^pFablF'Ffs*,FAFEFFFHF6FbpFIFHF[flF'FaaqFjbpF]hoF]cpFd`qFacpFggoFebqF\]s*
,FFFHFIFH,&F6Fa\lF]gpF'F'F6FbpFAFEF]hoF\^tF\bm*,FcfqF'FAFEFFFHF6F8FIFHF7*,,(F]r
F[dlF6F`inFfzF'F'FIFHFFFHF6FbpFAFEF\]sF]^tF\bmFjbqF\]s*&FcemF'F\]mF'F'FbcpF\bmF
c^tFd[mF`cqFd`qFdcp#Fi`nFhgo*&,PFedmF\bmFb_mF`cmFf_mF_^mFidmF\bmF^emF_jmF]^mF_j
mFc_mF_jmF[_mFj]mFjhmF`cmF^_mF`cmF_clFfsF`glF[gmF`^mF`cmFjflFielFijlF^]mFf^mF`c
mF^^mF^]mFg]mF`cmFbjlFfdlFdilFfdlF]_mF[gmF[jlFjhlFe^mF\bmF'F6F7FB*,FFFHFIFH,*F]
r!$8'F6"%*H"!$b)F'Fd^mFj]pF'FAF7F6FbpFd`qFjioFd`qF[dp#F]apFfjo**F]pFHF_emF'F6Fc
apFAFBFielF`dpF]ho*,F6FbpFIFH,,F]r"$%zF6!%_5"$/&F'Fd^m!$d#Fh\qF[ilF'FAF7FFFEF^]
mF[_tFddq**FfdmF'F6F[bsFAFBF]pFEF`cmF]_tFbaoFc`rFgjoFb_tF\it*,,(F]rF[dlF6FjcsFg
jlF'F'FIFHFFFHF6FbpFAFEFd`qFedpF]ioFd_tFb[pF[`tF\bmF_joF`boF^`tFielF_`tFb[pFict
F7*,FIFH,*Fd^mF[dlF]rFgbpF6Ff_tFjgqF'F'FAFEF6FbpFFFEFgjoFj]oF`]oFe]o#"$@&Fb_oF[
epF`boF\epF\bm*,Ff\lF'FFFHFIFHF6FbpFAFEFcfpF]atFjhl*,FIFH,,F]r"$b"F6!$*>Fj]pF'F
h\qFjxFd^mFdftF'F6FbpFAF7FFFEFe[mF^atFielFaatFb[pF(F(F(F(F(,\yF]gtFgjoFhhsFieoF
fgoFgjoFcgtFb\mFegtFj]mFggtFe[mFi^rFgjoFigtFgjoF_htFEF^`qF\]sFe`qFHFcisF]dl*&Fa
blF'Fc]mF'F'FgisFj]mF`htF`joFahtF\cpFh`qFj`qFbhtF[gmFh`pF\aqF]aqF\]sF`hoFd`qF_]
oFhhrFcaqF_^oFehtF\bmFfhtFd`qFeaqFielFbjsF\itFfjsF`rF]itFieoFgjsF_^mF_itFd`q*&F
fenF'F6F8Fd`lFeiqFeamF_apF]ioFeitFd`qFdapFgitFeapFiitF[jtFb\mF_[tF`rF\jtF'*&Fbe
sF'F6F8Fa`lF^jtFHFehoFd`qF`jtFabo*,FAFEFFFHF6F8FIFHF_dnF'F7Ff[tFc]pFdctFd`lFect
Fa`lFg_rFgjoFfioFd`qF\bqF[jrFjapFd`q*,FAFEFFFHF6F8FIFHF[eqF'F`rF`\tF]dlFh\tFd`q
FcjtF^]mF_bpFijtFi\tF[gmFjjtF^]mF_]tF\bmF][uF]hoFcbpF]ioFf]tF]hoF_[uF`cmF^bqF]_
oF`bqF\]sFebpF]ioFa[uFaaqFjbpF]hoF]cpFd`qFacpFggoFebqF\]sFb[uF]hoF\^tF\bmFe[uF
\]sF]^tF\bmFjbqF\]s*&Fa]mF'FaemF'F'FbcpF\bmFc^tFd[mF`cqFd`qFdcpFh[uF[\uFd`qFjio
Fd`qF[dpF`\uFa\uFielF`dpF]hoFb\uF^]mF[_tFddqFh\uF`cmF]_tFbaoFc`rFgjoFb_tF\itFi
\uFd`qFedpF]ioFd_tFb[pF[`tF\bm*&F6F7,PFedmF`cmFb_mF\bmFf_mF[gmFidmF`cmF^emFielF
]^mFielFc_mFielF[_mFjhlFjhmF\bmF^_mF\bmF_clFatF`glF_^mF`^mF\bmFjflF_jmFijlFb\mF
f^mF\bmF^^mFb\mFg]mF\bmFbjlF]dlFdilF]dlF]_mF_^mF[jlFj]mFe^mF`cmF'F'F_joF`boF^`t
FielF_`tFb[pF[]uFgjoFj]oF`]oFe]oF]]u*(F_blF'F]pFHF6F^pFatF[epF`boF\epF\bmF_]uFc
fpF]atFjhlF`]uFe[mF^atFielFaatFb[pF(F(,jt**F@F'FAFBF6F8F[eqF'Fd`lFc\qFb[pF^dtFf
sF`dtF\]sFdfpF]\rFj[oFf\rF[]q#F'F]^oF]asFd`lFg[oFcaoFh[oFa\rFbgpF]fpFdgpFa\r*(F
6FbpFj[lF'FAFBF]\r*.Fj\mF'FAFEFFF`rF6F[rFIFHF]pFEFfsFc]sFg]pFfbsFb[p**,(F]rFjvF
6F^gmFj_tF'F'FFF'FAFBF6FbpFbaoF\]qF_bqF]]qFb[p*&F]fnF'F6F8Fd`lF[csFbaoF`btFg]pF
fdtFb^oFd]qFegpFc\rFd[mF]etFd`lFa^sF]\r*(,*Fd^mF[dlF]rFf`mF6Fd[rFibpF'F'FAFBF6F
bpFb[p*&FgctF'F6F8Fa`lFbhpFchpF\]pF]fpFccsF\]sFgcsFb[p*,FAFEFFFHF6F8FIFHF_jtF'F
HFbetFa`lFcdsFb[p**FFF',*F6"%">"!$?(F'Fd^mFj]pF]rFeeqF'FAFGF6FbpFb[pF\esF]\rF]e
sF]\rF]ipFeaoFdetF\]s*(,*Fd^mF[dlF]rF]doF6"$Q"FdgqF'F'FAFBF6FbpFb[pFfgqFHF[^qFb
[pFhetFb[pFfesFb[pFiesF\]sF_fsFbaoF_^pFb^oF`^qF]iqFhipFd_oFdfsFb[p*&Fg[mF'FaemF
'F'*(FAFBF6FGF_dnF'Fa`lFb^qFbaoF\ftFb[pFh^qF_hqFi^q#"$\$F`^oF^jp#FajlF]^o*(F[]l
F'F6FgyFAFGF]\r*(,*Fd^mFjvF]rFd^sF6"$3%!$C#F'F'FAFBF6FbpFbaoF^ftFb[pF`gsFb[pFa`
sFb^o*(F6FbpF`]lF'FAFBF]\rF[\o#F]jlFa]oF_foFfdlFf_pF[gm*(,*Fd^mF[dlF]rFjenF6Fc_
pF_brF'F'FAFBF6FbpFb[pFa_qFcipFb_qFb[pFigsFb[p**F[]lF'F6FbpFAFGF@F'F]\r**FFF',*
F6"%]6!$-(F'Fd^mFj]pF]rF\fqF'FAFGF6FbpFb[pFg_qFb[pFgftF_boF`hsFb[p**F6FbpFddnF'
FFF9FAFBFb[pFfgrF]\rF(F(,jtFc\qFb[pF_dtFd`lF`dtF\]sFdfpF]\rFj[oFf\rF[]qF`^uFg[o
FcaoFh[oFa\rFbgpF]fpFdgpFa\rFa^uF]\rFb^uFfsFc]sFg]pFfbsFb[p*&F6F8F`[tF'Fd`lFc^u
FbaoF\]qF_bqF]]qFb[p*&F6F8FdfnF'Fa`lF[csFbaoF`btFg]pFfdtFb^oFd]qFegpFc\rFd[mFa^
sF]\rFf^uFb[pFbhpFchpF\]pF]fpFccsF\]sFgcsFb[pFi^uFHFaetFa`lFcetFatFcdsFb[pFj^uF
b[pF\esF]\rF]esF]\rF]ipFeaoFdetF\]sF^_uFb[pFfgqFHF[^qFb[pFhetFb[pFfesFb[pFiesF
\]sF_fsFbaoF_^pFb^oF`^qF]iq**FcfqF'F@F'FAFBF6F8Fa`lFhipFd_oFdfsFb[p*&FcemF'Fc]m
F'F'Fb^qFbaoF\ftFb[pFh^qF_hqFi^qFc_uF^jpFe_uFf_uF]\rFg_uFbaoF^ftFb[pF`gsFb[pFa`
sFb^oF[`uF]\rF[\oF\`uF_foFfdlFf_pF[gmF]`uFb[pFa_qFcipFb_qFb[pFigsFb[p*(FfcnF'FA
FBF6FGFd`lFe`sFa`lF_`uF]\rF``uFb[pFg_qFb[pFgftF_boF`hsFb[pFd`uFb[pFfgrF]\rF(7$7
%F9F(FcpX,F*6"F,[gl!"%!!!#1"%"%,\qFj\qFfdlF[gpFfcrF_gpFe[nFh[oFi[nFa^uFihm**F@F
'FAFBF6F8,(Fj\lFi`lFhvFgglF\\lFfsF'F'Fc^uF`cmFadqF_^m*(,,Fh\qFj]pFd^m!$J'F]r"%N
:F6!%_:"$e&F'F'FAFGF6FbpFb\mF\]qF_^mF`btFdv*(,,F]r"%vBF6!%-J"%S9F'Fh\qFj]pFd^m!
$s(F'FAFGF6FbpFb\m*(,,F]r"%/BF6!%-I"%/9F'Fh\qFj]pFd^m!$d(F'FAFGF6FbpFb\mFbhpFie
l*$Fh`mF9F'*&FablF'F_blF'F'*.F]pFHFIFHFbbmF'FFFEF6FcapFAF7Fjhl*.F[cmF'FFFHFIFHF
6F[bsFAFEF]pFEFjhl*&,<FacmF[gmFg\mFg\lFgcl#FjzFh\lFd\mF]zFcimFb\mFjbmF[gmF^dmFg
\lFabmF[gmFjglF\clFbdmFg\lF]hlF\clFcclF_jmFfclFg\lF'F6F7FB*&Fb\qF'F6F8FBFj^uFb
\mFf]qF7Fg]qF`rF_esFjcl*&F6F7,<FacmF_^mFg\mFf`lFgcl#F\]lFh\lFd\mF^^lFcimF^]mFjb
mF_^mF^dmFf`lFabmF_^mFjglFcelFbdmFf`lF]hlFcelFcclFielFfclFf`lF'F'*.FbcmF'FFFHFI
FHF6F[bsFAFEF]pFEFjhlFi]qF7Fj]qF`rFedqFb\mFgipFb\mFcfsFjcl*.F@F'FAF7F6FcapFIFHF
FFHF]pFHF`cmFf_oFcelF[gsF\w*,FAF7FFF`rF6FcapFIFHF]pFHFcelF\eqFb\m*&,&F^dmFbpF_h
lFMF'F6F7#FBFj]pFaeqFb\mFg_uFjhl*,FAF7FFFHF6F]\mFIFHF]pFHF\wFheqFb\mF[\oF[[lFa_
qFi[nF]fqF`cmF`_oFihmF_`uFihmF``uFb\m*(,*Fd^mFjvF]r!$L#F6"$#RF^]tF'F'FAFBF6FbpF
`cmF(F(,^o*.Fh`mF'FAFEFFF`rF6F[rFIFHF]pFEFfs*(FAFGF6FcdmF]pFHF_^mF`htF[^oFahtF_
^mF[aqF\aqFh`pF\aq*&F]dqF'F6F8FEFfhtF^bpFdaqF`]oFfaqFe[r**FAFGFFF'F6FcapF]pFHFf
`lF_itF]_oFeapFi[n*,,*Fd^mFhgoF]r!$y&F6"$L*FdjqF'F'FIFHFFFHF6FbpFAF7F__r*,FIFH,
,F]r"%DCF6!%%G$"%?;F'Fd^m!$u(Fh\qFj]pF'FAF7F6FbpFFFEF__r*&,,FiemFj]mFjflF[gmF\f
mF\bmF_dlF[gmF_clF_jmF'F6F7FBFh]o#FfzFc\m*,FIFH,,Fh\qFhgoFd^m!$)yF]r"%*3#F6!%GB
"$C*F'F'FAF7F6FbpFFFEF]_oFhfqF`rF][uFb\mFifqFa`l*,FIFH,,F]r"%DDF6!%`MFa]qF'Fd^m
!$$zFh\qFj]pF'FAF7F6FbpFFFEF__rFacpF\aq**F]pFHF]fmF'FAFGF6FcapF`cmFdcpFccpF[\uF
]_oF[dp#Fc[nFg]o*,FAFEFFFHF6F8FIFHFaauF'FHFb]oFe[rF_]uF`^uFjfqFfs*,FjemF'FFF'F6
F[bsFAFBF]pFEFjhl*,,*Fd^mFjvF]r!$U#F6"$G%!$[#F'F'FIFHFFFEF6FbpFAFEFcfpF(,HF[aoF
a`lF\aoFd`lFh`oFg_oFh[oF\gqFb`oFa_oF]gqFb[pF_arFBF\]qFchpFbgqFbaoFe`oFd_oFbhpFc
hpFggqFd`lFhgqFbaoF^hqFcaoF`hqFd_oF[\oFahqFa_qF\gqFbhqFbaoFehqFa`lF(F(F(F(,RF_^
uFa`lFc\qFcfpFj[oFcipFg[oFa_oFa^uFa_oFf`uFa`lFc^uFhgpF]]qFcfpF`btF_frFd]qFggr*(
,*Fd^mF\grF]r!$(QF6Fe]t!$E$F'F'F6FbpFAFBFcfp*&FcemF'FaemF'F'Fh^uFd`lFj^uFi_oF[^
qFcfpF`^qFg_pFh`uFd`lFb^qFi_oFi^qFdgrFg_uFhgpFb_qFcfpF_`uFa_oF``uFi_oFg_qFcfpF(
,^oF[duFfsF\duF_^mF`htF[^oFahtF_^mF[aqF\aqFh`pF\aqF]duFEFfhtF^bpFdaqF`]oFfaqFe[
rF^duFf`lF_itF]_oFeapFi[nF_duF__rFcduF__rFh]oF[euF\euF]_oF]bqF7F][uFb\mFbeuF__r
FacpF\aq*&F6F7,,FiemFjhlFjflF_^mF\fmF`cmF_dlF_^mF_clFielF'F'FgeuF`cmFdcpFccpF[
\uF]_oFecqFatF[dpFheuFieuFHFb]oFe[rF_]uF`^uF^dqFd`lFjeuFjhlF[fuFcfpF(F(,.*(,,Fh
\qF[dlFd^mFi`nF]r!$c#F6"$k'!$?%F'F'FAFGF6FbpFcfpF^hqFcaoF[\oFdaoF`hqFd_oFggqFd`
lFehqFa`l7$7%F'FbvF(X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,*FeerFb[pFf_oFa_oFc_oFe
aoFe[pFUF(F(,*FeerFb[pFf_oFa_oFc_oFeaoFd[pFLF(F(F(F(F(F(7$7%F'FcpF'X,F*6"F,[gl!
"%!!!#1"%"%F(,\s*,FIFH,*F]r!#!*F6Fdco!$="F'Fd^mF[dlF'F6FbpFAFEFFFEFb\mF]hrFccpF
[drFb[pF^hrF]]oF\drFbao*(Fg[rF'FAFBF6FGFEFadrFa`lFh`pFgjoF`hrFatFchrFa`lFdhrF\b
mFehrF7FfhrF__r*&FdgmF'F]glF'F'FihrFcfpFcdrFbaoF]irF`rFeiq#FaftFd]oF_apFgjqF^ir
F^]mFdapF`boFbirF\bmFeap#!$t'F`^oFhirFaapFhiqF`rFehoF^bpFjirFaapFiapF[gmF]`rF_b
oFdioFielFfio#FfisFfglFh]o#!#*)F^gpFgdrFEF_jrF\cpF_bpF]_oF]cpF__rFacpFajqFijrF_
_rFdcpF]epFgcpFgjoF][sFd`lFjioF^bpF[dp#!$"\F]^oF\joF_boFd[sFj]mFe[sF^bpFh[sF^bp
F\erF]ho*,F6FbpFIFH,*F]r!$)=F6"$"RFb`tF'Fd^mF[ilF'FAFEFFFEF]_o*,F6FbpFIFHFFFH,(
F]rFedoF6!$)o"$;(F'F'FAFEFd`q*,F6FbpFIFHFAFEFFFH,(F]rFjvF6F[iuFb_sF'F'F\bm*,F6F
bpFFF`rFIFH,&F6FgxFb\nF'F'FAFEFjiqF^joFatF_joF`]oFi[sF]]oFb]oFbaq*,FIFH,*F]r!$v
"F6F[[r!$=#F'Fd^mF[ilF'F6FbpFAFEFFFEF]_oF\_oF^bo*,FIFH,*F]r!$"=F6"$i$!$S#F'Fd^m
F[ilF'F6FbpFAFEFFFEF]_oF[epF`boF\epFe[rF]\sF^bpFd\sFBF^\sF\cpF(F(,\sF[huFb\mF]h
rFccpF[drFb[pF^hrF]]oF\drFbaoF_huFEFh`pFgjoFdhrF\bmFehrF7FfhrF__rFihrFcfpFcdrFb
aoF]irF`rFeiqFahuF_apFgjqF^irF^]mFdapF`boFbirF\bmFeapFbhuFhirFaapFj[rF7FehoF^bp
FjirFaapFiapF[gmF]`rF_boFdioFielFfioFdhuFh]oFehuFgdrFEF_jrF\cpF_bpF]_o*&F_glF'F
ggmF'F'FcjrF'F]cpF__rFacpFajqFijrF__rFdcpF]epFgcpFgjoFjioF^bpFa\sFa`lF[dpFghuF
\joF_boFd[sFj]mFe[sF^bpFh[sF^bpF\erF]hoF[frFd`lFihuF]_oF]iuFd`qFaiuF\bmFciuFjiq
F^joFatF_joF`]oFb\sFfsFi[sF]]oFb]oFbaqFeiuF]_oF\_oF^boFiiuF]_oF[epF`boF\epFe[rF
]\sF^bpFc\sFd`lF^\sF\cpF(F(,hsF^fpFcfp**F@F'FAFBF6F8F[\rF'Fa`lFg\sF\]sFefpF[gmF
[gpF^\rF]]sFi_oF_gpF]\rFharFf\rFh[oFa\rFafrFb[pFcgpF]\rFdgpFegpFc]sF_btFa\pFatF
d]sFb^o*,FFF'F6FbpF@F'FAFGFdtF'F_^mFe]sFcfpFi]sFi_oF]hpFcfpF]^sFcfpFd]qF]fpFa^s
F]fpFbhpFchpFe\rFEFghpFcfpFhhpFcfpFb^sFb[pF\ipF_boF]ipF_boFg^sFcfpFdipF]fpFi^sF
]fpFhfrFEFcbrF]\rFdbrF]\rFeipF]fpF[_sFi_oF`_sFcfpFc_sFi_oFjfrF\]s*&FfhlF'FggmF'
F'FgipFeaoF`^qF_boF`asFd`lFe_sFi_oF]jpF]fp**F6FbpF\rF'FAFGFdtF'Ff\rFi_sFcfpFi^q
F\gpF]`sFa`l**F6FbpFFF',(F]rFjvF6!$[""$."F'F'FAFBFb[pF^`sFcfp**F6FbpFFF',(F]rFj
vF6F^gm"#)*F'F'FAFBFb[pFa`sFb^o*(F6Fbp,*F]r!$s$F6"$s&F]guF'Fd^mF\grF'FAFBF\]sFb
grFd`lF[\o#!$h$F]^oF^^rFd[mF_foFggl*(F6Fbp,*F]rFhcuF6"$%Q!$'>F'Fd^mFjvF'FAFBFb[
p**F6FbpFFF',(F]rFj]pF6!$2$FadsF'F'FAFBF\]sF_goFb^oFd`sFfsFc[qFeaoFb\oF_^oFcasF
a`lFf`sF]fpFg`sFcfpF[asFd`lFfgrF]\rF(F(F(F(F(,hsF^fpFcfp**FiiqF'F@F'FAFBF6F8Fd`
lFg\sF\]sF^frFa`lFefpF[gmF[gpF^\rF]]sFi_oF_gpF]\rF^asFatF_asFa`lFharFf\rFh[oFa
\rFafrFb[pFcgpF]\rFdgpFegp*&FdgmF'F^ilF'F'Fc]sF_btFa\pFatFd]sFb^oFbjuF_^mFe]sFc
fpFi]sFi_oF]hpFcfpF]^sFcfpFd]qF]fpFa^sF]fpFbhpFchpFe\rFEFghpFcfpFhhpFcfpFb^sFb[
pF\ipF_boF]ipF_boFg^sFcfpFdipF]fpFi^sF]fpFhfrFEFcbrF]\rFdbrF]\rFeipF]fpF[_sFi_o
F`_sFcfpFc_sFi_oFjfrF\]sFgipFeaoF`^qF_boFe_sFi_oF]jpF]fpFh_sFa`lFdjuFf\rFi_sFcf
pFbasFd`lFi^qF\gpFejuFb[pF^`sFcfpF``sFd`lFijuFb[pFa`sFb^oF\[vF\]sF[\oF`[vF^^rFd
[mF_foFgglFb[vFb[pFf[vF\]sF_goFb^oFc[qFeaoFb\oF_^oFf`sF]fpFg`sFcfpFfgrF]\rF(F(7
$7%F'FMF9X,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(,htF^fpFb[pF[btFb[pFajuFd`lFg\sF__r
F^frFd`lFefpF_^mF[gp#F^flF`^oF]]sFbaoF_gpF]fpF^asFfsF_asFd`lFa]sFEFharFddqFh[oF
egpFafrFcfpFcgpFegpFdgpFa\rF]btFb[pFc]sFi]rFc]qFb^oF`btFf\rFbjuF[gmFe]sFcfpFi]s
FbaoF]hpFb[pFabtFddqF]^sFb[pFd]qF]\rFa^sF]\r**FAFGFFF9F6FbpFdtF'FddqFbhpFd\rFe
\rFHFghpFb[pFhhpFb[pFb^sFcfpF]ipFb^oFg^sFb[p*&Fg[mF'FggmF'F'*&F6F8FiinF'Fa`lFdi
pF]fpFi^sF]\rFcbtFa`lFcbrF]fpFdbrF]fpFeipF]\rFj^sFb^oFdbtFb[pF[_sFbaoF`_sFcfpFc
_sFbaoFgipFd_oF`^qFb^oF`asFa`lFebtFb[pFe_sFbaoF]jpF]\rFdjuFddqFi_sFcfpFfeqFa_oF
i^qF^\rFejuFcfpF^`sFcfpF`jpFatFijuFcfpFa`sF_boF[\o#"$T$F]^oF^^rFgglF_foFd[mFjbt
Fb[pFb[vFcfpFf[vF__rFc[qF]iqFc`oF_^oF_^rF_boFcasFa`lFf`sF]fpFg`sFb[pFfgrF]fpF(F
(,htF^fpFb[pF[btFb[pFj[vFa`lFg\sF__rFefpF_^mF[gpFa\vF]]sFbaoF_gpF]fpFa]sFEFharF
ddqFh[oFegpFafrFcfpFcgpFegpFdgpFa\rF]btFb[pFc]sFi]rFc]qFb^oF`btFf\rFbjuF[gmFe]s
FcfpFi]sFbaoF]hpFb[pFabtFddqF]^sFb[pFd]qF]\rFa^sF]\r*&FdgmF'Fc]mF'F'Fb\vFddqFbh
pFd\r*&FfinF'F6F8Fd`lFe\rFHFghpFb[pFhhpFb[pFb^sFcfpF]ipFb^oFg^sFb[pFdipF]fpFi^s
F]\rFcbrF]fpFdbrF]fpFeipF]\rFj^sFb^oFdbtFb[pF[_sFbaoF`_sFcfpFc_sFbaoFgipFd_oF`^
qFb^oFebtFb[pFe_sFbaoFhbtFd`lF]jpF]\rFh_sFd`lFdjuFddqFi_sFcfpFfeqFa_oFi^qF^\rFe
juFcfpF^`sFcfpF`jpFatF``sFd`lFijuFcfpFa`sF_boFbgrFa`lF[\oFe\vF^^rFgglF_foFd[mFj
btFb[pFb[vFcfpFf[vF__rFd`sFatFc[qF]iqFc`oF_^oF_^rF_boFf`sF]fpFg`sFb[pF[asFa`lFf
grF]fpF(F(F(F(F(F(7$7%F'F9FMX,F*6"F,[gl!"%!!!#1"%"%F(,\yFfgoF]_o*&,&FjflFcqF_hm
F8F'F6F7FieoF]hr#F\^oFb_oF^hrFaboF_is#F[rFd]pF`htF]erFahtF]hoFh`qF`_rFh`pFijtFf
hrFd`qFhis#F[rF^gp*,,*Fd^mFjvF]rF]fuF6"$=%!$G#F'F'FIFHFFFEF6FbpFAFEFd`qF\jsFbao
FcaqF^boFeht#FBFfjoFfhtF^bpF[itFa`lFdaqFielFfaq#Fi`nFb_oFihrF]ho*&,&F^^mF8F_clF
cqF'F6F7F`\o*&Fg[rF'F6F8FEF]itFieoFgjsF_jmF_itF^bpFditFd`l*,FIFHFFFH,*F]rFijpF6
"$d%FafpF'Fd^mF[ilF'FAF7F6FbpFb[pFhjsFbaoFeiqFahu*&,PFb_mF^]mFghmFb\mFedmF`cmF]
_mFielFidmF`cmFjflFielF_hmF`cmF^emFielF^_mFj]mF`^mFj]mFf^mFj]mFg]mFj]mF]^mFj]mF
jhmF\bmFc_mFj]mF^^mFb\mF_clF_^mF\hmF^]mFijlF\bmFhilF`cmFdjlF`cmFe^mF`cmFailF`cm
F'F6F7FBF_apF]ioFjjsF\bmFeitF^bpFgaqFcfpFdapF`boFeap#Fg[sFb_oF[jtF^]mFa[tFd`lFb
[tFb[pFe[tF\bmFehoFd`qF`jtF]]o*&FggmF'F\]mF'F'Fj[tFa`lF[\tFat*,F6FbpFIFH,,F]rFj
cnF6!$/$"$W"F'Fd^mFf`mFh\qFcqF'FFFEFAF7F[jrFjaqFat**FFF9F6F[bsFAFBF]pFEF`cmFdio
F`boFfioFdhuFh]o#!$(=F]^oFb\tFEFhfqF`r*,,*Fd^mF[dlF]r!##)F6"$["!#))F'F'FIFHFFFE
F6FbpFAFEF\bmFh\tF^bpF_jrF]hoF_bpF\aqFj\tFd`qF_]tFjhlF][uF\cpF`]tF^]mF_[uF\bmF`
[uFatFa[uFb_rF]cpFd`qFbeuF]_oFacpFajq*&,&F_clFidtF\hmFMF'F6F7F`\oFj]tF\bmF[^tF
\bmFb[uF\cpF\^tFjhlFe[uF__rFijrFd`qF]^tFjhl*,,*Fd^mFjvF]r!$O#F6Fe^s!$9#F'F'FIFH
FFFEF6FbpFAFEFd`qFc^tFb\mFd^tF\]s*&FdgmF'F_blF'F'Fdcp#Fj^mFb_oF[\uF__rFjioFd`q*
,FfinF'FAFEFFFHF6F8FIFHF`r*(Fb`rF'FAFBF6FGFEF[dp#!$@%F]^oFg^tF]hoFa\uF_jmFb\uF^
]mFe[sFd`qFh\uF\bm*,,*Fd^mFMF]rF`\lF6F^_nF`\lF'F'FIFHFFFEF6FbpFAFEFUF]_t#FBFa]o
*,Fb^rF'FAFEFFFHF6F8FIFHF7Fi\uF^bpF[`tFjhlF^joFatF_joF`]o*,,*Fd^mF[ilF]rF\`pF6"
$'HFj_pF'F'FIFHFFFEF6FbpFAFEF^]mF^`tFjhlF_`tFaaqFi[sFabo*,,*Fd^mFjvF]rFd_vF6"$/
%Fj_uF'F'FIFHFFFEFAFEF6FbpFgjoF[]uF]_o*,,*Fd^mF[dlF]r!#')F6"$i"!$+"F'F'FIFHFFFE
F6FbpFAFEF\bmFb]oFg_vFg`tFb]vF[epFgitF\epF`cmF_]uFb[pF^atFjhlFaatFb[pF^\sF]hoF(
F(,\yFfgoF]_oF_]vFieoF]hrFa]vF^hrFaboF_isFb]vF_ctFfs*&Fa]mF'FdgmF'F'F`htF]erFah
tF]hoFh`qF`_rFh`pFijt*&FablF'FggmF'F'FfhrFd`qFhisFc]vFd]vFd`qF\jsFbaoFcaqF^boFe
htFh]vFfhtF^bpFdaqFielFfaqFi]vFihrF]hoFj]vF`\oF\^vFEF]itFieoFgjsF_jmF_itF^bpFf]
uFa`lF]^vFb[pFhjsFbaoFeiqFahu*&F6F7,PFb_mFb\mFghmF^]mFedmF\bmF]_mF_jmFidmF\bmFj
flF_jmF_hmF\bmF^emF_jmF^_mFjhlF`^mFjhlFf^mFjhlFg]mFjhlF]^mFjhlFjhmF`cmFc_mFjhlF
^^mF^]mF_clF[gmF\hmFb\mFijlF`cmFhilF\bmFdjlF\bmFe^mF\bmFailF\bmF'F'F_apF]ioFjjs
F\bmFeitF^bpFgaqFcfpFdapF`boFeapFb^vF[jtF^]mFg]uFd`lFb[tFb[pFe[tF\bmFehoFd`qF`j
tF]]oFcctFa`lFd^vF[jrFjaqFatFh^vF`cmFdioF`boFfioFdhuFh]oFi^vFb\tFEF]bqF7F[_vF\b
mFh\tF^bpF_jrF]hoF_bpF\aqFj\tFd`qF_]tFjhlF][uF\cpF`]tF^]mF_[uF\bmFa[uFb_rF]cpFd
`qFbeuF]_oFacpFajqF`_vF`\oFj]tF\bmF[^tF\bmFb[uF\cpF\^tFjhlFe[uF__rFijrFd`qF]^tF
jhlFb_vFd`qFc^tFb\mFd^tF\]sFdcpFg_vF[\uF__rFjioFd`q*,FAFEFFFHF6F8FIFHFiinF'F7*,
FAFEFFFHF6F8FIFHFh]rF'F`rFi_vFEF[dpFj_vFg^tF]hoFa\uF_jmFb\uF^]mFe[sFd`qFh\uF\bm
F\`vFUF]_tF^`vFi\uF^bpF[`tFjhlF^joFatF_joF`]oF``vF^]mF^`tFjhlF_`tFaaqFi[sFaboFc
`vFgjoF[]uF]_oFf`vF\bmFb]oFg_vFg`tFb]vF]^uFfsF[epFgitF\epF`cmF[dtFd`lF_]uFb[pF^
atFjhlFaatFb[pF^\sF]hoF(F(,^uF]dtFa`lF^dtFfsFdfpF]\rF[]qF`^uFharFi]rFh[oFa\rFbg
pFegpFdgpFa\rFa^uF]fpFc]sFddqFa\pFatFfbsFb[pFddtFb[pFc^uFi_oF_arFEF\]qF_bqFe^uF
a`lF[csFbaoF`btFcipFfdtFb^oFbjuF_^mFgdtF\]sFd]qF]fpFhauF__rFc\rFd[mFjdtFb[pF]et
Fd`lFa^sF]\rFf^uFcfpFb\vFi]rFh^uFd`lFbhpFchpF\]pF]fpFccsFb[pFgcsFbaoFfhpF_boF^e
tF\]s**F@F'FAFBF6F8Fh]rF'Fd`lFbetFa`lFcdsFb[pFj^uF__rF\esF]\rF]esF]\rF]ipFeao*&
Fg[mF'FdgmF'F'FgetFEF^_uFcfpFfesFbaoFiesFb[pF_fsFbaoFheoF_boF`^qFd_oFhipF]iqFdf
sFb[pF`^pFa_o*(F6Fbp,*Fd^mF[dlF]rFcilF6F]wFhglF'F'FAFBF\]sFdjuFi]rFjetF\]sFh^qF
j`qFi^q#F_cmF]^o*(FAFBF6FGFiinF'Fa`lF^jp#"$^"F`^oFf_uF]fp*(F6Fbp,,Fh\qF[dlFd^mF
\^sF]rFe`mF6FG!$3"F'F'FAFGF\]sFg_uFi_oF`gsFb[pF[`uF]fp*(F6Fbp,*Fd^mF[dlF]rFa_mF
6F^_n"#;F'F'FAFBF\]sF[\oF_\pF_foFgglFf_pF[gmF]`uFcfpFa_q#F`yF]^oFigsFb[pFbftFb[
pF_`uF]fpF``uFcfpFgftF_boF`hsFbaoFd`uFcfpFfgrF]\rF(F(F(F(F(,^uF_dtFd`lFdfpF]\rF
[]qF`^uFharFi]rFh[oFa\rFbgpFegpFdgpFa\rFa^uF]fpFc]sFddqFa\pFatFfbsFb[pFddtFb[pF
f`uFa`lFc^uFi_oF_arFEF\]qF_bqFg`uFd`lF[csFbaoF`btFcipFfdtFb^oFbjuF_^mFgdtF\]sFd
]qF]fpFhauF__rFc\rFd[mFjdtFb[pF\etFd`lFa^sF]\rFf^uFcfpFb\vFi]rFbhpFchpF\]pF]fpF
ccsFb[pFgcsFbaoFfhpF_boF^etF\]s*&FggmF'Fc]mF'F'FaetFa`lFcetFatFcdsFb[pFj^uF__rF
\esF]\rF]esF]\rF]ipFeao**Fb^rF'F@F'FAFBF6F8Fa`lFgetFEF^_uFcfpFfesFbaoFiesFb[pF_
fsFbaoFheoF_boF`^qFd_oFhipF]iqFdfsFb[pF`^pFa_oFeavF\]sFdjuFi]rFjetF\]sFh^qFj`qF
i^qFgav*(FfinF'FAFBF6FGFd`lF^jpFiavFf_uF]fpF[bvF\]sFg_uFi_oF`gsFb[pF[`uF]fpF^bv
F\]sF[\oF_\pF_foFgglFf_pF[gmF]`uFcfpFa_qFabvFigsFb[pFbftFb[pF_`uF]fpF``uFcfpFgf
tF_boF`hsFbaoFd`uFcfpFfgrF]\rF(F(7$7%F'F'FcpX,F*6"F,[gl!"%!!!#1"%"%F(F(F(F(F(F(
,fsFdfpF]fpF[]qF_bqFh[oFegpFbgpF]\rFdgpFegpFa^uF]\rFc]sFcipFfbsFcfpFf`uFd`lFc^u
FbaoF_arFHF\]qF`^uFe^uFa`lF[csFi_oF`btFg]pFfdtF_boFbjuF[gmFd]qF]\rFhauF\]sFc\rF
gglFa^sF]fpFf^uFcfpFbfuFb[pFb\vFcipFbhpFd\rF\]pF]\rFccsFcfpFgcsFi_oFi^uFEFcavFa
`lFaetFd`lFbetFd`lFcetFfsFcdsFcfpFj^uF\]sF\esF]fpF]esF]fpF]ipFd_oF^_uFcfpFfesFi
_oFiesFcfpF_fsFi_oF_^pF_boFheoFb^oF`^qFeaoFhipFeaoFdfsFcfpFh^qF`_rFi^qFe_uF^jpF
gavFf_uF]fpF`jpFatFg_uFbaoF`gsFcfpF[`uF]fpF[\o#"#PFa]oF_foFd[mFf_pF_^mF]`uFcfpF
a_qFaarFigsFcfp*&FcemF'FdgmF'F'Fj`uFa`lF_`uF]\rF``uFb[pFgftFb^oF`hsFi_oFd`uFcfp
FfgrF]fpF(F(,fsF^dtFatF_dtFa`lFdfpF]fpF[]qF_bqFh[oFegpFbgpF]\rFdgpFegpFa^uF]\rF
c]sFcipFfbsFcfpFc^uFbaoF_arFHF\]qF`^uFg`uFd`lF[csFi_oF`btFg]pFfdtF_boFbjuF[gmFd
]qF]\rFhauF\]sFc\rFgglF]etFa`lFa^sF]fpFf^uFcfpFbfuFb[pFb\vFcip*&FggmF'FaemF'F'F
h^uFa`lFbhpFd\rF\]pF]\rFccsFcfpFgcsFi_oFi^uFEFcdsFcfpFj^uF\]sF\esF]fpF]esF]fpF]
ipFd_oFdbvFd`lF^_uFcfpFfesFi_oFiesFcfpF_fsFi_oF_^pF_boFheoFb^oF`^qFeaoFhipFeaoF
dfsFcfpFb_uFd`lFh^qF`_rFi^qFe_uF^jpFgavFf_uF]fpF`jpFatFg_uFbaoF`gsFcfpF[`uF]fpF
[\oF[cvF_foFd[mFf_pF_^mF]`uFcfpFa_qFaarFigsFcfpF_`uF]\rF``uFb[pFgftFb^oF`hsFi_o
Fd`uFcfpFfgrF]fpF(F(F(F(F(F(7$7%F'F(FbvX,F*6"F,[gl!"%!!!#1"%"%F(,fnF\duF[gmF`ht
F\boFahtFbaqF[aqFa_rFh`pFa_rFfhtFd`qFdaqF`boFfaqF]epF^duFg\lF_itFd`qFeapF[inFja
qFatFh]o#FfxFc\mF\euFd`qF]bqF`rF][uFb[pFifqFd`lFacpFa_r*,,(F]rFjvF6F`_tF^enF'F'
FIFHFFFHF6FbpFAFEF^]mFgeuF\bmFdcpFbaqF[\uFd`qF[dp#Fi`nFg]o*&,*F_clFf`lFiemFjhlF
_dlF_^mF\fmF`cmF'F6F7FB*&Fb`rF'F6F8FEFieuFEFb]oF]epFjfqFatFjeuFj]mF(F(,fnF\duF[
gmF`htF\boFahtFbaqF[aqFa_rFh`pFa_r*&F6F7,*F_clFg\lFiemFj]mF_dlF[gmF\fmF\bmF'F'F
fhtFd`qFdaqF`boFfaqF]epF^duFg\lF_itFd`qFeapF[inFjaqFatFh]oFecvF\euFd`qFhfqF7F][
uFb[pFacpFa_rFfcvF^]mFgeuF\bmFdcpFbaqF[\uFd`qFecqFfsF[dpFhcvF[dvFEFieuFEFb]oF]e
pF^dqFa`lFjeuFj]mF(F(,,F[guFb[pF^hqFa_oF[\oFg_oF`hqFeaoFggqFUF(F(F(F(F(,,F[guFb
[pF^hqFa_oF[\oFg_oF`hqFeaoFehqFLF(F(7$7%F(FjxF(X,F*6"F,[gl!"%!!!#1"%"%,2FjfrF^]
mF`^pF[foF[\o#"#\Fh\lFe`oF`goFc`oFb\m*(FicrF'FAFBF6FGFBFhbrF`rFebrF7F(F(,<F^drF
d`qFh]o#F8F`bvFeioF`]oFdioF\boFe]oFhhrF\_oF^boFi^oF_bo*(FcerF'FAFBF6FGFEFhdrF`r
FgdrFE**F@F'FAFBF6F8FfbrF'Fa`lFa^oF]joF^^oFgjoF(FderF(F(F(F(F(F(,<F^drFd`qFdioF
\boFe]oFhhrFh]oFjdvFeioF`]oFa^oF]joF^^oFgjoFgdrFE**FibrF'F@F'FAFBF6F8Fd`lF[evFE
FherF7F\_oF^boFi^oF_boF(F(,2F[\o#FfxFh\lFjeoFcaoFb\oFg_pF^\oFeaoF\crFb[pFhfrFB*
*FidrF'F@F'FAFBF6F8Fd`l**F@F'FAFBF6F8FierF'Fa`l7$7%F(FbvF'X,F*6"F,[gl!"%!!!#1"%
"%F(F(,>FdioF[^oFe]oFbdrF\_oF_^oFi^oFb^oFh]o#FMF`bvFeioF`boF^drF__r*(FbhrF'FAFB
F6FGFEFherF`rFgdrFHF\evFd`lF]iuF]_oF\joF]joFejrFgjoF(F(F(F(F(,>F]iuF]_oFdioF[^o
Fe]oFbdrFh]oFhevFeioF`boF\joF]joFejrFgjoFgdrFHF^evFa`lFievFEFhdrF7F\_oF_^oFi^oF
b^oF^drF__rF(F(,8F[\oF`frFjeoFa_oFc`oF_^o**FfjrF'F@F'FAFBF6F8Fb^o*(F6Fbp,*Fd^mF
j]pF]r!$"[F6"$K)!$g%F'F'FAFBF__rFhfrFHFaevFUFa]sFEF\crF__rFb\oF^boF^\oF_boF(F(,
8F\crF__rF[\oF`frFjeoFa_oFb\oF^boF^\oF_boFa]sFEFbevFLFhfrFHFc`oF_^oF\fvFb^oF]fv
F__rF(7$7%F(FcpF9X,F*6"F,[gl!"%!!!#1"%"%,bp*&,&FgclF8Fg\mFcqF'F6F7Fa^q*&,6F\\nF
[gmFh[mF_^mF_\nFf`lF]]mFb\mFj[mF[gmFf_nF[gmF_hlFf`lF^dmFd_nF_gnFielF`hlF`gmF'F6
F7FB*&F6F7,6F\\nF_^mFh[mF[gmF_\nFg\lF]]mF^]mFj[mF_^mFf_nF_^mF_hlFg\lF^dmF`gmF_g
nF_jmF`hlFd_nF'F'F[]qF[gmFbgpF]goFdgpFi[nFddtF^]m*(F^dsF'FAFBF6FGFB*&,&FgclFjxF
bgmFbpF'F6F7Fa^qF\]qF_^mFj]rF`go**F6FbpFAFBFFF',(F]rF[dlF6F_enFh^mF'F'F^]mFgdtF
^]mFe]sF\bmFjdtF^]mFacsF`rFbhpF_^mF^etF^]m*.FFF`rFIFHF]\nF'F]pFEF6F[bsFAFEFjhlF
_esFjhl*.FIFHF6FcapFAFEFFFHF]pFHF]jmF'F]dlFdipF[foF`esFjhlFaesF7F`_sF\bm*&F6Fbp
FbgvF'F^]mFhipFa^qFebrF7FhbrF`rF[gsFj]mFi_sF\bmFjetF^]mF^hqF[foFh^qF\wF^jpF]goF
^`sF^]m*&F``lF'Fc`lF'F'F[\o#FfzFgxFa_qF_^mFbftF^]mFb\oF^]mFf`sF[fo*&FicrF'F6F8F
BF(F(,br*&,&F_clFcqFa`mF8F'F6F7F`\oF]hrFbaq**F6FcapF]pFHFjgnF'FAFBF\bm*,F@F9FAF
i`qF6FbpFFFHFIFHFa_r*&,4FjhmF^]mFjflFielFi`mF`cmFe^mFb\mF\]nF\bmF`^mF\bmFb^nF\b
mFbglF\bmFdgnF`cmF'F6F7FBFh`qF`_rFh`pFj`qFhisF[jrFd]vFd`qFcaqF]_oFdaqF\boFeaqF`
]oFfaqF[gm*&FcerF'F6F8FE*&,&F_clFidtFhgnFMF'F6F7F`\o**F]]nF'F6F[bsFAFBF]pFEF`cm
FeiqF_jmF[[tF\]sFgaqF_bqFeap#FagnFd]oF[jtF\bmF_[tF`rFhirFh]vFjirFh]v*,F6FbpFIFH
FFFHFb[mF'FAFEF^`vF]`rF]joFeioF`]oFfioFddqFh]oFbaqF\bqF]_o*,F6FbpFIFHFAFEFFFHFb
gvF'F\]sFb\tFEFherF7Fh\tF^`vF_bpF_^oFj\tFgjo*,F6FbpFIFHFFFH,(F6FidtF`bvF'F]rFbv
F'FAFEF^`vF^bqFcfpFejrF]_oF\^tF`cmFb_vFd`qFbcpFe[rF^^tFc]vFdboFb^o*,FFFHFIFHFjg
nF'F6FbpFAFEF\]sFc^tF`cmFd^tFgjoF[dpF^bpF^evFd`lFh[sFgjo*&Fh`lF'Fc`lF'F'F]_tFh]
vFg_tF\]s*(Fi[tF'FAFBF6FGFE**F@F'FAFBF6F8FbesF'Fa`lF^`tF`cmFe]o#F\^oFhfpF[epF_h
oF]\sFgjoF(,XF[btFcfpF[gpFggrFcgpFggrF]btFcfpFc]sFf\rF`btFcipFe]sFbaoFabtFi]rFb
\vFf\rFi\vFa`lFd\vFd`lFdipFcaoFdbtFcfpF`_sFbaoFebtFcfpFdjuFcipFi_sFbaoFfeqFcaoF
^`sFbaoF``sFa`l*&FdgmF'FggmF'F'F\[vFcfpF[\oFdaoFjbtFcfpFc[qFg_pFcasFd`lFf`sFcao
F(F(F(F(,2F]fvFb[pF[\oF`evFjeoFcaoFc`oFd`oF\fvFd_oFa]sF'FbevFa`lFaevFd`lF(,brFj
gvF`\oF]hrFbaqF\hvF\bmF]hvFa_rFh`qF`_rFh`pFj`qFhisF[jrFd]vFd`qFcaqF]_oFdaqF\boF
eaqF`]oFfaqF[gmF`hvFEFahvF`\oFchvF`cmFeiqF_jmF[[tF\]sFgaqF_bqFeapFdhvF[jtF\bmFh
irFh]vFjirFh]vFehvF^`vF\evFa`lF]`rF]joFeioF`]oFfioFddqFh]oFbaqF\bqF]_oFfhvF\]sF
fctF7Fb\tFEFh\tF^`vF_bpF_^oFj\tFgjoFghvF^`vF^bqFcfpFejrF]_oF\^tF`cmFb_vFd`qFbcp
Fe[rF^^tFc]vFdboFb^oFhdrF`rFihvF\]sFc^tF`cmFd^tFgjoF[dpF^bp*&F6F7,4F\]nF`cmFjhm
Fb\mF`^mF`cmFb^nF`cmFe^mF^]mFjflF_jmFi`mF\bmFdgnF\bmFbglF`cmF'F'Fh[sFgjo*&F``lF
'F`alF'F'F]_tFh]vFg_tF\]s**FbcsF'F@F'FAFBF6F8Fd`lF[ivFEF^`tF`cmFe]oF]ivF[epF_ho
F]\sFgjoF(F(,RF[]qFd\rF\fvFd_oFdgpF\gqFc]sFf\rF`btFcipFb\vFf\rFbhpFchpF[dsFbaoF
_dsFb[pFidsFbaoFbevFa`l*(F@FMFAF8F6FbpFeaoFgetFBFjeoFcaoFdjuFcipFg^qFcaoFh^qF_h
qFaevFd`lF\gsFb[p*&Fh`lF'F`alF'F'F[\oF\gq**F`[tF'F@F'FAFBF6F8Fd`l**F@F'FAFBF6F8
FgctF'Fa`lFa_qFcip7$7%F(FMFMX,F*6"F,[gl!"%!!!#1"%"%F(F(,brF]hrFccpF\hvF`cmF]hvF
\aqFh`qFj`qFh`pF`_rFd]vF^bpFcaqFgjoFehtFjiqFdaqF[^oFeaqF`boFfaqF_^m*&,&F_clFbpF
a`mFMF'F6F7F`\oFchvF\bmFeiqFielF[[tF__r*&,&F_clFfisFhgnF8F'F6F7F`\oFgaqF`^uFeap
F^erF[jtF`cmFhirFjiqFjirFjiqFehvFgjqFd^vF`jqFeioF`boFfioFi]rFh]oFccpF\bqFgjoFfh
vF__r*(FAFBF6FGF_jtF'FEFfctF`rFb\tFHFh\tFgjqF_bpF^boFj\tF]_oFghvFgjqF^bqFb[pF\^
tF\bmFb_vF^bpFbcpF]epF^^tFb^tFdboF_boFhdrF7FihvF__rFc^tF\bmF[dpFd`qF^evFa`lFbiv
FB*&FbhrF'F6F8FEFh[sF]_oFddpF]joFg_tF__rF\ivFd`l*&F`alF'Fc`lF'F'F^`tF\bmFc`vF]_
oFe]o#FfilFhfpF^^oF]_oF[epFdiqF]\sF]_oF(F(F(F(F(,brF]hrFccpF\hvF`cmF]hvF\aqF^hv
F'Fh`qFj`qFh`pF`_rFd]vF^bpFcaqFgjoFehtFjiqFdaqF[^oFeaqF`boFfaqF_^mF`jvF`\oFchvF
\bmFeiqFielF[[tF__rFbjvF`\oFgaqF`^uFeapF^erF[jtF`cmF_[tF7FhirFjiqFjirFjiqFehvFg
jqFd^vF`jqF\evFd`lFeioF`boFfioFi]rFh]oFccpF\bqFgjoFfhvF__rFdjvFEFb\tFHFherF`rFh
\tFgjqF_bpF^boFj\tF]_oFghvFgjqF^bqFb[pF\^tF\bmFb_vF^bpFbcpF]epF^^tFb^tFdboF_boF
ihvF__rFc^tF\bmF[dpFd`qFejvFEFh[sF]_o*&F``lF'Fh`lF'F'FddpF]joFg_tF__rFeivFa`lF^
`tF\bmFc`vF]_oFe]oFgjvF^^oF]_oF[epFdiqF]\sF]_oF(F(,V*(F6Fbp,*Fd^mF[ilF]rFjjoF6"
$3#Fj`vF'F'FAFBFcfpF[]qFchpF\fvFb^oFdgpF^arFc]sFcipF`btFf\rF^\oF_boFb\vFcipFbhp
Fd\rFi^uFEF[dsFi_oF_dsFcfpFidsFcfp*(F6Fbp,,F]r"$Q'F6!$G("$)GF'Fh\qF[ilFd^mFhcuF
'FAFGF__rFbevFLFgivFd_oFgetFHFjeoFa_oFdjuFf\rFg^qFa_oFh^q#FMFd]oF\gsF__r*$Fh`lF
9F'F[\oF^arFiivFUFa_qFf\rF(F(,VF[[wFcfpF[]qFchpF\fvFb^oFdgpF^arFc]sFcipF`btFf\r
F^\oF_boFb\vFcipFbhpFd\rFi^uFEF[dsFi_oF_dsFcfpFidsFcfpF^[wF__rFgivFd_oFgetFHFje
oFa_oFdjuFf\rFg^qFa_oFh^qFc[wFaevFUF\gsF__rF[\oF^arFjivFLFa_qFf\r*$F`alF9F'F(7$
7%F(F9FcpX,F*6"F,[gl!"%!!!#1"%"%,bpFjasFgdl*(F6FbpF]enF'FAFBF^]mF_bsFdzF[btF^]m
*&F6F7,FFainF_^mFd\mF[gmFh[mFf`lF^cnFg\lFb`nF\bmFb_nF\wFc_nF\wF^dmF`gmF]inF_jmF
_\mF_jmF\inF_jmF\\nF[gmF_hlF[gmF_`nFg\lFj[mF[gmF`hlFd_nFjglF[gmFgclFg\lF'F'F[]q
F[gmF[gpF]goFcgpF]goFdgpFi[nF]btF^]m*(FAFBF6FGFaauF'FB*.FAF7FFFHF6FcapFIFHF]pFH
FdtF'FielFabtF[gmFacsF`rFf^uF\bmFbhpFielFcgvFj]mF_esFj]mF`esFj]mFaesF7F^_uF\bm*
&,FFainF[gmFd\mF_^mFh[mFg\lF^cnFf`lFb`nF`cmFb_nFfwFc_nFfwF^dmFd_nF]inFielF_\mFi
elF\inFielF\\nF_^mF_hlF_^mF_`nFf`lFj[mF_^mF`hlF`gmFjglF_^mFgclFf`lF'F6F7FB*&F^d
sF'F6F8FBFdbtF^]m*&F``lF'FablF'F'FebtF^]mFf_oF[foF[gsF_jmFacuF_jmFh^qF\wFf_uF[f
o*.FjhnF'FIFHFFF`rF]pFEFAFEF6F[bsF]dl*&F_blF'Fc`lF'F'F[`uF[foFecuF_jm*.F`cnF'FI
FHFFF`rF6F[bsFAFEF]pFEFjhlF[\oF[gmFjbtF^]mF]`uF\bmFa_qF_^mFc[qF^]mF[guF^]mFd`uF
^]mF(F(,jo*,F@F'FAFGF6FcapF]pFHFdtF'Fb\mF]hvFa_rF`htF\boFahtF[gm**F6F[bsF`_nF'F
AFBF]pFEF\bmFehtF\]sFeaqF`]oF^duF[gm*&Fi[tF'F6F8FEFeiqF_jmFeitFd`q**F]_nF'F6F[b
sFAFBF]pFEF\bmFeapFbaq*,F@F'FAFGF6FcapFFF'F]pFHF^]mF_duF\]s*,FddnF'FFF9F6F[bsFA
FBF]pFEF`cmFfioFddq**FAFGF6F]\mFFF'F]pFHF`cmF\bqF]_oF\euFgjoFfctF7Fh\tFgjo*&,4F
[jnF\bmFi`mF`cmF\_nF`cmF_hmF^]mFbglF\bmFeanF`cmF_clFielFhanF`cmFijlFb\mF'F6F7FB
F_bpF\aq*&Fh`lF'FablF'F'F^bqFcfp**FAFGF6F]\mF]pFHFdtF'F\bmFacpFa_rFe[uFgjoFbcpF
e[rF[dp#Fc[nFd]oFi\uFd`qFeivFd`lFieuFEF[]uF\]sFe]oFe[r**Fa^nF'F6F[bsFAFBF]pFEF
\bmF\epFbaqF_]uF_bqF(,XFbgpFggrFc]sFf\rFddtFcfpFg`uFa`lFe^uFd`lF`btFcipFjdtFcfp
Ff^uFbaoFbfuFcfpFb\vFf\rF^_uFbaoFhipFg_pF`^pFcaoFeavFcfpFdjuFcipFhavFd`lFebvFa`
lF^jpFggrFf_uFcaoF[bvFcfpF_ivF'F[`uFcaoF^bvFcfpF[\o#F\]lFajoF]`uFbaoFbftFcfpFd`
uFbaoF(F(F(F(,RF[[wFbaoF[]qFd\rFdgpF\gqFc]sFf\rF`btFcipF^\oFeaoFb\vFf\rFbhpFchp
Fi^uF'F[dsFbaoF_dsFb[pF^[wFb[pFbevFa`lFgivFeaoFjeoFcaoFdjuFcipFg^qFcaoFh^qF_hqF
aevFd`lFhivF'F[\oF\gqFiivFd`lFjivFa`lFa_qFcipF(,joFi\wFb\mF]hvFa_rF`htF\boFahtF
[gmFj\wF\bmFehtF\]sFeaqF`]oF^duF[gmF[]wFEFeiqF_jmFeitFd`qF\]wF\bmFeapFbaqF_[tF`
rF]]wF^]mF_duF\]sF^]wF`cmFfioFddqF_]wF`cmF\bqF]_oF\euFgjoFh\tFgjoF_bpF\aqF^bqFc
fpFc]wF\bmFacpFa_rFe[uFgjoFbcpFe[rF[dpFd]w*&F_blF'F`alF'F'*&F6F7,4F[jnF`cmFi`mF
\bmF\_nF\bmFeanF\bmFhanF\bmF_hmFb\mFbglF`cmFijlF^]mF_clF_jmF'F'Fi\uFd`qF\ivFa`l
FieuFEF[]uF\]sFe]oFe[rFe]wF\bmF\epFbaqF_]uF_bqF(F(,,FbauFb[pFg^qFcaoFgivFeaoFji
vFa`lFiivFd`l7$7%F(F'FbvX,F*6"F,[gl!"%!!!#1"%"%F(F(,joFi\wF^]mF]hvF\aqF`htF[^oF
ahtF_^mFj\wF`cmFehtF__rFeaqF`boF^duF_^mFeiqFiel*&F`alF'FablF'F'FeitF^bpF\]wF`cm
FeapFccpF_[tF7F]]wFb\mF_duF__rF^]wF\bmFfioFi]rF_]wF\bmF\bqFgjoF\euF]_oFh\tF]_oF
_bpFa_rF^bqFb[pFc]wF`cmFacpF\aqFe[uF]_oFbcpF]epF[dp#Fi`nFd]oF[^wFBFi\uF^bpFeivF
a`lFieuFHF[]uF__rFe]oF]epFe]wF`cmF\epFccpF_]uF`^u*&F_jtF'F6F8FEF(F(F(F(F(,joFi
\wF^]mF]hvF\aqF`htF[^oFahtF_^mFj\wF`cmFehtF__rFeaqF`boF^duF_^mFeiqFielFeitF^bpF
\]wF`cmFeapFccpF]]wFb\mF_duF__rF^]wF\bmFfioFi]rF_]wF\bmF\bqFgjoF\euF]_oFfctF`rF
h\tF]_oF`]wF'F_bpFa_r*&F_blF'Fh`lF'F'F^bqFb[pFc]wF`cmFacpF\aqFe[uF]_oFbcpF]epF[
dpFd^wFi\uF^bpF\ivFd`lFieuFHF[]uF__rFe]oF]epFe]wF`cmF\epFccpF_]uF`^uFe^wFEF(F(,
*FbauFcfpFg^qFa_oFgivFd_oFjivFLF(F(,*FbauFcfpFg^qFa_oFgivFd_oFiivFUF(7$7%F(F(Fj
xX,F*6"F,[gl!"%!!!#1"%"%,8FbfuF^]mFfeqF[foF[\oF\clFg\wFj]mFc_oF`goF[gsF\bmFecuF
j]m*&,,F_cnF_^mFgclF_^mFd\mFf`lF^fnFf`lF_fnFb\mF'F6F7FB*&FaauF'F6F8FBFebuF'*&F6
F7,,F_cnF[gmFgclF[gmFd\mFg\lF^fnFg\lF_fnF^]mF'F'F(F(F(F(FjfuF(F(F(F(F]^wF(F(F(F
(F(F,
