M7R0
I#G2X,%)anythingG6"6"[gl!"%!!!#1"%"%,fn"""F(**%"rG!"',(!#:F(*$F*""#""*F*!#5F(,&
F*F(!"$F(!""%#X3G""%#F("#7**%#X1GF/,&F*F/F3F(F(F2F4F*F3F(*(%#X2GF/F2F4F*!"#F4*&
F5F/F*F3F>*,F*F+,*F*"#6""'F(F.!#9*$F*""$FFF(F2F>F=F/F5F/#F(F/*,,*FE"%+=F.!%%y)F
*"&.4"!$;)F(F(F*!"*F2F4F:F6F=F/#F4"$?"*.,,*$F*F6"%]SFE!&\$HF."&?>(F*!&5'o"&f-#F
(F(F*FNF2F>F:F/F=F/F5F/#F("$!=*.,*FE"$+#F.!$j*F*"%y7!$/$F(F(F*#F-F/,&F*F(F>F(#F
4F/F2F4F:FFF=F/#F("#?*,,.*$F*""&"%D?FS!&L,#FE"&vp(F.!'7#R"F*"'d\6!&u8$F(F(F*FNF
2F3F:F/F5F6FY**F*FN,,F."%d9F*"#'*!$o%F(FE!%M6FS"$D#F(F2F>F5FC#F4"$g$*,,.Fbo"$v'
FS!%')eFE"&uu"F.!&G&=F*"$n&"%EkF(F(F*FNF2F3F=F/F5F6Fap**,(F.F0F*!#?!#7F(F(F*F+F
2F4F=F6F7*,,*FEFepF.!%sIF*"%XG"%E8F(F(F*FNF2F4F:F/F=F6#F("#g*,F*FN,,FSFepFE!%?V
F."%+wF*!%c5!%WPF(F(F2F>F=F6F5F/Fap**,(F."#CF*!#u"#XF(F(F*F+F2F4F:F6F7*,,,FSFJF
E!&WX"F."&xV%F*!&A6'"&7C$F(F(F*FNF2F>F:F6F5F/FO**,*FEF`pF.!$=*F*"$7%"%w6F(F(F*F
NF2F4F=FCFap*,,(F."#=F*!#]"#@F(F(F*F+F2F4F:F/F=F/#F4FF*.F*#FNF/,(F.F(F*F3F/F(F(
F2F4F\oF]oF:F(F5F/FF*.,*FE"#DF.!$<"F*"$S"F^qF(F(F*F[oF\oFGF2F>F:F(F5F6#F3F_o*,F
;F(F\oFGF*FcsF2F4F:FFF4*.F*F[o,,F."%?\F*!%Cn"%/NF(FE!%<;FSFgnF(F2F>F\oF]oF:FFF5
F/F^o*.,(F.FFF*!")F6F(F(F*FcsF2F4F\oF]oF:F(F=F/F(*0F*F[o,,F."$8)FE!$_$FS"#]F*!$
)oFisF(F(F2F>F\oF]oF:F(F=F/F5F/Fjs**,*FEFZF.!$P)F*"$f*F`sF(F(F*FNF2F4F:FC#F("#!
**.,*FE"#vF.!$I$F*"$#H"$O"F(F(F*F[oF2F4F\oF]oF:F(F=F6#F4F_o*,F*F+,*FE"#OF.!$?#F
*"$T%!$(HF(F(F2F>F:F/F5F/#F4FC*,,(F."#5F*!#GF0F(F(F*F[oF\oFGF2F4F:Fco#F4Fco,J*&
F5F(F*#F3F/F(**F*Fcs,&F*"#8!#=F(F(F2F4F5FF#F4F8**F*F[o,*FE"$z#F.!%#Q"F*"%K>!$7'
F(F(F2F>F5Fco#F(Fbp*,F*Fcs,&F*Fiv!#IF(F(F2F4F=F/F5F(F[w*,,*FE"$e&F.!%8LF*"%+g!%
9JF(F(F*F[oF2F>F=F/F5FFFbw*,,(F.F^wF*!%%4""%c5F(F(F*F[oF2F4F=F6F5F(Fbw*,F2F4F\o
FGF*F3F:F(F5F(F>*.F*F+,*F.!$$>F*"$)Q!$_#F(FE"#JF(F2F>F\oF]oF:F(F5FF#F(Fav*.,,FS
"%0;FE!&;I"F."&#GPF*!&4N%"&gl"F(F(F*FNF\oFGF2F3F:F(F5Fco#F4"$?%*0F\oFGF*F+,&F*F
fx!#jF(F(F2F4F:F(F=F/F5F(Fgx*0F\oFGF*FN,*FEFjxF.!%'o*F*"&L$=!&B1"F(F(F2F>F:F(F=
F/F5FF#F4"$5#*0,*FEFjxF.!%m&*F*"&'**=!&oD"F(F(F*FNF2F4F\oF]oF:F(F=F6F5F(F_y*,F2
F4F\oF(F*FcsF:F/F5F(#F0F6*,,*FE"%TAF.!&!*R"F*"&U&G!&3!>F(F(F*F[oF2F>F:F/F5FFFap
*.F*F[o,(F.FdzF*!%S!*"%'=*F(F(F2F4F:F/F=F/F5F(Fap*.,&F*F8!#DF(F(F\oFGF2F4F*F+F:
FFF5F(Fcv*.,,FS"%06FE!%j#*F."&)*)GF*!&F(R"&'G?F(F(F*FNF\oF]oF2F>F:FFF5FF#F("$0"
*0,*FE"%5AF.!&mO"F*"&*>G!&9%>F(F(F*FNF2F4F\oF]oF:FFF=F/F5F(#F(Fjy*.,&F*Fav!#BF(
F(F\oF(F*F[oF2F4F:F6F5F(#F(F6*.,(F.FbpF*!%t;"%C>F(F(F\oFGF2F4F*FNF:FcoF5F(#F4Fi
s,>*,F2F4F\oFGF*F3F=F(F5F(F/*.,(F."#9F*!#f"#RF(F(F\oFGF*F+F2F>F=F(F5FF#F4Fav*.,
,FS"$&\FE!%9UF."&'47F*!&RK""%!o%F(F(F\oFGF*FNF2F3F=F(F5Fco#F(F`y*.,&F*""(!#;F(F
(F\oFGF2F4F*F+F=FFF5F(Fcv*.F*FN,,FSFb]lFE!%HUF."&kG"F*!&aj""%krF(F(F\oF]oF2F>F=
FFF5FFF^\l*.F\oFG,(F.Fb]lF*!%kA"%'f#F(F(F2F4F*FNF=FcoF5F(Fg]l*.F*Fcs,&F*Fgs!#[F
(F(F2F4F:F(F=F(F5F(F^v*.,*FE"%)4"F.!%=rF*"&jQ"!%t!)F(F(F*F[oF2F>F:F(F=F(F5FFFY*
.F*F[o,(F.F[_lF*!%8\"%UaF(F(F2F4F:F(F=FFF5F(FY*0F\oFGF*F+,&F*"#r!$b"F(F(F2F4F:F
/F=F(F5F(Fgx*0F*FN,,FS"%&\$FE!&D4$F."&uy*F*!'J;8"&YK'F(F(F\oF]oF2F>F:F/F=F(F5FF
Fiy*0,(F.Fi_lF*!&Do""&k)>F(F(F\oFGF*FNF2F4F:F/F=FFF5F(Fiy*.,(F."%<>F*!%&y)"%n)*
F(F(F*F[oF2F4F:FFF=F(F5F(#F4FZ*0,*FE"%+iF.!&*3WF*"'sB5!&))z(F(F(F*FNF2F4F\oF]oF
:F6F=F(F5F(Fg]l,T*,F\oFGFc^lF(F2F4F*FNF=FCF_y*,F][lF(F\oFGF2F4F*F+F:F6#F(Fco**F
2F4F\oF(F*FcsF:FF#FNF6*.F\oFG,(F."%&f)F*!&1+%"&7g%F(F(F2F4F*FNF:F/F=F6Fg]l*.F*F
NF]^lF(F\oF]oF2F>F=F6F5F/Fiy*,FczF(F*F[oF2F>F:FFF5F/Fbw*.Fa]lF(F\oFGF*FNF2F3F=F
/F5F6F_y*.F\oFG,&F*"#^!$4"F(F(F2F4F*F+F:F/F=F/Fcv*.,*FE"%aFF.!&\v"F*"&EP$!&g#>F
(F(F*F[oF2F>F:F(F=F/F5F/Fap**F2F4F\oFGF*F3F=F/F>*.F`[lF(F*FNF\oF]oF2F>F:F6F5F/#
F4Fg[l**F2F4F\oFGF*F3F:F/F/*,,(F."$0%F*!%u<"%G>F(F(F*F[oF2F4F:FFF=F/#F(F^r*,Fi]
lF(F\oFGF2F4F*F+F=F6Faal*.,(F."&?1"F*!&"=]"&3%eF(F(F\oFGF2F4F*FNF:F6F=F/F_y*.,.
FboFjxFS!&Ei"FE"&9L'F.!'t!="F*"'yN5!&?J$F(F(F*FNF\oF]oF2F3F:F/F5F6Fg]l*,,(F."$l
"F*!$G("$'zF(F(F2F4F*F[oF:F(F=F6#F4F^r*,F`\lF(F\oF(F*F[oF2F4F:Fco#F4F6*0,,FS"%+
<FE!&2Y"F."&$>XF*!&S'f"&k"GF(F(F*FNF2F>F\oF]oF:F/F=F/F5F/#F("#q*,F*FcsFhvF(F2F4
F:F(F5F/F7*,F]wF(F*F[oF2F>F:F(F5F6Fap*,Fd\lF(F\oFGF2F4F*FNF:FC#F(Fis*,F2F4F\oF(
F*FcsF:F(F=F/#F`sF6*.F[]lF(F\oFGF*F+F2F>F=F/F5F/Fgx*.F*F+FbxF(F2F>F\oF]oF:F/F5F
/F_]lFdv,RF4F(*(F5F/F2F4F*F>#F(FF**,*FE"#FF.!#YF*!$*="$C$F(F(F*F+F2F>F5F6Fg`l**
,.Fbo"$]%FS!%;<FE!%neF."&n!QF*!&#*>'"&g=$F(F(F2F3F*FNF5FC#F("%S]*&F=F/F*F3Fhel*
,,(!#")F(F."#aF*!##*F(F*F+F2F4F=F/F5F/Fg`l*,,,F*"&:;"!&M,"F(F.!%i:FEFbflFSFaflF
(F2F>F*FNF=F/F5F6#F("%!o"*(,&F*F[flF\flF(F(F*F+F=F6Fg`l*,,*FEFaflF.FbflF*"$V*Fc
qF(F(F*FNF2F4F=F6F5F/Fdgl*(,(F.F`pF*!$e)"$C)F(F(F*FNF=FC#F("%?D*,F2F4F*#!"(F/F
\oFGF:F(F5F/F]o*.,,F.F1F*"$;"!$7"F(FSFcoFEF]qF(F*F[oF2F>F\oF]oF:F(F5F6Fgx**F*Fc
sF\oFGF:F(F=F/F]o*0,*FEF(F.!"%F*FFF/F(F(F*F[oF2F4F\oF]oF:F(F=F/F5F/F(**F*F[oF\o
#FFF/F:F(F=F6FG*,,(F."$3"F*!$^#"#[F(F(F*F+F2F4F:F/F5F/FY*,,,FS"%+aFE!&$=CF."%C8
F*"'k%4"!'co6F(F(F2F>F*FNF:F/F5F6#F4Fhfl**,&FailF(F*F`ilF(F*F+F:F/F=F/FY*.,*FEF
eilF.FfilF*"&(yC"%eZF(F(F2F4F*FNF:F/F=F/F5F/#F4F`hl**,(F*Ffil"&]m#F(F.FeilF(F*F
NF:F/F=F6Fjil*.,(F.FavF*!#HF8F(F(F*F[oF\oFGF2F4F:FFF5F/#F4"#:*,F*F[oF\oFG,&Fgjl
F(F*FavF(F:FFF=F/Fhjl*,,*FE"%+OF.!&^/#F*"&3]$!&go"F(F(F*FNF2F4F:F6F5F/Fgfl**,(F
*F_[m"&Ur#F(F.F^[mF(F*FNF:F6F=F/Fgfl,D*,F\oFGF2F4F*FcsF=F(F5F/FG*.,*F.FewFEFcoF
*"#d!#MF(F(F2F>F*F[oF\oF]oF=F(F5F6F_]l*.,(F.F(F*F[ilF6F(F(F*F[oF2F4F\oF]oF=FFF5
F/F]o*(F:F(F=F(F*F3Fas*.,(F.F[flF*!$;$"$*[F(F(F*F+F2F4F:F(F=F(F5F/FY*.,,FSFaflF
E!&;V"F."&4a(F*!'r"Q""&uE)F(F(F2F>F*FNF:F(F=F(F5F6Fjil**FgglF(F*F+F:F(F=FFFY*.,
*FE"$+*F.!&Kg"F*"&dO&!&-0&F(F(F*FNF2F4F:F(F=FFF5F/Fjil**F\hlF(F*FNF:F(F=FcoFajl
**F*FcsF\oFGF:F/F=F(FG*0,*FEFcoF.F_sF*"$P"!$9"F(F(F*F[oF2F4F\oF]oF:F/F=F(F5F/F_
]l**F*F[oF\oF]ilF:F/F=FFF]o**F\jlF(F*F+F:FFF=F(Fg`l*.,*FEFeilF.!&$Q\F*"'aF8!''*
)4"F(F(F2F4F*FNF:FFF=F(F5F/Fgfl**FcjlF(F*FNF:FFF=FFFgfl*,F*F[oF\oFGF[[mF(F:F6F=
F(#F(Fijl**Fc[mF(F*FNF:FcoF=F(Fjil,D*,F\oFGF2F4F*FcsF=F/F5F(F]o*.Fh[mF(F2F>F*F[
oF\oF]oF=F/F5FFFgx*.F\\mF(F*F[oF2F4F\oF]oF=F6F5F(FG**F:F(F5F(F2F4F*F>Fas*,FjelF
(F*F+F2F>F:F(F5FFFY*,F`flF(F2F3F*FNF:F(F5FcoFjil*.,(F.F[flF*"$C#!$q&F(F(F*F+F2F
4F:F(F=F/F5F(FY*.,,FSF[]mFE"%o"*F.!&&4!)F*"';I<!'wI6F(F(F*FNF2F>F:F(F=F/F5FFFji
l*.,*FEF`pF.Fb_lF*!&9a#"&Ss#F(F(F*FNF2F4F:F(F=F6F5F(Fajl*,F2F4F*FbhlF\oFGF:F/F5
F(FG*.FehlF(F2F>F*F[oF\oF]oF:F/F5FFF_]l*0,*FEFcoF.FavF*!$2""$M"F(F(F*F[oF2F4F\o
F]oF:F/F=F/F5F(F_]l*,F_ilF(F*F+F2F4F:FFF5F(Fg`l*,FdilF(F2F>F*FNF:FFF5FFFgfl*.,*
FEFeilF."%<5F*!&!=$)"'7%>"F(F(F*FNF2F4F:FFF=F/F5F(Fgfl*.FfjlF(F*F[oF\oFGF2F4F:F
6F5F(F^^m*,F][mF(F*FNF2F4F:FcoF5F(FjilFh\lFe[m,RF4F(**F5F/F;F(F2F4F*F3Fas**,*FE
F`ilF.!$`'F*F[s!$R'F(F(F2F>F*F+F5F6FY**,.Fbo"%]8FS!&JV"FE"&+u&F.!'Ty5F*"&m^*!&_
<$F(F(F2F3F*FNF5FCFajl*,,(F.F`ilF*!$$Q"$U$F(F(F*F+F2F4F=F/F5F/FY*,,,FSFeilFE!&C
Z%F."'GE8F*!'^o;"&mW(F(F(F2F>F*FNF=F/F5F6Fjil*,,*FEF\amF.!%J!)F*"&9h"!&'*3"F(F(
F*FNF2F4F=F6F5F/Fajl*.F*FcsF\oFG,&F*F6FchlF(F(F2F4F:F(F5F/FG*.,,FEFailF."$[(F*!
$Y*"$G%F(FS"#IF(F*F[oF2F>F\oF]oF:F(F5F6F_]l*0,*FEFhbmF.!$"=F*"$k$!$W#F(F(F2F4F*
F[oF\oF]oF:F(F=F/F5F/F_]l*&F:F/F*F3Fhel*,,("%5HF(F."$H(F*!%[HF(F*F+F2F4F:F/F5F/
Fg`l*,,,FE!'WJ8F."'CqTF*!'0Xb"'1VEF(FS"&]^"F(F2F>F*FNF:F/F5F6Fdgl**FgglF(F*F+F:
F/F=F/Fg`l*.,*FE"&]H#F.!'u,:F*"'"*QK!'-3BF(F(F*FNF2F4F:F/F=F/F5F/F_hl**F\hlF(F*
FNF:F/F=F6F_hl*(F*FcsF\oFGF:FFF]o*.,*!%W>F(F.!%C8FE"$0#F*"%+GF(F*F[oF2F4F\oF]oF
:FFF5F/#F(Fhbm**F*F[oF\oF]ilF:FFF=F/FG*(F\jlF(F*F+F:F6FY*,,*F.!&D4'F*"'`z8!''[,
"F(FE"%+()F(F*FNF2F4F:F6F5F/#F4"$S)**FcjlF(F*FNF:F6F=F/Fjil**F*F[oF\oFGF[[mF(F:
FcoFhjl*(Fc[mF(F*FNF:FCFgfl,>*,F=F(F5F(F;F(F2F4F*F3Fhel*,Fg`mF(F2F>F*F+F=F(F5FF
Fg`l*,F[amF(F2F3F*FNF=F(F5FcoF_hl*,FcamF(F*F+F2F4F=FFF5F(Fg`l*,FgamF(F2F>F*FNF=
FFF5FFFgfl*,F]bmF(F*FNF2F4F=FcoF5F(F_hl*0,(F.F/F*FchlFCF(F(F*FcsF2F4F\oF]oF:F(F
=F(F5F(F4*0,,"$%RF(F."$=(FE!$Y#FSFhbmF*!$*))F(F2F>F*F[oF\oF]oF:F(F=F(F5FFFgx*0,
*FEFijlF.!#))F*"$s"FghlF(F(F*F[oF2F4F\oF]oF:F(F=FFF5F(Faal*.,(F."$-(F*!%KE"%@CF
(F(F*F+F2F4F:F/F=F(F5F(FY*.,,FS"&+]%FE!';^QF."(jc<"F*!(W`_""'W-rF(F(F*FNF2F>F:F
/F=F(F5FFFjil*.,*FEFbgmF.!';VGF*"'DTf!'-6TF(F(F*FNF2F4F:F/F=FFF5F(Fjil*0,*FE"$!
>F.!%u6F*"%*Q#!%-;F(F(F*F[oF2F4F\oF]oF:FFF=F(F5F(#F4Fhbm*.,*FE"&+o%F.!'nhJF*"'k
\p!'?!*\F(F(F*FNF2F4F:F6F=F(F5F(FgflF^alF`^mFhem,RF4F(**F=F/F;F(F2F4F*F3Fas*,Fg
`mF(F2F>F*F+F=F/F5F/FY*,F[amF(F2F3F*FNF=F/F5F6Fajl**FcamF(F*F+F2F4F=F6FY*,FgamF
(F*FNF2F>F=F6F5F/Fjil**F]bmF(F*FNF2F4F=FCFajl*.,(F.F6F*!#8FavF(F(F*FcsF2F4F\oF]
oF:F(F=F/FG*0,,FbpF(F*!$K)F."$)oFE!$T#FSFhbmF(F*F[oF2F>F\oF]oF:F(F=F/F5F/F_]l*.
,*FEFavF.!#dF*F`il!#oF(F(F*F[oF2F4F\oF]oF:F(F=F6#F3Fav*(F:F/F2F4F*F>Fhel*,FjelF
(F*F+F2F>F:F/F5F/Fg`l*,F`flF(F2F3F*FNF:F/F5F6Fgfl*,,(F.FbcmF*!%3C"%^=F(F(F*F+F2
F4F:F/F=F/Fg`l*.,,FS"&v9"FE!&()R*F."'#*QFF*!'#3Q$"'#H\"F(F(F2F>F*FNF:F/F=F/F5F/
#F("%g7*,,*FEFjcmF.!&W6*F*"'*4"=!'u)="F(F(F*FNF2F4F:F/F=F6Fdgl**F2F4F*FbhlF\oFG
F:FFF]o*.FehlF(F2F>F*F[oF\oF]oF:FFF5F/Fgx*.,*FEFhdmF.!%W6F*"%o?!%+7F(F(F*F[oF\o
F]oF2F4F:FFF=F/Fjdm**F_ilF(F*F+F2F4F:F6FY*,FdilF(F2F>F*FNF:F6F5F/Fjil*,,*FEFbem
F.!&DD&F*"'k>5!&oK'F(F(F*FNF2F4F:F6F=F/Fcem*,FfjlF(F*F[oF\oFGF2F4F:FcoFhjl**F][
mF(F*FNF2F4F:FCFgflF&
