M7R0
I#G1=6"6$;"""""%F&E\[l16$F'""#,J*&%#X3GF'%"rG#!"$F+F'*.%#X1GF'F.F',&F/F'F1F'#!"
"F+,&F/F'!"#F'#F'F+F/F1*$F4F6F9F8*0F3F+F.F'F:F9F/!"%F7F9*&F7F'F/F6F9F4F5#""*F(*
(%#X2GF+F.F',(*,F4F5F7#""$F+F/!"&F:F9F=F5F5*$F/#!"*F+#F6FE*,F:F9F/F<F7F9F=F9F4F
5#F6F(F'F'*&F.FE,&FK#F1F(*&F4F6F/#!"(F+FJF'F'*(F3FEF.F',(*,F7F9F/!"'F:F9,&F/F(F
IF'F'F4F5#F1""&*,,&F/F+F1F'F'F4F0F/FVF7F9F:F9#F8FY**F4F0F7F9F/FFF:F9#F+FYF'F'**
F3F'FAF+F.F',,*,F:F9F7F9,&F/F'F6F'F'F/FVF4F5#F6FY**F4F5F7FDF/FVF:F9F+**F:F9F7F9
F/FVF4F5#F(FY*&F=F9F/#!#6F+F9FU#F'FYF'F'*(F3F'F.FE,.*,,(F/!#;"#7F'*$F/F+FYF'F:F
9F/FVF7F5F4F5FdoF_oFhnF^oF`o*(F4F6F/FHF=F9F9FUFdoFgnFhnF'F'*(F3F(F.F',(*.F=F9F7
F9F/FRF:F9,&F/"#5!#FF'F'F4F5#F'F(*.FenF'F4F0F/FRF:F9F7F9F=F9F'*,F4F0F7F9F/FVF:F
9F=F9F6F'F'**F3F+FAF+F.F',TF_p#F6FjoFdp#F8"#:*.F/FRF=F9F:F9F7F9,&F/"#N!#tF'F'F4
F5#F6"#S*.FenF'F4F0F/!")F7FDF:F9F=F5#F1F`q*.F4F5F7F9F/FRF=F9F:F9,&F/FYFcoF'F'#F
FFjo*.F=F9F:F9F/FRF7F9,&F/FY!#7F'F'F4F5Ffq*.F4F0F7F9F/FbqF:F9,(F[pF'F/F1F+F'F'F
=F5F_q*.F:F9F7F9,(F/!#<"#9F'F[pFYF'F=F5F/FbqF4F5#F'"#C*.F/FbqF7FDF:F9,&FIF'F/FY
F'F=F5F4F5F`r*.F7FDF:F9,&FVF'F/FYF'F=F5F/FbqF4F5F`r*.F=F9F7F9F:F9FerF'F4F5F/FRF
`r*.F/FRF=F9F:F9,(F[pF]qF/!$V""$Y"F'F'F4F5F7F5#F6"#g*.F4F0F7F9F/FRF:F9F=F9F\oF'
#F'F`q*,F4F0F/FRF7FDF:F9F=F5#F'""'*,F4F5F7F9F/F1F:F9,&**F/FFF[rF'F4F6F=F5F'*(F4
F6F/F1F=F9F9F'F5*,F:F9F=F5F/FbqF7FDF4F5Fhp*,F/FRF:F9F7F9F=F9F4F5#!#VFar*,F4F0F7
FDF/FRF:F9F=F9F_q*,F4F0F7#FYF+F/FbqF:F9F=F5#FIF`q*,F4F5F7F9F/F1F:F9,&**F4F6F7F'
F/F<F=F9FL**F/F<F=F9F\oF'F4F6FcpF'FD*(,&FCF+FKFDF'F4F6F/F8F`s*$F/#!#:F+#F'"$?"*
&FWF'F/FetFcq*&,&*&FWF'F/FVFcq*$F/FVFgtF'F/F0F'*&,(FKF8FGF`sFCF6F'F/F1F`sF'F'*(
F3F+F.FE,D*.F=F9F:F9,*!$;#F'F[p!$m"*$F/FE"#DF/"$S$F'F7F5F/FRF4F0#F6FarFdq#F6Fas
*,F4F5F7F9F/F1F:F9,*F`tF9**F4F5F7F9F/FHF:F9F9**F4F6F7F+F/FFF=F5F9*&F=F9F/F<F9F'
F5Fep#!#RF`qFgqFju*.,(F[pFguF/!#%)"#oF'F'F7F9F:F9F/FbqF4F5F=F5FiuFdp#FFFar*(,&F
KF9FPF`sF'F4F6F/F8F`s*&,&*(F4F8F7F'F/FVFI*&F4F8F/F<F'F'F/F0Fgt*.,(F[pFguF/!#$)"
#mF'F'F7F9F:F9F/FbqF4F5F=F5FiuF_pFhp*&,(*(F/FFF4F6FWF'FcqF[wFcqF\wFgtF'F/F0F'F[
t#F6"")FgsFOFjsFdw*(F/#!#8F+F4F6FWF'FcqF_s#F'F\sF'F'*(FAF(F.F',H*.F7FDF:F9,&Fbq
F'F/FYF'F=F5F/FbqF4F5FiuFfsF^s*&F7F'F/Fet#FEF`qFdtFgtFbrFiu*.F/FbqF7FDF:F9FeqF'
F4F5F=F5F_qF_sF_xF[t#F?F`q*.F/FbqF:F9F=F5F4F5F7F9,(F[pFjpF/!#h"#iF'F'#F'"#?FjqF
]t*&,&FCF5FGFjuF'F/F1FjuFep#F+FjpF^tF0*&,&*&F7F'F/FVF_xF]uFgtF'F/F0F'FjsF^sF]sF
_qFdqF[sFgsFiw*.F:F9F/FRF4F5F7F9F=F9,&F/Fjp!#JF'F'#F'"#IF'F'*(FAF+F.FE,VFdqF`rF
jqF]tFbrF`rFdr#""(F\sF]sF_qF\xF`r*.,&F/Fjp!#>F'F'F:F9F7FDF/FbqF4F5F=F5F[s*.,&FR
F'F/FYF'F:F9F7FDF=F5F4F5F/FbqFay*.FhoF'F7F9F:F9F/FbqF4F5F=F5Ffx*.F:F9,*F[pFbpF/
"#[!#GF'FfuFYF'F=F5F/FbqF4F5F7F5Ffx*.,(F[pFjpF/!#\"#QF'F'F7F9F:F9F/FbqF4F5F=F5F
_qFepFaxF_sF^sFfs#FRF`qFgs#FfyF`qFjsF^sF[tFax*,,&F`tFcpFatFLF'F4F5F7F9F/F1F:F9F
D*(,(FYF'F[pF'F/F<F'F/FetF4F6#F1Fgx*(F4F6F7F+F/FetF[[l*(F/Fet,(F[pFEF/FbqF(F'F'
F4F6F_x*(FixF'F4F6F/F8Fju*(,("#6F'F[pFEF/FiqF'F/FetF4F6F_x*&F/FgwF4F6Fiw*&,&FKF
5FPFjuF'F/F1Fju*&F/F0,,*(Fa[lF'F/FVF4F6F_x*&F/FFF4F6Fiw*(FjzF'F/FVF4F6F[[l*(F4F
6F7F+F/FVF[[l*(F/FVF^[lF'F4F6F_xF'F'F'F'*&F.FY,0FgyF`rFepF`rFgs#FYFar*(,(F[pF'F
/F'F<F'F'F/FetF4F6F_x*&F4F8F/FboFgt*(F4F6F/F8Fe[lF'Fju*&,&*(Fa\lF'F/FVF4F6F_xF
\wFgtF'F/F0F'F'F'*(F3FYF.F',>*,F7F9F/FIF:F9,(F[pF\sF/!$>$"$0%F'F'F4F5#F1"#q*,F4
F0F7F9F/FIF:F9,(F[pFewF/!#I"#FF'F'#F^r"$g&*,F4F0F7F9F/FbqF:F9FWF'#"#J"$!G*,F7FD
F/FIFenF'F4F0F:F9#!#")"$S"**F:F9F7FDF/FbqF4F0#"#")F\^l*.FenF'F4F0F/FIF7F9F:F9FW
F'#FI"$7"**,&FgnF1FZFEF'FenF'F4F6F/F1#F6"$?(*,,&F[wF?F\wF6F'F4F5F7F9F/F1F:F9#F'
"$S#*,,(*(F/FVF`]lF'F4F6#F'Few*(FenF+F4F8F/FVF`rF[w#F1FewF'F4F5F7F9F/F1F:F9F5*(
,(FU#FEFewFZF^_lFgnFdwF'F4F6F/F8F`s**,(FZF_qFgnF^sFUF]tF'FenF'F4F6F/F1F9*,,(F[w
F_xF\w#F6FhtFcwF_xF'F4F5F7F9F/F1F:F9FD*,,&F[wFIF__lF'F'F4F5F7F9F/F1F:F9#F6"%!o"
*(Fd^lF'F4F6F/F8#F'"%S]F'F'**F3FEFAF+F.F',dr*(F=F9F`pF'F/#F^rF+Fay*(,&F^o#!#BFe
wFU#FRFewF'F4F6F/F8F`s*(Fe_lF'F4F6F/F8F5**FenF'F4F6F/F1,*F[oFcqF^o#FEF(F_oFfxFU
F_xF'F9F`^l#FEFb^l*.F4F0F7F9F/FIF:F9F\oF'FWF'#"#<Fh]l*.F:F9F/F<F7F9F=F9F4F5FcsF
'F\al*.FenF'F4F0F/FIF:F9F7F9F\oF'#F1Fb^l*.F:F9F/F<F7F9F=F9F4F5F_tF'F0F]^l#!$@"F
j^l**FctF'F4F6F/F1F=F9FL**F/FbqF4F0F7F9F:F9#F6Fj^l**F/FIF4F5F7FDF:F9#"%x=F\`l**
F7F9F:F9F4F5F/FI#F6"$0"**F4F0F7F\tF/FIF:F9#"$R$Fd]lFi\l#F'F^]lFe]l#F^r"$?%Fi]l#
"$H"Fh]lFf_lF0Fg^lFial*,,&F[wF?*(FenF'F4F8F/FFF6F'F4F5F7F9F/F1F:F9#F6"$S)*,F/FI
F7FDF:F9,&F/F_bl!$W#F'F'F4F5Fgt*,F7F9F/FIF:F9,(F[pFbyF/!$\""$!=F'F'F4F5#F'F_r*,
F7F9F/FIF:F9,(F[pFbyF/!$U""$l"F'F'F4F5Fdcl*,F7F9F/FIF:F9,(F[pF^]lF/!$A$"$l$F'F'
F4F5#F'"#!)*,F/FIF7FDF:F9,&F/FbyF^qF'F'F4F5#FfyFj^l*,F4F0F7F9F/FIF:F9F^[lF'Fa^l
*,F4F0F7F9F/FIF:F9,(F[pF(F/FhwFapF'F'#F`alFd]l*,F:F9F/FIF7F9F4F0F[rF'Fdo*,F/FIF
7FDF:F9,&F/Fby!#xF'F'F4F5Fdcl*,,.*(F/FVFddlF'F4F6FdwFjblFhpF[wF\al*(F/FVF[rF'F4
F6F6**F/FVF\oF'FWF'F4F6FLFcwFdwF'F4F5F7F9F/F1F:F9F5*,F4F0F7F9F/FIF:F9,(F[pF(F/F
hwF?F'F'Fa^l*,F/FIF:F9F7F9,(F[pFapF/!#T"#UF'F'F4F5#F1F\^l*,F4F0F7FDF/FIF:F9FWF'
#F?Fb^l*,F7F9F:F9,(F/!$<""$5"F'F[pFbyF'F/FIF4F5#F6F\^l*,F:F9F7F9F/FIF4F0FenF'Fi
^l*,F/FIF:F9F7FD,&FiyF'F/FapF'F4F5Feel*,F:F9,*F[p!#eF/"$6"!#qF'FfuFapF'F/FIF4F5
F7F5Feel*,F7F9F:F9,(F/!$2""#!*F'F[pFbyF'F/FIF4F5#F6F^]l*,F/FIF:F9F7F9,(F/!$G""$
N"F'F[pFbyF'F4F5F\fl*,FWF'F/FIF4F5F7F9F:F9#"$T"Fd]l*,,&F[wFIFjblF'F'F4F5F7F9F/F
1F:F9Fi^l*,,&F]uFh_lF\uF_xF'F4F5F7F9F/F1F:F9FD*,F[uF'F4F5F7F9F/F1F:F9F0*,F7F9F:
F9,(F/!#bF_zF'F[pFjpF'F/FIF4F5Fifl*,F7F9F:F9,(F/!#N"#HF'F[pFapF'F/FIF4F5Feel*,F
4F0F7F9F/FIF:F9FjzF'Fgel*,F/FIF:F9F7F9F\oF'F4F5#F`alF\`l*,F:F9F/FIF7FDF4F0F\oF'
Fcq*,F/FIF7F9F:F9,(F[pFbyF/!$L"FjrF'F'F4F5#F'F_z*,F7F5F/FIF:F9,*FfuF^]lF[p!$i%F
/"%45!$I(F'F'F4F5#F'Fb^lF]`l#F'Ff^l*(F_uF'F=F9F/F<FL*&,&*(F=F9F`pF'F/FRFay*&F/F
RF=F9F_qF'F/F0F'*&F/Fc`lF=F9F_q*&,&FZF1FgnFEF'F/F1#F6F_`l*&,(FUF`_lFZFdwFgnF^_l
F'F/F1Fju*&,,F[oF^_lF^o#"#8FewF_oFLFaoFLFUF\alF'F/F1F`s*,F/FIF7F9F:F9,(F[pF_blF
/!$a%"$)[F'F'F4F5#F'"$o"*,F4F5F7F9F/F1F:F9,6Fj[lF_xF[\lFc_lF\\lFcqFi[lFh_lF[wFc
qFjblFgt**F7F'F/FVF4F6FWF'F_x**F/FVF7F'F\oF'F4F6#F1Fap*(F/FVFenF'F4F6Fh_l*(F/FV
F`elF'F4F6FcqF'FDF'F'*(F3FEF.FE,hp*(,.FgoFdwF_oFdwF^oF5F\pFLFUFdwFgnFdwF'F4F6F/
F8F`s**F4#FFF+F7FDF/FIF:F9#FEFd]l**F4F][mF7F9F/FRF:F9#F6"$5#**F4F6F/FetF`pF'F=F
9Fay**FhvF'F4F6F/F1F=F9FL**FenF'F4F6F/F1,,FgoF_xFgnF^sF^o#FEFapF_oF^sFUF_xF'F9*
(FcilF'F4F6F/F8Fdil*(F4F6F/F8FfilF'FjuF`^lF]al*.F:F9F/F<F7F9F=F9F4F5F\vF'F\al*.
FhoF'F:F9F/FIF7F5F4F0FenF'F]alF]^l#"#zF`jlFhalF[`lFjal#"#dFh]lF`bl#FjilFgxFi\lF
cblFe]l#"$p"F\`lFi]lFf[m*,FjvF'F4F5F7F9F/F1F:F9Fial*,F4F5F7F9F/F1F:F9FbwF'F0F`c
l#F'F]qFeclFd\mFgdlFd\mFfelF_alF]flF^[mF^glFf]l*,F7F9F:F9,*F[p!%05F/"%W@!%_9F'F
fu"$]"F'F4F0F/FIFi^l*,,0*(,(F[pF(F/FcoFfyF'F'F/FVF4F6FdwFfjlFhpF[\lF6*,F:F9F/Fb
oF7F9F=F9F4F5FOFcjlFLF[wF`_lF\uFdwF'F4F5F7F9F/F1F:F9F5*,F7F9F:F9,*F[p!$)**F/"%4
@!%59F'FfuFj\mF'F4F0F/FI#F'F\^l*,F4F][mF7F9F/FbqF:F9FenF'Fi^l*,F4F0F7F9F/FIF:F9
Fa\lF'Fa^l*,F4F0F7F9F/FIF:F9F^]mF'Fedl*,F4F0F/FbqFhoF'F:F9F7F5Fial*,FerF'F7F9F:
F9F/FbqF4F0#F6F`jl*,,&Ff\lFcqF\wFh_lF'F4F5F7F9F/F1F:F9FD*,F7F9F:F9,*F[p!%J5F/"%
8A!%&["F'FfuFj\mF'F4F0F/FIFe]m*,F7F9F:F9,*F[p!%Q5F/"%\A!%I:F'FfuFj\mF'F4F0F/FIF
i^l*,F7F9F/FIF:F9,*F[p!%(3"F/"%'R#!%?;F'FfuFj\mF'F4F0Fi^l*,,*FfuFj\mF[p!$O)F/"%
B:!$-*F'F'F:F9F7F5F/FIF4F5Fe]m*&,(**F4F6F/FVF`pF'F=F9Fay**F4F8F7F'F/FRF=F9Fax*(
F4F8F/FFF=F9F_qF'F/F0F'*&,&Fe_mFb]lFf_mF1F'F/F0Fgt*&Fd^lF'F/F1F[il*&Fe_lF'F/F1F
5*,F7F5F/FIF:F9,,F[p"%qXF/!%7k"%SKF'Ffu!%(Q"*$F/F(Fj\mF'F4F0#F'"$O$*,F:F9,,F[p"
%aTF/!%Sd"%/HF'Ffu!%08Fa`mFj\mF'F4F0F/FIF7F5Fb`m*,F:F9,,F[p"%DVF/!%Gg"%gIF'Ffu!
%Q8Fa`mFj\mF'F4F0F/FIF7F5Fb`mF'F'**F3F'FAF(F.F',\s*(,(F^o#FfyFewFZFdwFgnF^_lF'F
4F6F/F8F`s*(F/Fc`lF=F9FeqF'#F6Fby*(F[alF'F4F6F/F8F5*(FixF'F=F9F/F<FcpFg[mF^`lFa
alFL*.F:F9F7F9F_yF'F\oF'F/FIF4F5Fe]mF]^l#!#*)Fc`mFhalFialFjal#!$t'F\`lF]blF^blF
`bl#!$"\Fd]lFe]lFcalFb\mF[`lFeclFe]mFbdlFfxFfdl#"#=F]qFgdlFe]mF_elFgelFaelFjhlF
felFa^lF]flFi^lFjflFb`mF^gl#F^rF\`lFaglFialF]hlFa^lF^hlF_hlF`hl#"#TFh]l*(F=F9Fh
qF'F/Fc`lF[sFailF_qFi_mF^`l*&,(*(F/FRF=F9FeqF'Ffam*(F=F9FhqF'F/FRF[sF`ilF_qF'F/
F0F'*&,,F[oFdwF^o#FYF(F_oFcpFaoFcpFUF^_lF'F/F1Fju*&,(F^oFh`lFZF^_lFgnFdwF'F/F1F
`s*&FctF'F_tF'F'FajlF0*,F/FIF:F9F7FDF4F5,&F/Fhfl!$<#F'F'F[^m*,F:F9F/FIF4F5F7FD,
&F/"#X!$."F'F'#F6"#%)*,F/FIF:F9F7FDF4F5,&F/Fecm!#)*F'F'Fgcm*,F4F5F7F9F/F1F:F9,(
F\\lF^_lF[wF`_lF\wF`rF'F5*,F/FIF:F9F7F9F4F5,(F[pFhflF/!$7%"$l%F'F'Fifl*,F:F9F7F
9F\oF'F/FbqF4F0F]al*,F/FIF:F9F7FDFeqF'F4F5#FEF^]l*,F\yF'F4F5F7F9F/F1F:F9F0*,F7F
9F:F9,(F/FfalFhtF'F[pFbyF'F/FIF4F5Fb`m*,F7F9F:F9,(F/!#g"#fF'F[pFjpF'F/FIF4F5F_j
l*,,&F]yFcqF]uFh_lF'F4F5F7F9F/F1F:F9FD*,F/FIF:F9F4F5F7F9,(F[pFhflF/!$(R"$M%F'F'
Fh_l*,F/FIF:F9F4F5F7F9,(F[pFecmF/!$$>"$1#F'F'F[s*,F/FIF:F9F7FDF[zF'F4F5#FEF\^l*
,F/FIF7FDF:F9F]xF'F4F5Fgem*,F/FIF:F9F7FD,&!#HF'F/FjpF'F4F5Fcbl*,F7F9F:F9,(F/!$:
""$4"F'F[pFbyF'F/FIF4F5Fb`m*,F/FIF:F9F7FD,&!#fF'F/FbyF'F4F5Fe]m*,F/FIF4F5F7FDF:
F9,&F/Fjp!#MF'F'Fe]m*,F7FDF:F9FcrF'F/FIF4F5Fddm*,F/FIF7FDF:F9,&F/Fjp!#QF'F'F4F5
Fcbl*,F:F9,*F[p!#!*F/"$z"!$="F'FfuFjpF'F/FIF4F5F7F5Fgt*,F/FIF:F9,*F[p!$)=F/"$"R
!$q#F'FfuFbyF'F4F5F7F5Fi^l*,F/FIF:F9F7F9,(F[pFhclF/!$)o"$;(F'F'F4F5F\fl*,F/FIF:
F9F4F5F7F9,(F[pFecmF/Fagm"$'>F'F'F[s*,F/FIF7FDF:F9,&F/Fap!#@F'F'F4F5F]dl*,F:F9,
*F[p!$v"F/Fbbl!$=#F'FfuFbyF'F/FIF4F5F7F5Fi^l*,F:F9,*F[p!$"=F/"$i$!$S#F'FfuFbyF'
F/FIF4F5F7F5Fi^lF'F'**F3F'FAF+F.FE,\y*(F[cmF'F4F6F/F8Fju*(F=F9F/FetF4F6#F6Fgx*(
Fe[mF'F4F6F/F8F5**F[rF'F/#FiyF+F4F6F=F5F[s**F=F9F/Fc`l,(F[pFjpF/!#YFarF'F'F4F6F
[s**,*F/"#k!#[F'FfuFYF[pFa]lF'F/F^imF4F6F=F5FayF\[mF^[mFaalFLFi[mFL*(,0FgoF^_lF
_oF^_l**F4F6F7F'F/FboF=F9FLF[oF^_l**F/FboF=F9F\oF'F4F6FcpF^oF^_lFZFdwF'F4F6F/F8
F`s*(Fe[lF'F=F9F/F<FcpF]^l#!$(=Fd]lFhal#F8F_blFjal#FbfmF\clF]blF^blF`bl#!$@%Fd]
lFe]l#F`yF\clFhblFi^lFeclF\flFbdlFa^lFfdlF`bmFgdlF\flF_elFgelFaelFeelFfelFa^lF]
fl#F'Fa[mFjflF\flF^glFajmF]hl#"$,"Fd]lF^hlFiwFf]mF[`lFg]mFfxFi]m#FiyF\clFj]mF_j
lF\^mF0F`hlFcbm*&,&**F4F8F7F+F/FbqF=F5!#=**F4F8F/FRF[rF'F=F5FEF'F/F0#F'Fccl*&,.
FgoF^_lF_oF^_lF^oF9F\pFcpFUF^_lFgnF^_lF'F/F1Fju*&,0FgoFdwF_oFdwFhimFcpF[oFdwFii
mFLF^oFdwFZF^_lF'F/F1F`s*&,&FhjmF?**F4F8F7F+F/FRF=F5F1F'F/F0F[[n*&,&**F4F8F/FVF
7F'F=F9F1Fe_mF?F'F/F0#F'"$g$*&F[alF'F/F1F5*&,&Fe_mFijm**F4F8F/FVF=F9F\oF'FEF'F/
F0Ff[n*&F_uF'FhzF'F'*&FhvF'F_tF'F'*&F/F0,P**F/FRF4F6F7F'F=F9Fgt**F/FRF=F9F\oF'F
4F6Fh_l**,*F/FcclFfuFjpF[p!#"*!$;"F'F'F/FbqF4F6F=F5F[s*(F=F9F/FVF4F6F[im**,*F/"
$)=!$C"F'FfuFjpF[p!#$*F'F/FbqF4F6F=F5F[sFhjmF[imFb[nF[s**F=F9,("#AF'F[pFYF/!#AF
'F/FRF4F6F[im**FcimF'F/FbqF4F6F=F5Fay**F/Fbq,*F/"#h!#UF'FfuFYF[pFa]lF'F4F6F=F5F
ay**,*F/Fev!#_F'FfuFYF[pF`yF'F/FbqF4F6F=F5Fay**F=F9,(FbyF'F[pFYF/F_]nF'F/FRF4F6
Fay*,F4F6F7F'F/FRF=F9FeqF'Fay**F7F+F/FbqF4F6F=F5Fiw*,F=F9F4F6F7F'F/FRFhqF'FayFe
[nFh_lFe_mF_qF[\nFgtFjjmFiw**F/FRF=F9,(F[pFjpF/FcelFgxF'F'F4F6F[s**F/FRF=F9,(F[
pFjpF/FisF^]nF'F'F4F6F[s**F[rF'F/FbqF4F6F=F5F[s**F=F9F/FRF`imF'F4F6F[sF'F'Fbdm#
F`alF\clFcdmF]]lFfdmF\flFhdmFiflFiemFiflF\fmF\flF`fmF\flFffmF]]lFgfmFifl*,,&F/F
EF<F'F'F:F9F7FDF/FIF4F5#FFFdel*,F/FIF7F9F:F9,*!#sF'F[pFbflFfuF?F/"$;"F'F4F0#FFF
c`m*,,(F[pFjpF/!#c"#]F'F'F:F9F7F9F/FIF4F5Fgcm*,,&F/FjpF_]nF'F'F:F9F7FDF/FIF4F5F
gcm*,,(F[pFbyF/!$0""#')F'F'F:F9F7F9F/FIF4F5F[^m*,F4F5F7F9F/F1F:F9,0Ff\lF^_lFi[l
#F'FjoF_]mFcpFj[lFcpF[\lFcpF[wF`_lF]yF^_lF'F5*,FhyF'F7FDF:F9F4F5F/FIFe]m*,,*Ffu
FecmF[p!$N#F/"$'R!$7#F'F'F:F9F7F5F/FIF4F5F\fl*,F:F9,,Ffu!$p#F[p"$v)F/!%H7"$I'F'
Fa`mFbyF'F4F0F/FIF7F5Fh_l*,,(F[pFecmF/!$Y"Fb^lF'F'F:F9F7F9F4F5F/FI#F6Fc`m*,,*Ff
uFbyF[p!$s"F/"$@$!$%>F'F'F:F9F7F5F/FIF4F5Fifl*,FbzF'F:F9F7F9F4F5F/FI#F6Fb^l*,F4
F6F7F'F/Fc`lF=F9FeqF'Fay*,F/FIF7F9F:F9,*F[p!$-#F/"$@%FcgmF'FfuFbyF'F4F0#F6F]q*,
,(F[pFEF/!#5FewF'F'F:F9F7F9F4F5F/FIFf^n*,F=F9F4F6F7F'F/Fc`lFhqF'Fay*,F/FIF7FDF:
F9,(F/!$P""$E"F'F[pFbyF'F4F0F[^m*,Fa[lF'F/FIF4F0F7F9F:F9#FI"#c*,F/FIFhoF'F:F9F7
F5F4F5Fifl*,,*FfuFjpF[p!#zF/"$O"!#wF'F'F:F9F7F5F4F5F/FI#F6F^dl*,,*FfuFhflF[p!$#
\F/"$"))!$9&F'F'F:F9F7F5F/FIF4F5Fe]m*,F7F9F:F9,*F[p!$%fF/"%P7!$5)F'FfuFhflF'F4F
0F/FIFe]m*,,(F[pFjpF/Fd]nF\hlF'F'F:F9F7F9F/FIF4F5Fe]m*,F4F5F7F9F/FIF:F9,&F/FfyF
ftF'F'Fddm*,,&F/Fecm!#iF'F'F:F9F7FDF/FIF4F5Fcbl*,F4F5F7F9F/FIF:F9FeqF'Fd\m*,F7F
9F:F9,&F/Fjo!#DF'F'F/FIF4F5Fcbl*,,(F[pFjpF/F`zFjilF'F'F:F9F7F9F/FIF4F5Fb`m*,F7F
9F:F9,*F[p!$8'F/"%*H"!$b)F'FfuFhflF'F4F0F/FIFb`m*,F/FIF:F9,,F[p"$%zF/!%_5"$/&F'
Ffu!$d#Fa`mFbyF'F4F0F7F5Fh_l*,,(F[pFjpF/!#OF^]nF'F'F:F9F7F9F/FIF4F5Fe]m*,F:F9,*
FfuFjpF[pFbflF/"#p!#EF'F'F4F5F/FIF7F5Fi^l*,FerF'F7F9F:F9F/FIF4F5F[^m*,F:F9,,F[p
"%DDF/!%`M"%5<F'Ffu!$$zFa`mFhflF'F4F0F/FIF7F5Fi^l*,,*FfuFecmF[p!$U#F/"$=%!$G#F'
F'F:F9F7F5F/FIF4F5F\fl*,F:F9F7F9,*F[p!$4#F/"$d%!$:$F'FfuFbyF'F4F0F/FIF[^m*,F/FI
F:F9,,F[p"$K#F/!$/$"$W"F'FfuFfbnFa`mF?F'F7F5F4F0#F6F_z*,,*FfuFjpF[p!##)F/"$["!#
))F'F'F:F9F7F5F/FIF4F5F[s*,,*FfuFecmF[p!$O#F/"$*R!$9#F'F'F:F9F7F5F/FIF4F5F\fl*,
,*FfuFEF[pFioF/"#GFioF'F'F:F9F7F5F/FIF4F5FJ*,,*FfuFbyF[p!$l"F/"$'HF[anF'F'F:F9F
7F5F/FIF4F5Fh_l*,,*FfuFecmF[pF_gnF/"$/%!$C#F'F'F:F9F7F5F4F5F/FIFial*,,*FfuFjpF[
p!#')F/"$i"!$+"F'F'F:F9F7F5F/FIF4F5F[s*,F4F5F7F9F/F1F:F9Fg[lF'F0*,F4F5F7F9F/F1F
:F9,6Fh[lFcqFi[lFh_lFj[lF_xF[\lF]tFjblFh_lF[wF_xFcjlFcqFdjlFf[mFfjlFgtFgjlF_xF'
FD**F/Fc`lF=F9F^^nF'F4F6F[s**F/Fc`lF=F9F`^nF'F4F6F[s**F/F^imFb]nF'F4F6F=F5Fay**
Ff]nF'F/F^imF4F6F=F5Fay**F/Fc`lF4F6F7F'F=F9Fgt**F=F9Fi]nF'F/Fc`lF4F6Fay**FixF'F
4F6F/F1F=F9Fcp**F/Fc`lF=F9F\oF'F4F6Fh_l**Fh\nF'F/F^imF4F6F=F5F[s**F=F9F]]nF'F/F
c`lF4F6F[im**Fc\nF'F/F^imF4F6F=F5F[s**F7F+F/F^imF4F6F=F5FiwF'F'*(F3F'F.FY,fn*(F
4F8F/FgwF=F9F_q*(F4F6F/F8F][nF'FjuF_[mF`[m**F4F6F/F1F=F9Fe[lF'FcpFi[mFLF]^l#Fhw
FhtFhalF`[mFjalFezF]blF`[mF`bl#FiyF\^lFe]lFbbmF^glFcalFg]mFa^lFi]mFbbm*,F4F5F7F
9F/F1F:F9Fe\lF'F0*&Fe[mF'F/F1F5*&F/F0,*Fe_mFcq*,,(F[pFYF/F(!#?F'F'F7F'F/FbqF4F6
F=F5FfamFf_mF_q**F=F9,*F/Fifm"#sF'FfuFYF[pFiqF'F4F8F/FRF[sF'F'F^bnFc]lFabnFcalF
hbnF\flF]cnF\flFfcnF[^mF_dnF\fl*,F:F9,,Fa`mF_blFfu!$)yF[p"%*3#F/!%GB"$C*F'F'F4F
0F/FIF7F5F\fl*,F4F5F7F9F/F1F:F9,(Fh[lF^_lF]uF`rF_]mFcpF'F5*,F]jnF'F7F'F/F^imF4F
6F=F5Ffam*,,(F[pFecmF/!$_""$C"F'F'F:F9F7F9F/FIF4F5Fh_l**F4F8F7F'F/Fc`lF=F9Fcq**
F=F9F`jnF'F4F8F/Fc`lF[sF'F'6$F(F',T*.F3FEF:F9F/F<F7F9F=F9F4F5#FIF(*,F3F+F4F5F7F
9F/F1F:F9F+*,FAF+F4F5F7F9F/F1F:F9F8*(F3F'FAF+,&FCFEFKF>F'F'*(F3F'F.F+,(FKF9FP#F
'FEFCFcpF'F'**F3F'FAF+F.F+,`pFdp#"#`FhtFaq#F'FapFdq#F6FjpFgqFiuFjqFaxF\rFdwFbrF
hpFdr#FRFarFfrFiuFbuF_qFbvF_q*.,&F/Fgu!#LF'F'F:F9F7FDF/FbqF4F5F=F5F[sF]wF_q*.F=
F9F7F9F:F9,(F/Fe\n"$3"F'F[pFguF'F4F0F/FRF[s*.,&F/FguFefmF'F'F:F9F7FDF/FbqF4F5F=
F5F[sF]sF]tF\xFiuF`xF[s*.F\oF'F:F9F7FDF/FbqF4F5F=F5#FFFas**F/FetF7F'F\oF'F4F6Fe
jl**FenF'F4F6F/F1,(FKF+FGFjuFCF'F'F`s**FenF'F4F6F/F1Fe[lF'Fju**F7F'F/FetF4F6FWF
'F_xFep#FcoFhtF_s#FiyFht*,,(FdsFLF`tFL**F=F9FenF'F4F6F/F<FLF'F4F5F7F9F/F1F:F9F0
FfsFJFgsF`_lFjs#FfyFgxF[vF5F[t#F6Fap*,,&F^vFcpFdsFLF'F4F5F7F9F/F1F:F9FDFizF_xF
\[lFc_lF][lFcq*(F/FetFenF'F4F6Fh_l*(F/FetF`elF'F4F6Fcq*(F4F6F/F8,&FCF9FGF`sF'Fj
u*&,&FCF'FKF\alF'F/F1F5*&,6Fj[lFcqF[\lF`_lFfjlFgtFcjlFcqFi[lFgtF\\lF_xF[wF_xFjb
lFh_lF]elFf[mFgjlF_xF'F/F0F6*&FbglF'F/F0FgtFc[lFh_lF'F'*(F3F+FAF+,&F^o#Fg`lFYFU
#FRFYF'F'*&F3F(,(FU#FEFYFZFhnFgnFfnF'F'*(F3F+F.F+,0FgoFdwF_oFfnF^o#F<FYF\pF5FUF
]oFgnFfn*,FerF'F7F9F:F9F/FVF4F5FcqF'F'*&FAF(,(F^o#FfyFYFZFfnFgnFhnF'F'*(FAF+F.F
+,4F^_oF_xFZFfnF[oFdoF^oFdoF_oFhn*&Fj]oF'F/F0F6FgoF^_lFhimFLFiimFcpF'F'*&F3FY,(
F_pFLFdpF6FepF'F'F'*(F3FEFAF+,8F[qF`rFaqF[\oFdq#"#BFarFgqFi_oF_p#FfyFjoF_sFjuFj
qFLFbsF9*(F4F6F/F8,&FCF8FKF0F'F`s**FenF'F4F6F/F1F`^oF'F9*,,&FdsF9Ff]oFcpF'F4F5F
7F9F/F1F:F9F0F'F'*(F3FEF.F+,LFbuF^sFdqF`sF[vF9Fep#"#RF`qFgqF`sFbvF^sFaqFjxFdpF_
xFc\lF`sFc\oFiwF]wF^sFf\oFiwF_pFh_nFawF6Fi\oFiwF[tF^_lFgsF\alFjsF^_l*&Fh^lF'F/F
0FgtFfwF_xF_sF[sF'F'*(F3F'FAF(,<*.F/FbqF:F9F=F5F7FDF4F5F_yF'FjuFaqF`sFjqFcpF[qF
iuF_sFJFepF`_lFdpFc_lFdqFb\oFgqFb\o*(F`^oF'F4F6F/F8F5F_`oFDFbsF5**FenF'F4F6F/F1
F]`oF'FjuF'F'*(F3F'F.F(,4*.FcbnF'F:F9F7F5F/FbqF4F5F=F5F[sFfsFipFepFiuFd\lF6FgvF
juFgyF_qFgsFcqF`\lFcqFb\lFh_lF'F'*(F3F(FAF+,`oFg[mF[ilF`^l#FcoF^]lF^al#F^rFh]l*
.F``oF'F:F9F/F<F7F9F=F9F4F5FDFaalFOF]^l#"$@"Fj^lFc^lF^`l**FenF'F4F6F/F1FfilF'Fj
u**,&F^o#!#pF`qFU#F]hmF`qF'FenF'F4F6F/F1F9**F4F6F/F1F=F9F]`oF'FLFi\lFh]oFe]l#F`
alFeblFi]l#!#rF^dlF_]lFfxFi_lF[`lFf_lFDF[_lF5Fb\mFialFhbl#F'F_blF]clFiflF`cl#Fg
`lF\^lFeclF`bo*,F=F9FenF'F4F6F/F<F`^oF'F5*,,.F\\lFcqFjblFiwF[wF[[lF]elFXFgjlF[[
lF]_lFcqF'F4F5F7F9F/F1F:F9F0FiclFeelF_dlF[imFbdlFgelFcdlFc]lFfdlFhnFgdlF`boFjdl
F9F_el#F?F`bn*(,(FUFaxFZF^sFgnF_qF'F4F6F/F8F5*(F4F6F/F8,&F^o#Fj_oFewFUFdamF'F`s
F'F'*&F3Fas,>Fi\lFddmF`^lFgelFe]l#F`yFh]lFi]lF^^lF]^lFj]lF_]lFedlFi_l#F'F\`lF]`
lFdil**FfboF'FenF'F4F6F/F1F9Ff_lF0F[_lF9Fh[mF`s**FcilF'FenF'F4F6F/F1Fe^lFb\mFi^
lF'F'*(F3F(F.F+,dpFdinF`sF\[m#F1Fd]lF_[mFbjmFb[mFfamFeinFL**,,F^_oFcqFgnF_qF^oF
ejlFUFcqF_oF_qF'FenF'F4F6F/F1F9Fg[mF^`lF`^lFcalFi[mFOFj[mF_q*.FenF'F4F0F/FIFerF
'F7F9F:F9#F6Fd]lF]^l#FdbnF`jlFhalF]coFjal#!#dFh]lF`bl#FhwFgxFi\lFiflFe]l#!$p"F
\`lFi]lFejlFc\mFDFg^lFialF`clFeanFeclFeanFgdlFeanFfelFaaoF]flFbcoF^glF\coFe\mF
\flF[]mF9F`]mF\flFf]mFialFg]mFgelFh]mFc]lFi]mFi^lFj]mF_jlF\^mF0F^^mF\flFc^mF\fl
Fh^mF\flF]_mF\flFa_lFjuFbilF[ilFb_mF6*&FfboF'F/F1F5*&,&Fe_mFbpFf_mFEF'F/F0FgtF'
F'**F3F+FAF+F.F+,dy*(F4F6F/F8F_[nF'F`sFjhmF^s*(F4F6F/F8,,F[oF^_lF^o#FFF(F_oFLFa
oFLFUFdwF'Fju*(FdcoF'F4F6F/F8F5**F/Fc`lF=F9,(F[pFYF/FioFb[lF'F'F4F6#F'Fjp**F=F9
F/Fc`l,(F[pFapF/!#PFb]lF'F'F4F6Fay**FenF'F4F6F/F1,,F[oFdwF^o#FhwFewF_oFcpFaoFcp
FUFOF'F`sF]imFiwF_imFiw**FenF'F4F6F/F1,,F^_oF_xFZF_qF[oF_xF^oF_xF_oF^sF'F9**F4F
6F/F1F=F9F^^oF'Fcp**F=F9F/Fc`l,(F[pFYF/F^rFjoF'F'F4F6Fido**F=F9F/Fc`lFenF'F4F6F
^sFbimF[s**FenF'F4F6F/F1F][nF'FjuF`^l#F^rFj^lFbalFiwFj[mFdhlFecoFialF]^l#"$(=Fd
]lFhalFcblFjal#"$d"F\^lF`blF_bn*.Fj]oF'F:F9F/F<F7F9F=F9F4F5F0*.FcsF'F4F5F7FDF/F
FF:F9F=F5FcpFe]l#Fg]lF\clFi]l#!$@&F\clF_]lFa^lF`clFe]mFeclFcblFbdlFgelFfdl#!$$=
Fh]lFgdl#"#>F\`l*,,6Fj[lF_xF[wF_xFjblFh_lF[\lFc_lF]elFf[mFgjlF_xFi[lFh_lFcjlF_x
F]_lF_xFfjlFh_lF'F4F5F7F9F/F1F:F9F0FaelFddmFfelFh]oFhelFe]mF]flFcblF^flFgemF`fl
FgemFeflFcblFjflFcblF^gl#Fc]nFh]lFfglFcblFiglFgemF]hlFh]oFe\mFe]mF[]mF5F`]mFe]m
Fg]mF[imFh]mF[imFi]mFdhlFj]mFialF\^mFDF^^mFe]mFc^mFe]mFh^mFe]mF]_mFe]mF`hl#F?Fg
x*&,&Fe_mFIFe[nFEF'F/F0Ff[n*&,&FhjmFabmFjjmF1F'F/F0#F'Fhfl*&,&Fe_mFb]l**F=F9Fen
F'F4F8F/FVF1F'F/F0Fgt*&,&Fe_mFabmF[\nF1F'F/F0Ff[n*&Fe]oF'F_]oF'F'*&FgaoF'F/F1F5
*&,NF`]nFiwF`\nFh_lFa]nFiw**F=F9F/FRFenF'F4F6F_qFe]nFiwFh]nFiwFj]nFh_nFa^nFh_lF
\^nFh_nFf\nF_q*,F=F9F7F'F/FRF4F6F`pF'FayFb[nF[sF]^nF[sFjjmFayFe_mF]tF`goF^sF_^n
F[sFhjmF[[lFb^nF[s**F/FRF=F9FhdoF'F4F6Fa\o**F=F9F/FRFdeoF'F4F6Fa\o**F=F9F/FRF[e
oF'F4F6FfamF'F/F0F6*&F`^oF'F\vF'F'*&F``oF'Fe[lF'F'Fbdm#F^rF\clFcdmFddmFfdmFe]mF
hdmFcblFiemFcblF\fmFe]m*,F/FIF7F9F:F9F4F5,(F[pFbyF/F\bn"$a"F'F'Fb`mF`fmFi^lFffm
FddmFgfmFcbl*,,(F[pFecmF/Fg`n"$2"F'F'F7F9F:F9F/FIF4F5Fe]mFd^n#F+FfyFg^nFdhlF\_n
Fd\m*,F7F9F:F9,*F/"#x!#XF'FfuFasF[pFavF'F4F0F/FI#F'FfyF`_nFd\m*,,&F/FecmF^_nF'F
'F7FDF:F9F4F5F/FIFb`m*,,&F]]mF_xF__lFh_lF'F4F5F7F9F/F1F:F9F0Fb_nFcbl*,,&F/FjpF^
rF'F'F:F9F7FDF/FIF4F5#F+F]qFf_nF9*,Fb^oF'F4F5F7F9F/F1F:F9FD*,F/FIF:F9F7F9,(F/!$
>""$="F'F[pFbyF'F4F5Fb`mFi_nFjhlFj_nFi^lF_`nFcbl*,,*FfuFbyF[p!$i"F/"$"G!$a"F'F'
F:F9F7F5F/FIF4F5Fcbl*,F/FIF7FDF:F9,(F/!#S"#OF'F[pF?F'F4F0#FYFc`mFe`nFi^lFi`nFcb
l*,,&F/FapFhwF'F'F7FDF:F9F4F5F/FIFddmF^an#Fj_oFd]l*,,(F[pFecmF/F][o"$9"F'F'F:F9
F7F9F/FIF4F5Fe]m*,,(F[pFasF/F^jnFjpF'F'F:F9F7F9F/FIF4F5Fjho*,,(F[pFbyF/!#&*F_en
F'F'F:F9F7F9F/FIF4F5Fcbl*,,(F[pFecmF/!$X""$1"F'F'F:F9F7F9F/FIF4F5Fb`mF`anFhpFaa
nFddmFfanFeho*,F=F9F7F'F/Fc`lF4F6F`pF'FfamFianFhpFjanFd\mFehnFiwFfhnFiwFghnF[sF
hhnF[sFihnFiwFjhnF[sF'F'*(F3F+FAF(,do*(F4F6F/F8F^cmF'F`s**FenF'F4F6F/F1FhboF'Fj
u**FenF'F4F6F/F1,(F^o#"#@F`qFZF_qFgnF^sF'F9Fg[mFdilF`^lFgeoF^alF_alF]^l#"$d)F\c
lFc^lFe^lFe]lFgfoFi]l#!$P%F\clF_]lFa^lFi_lFi^lFb\mF]coFhblF^blF]clFcblF`clFfxFe
clFfxFbboFDFiclFgemF_dlFfxFbdlF[imFcdlF[imFfdlFfnFgdlFfxFjdlF5F_elF_bn*(FgaoF'F
4F6F/F8F5*&FcsF'F`^oF'F'*&F``oF'F]`oF'F'F`cmFd\mFccmFaio*,F/FIF:F9F7FD,&F/Fhcl!
$e$F'F'F4F5Fe]mFicmFaioF\dmF9*,,(F[wF_xF__lFh_lF\elF_xF'F4F5F7F9F/F1F:F9F0F^dmF
d\mF'F'*(F3F+F.F(,^oFcinF^sFjjlFjuF_[mFbjmFc[mFcpF]^l#FjilFhtFhalFbjmFjalFfzF]b
lFbjmF`bl#FdfoF\^l*.F\vF'F4F5F7FDF/FFF:F9F=F5FcpFe]lF_hlF^glF]alFg]mFgelFi]mF_h
lFhinFD*&FdcoF'F/F1F5*&,,F\jnFfamFhjmF_qF_jnF[sFf_mF_qFe_mF[imF'F/F0F6F^bnFedlF
abnF^sFhbnFe]mF]cnFi^lFfcnFgtF_dnFi^lFaen#F'Fd]l*,,*FfuF_blF[p!$y&F/"$L*FghlF'F
'F:F9F7F9F/FIF4F0Fb`m*,F:F9,,F[p"%DCF/!%%G$"%?;F'Ffu!$u(Fa`mFhflF'F4F0F/FIF7F5F
b`mFbjnFi^lFbenFb`mFhjnF9FjjnFay*,,*FfuFecmF[pFjenF/"$G%!$[#F'F'F:F9F7F5F/FIF4F
5F_jlF_[oF_xF`[oFiwF'F'*(FAF(F.F+,br*(FaeoF'F4F6F/F8F5F\[mF^[mFbalF_hlFj[mFi^lF
ecoF_jlFiamFialF]^lFcalFc^lFdilFhalFbcoFjal#FdxFh]lF`blFe]mFi]l#F`alFa[mFcdlFge
lFfdl#F6F`bnF]flF]coF]hlFaaoFf]mFi^lFg]mFc]lFh]mFgelFi]mF_qFj]mFfcoF`hlF[imFi_m
F[il*&,&Fe_mF?*,FenF'F4F8F/FRF7F'F=F9F1F'F/F0Ff[n*&,4F[^nFh_lFhjmFfx*,FenF'F4F8
F/FbqF7F+F=F5FiwFa^nFgt**,*F/Fex!#WF'FfuFYF[pFa]lF'F/FbqF4F6F=F5F[sFa]nF[s*,F/F
bqF4F6F7F+F=F5FeqF'F[s*,FenF'F4F8F/FbqF[rF'F=F5F[s**F/Fbq,*F[pFfbnF/"$B"FhcnF'F
fuFjpF'F4F6F=F5FiwF'F/F0F6*&Ff[pF'F/F1F5*&,&Fe_mFijm*,FenF'F4F8F/FRF=F9F\oF'FEF
'F/F0Ff[n*&Fj]oF'F^^oF'F'*,F4F5F7F9F/F1F:F9,(F\elFcqF__lFgtF[wFcqF'F0FbdmFcalFf
emFgbnFhemFgbn*,,&F[wF?F__lF6F'F4F5F7F9F/F1F:F9Fi^lFcfmFialFg^nFgfnF[ioFh`nF]io
FDFf_nF5Fi_nF_anFj_nFialF\joF[_nFe`nFialF^anFgbnF\[pFh`nF`anFiwFhenF\flF]gnF\fl
*,FenF+F4F][mF/FIF7F9F:F9F`[m*,F/FIF:F9F7F9F]rF'F4F5F_an*,F/FIF:F9F4F5F7F9,(F[p
FjpF/!#kFevF'F'Fh`n*,F/FIF:F9F7F9,(F/Fijm"#;F'F[pFYF'F4F5F_an*,F7F9F:F9,(F[pFjp
F/FaimFg]lF'F'F/FIF4F5Fh`nFghnFiwFihnFiwF\inF[s**FcamF'FenF'F4F6F/F1F`s**F/Fc`l
F=F9Fb`pF'F4F6F[s**Fi^pF'F/F^imF4F6F=F5Fiw**FenF'F4F6F/F1F_[nF'FjuF'F'*&FAFas,<
F`\pF\flF]^l#F1F``pFcdlFgelFbdlFc]lFi]l#F`alFj^lFb\mF[`lF_coF^`l*(Ff[pF'F4F6F/F
8F5Fc\pFDF\dmF5**FenF'F4F6F/F1F^cmF'FjuF]`lF[ilFi_lFialF'F'*(FAF+F.F(,joFbalF_h
lFj[mFi^lFecoF_jlFjalFcalF]blF`[mF`bl#FdfoFh]lFi]lF_hlFfdlFa^pF]flFbjmF^hlFcalF
h]mFgelF`hlF[im*&FaeoF'F/F1F5*&,4*,,(F[pFjpF/Faim"#KF'F'F7F'F/FbqF4F6F=F5F[sFg^
pFiw**,*FfuFYF[pF]hmF/FdgnFiqF'F'F/FbqF4F6F=F5FiwFb[nFh_lF\_pF[s*,,(F[pFYF/Fhan
F(F'F'F7F'F/FbqF4F6F=F5FiwFe_mFfx*,F/Fbq,(F[pFYF/FhanFEF'F'F7F'F=F5F4F6FiwFjjmF
gtF'F/F0F6*&Fj]oF'FhvF'F'Fi_nFial*,F4F5F7F9F/F1F:F9,&F]]mFcqF__lFgtF'F0F^bnFc]l
FabnF_qFbbnFh`nFbcnF\flF]dnFialFjdnF\flF]enFh`nFaenFfcoF^]pFh`nFbjnFialFhjnF5Fi
_pF`[m*,FenF'F4F8F/Fc`lF=F9F\oF'Fgt*,FenF'F4F8F/Fc`lF7F'F=F9Fh_l*,,&F/FjpFioF'F
'F7F+F/F^imF4F6F=F5FiwF_[oF_q**FgimF'FenF'F4F6F/F1F`s**F/F^im,*FfuFYF[pF^jnF/Fj
_oFVF'F'F4F6F=F5F[s**FgapF'F/F^imF4F6F=F5F[s**F4F8F/FetF7F'F=F9Fiw**F4F8F/FetF=
F9F\oF'F[s**,*FfuFYF[pF^jnF/FarFbqF'F'F/F^imF4F6F=F5F[sF'F'6$FEF(,>*,FAF'F.F'Fe
nF'F4F6F/F1F[\o**F3F'FAF'F.F',(FdsF5F`tF5Ff]oF5F'F'**F3F+FAF'F.F',6Fj[l#FEFgxF[
wFhnFjbl#F8FecmF[\lF\alF]elFj^oFgjlFbcpFi[lFccpFcjlFbcpF]_lFbcpFfjlFccpF'F'*(FA
FEF.F',(F\elF[[lF__l#F+FecmF[wFfnF'F'*(FAF'F.FE,&F]]mF[[lF__lFfcpF'F'**F3FEFAF'
F.F',PFh]nFfamFjgoFip*,F4F5F7F9F/F1F:F9,&FCF5FKF6F'F9Fj]nFjuFe[nF^sFa]nFfamFa^n
F^sF[hoFa\oFe]nFfamFhgoFa\oFe_m#FIFapFf\nFjxF`]nFfamFigoFipFhjmF[[l*(Fe]oF'F4F6
F/F8FjuF`\nF^sF\^nFjuFjjmF^sF`go#Fb[lFht**F=F9F/FR,(F[pFgxF/FdvF_^lF'F'F4F6Fa\o
*&F/F1,(FdsFcpF`tFcpFf]oFcpF'F`sFggoF_dpF'F'**F3F'FAFEF.F',L**F/FRF=F9,(F[pFgxF
/!#nF_\oF'F'F4F6FayFd^pF_qF[dpF5Fj]nFay**F=F9F/FR,(F[pFgxF/F^qF\sF'F'F4F6Fay**F
e]oF'FenF'F4F6F/F1F`sFa]nFayFa^nFh_l**FenF'F4F6F/F1,&FdsF5Ff]oFLF'F`s*.F/FbqF7F
'F_yF'F\oF'F4F6F=F5Fay**FenF+F4F8F/FRF=F9F[imFe_mFg[pFa\nF[s**F/FRF=F9,(F[pFgxF
/Fiao"#bF'F'F4F6Fay*&F/F1,&F^vFLFdsFcpF'FjuFhjmFhfo*,F4F5F7F9F/F1F:F9F`^oF'F9Fh
^pFayF`\nFiwF[^nFgtF\_pFcqF'F'**F3F'FAF'F.FE,J**,&F`tF9Ff]oFcpF'FenF'F4F6F/F1Fj
uFd^pFcq**,*FfuFgxF[p!#(*F/"$_"FfbnF'F'F/FbqF4F6F=F5FayFe[nF[sFhapFay**FenF'F4F
6F/F1FcdpF'FjuFjapFayF_epF[imFe_mFfx**F=F9,*FfuFgxF[p!$B"F/"$E#!$E"F'F'F4F8F/FR
FayF[\nFiwFhjmFbcp**,*FfuFgxF[p!#**F/"$g"FdvF'F'F/FbqF4F6F=F5Fay*,FbbpF'F7F+F/F
bqF4F6F=F5FayFjjmFgtFfapFiwFb[nFh_l*(F4F6F/F8FdepF'F`sF\_pF_q*,,(F[pFYF/FcoFasF
'F'F7F'F/FbqF4F6F=F5FiwF'F'**F3F(FAF'F.F',dr*(F/FI,*F/"$F%FafnF'FfuFbyF[p!$&>F'
F4F6F_jl*(F/FI,*FfuFbyF[p!$z"F/"$H$!$!=F'F'F4F6#F'Fdel*(FbglF'F4F6F/F8F^`l*(F/F
I,*FfuFbyF[pF[anF/"$2$FggnF'F'F4F6Fggp*(F4F8F/FbqF`elF'#FhwF\`l*(F/FI,*FfuF\sF[
p!$z$F/"$C(!$0%F'F'F4F6#F'Fhcm*(F4F8F7F'F/FI#F6Fh]l*(F/FI,*F/"$2%!$%HF'FfuFbyF[
p!$!>F'F4F6F_jl*(,*F/"$[%!$g$F'FfuFbyF[pFagpF'F/FIF4F6F_jl*(F/FIFjzF'F4F6F]hp*(
F4F8F/FbqFjzF'F]hp*(F/FIF`]lF'F4F6F]hp*(F/FIF`elF'F4F6F]hp*(F4F8F/FbqF7F+#F\dnF
c`m*(F[uF'F4F6F/F8F`s*(F=F9F/F<FcdpF'FL*(,*F/"$+%!$.$F'FfuFbyF[p!$&=F'F4F6F/FIF
_jl*(F/FI,*F/"$)Q!$w#F'FfuFbyF[pF[jpF'F4F6F_jl*(F/FI,*F/"$?&!$]%F'FfuFbyF[pF_fn
F'F4F6F_jl*(FffoF'F4F6F/F8Fju*(F/FbqFenF'F4F8F^`l*(,*F/"$x%!$!RF'FfuFbyF[pFcanF
'F/FIF4F6F_jl*(,*F/F]ip!$_$F'FfuFbyF[p!$(>F'F4F6F/FIF_jl*(F7F'F/FbqF4F6#FcoFb^l
*(F/FIFenF'F4F6#F'"%?D*(FWF'F/FbqF4F6#FhwF\cl**FWF'F/FIFenF'F4F6F]hp**F4F8F/Fbq
F7F'FWF'F]hp**F/FIF7F'FWF'F4F6F]hp**F4F8F7F'F/FIF\oF'#FjilFd]l**F7F'F/FIF4F6Fac
lF'#FYF`jl**F7F'F/FIF4F6Fj\lF'Fchp**F/FIF7F+F4F6FhdlF'F[\q**F7F'F/FIF4F6FfclF'F
[\q**F7F'F/FIFenF'F4F6#F6Fdgn**Fe]oF'F4F6F/F1F=F9Fcp**FdglF'FenF'F4F6F/F1Fju*.F
:F9F/F<F7F9F=F9F4F5F\dpF'FO*(F4F8F/FbqF[rF'Fa\o**F4F8F7F'F/FIFWF'#"$<"Fd]l**F7F
'F/FbqFenF'F4F8F`\q**F/FbqF4F8FWF'FenF'F]hp**F/FIF7F',(F[pFbyF/FgflFhhoF'F'F4F6
Fggp**FenF'F4F6F/F1FbwF'F`s**FjvF'FenF'F4F6F/F1F^`l*,FcilF'F4F5F7F9F/F1F:F9F[`l
*,FfboF'F4F5F7F9F/F1F:F9F9*,,*F[oF_xF^oFc`oFUFhfoF_oF[imF'F4F5F7F9F/F1F:F9F9*(F
/FI,*FfuFhtF[p!$=)F/"%n<!%:7F'F'F4F6Fchp*(F4F8F/FIF7F+#"$H&Fd]l*(F/FbqF`]lF'F4F
8F]hp*(F/FIF4F6F7F+Fdip*(F[rF'F4F6F/FIFa\o*(,*F/Fa[mFiioF'FfuFjpF[pF[[pF'F4F6F/
FIFchp*&FbglF'F/F1F^`l*&F/FRF4F8F^`l*&Fh^lF'F/F1Fdil*&F/FbqF4F6Fa[q*&F/F1,6Fj[l
FcqF[wFcqFjblFgtF[\lF`_lF]elFejlFgjlFcqFi[lFgtFcjlFcqF]_lFcqFfjlFgtF'F`s*&F/F1F
g_lF'FjuF'F'**F3F+FAFEF.F',dtF^gpF[^m*(,*F/Faem!$I$F'FfuFbyF[pFagpF'F/FIF4F6F[^
mFdhp#F'Fh]lFfhpF[^mF_ipF]hp*(F4F8F/FbqFddlF'#FjilF\`l*(F/FIFenF+F4F8FdilFbipF]
_qFejpFdilF^[qF]_qF`[qFa[q*(F/FIFddlF'F4F6F]_q*(F/FI,*F[p!$Q#F/F`gn!$1#F'FfuFec
mF'F4F6F[^m*(,*F/"$$>!$Q"F'FfuFjpF[p!##*F'F4F6F/FIFgcm*(Fh_pF'F4F6F/F8F^`l*(F/F
I,*F/"$(>Fg_qF'FfuFjpF[p!#%*F'F4F6Fgcm*(F/FI,*F[p!$([F/"$J)!$M%F'FfuFhflF'F4F6F
h`n*(,*F/"$0#!$^"F'FfuFjpF[pF[[pF'F4F6F/FIFgcm*(F/FI,*F/"$">!$M"F'FfuFjpF[pFh_q
F'F4F6Fgcm*(F/FI,*F/"$'Q!$s#F'FfuFbyF[pF[jpF'F4F6F[^m*(F/FI,*F/"$%>!$W"F'FfuFjp
F[pFd\nF'F4F6F[^mFg[qF]hpFh[q#FhwFd]lF]\qF[^mF^\qF[^mF_\qF]_q**F7F+F/FIFenF'F4F
8#FguFc`m**F7F'F/FIF\oF'F4F6F`r**F/FIF[rF+F4F8F7F6Fdcl**FenF'F4F8F/FIF^[lF'F]_q
**FenF'F4F6F/F1,.F\\lF_xFjblF[sF[wFbcpF]elFj^oFgjlFbcpF]_lF_xF'F`s**F/FIF`elF'F
4F8FenF'Fi[q**F/FIF[rF'F4F8F7F'Fdcl**FjzF'F/FIF4F8FenF'F]_q**F/FIF7F+F4F6FhfmF'
Fgcm**F/FIF4F6F7F+FdfmF'F[^m**FbglF'FenF'F4F6F/F1Fdil**FffoF'FenF'F4F6F/F1F`s**
F]emF'FenF'F4F6F/F1Fju*(F/FIF^[lF'F4F6F]_q*(,*F/"$*>!$b"F'FfuFjpF[pFd\nF'F4F6F/
FIF[^m*(F\yF'F4F6F/F8F`s*(,*F/"$!R!$"GF'FfuFbyF[pF[jpF'F4F6F/FIF[^m**FenF'F4F8F
/FIF`]lF'#FjilF\clFe\q#F\doFd]l**F7F'F/FIFenF+F4F8#F'Fdgn**F/FIF7F',(F[pF\sF/Fd
uF]gmF'F'F4F6Fgcm**FiblF'FenF'F4F6F/F1Fa[q**FenF'F4F8F/FIF[rF'Fdo**F/FIF7F',(F[
pFhtF/!$e%"$&QF'F'F4F6F[^m**F/FIF7F',(F[pFhtF/!$W%"$r$F'F'F4F6F[^mF^]qF[`l*,Fga
oF'F4F5F7F9F/F1F:F9F9F`]qF5*,FenF'F4F8F/FIF7F'FWF'F]_q*(F/FI,*F/FjgmFbaqF'FfuFj
pF[pFh_qF'F4F6F[^m*(F/FI,*FfuFhflF[p!$-&F/"$x)!$l%F'F'F4F6F[^mFg]q#!%*R"Fd]l*(F
/FI,*FfuFhtF[p!$Y(F/"%l9!$+*F'F'F4F6F[^m*(F/FI,*FfuFhtF[p!$/(F/"%E8!$&zF'F'F4F6
F[^m*(F/FI,*FfuFhtF[p!$=(F/"%q8!$D)F'F'F4F6F[^m*(F=F9F/F<FdepF'Fcp*(F4F6F/F8Ff_
pF'FjuF[^qFdipF\^qF^sF_^qFdilFb^qFa[q*&Fh_pF'F/F1F^`l*&F`^oF'F\dpF'F'*&F/F1Fd\p
F'F`s*&Fe]oF'F]epF'F'*&F/F1,6Fj[lF_xF[\lFc_lFfjlFh_lFcjlF_xFi[lFh_lF\\lFcqF[wFc
qFjblFgtF]elFejlFgjlFcqF'Fju*,F/FIF7F'FacmF'F\oF'F4F6Fh`n*,F/FIF7F'FdcmF'F\oF'F
4F6F[^m*,F/FIF7F'FjcmF'F\oF'F4F6Fgcm*,F4F5F7F9F/F1F:F9,(FZF^sFgnF_qF^oFjaoF'F9F
'F'**F3F+FAF'F.FE,jt*(FenF+F4F1F/FbqFdil*(,*FfuFbyF[p!$D"F/FgfpFdxF'F'F4F6F/FIF
[^m*(F4F8F7FEF/FIFdcl*(F4F6F/F8F^bpF'Fju*(F/FI,*FfuFjpF[pFhcnF/"#w!#CF'F'F4F6F[
^m*(F4F8F/FbqF^]mF'F]_q*(,*FfuFjpF[pFhcnF/"#yF`zF'F'F4F6F/FIF[^m*(,,F[p"$t&F/!$
u&FcclF'Fa`mFbyFfu!$D#F'F4F8F/FIF[^m*(,*FfuFbyF[pF\bnF/"$)>Fh_qF'F'F4F6F/FIF[^m
*(F/FI,,F[p"$T&F/!$0&F]bnF'Fa`mFbyFfu!$?#F'F4F8Fh`n*(,*FfuFjpF[p!#oF/"#%*FavF'F
'F4F6F/FIFgcm*(F/FIFa\lF'F4F6F]_q*(Fa[lF'F/FbqF4F8F]_q*(,*FfuFecmF[pFb_qF/"$3%F
\hnF'F'F4F6F/FIFgcm*(,6Fh[lF_xFfjlFh_lF[\lFaxFcjlF_xFj[lFcqFjblFgtF[wFcqF]elFej
lFgjlFcqFi[lFgtF'F4F6F/F8F`s*(FiblF'F4F6F/F8Fdil*(,*FfuFjpF[pFdbnF/FahoF[dmF'F'
F4F6F/FIF[^m*(,*FfuFjpF[pFfbnF/FgblFdflF'F'F4F6F/FIF[^m*(F/FIF^]mF'F4F6F]_q*(,*
FfuFjpF[pFidlF/"$Q"!#!)F'F'F4F6F/FIF[^mF\hpF]hpFdhpFehpF`ipF]hpF^_q#F6"%g7*(,*F
fuF\sF[p!$1$F/"$-&!$j#F'F'F4F6F/FIFgcm*(,,F[p"%)*HF/!%$z$FfenF'Fa`mFhtFfu!%/5F'
F4F8F/FIF[^m*(,,F[p"%)4$F/!%FS"%!*=F'Fa`mFhtFfu!%=5F'F4F8F/FIF[^mFcip#"#LFd]l*(
F4F1F7F'F/FbqFfco*(F/FI,,F[p"%2KF/!%KTFgjqF'Fa`mFhtFfu!%Y5F'F4F8F[^mFejp#F6Fb[q
*(,,F[p"%6IF/!%7R"%[=F'FfuFb]mFa`mFhtF'F4F8F/FIF[^m*(F4F8F/FIFhoF'F`\q*(,,F[p"%
8HF/!%)o$F\`lF'Fa`mFhtFfu!$%)*F'F4F8F/FIF[^m*(F/FI,*FfuFbyF[pFjfqF/"$c"Fg]nF'F'
F4F6Fh`n*(,*FfuFjpF[pF]`pF/Fe_nF\enF'F'F4F6F/FIF[^mFf[qF]_qFh[qFcaq**F4F1F7F'F/
FIFenF'F]]p**F4F8F7F'F/FIFerF'#F1Fh]lFdaq#"$\$F\`l**F4F8F/FbqF7F'F\oF'FiuF[bqF]
_qF\bqFdclF]bqF]_qF`bqFdil**FenF'F4F6F/F1Fd^qF'Fju**FenF'F4F8F/FIFa\lF'F]_q*(F/
FI,,F[p"$m&F/!$Q&F]glF'Fa`mFbyFfuFigqF'F4F8F[^m*(,*FfuFjpF[p!#lF/"#&)!#KF'F'F4F
6F/FIFgcm*(,,F[p"$B'F/!$"p"$q#F'Fa`mFbyFfu!$K#F'F4F8F/FIF[^m*(F4F1F/FRFenF'F^`l
Fd\qF_qF]cqF^cqFe\qFcaqF`cqFacqFecqFido*.F\dpF'F4F5F7FDF/FFF:F9F=F5FcpF_dqFi[q*
,FdcoF'F4F5F7F9F/F1F:F9F9Fg]q#F\eoFb^lF`^qFa[q*&F/F1F^ioF'F`s*&F/F1F]^mF'Fju*&F
iepF'FcdpF'F'*,F4F5F7F9F/F1F:F9,,F^_oFcqFZF^sF[oFcqF_oF_qF^oFcqF'F9**FenF'F4F6F
/F1Fe\lF'F`s**F/FIF7F',*F/"$@#!#jF'FfuFbyF[p!$g"F'F4F8Fh`n**F4F6F/F1F=F9FdepF'F
L**F/FI,(F[pFbyF/F`]r"#EF'F'F7F'F4F6Fh`n**,(F[pFjpF/FefmFabmF'F'F7F'F/FIF4F6F[^
m**F/FI,(F[pFjpF/Fb]rFjoF'F'F7F'F4F6F[^m**,(F[pFjpF/Fb]rF_rF'F'F7F'F/FIF4F6F[^m
**,(F[pFecmF/FirF_[pF'F'F7F'F4F6F/FIFgcm**F7F',*F/"%">"!$?(F'FfuFhflF[p!$#fF'F4
F8F/FIF[^m**Fa[lF'F/FIF4F8FenF'F]_q**F7F',*F/"%]6!$-(F'FfuFhflF[p!$x&F'F4F8F/FI
F[^m**F/FIFbbpF'F7F+F4F6F[^m**,,Fh[lFcqFfjlFiwF[\lFXFcjlF[[lF]_lFcqF'FenF'F4F6F
/F1FjuF'F'*(FAFYF.F',8**F/FIF7F',(F[pFhflF/!$,$"$I#F'F'F4F6Fb`mFg]q#FjilF`q**Fe
nF'F4F8F/FIFddlF'Fd[q*,Fd^lF'F4F5F7F9F/F1F:F9F[`l**Fj_lF'FenF'F4F6F/F1F^`lFcfqF
5**FenF'F4F6F/F1Ff_pF'F[\o*,F4F5F7F9F/F1F:F9Ff[pF'F9F^]qF]co**Fh_pF'FenF'F4F6F/
F1Fdil*(F/FI,*FfuFhflF[p!$"[F/"$K)!$g%F'F'F4F6Fb`mF'F'*(FAFEF.FE,VF[gqFacq*(F/F
I,*FfuFbyF[p!$R"F/"$3#FahnF'F'F4F6F_jl*(F/FI,,F[p"$Q'F/!$G("$)GF'Fa`mFbyFfu!$L#
F'F4F8Fb`m*(FenFEF4F1F/FIFa[qFdhpF[_qFg[rFacqFh[q#FjilFh]lFb\rFehp**FenF'F4F8F/
FIF^]mF'Fd[qFc\r#FEFh]lF\bqF`\q**F/FI,(F[pFbyF/FdbnF__nF'F'F7F'F4F6F_jl**F/FIF7
F',*FbaqF'F/"$#HFfuFbyF[p!$t"F'F4F8Fb`m*(,*FfuFbyF[pFirF/"$<#!$/"F'F'F4F6F/FIF_
jl*(,*FfuFbyF[pFharF/FeemF\fpF'F'F4F6F/FIFchpF[arF^`lFi`rFd[qFg]qFabr*$FdepF+F'
*,F4F5F7F9F/F1F:F9FaeoF'F9F`^rF5**F/FIF[rF'F4F8F\oF'Facq**F4F8F7F+F/FIF\oF'F`\q
**Fd\pF'FenF'F4F6F/F1FJF^arFdil**FenF'F4F6F/F1F^bpF'F[\oF'F'*(FAF'F.FY,**(,,Fa`
mFhflFfu!$J'F[p"%N:F/!%_:"$e&F'F'F4F8F/FIF_jlFbbrFd[qF`brFa[q**F^ioF'FenF'F4F6F
/F1FJF'F'6$F(F+,D**F3F'F.F'F4F6F/F8FJ*,F3F+F.F'F4F6F/F1F=F9F9*(FAF+F.F',*F`tFcp
FatFLF^vFcpFdsFLF'F'*(F3FEF.F',(FcwF[[lF[wFfnF\wFfcpF'F'**F3F'FAF+F.F',8Fj[lF[[
lF[\lFOF\\lFbcpFi[lFfcpF[wFhnFjblFccpFcjlF[[lFdjlFf[mFfjlFfcpFgjlFbcpF]elFf[mF'
F'*(F3F'F.FE,&Ff\lFbcpF\wFfcpF'F'*(F3F(F.F',(Fd_mFidoFe_m#FasFYFf_mFipF'F'**F3F
+FAF+F.F',ZFe_mF`vFhjm#FRFgxF`goF_dpFb^nFfamFjgoFipF]^nFfamF[hoFa\oFigoFipF_^nF
famFjjmFidoFh]nFayFe[nFh_lFa]nFayFa^nF_qFe]nFayF`]nFayF`\nF_qFggoFb]oF[\nFgtFb[
nF[sFeepF5Fj]nF`sFhgoFidoF\^nF`s*(F``oF'F4F6F/F8F`sFf\nFip*(F4F6F/F8F_tF'F`s*&F
e]oF'F/F1F`sF'F'*(F3F+F.FE,,Fe_mFLF\jnFa\oFf_mFipF_jnFfamFhjmF[[lF'F'*(FAF(F.F'
,FF[^nFh_lFhjmFfxFg^pFiwFa^nFgtFh^pFfamFa]nFfamF[_pF[sF\_pF[sF]_pFiw*&Fj]oF'F/F
1FjuFe_mFbcp**FenF'F4F6F/F1F_tF'FjuFd^pFgtFc_pFh_lFj]nF[sF`\nF[s**F/FRF=F9Fb`pF
'F4F6FiwFa\nFiwF'F'*(FAF+F.FE,FFcapF[sFg^pFiwFfapFayFb[nFh_lF\_pF[sFhapFiwFe_mF
doFjapFiwFjjmFgt*(Fj]oF'F4F6F/F8Fju**FhzF'FenF'F4F6F/F1F`sFhfpF[sFe[nF[sF[\nFiw
**FjbpF'F/FbqF4F6F=F5FiwFd^pFgt**F/FbqFebpF'F4F6F=F5FiwFc_pFh_lF'F'*(F3FYF.F',:
Fe\q#FavFh]l*(F4F8F/FRFWF'F^cqFj`rF[`l*(Fh^lF'F4F6F/F8F^`lFg]q#FffpFb^l*(F4F8F/
FRF7F'#Fb[lFb^l*(F/FbqF4F6Fj\lF'FgcmF_]qF5*(Fg_lF'F4F6F/F8F[\o*,Fe_lF'F4F5F7F9F
/F1F:F9F9F^]qF]co*(FjvF'F4F6F/F8FdilF'F'**F3FEFAF+F.F',jsF^gpF[^mFbgpFggpFhgpF^
`lFigpFggp*(F4F8F/FbqF^[lF'Fd[qF]iqFa[r*(F/FI,*FfuFhflF[p!$2&F/"$Q)F^ipF'F'F4F6
F_jl*(F/FI,*FfuFhflF[p!$'[F/"$z(Fj^qF'F'F4F6F_jlF\hpFcaqF^hpFchp*(F/FI,*FfuFhfl
F[p!$s%F/"$N(!$+$F'F'F4F6F_jl*(FcboF'F4F6F/F8F`sFdhpF[_qFfhpF[^mF[ipF[^mF_ipF]_
qF`ipF]_qFaipF]_q*(F4F6F/F8FbjlF'F`sFbipF]_qFcipFeaqFeipFjuFgipF[^mF\jpF[^mF`jp
F[^mFejpFdilFfjpF[^mFjjpF[^mF^[qFhfrF`[qFa[rFc[qF^cqFe[qF]_qFf[qF]_qFg[qF]_qFh[
qFcaqFj[q#FFF`jlF\\qFgcmF]\qF_hrF^\qF_hrF_\qFacqFb\qF`sFg\rF_q**F4F6F/F1F=F9F_t
F'FL**Fh^lF'FenF'F4F6F/F1Fdil*.F:F9F/F<F7F9F=F9F4F5F`^oF'F\alFd\qFezFe\q#"$V"Fd
]lFh\qF`\qFi\qF]hp**Fg_lF'FenF'F4F6F/F1Fju**F``oF'F4F6F/F1F=F9FLFj\qFggp**F/FIF
7F',(F[pFhflF/!$x#F\^lF'F'F4F6F_jl**F/FIF7F',(F[pFhflF/!$"HFahoF'F'F4F6F_jl**F/
FIF7F',(F[pFecmF/Fchl"#lF'F'F4F6FchpFj`rF]coF[grF5F^dqF5Fg]q#"$2&Fh]lFj]qF]hpF[
^qFeaqF\^qFidoF]^qFgcm*(Fe]oF'F=F9F/F<FL*&FbwF'F/F1FjuF_^qFdilF`^qFdilFa^qF^`l*
&FffoF'F/F1F`sFb^qFa[r*,F4F5F7F9F/F1F:F9F[alF'F9F'F'*(F3FEF.FE,J*(F4F6F/F8FbwF'
FJFgfrFhfrFe\qFabrFdfrF^cq*(F/FI,,F[p!#mF/"%M5!%!3"F'Fa`mFbyFfuFbclF'F4F8F_jl*,
F4F5F7F9F/F1F:F9Fe[mF'F9F[[rF[_q*(,*FfuFjpF[pFg`lF/FfiqF]bnF'F'F4F6F/FIFchpF\gr
FdilFdhpF[_qF[^rF5FefrF^`l*(,,F[pF`enF/"$g(!$#zF'Fa`mFbyFfuF\bnF'F4F8F/FIFchp*(
F4F8F/FbqFa\lF'Fd[qFc\rF^[m*&F4F1F/FVFa[rFg]q#Fg]lF`qFg[rFcjo*(,,F[pFavF/"$g)F]
eqF'Fa`mFbyFfuFgclF'F4F8F/FIFchp*(F]^mF'F4F6F/F8F[\oF'F'**F3F'FAF(F.F',hsF^gpF_
jlFh^qF_jl*(Fj]oF'F=F9F/F<Fcp*(F/FI,*F[pF_brF/"$%Q!$'>F'FfuFecmF'F4F6F[^m*(F/FI
,*F[p!$s$F/"$s&!$c#F'Ffu"#vF'F4F6Fh`nFdhpFehpFfhpF_jlF_ipF]_qF\_qF]_qF^_qF^`lFb
ipF]hpFejpF^`lF^[qF]hpF`[qFa[rF__qF]hpF`_qF[^mFd_qFchpFj_qFchpF^`qFh`nFc`qFchpF
g`qFchpF[aqF_jlF_aqF_jlFg[qF]_qFh[qFi[qF]\qF_jlF^\qF_jlF_\qF]hpFdaqFdipFfaqFiuF
gaqFacqFhaqF]_q**F/FIF7F',(F[pFh[sF/!$A#"$G"F'F'F4F6Fh`nF[bqF]_qF\bq#F6F_rF]bqF
]hpF^bqFchpF_bqF_jlF`bqFdilFbbqF`sFcbqF]hpFdbqF_jlFhbqFjuFibqF_jlFbhrFLFe\qFcaq
FecqF`rFj`rF]coF_dqF]hpF`dqF_jlFbdqF[^mFg]q#!$h$Fd]l*(Fj_lF'F4F6F/F8FdilF[^qFea
qF\^qF_q*(Fd\pF'F4F6F/F8F`sF_^qF^`lFb^qFa[rFjeqFdil*&Fb^oF'F/F1Fju*&Ff_pF'F/F1F
`s*&F``oF'F_tF'F'FeirF5F]arF5*,F7F'F/FIFenF'F4F8F\oF'F^s**FenF'F4F6F/F1FbjlF'Fj
uFbcrFacq**F/FIF7F',(F[pFecmF/!$[""$."F'F'F4F6F[^m**F/FIF7F',(F[pFecmF/Fir"#)*F
'F'F4F6F[^m**F/FIF7F',(F[pFhflF/!$2$F\crF'F'F4F6Fh`nF'F'**F3F'FAF+F.FE,^uFhgpF^
`lFgfqFdil*(,*FfuFjpF[p!#^F/"#MFewF'F'F4F6F/FIF[^mFhfqF[^m*(,*FfuFjpF[pFaimF/Fd
foFarF'F'F4F6F/FIF[^mF[gqF`\q*(F^ioF'F4F6F/F8F`s*(,*FfuFjpF[pFeimF/Fb]lF_rF'F'F
/FIF4F6F[^mF]gqFgcmFagqF]_qFbgqFgcmFegqF[^mFjgqF[^mF]hqF[^mFbhqFgcm*(F/FI,*FfuF
jpF[pFeimF/FdgnF``pF'F'F4F6Fh`n*(F/FI,,Fa`mFjpFfuFh_qF[pF]fpF/F8!$3"F'F'F4F8Fh`
n*(F/FI,*FfuFjpF[pFaimF/FgxFarF'F'F4F6Fh`n*(F4F6F/F8Fg[lF'FjuFfhqF]hpF_grFd[qFg
hqF]hpFhhqFchpF^iqF_jlF`iqF_jlFbiqF]hpFciqF_jlF\hpF]hp*(,,F[p"%vBF/!%-J"%S9F'Fa
`mFhflFfu!$s(F'F4F8F/FIFb`mFdhpFehpF`ipFi[qF^_qFa[qFcip#"$^"F\`lF[[rFfcoFejpFa[
rFg[r#Fg`lFd]lF]\rF[^mF`\rFgcmFf[qF]_qFh[qFcaqFb\rF]]pFc\rFbcoFdaq#Fe\oFd]lFg\r
FiuFgaq#F'F`bnF[bqF]_qF\bqFa^pF]bqF]_qFi\rF]_qFj\rF[^mF^]rFgcmFc]rF[^mFbhrFL*(F
b^oF'F4F6F/F8FjuFi]rF^`lFd\qF_qFe\qFcaqFdcqF^`lFecqF`rF_dqF]hpFg]q#FhwFdgnF`^qF
giq*&Fe\lF'F/F1Fju*&F^bpF'F/F1F`s*&Fe]oF'FhzF'F'F^jrF5FacrF5Fe\sF^s**Fj]oF'F4F6
F/F1F=F9Fcp**F/FI,(F[pFjpF/FijmFbqF'F'F7F'F4F6Fh`n**F/FIF7F',*F/Fdgn"#aF'FfuFjp
F[pFhcnF'F4F8Fh`n**F]^mF'FenF'F4F6F/F1Fju**F/FI,(F[pFjpF/FioFiqF'F'F7F'F4F6Fh`n
Fb_rFchpFd_rFb`mFi_rF]hpFj_rF_jlF_`rF_jlFbcrF^_sFccrF^_s**FenF'F4F6F/F1FdhnF'F`
sF'F'*(F3F'F.FY,,*(,,Fa`mFjpFfuFiyF[pFg[sF/"$k'!$?%F'F'F4F8F/FIF[^mFejrFd[qFg]q
F_[qFfjrFa[r*(F4F6F/F8Fe\lF'FJF'F'6$F'F',fnF'F'*,F3FEF=F9FenF'F4F6F/F<F6**F3F+F
enF'F4F6F/F1F'*(FAF+F4F6F/F8F6*&F.F+F/F1F8*(F3F'FAF+,&FdsF+FesF'F'F'*(F3F'F.F+,
*F`tF'F]vF(F^vF'F_vF'F'F'**F3F'FAF+F.F+,doFe_m#Fh[pFapFhjmFDFh]nFh]oFe[nF]oFa]n
F]oFa^nFfnFe]nFh]oF`]nFh]oF_jnF[imFb[nF]oFh^pFh]o**F4F5F7FDF/FetF:F9F0**F:F9F7F
9F/FetF4F5Fh]o**F=F9F4F6F/FR,(F[pFYF/F_]nFarF'F'F[imF_frFh]oFfapFh]oF`frFh]oFj]
nF[[lF\^nF[im*,F4F5F7F9F/F1F:F9Fe[lF'F0*,FhvF'F4F5F7F9F/F1F:F9FD*,F7F9F/FetF:F9
FWF'F4F5F[[lF\jnFh]o*,F:F9F7F9F\oF'F/FetF4F5FbcpF[_pF[im*,FixF'F4F5F7F9F/F1F:F9
FD*,F4F5F7F9F/F1F:F9F_]oF'FD*,F_uF'F4F5F7F9F/F1F:F9F0*,F4F5F7F9F/F1F:F9F^^oF'F0
FhbmFh]oFibmF[imFf\nFfn*(F\vF'F4F6F/F8F6*&F/F0FddoF'F'*&FcsF'F/F1F6*&F[cmF'F/F0
F6F'F'*&F3F(,(F]_lFcpF__lF[\oF[wF1F'F'*(F3F+FAF+,.F\elFLFjbl#F8FEF[wFasF]elF8F^
elF5FcwFLF'F'*(F3F+F.F+,0F]]mFLFfjlFfbsF[\lF8F_]mFHFcjlF5F[wF1F\uFLF'F'*&FAF(,(
F\\lFcpF[wF1F\wF[\oF'F'*(FAF+F.F+,4Ff\lFcpFi[l#F+FEF_]mF9Fj[lF9F[\lF9F[wF1F]yFc
p*&FixF'F/F0F6*&F/F0F^^oF'F'F'F'*&F.F(,,Fh[lFcpF]uF[\oF_]mF9*&Fe[lF'F/F0F6*&F/F
0FhvF'F'F'F'*&F3FY,(F`dpFh]oF_ep#FRFapFe_m#"#jFapF'F'*(F3FEFAF+,>Fd_mF`\o*,F=F9
F/FRF\oF'F`pF'F4F6FdoFfdpFfx*,F/FRF=F9F\oF'FeqF'F4F6FhnFidpFfxFe_m#F[^lFap**Fen
F'F4F6F/F1FcsF'F'F`epFfx*,F=F9F/FRF\oF'FhqF'F4F6FhnFhjm#FiqFY*,F4F5F7F9F/F1F:F9
F]`oF'FD*,FctF'F4F5F7F9F/F1F:F9F0F`go#F?FapF\_pFhnF'F'*(F3FEF.F+,HFfasFDFgasF0F
_ilF`\oFd^pFdoFj]nFhnFjepFfx**FenF'F4F6F/F1F\vF'F'Fg^pFdoFhgoFdoFe_m#F__pFgxF_f
pFfxFhasFhfo*&F/F0Fb_lF'F'Fhjm#FIFgxFdfpFfx*&FcilF'F/F0F[sF\^nFhn*&FfilF'F/F0F6
FggoFcdsF'F'*(F3F'FAF(,8*,F/FbqF_yF'F[rF'F4F6F=F5Fh]oFhjm#FjoFYFjjmFfnF]^nF[imF
e_m#F?FYFf_mF]oF_^nF[imFb^nF[im*(FcsF'F4F6F/F8F6FbdsFDFadsF0F'F'*(F3F'F.F(,HFfa
sFDFgasF0FbasFXFcasF[im**,*FfuFjpF[pFfbnF/F^[oF]`pF'F'F/FbqF4F6F=F5F[imF\]nF[[l
Fe_mFXFhasF[[lF`ilF]o**F4F0F7F9F/FgwF:F9F[im*,FhoF'F:F9F/FetF7F5F4F5F[[lFg\nF[i
mFb\nF[im*&F/F0F[[mF'F'*&F\vF'F/F1F6*&F][nF'F/F0F6F`\nF]oFhfpF[imF[^nF]oF'F'*(F
3F(FAF+,jn*.FctF'F:F9F/F<F7F9F=F9F4F5FD*.F:F9F/F<F7F9F=F9F4F5F]`oF'F0Fe\q#FfyF(
FbcqF[s**F/FIF\oF'FaclF'F4F6Fa\o**F/FIF\oF'FfclF'F4F6Fa\oFh\qF]o**F[elF'FenF'F4
F6F/F1F'FdcqF[[nFi`r#FRFht**F/FIF\oF'Fj\lF'F4F6FfamFecq#FhwFjpFi\qFcfsFfcqFh_lF
jcqFh_lFj`rFgt*,Fb_lF'F4F5F7F9F/F1F:F9FD*,F4F5F7F9F/F1F:F9FfilF'F0*,F/FIF7F'F\o
F'FhdlF'F4F6Fa\o*,F=F9FenF'F4F6F/F<FcsF'F6*,Fe`lF'F4F5F7F9F/F1F:F9F0*,F4F5F7F9F
/F1F:F9FhboF'FD*,FenF'F4F8F/FIF\oF'FWF'#FRF\sFifrF[sFg]q#FegpF`qF`\s#F6Fg[nFj]q
FcfsFidqFh_lF^eqFh_lFceqFh_l*(F\_lF'F4F6F/F8F6F'F'*&F3Fas,6Fb]qFiwF]cq#FfyFhtFe
\qFjaoF`cqFg]oFg]q#Ff^rFgxF[arFf[nFj`rFh_l**F\_lF'FenF'F4F6F/F1F'FffsF0FgfsFDF'
F'*(F3F(F.F+,\pFdhpF^sFaipFcfsF^_q#F6FcclFiiqF[sF^jqFh_lFcjqFh_lF[[rF^sF\[rFh_l
Fb[rFh_lFg[rF^sFh[rFh_lFe[qFcfsFj[qFa\oF\\qFfamF]\qFa\oF^\qFa\oF_\qF]o**F\]mF'F
enF'F4F6F/F1F'Fb\rF_qFbbrFcfsFc\rFbcpFdaqFefs*.F=F9F7F9F/Fc`lF:F9F`pF'F4F5F]o*.
F:F9F/F<F7F9F=F9F4F5Fe[lF'F0*.FhvF'F:F9F/F<F7F9F=F9F4F5FDFe\qF`erFffsF0FgfsFDF^
]qFgtF_dqF]gs*,F=F9FenF'F4F6F/F<F\vF'F6*,F[[mF'F4F5F7F9F/F1F:F9F0*,F4F5F7F9F/F1
F:F9F][nF'FDFg]q#F\eoFgx*&F/FIFj\lF'F[s*&Fj_lF'F/F1F_gs*&F\_lF'F/F1F6*&,&FdpF?F
epFIF'F/F0F[s*&F/F0,(F_pF[[lFdpFejlFepFf[mF'F'*&,(F_pFbcpFdpFf[mFepFejlF'F/F0F6
F'F'**F3F+FAF+F.F+,`wF^gpFayFh^qFiwFhfqFiwF]gqFayFagqFcgsFbgqFayFegqFiwFjgqFiwF
]hqFiwFbhqFay*(F/FIF7F'FhfmF'Fiw*(F/FIF7F'FhdlF'FiwF_jrFiwFiirFgtFdhpFfxFfhpFay
FhjrFiwFajrFiwF[ipFiwFcip#FjilFjpFgipFiwF\jpFiwF`jpFiwFejpF]goFfjpFiwFjjpFiwFg[
rF[imF^[qFdoFc[qFeyF__qFcgsFd_qFayFj_qFayFc`qFayFg`qFayF[aqFiwF]\rFiwF`\rFayFf[
qFeyFh[qFjaoFj[qFiwF]\qFiwF^\qFayF_\qFcgsFc\rFejlFdaqFeyF\bqF`oF]bqFeyF^bqFay**
F4F6F7F'F/FIF`hoF'Fiw**FenF'F4F6F/F1Fg_nF'F'FdbrFiwFi\rFcgs**F/FIF\oF'FWF'F4F6F
eyFfbrFgtFj\rFiwF^]rFayFjbrFgtFc]rFiwF^crFiw*(F\]mF'F4F6F/F8F6FibqFiwFjgsFido*.
F7FDF:F9FerF'F=F5F/F^imF4F5Ffam*.F/Fc`lF=F9F:F9FhrF'F4F5F7F5Fay*.F4F5F7F9F/Fc`l
F=F9F:F9FeqF'F[\o*.F/F^imF7FDF:F9FcrF'F=F5F4F5Ffam*.F=F9F:F9F/Fc`lF7F9FhqF'F4F5
F[\oFe\q#F]hmFgx*.F=F9F7F9F:F9FerF'F4F5F/Fc`lFfam*.F:F9F7F9F]rF'F=F5F/F^imF4F5F
fam*.F:F9F/F<F7F9F=F9F4F5F^^oF'FD*.FixF'F:F9F/F<F7F9F=F9F4F5F0F^hsFDF_hsF0Fg]q#
F[fmFYF\^qF^isF]^qFay*&F/FIFfclF'Fiw*&F/FIFaclF'Fgt*&FiblF'F/F1Fhgs*&,&FdpFEFjs
FIF'F/F0Fhgs*&,&FjqFIF_sFasF'F/F0#F6Fecm*&FhvF'F]`oF'F'*&F_uF'F_]oF'F'*&F/F0,BF
drF_qFgs#FYFewFdtFh_lFbrF_qF\rF_qFfrF_qFdqFcpFfsFfxFgqFcpFitF_xF_pFfxFaqF_xF[tF
axF[qF^sFjqFcqF_sFh]oF'F'*&,&FdpFVF]sF?F'F/F0Fhgs*&F[elF'F/F1F6*&,BFdrF^sFgs#FF
FewFdtFgtFbrF^sF\rF^sFfrF^sFdqFLFfsF[imFgqFLFitFcqF_pF[imFaqFcqF[tF]tF[qF_qFjqF
_xF_sF`\oF'F/F0F6*&FcsF'F\vF'F+*&FctF'Fe[lF'F'*,F:F9F=F5F/F^imF7FDF4F5Fido*,Fhi
lF'F4F5F7F9F/F1F:F9F0*,FgimF'F4F5F7F9F/F1F:F9F0*,F4F5F7F9F/F1F:F9F_[nF'FD*,F[cm
F'F4F5F7F9F/F1F:F9FD*,F4F5F7F9F/F1F:F9FddoF'F0*,F4F5F7F9F/F1F:F9F^eoF'FD*,F/Fc`
lF:F9F7F9F=F9F4F5F[\oF'F'*(F3F+FAF(,jnF]iqFhgsF`grFgtFdgrFgtFhgrFgtF\_qFcgsFgaq
Fhn**F/FIFacmF'F[rF'F4F6Fiw**F/FIFjcmF'F[rF'F4F6Fay**F/FIFdcmF'F[rF'F4F6FayFhaq
Fcgs**F/FbqF\oF'FWF'F4F8FeyFd`rFgt**F/FIF\oF'F_dmF'F4F6Fiw**FenF'F4F6F/F1F]dmF'
F'Fd\qF^isFe\q#FczF`qF]]qFf[nFghrFgtFjhrFgtF]irFiwF^]qFh_lFjfsFDF[gsF0FdfrFcgsF
gfrF`\oFg]q#!$.#Fgx*(F[elF'F4F6F/F8F6*&FctF'F]`oF'F'*$FcsF+F'*,F4F5F7F9F/F1F:F9
F^cmF'FD*,FcamF'F4F5F7F9F/F1F:F9F0F'F'*(F3F+F.F(,\q*(,*FfuFecmF[pF_brF/"$#RF^`n
F'F'F4F6F/FIFiwF[gqFhnFhhqFayFbiqFcgs*(,,F[p"%/BF/!%-I"%/9F'Fa`mFhflFfu!$d(F'F4
F8F/FIFgtFhcrFgtFd^sFgtFdhpFfx*(,*!$*QF'F/"$#eFfuFecmF[p!$$GF'F4F6F/FIFiw*(,*F/
"%37!$C)F'FfuFhflF[pF^`rF'F4F6F/FIFgtF[[rF^s*(,*F/"%>8!$I*F'FfuFhflF[p!$1'F'F4F
6F/FIFgt*(,*F/"%k7!$!))F'FfuFhflF[p!$"fF'F4F6F/FIFgt*(F/FI,*F/"$k%Fj^qF'FfuFbyF
[pF_fnF'F4F6F^s*(,*F/"%h7!$q)F'FfuFhflF[pFh_rF'F4F6F/FIFgtFg[rFfzF`[qFgtFg[qFey
FjgsFidoF[hsF0F\hsFDFeisFjxFgisFjxFe\qFfz*.F=F9F:F9FcuF'F7F5F/Fc`lF4F0Fay*.FcvF
'F7F9F:F9F/F^imF4F5F=F5Fay*.F^wF'F7F9F:F9F/F^imF4F5F=F5Fay*.FenF'F4F0F/Fc`lF:F9
F7F9F=F9FiwF^hsF0F_hsFDFg]qF]erF[^qF^is*&F/FIFWF'Fcgs*&F7F'F/FIF`\o*&FhvF'Fe[lF
'F'*&,<F]wF_qFjsFcqFep#FcoF`qFgsFejlFivFgtFbvF_qF[tFcqFbuF_qFdqFh]oFfwFcqFgqFh]
oF_pF[imFdpFcqF'F/F0F6*&F\]mF'F/F1F6*&F/F0,<F]wF^sFjsF_xFep#Fb[lF`qFgsFf[mFivFh
_lFbvF^sF[tF_xFbuF^sFdqF`\oFfwF_xFgqF`\oF_pFfxFdpF_xF'F'*&,&F[tFIF_sFEF'F/F0#F6
FhflFj[tFbcp*,F4F0F7FDF/Fc`lF:F9F=F9F`\o*,F4F0F7F9F/FetF:F9F=F9FbcpFb_rFiwFd_rF
gtFi_rFcgsFj_rFgt**FenF'F4F6F/F1FijnF'F'*$F\vF+F'F'F'*(FAF(F.F+,bpFc]sFh_lFg]sF
h_lFj]sFh_l*(Fg_nF'F4F6F/F8F6FdhpF^sFejrFcfsF`ipF]gsFcipF]gsF[[rF^sFg[rF^sF^[qF
cfsF_aqF[sFh[qFfzFb\rF_qFc\rFbcpF_bqFh_lFcbqFcfsFdbqF[sFeisFayFfisFay*.F7FDF:F9
F]xF'F=F5F/F^imF4F5Fay*.F:F9F/Fc`lF4F5F7F9F=F9F_yF'Fa\oFj`rFh_lF`dqF[sFg]q#Fjil
FapF`^qFhgs*&FjvF'F/F1F_gs*&,&FepF1FjsF?F'F/F0Fhgs*&,6F\xF_qFfsF^sF^xF_xFdtFgtF
brF_qF`xF_qF_sF_xF[tFaxFbxFfxFjqF]tF'F/F0F6*&F/F0,6F\xF^sFfsF_qF^xFcqFdtFh_lFbr
F^sF`xF^sF_sFcqF[tF]tFbxF[imFjqFaxF'F'*&,&FepFasF]sFIF'F/F0Fhgs*&F/FIF\`pF'Fh_l
*&FixF'F^^oF'F'*&F]dmF'F/F1F6Fi\tF0Fj\tFDFe[tFDFf[tF0Fj[tFfamFe_sFh_lFg_sFh_lF[
`sFh_l**F/FIF4F6F7F'F\`pF'Fh_lF'F'*&FAFas,2Fi[sFh_lF_grFcfsFg]q#"#\F`qF\grF_gsF
^]qFgt*(F]dmF'F4F6F/F8F6Fj\tFDFi\tF0F'F'*(FAF+F.F(,bpF``sFh_l*(F/FI,*FfuFYF[pFb
]rF/F`wFj^pF'F'F4F6F_q*(,*FfuFjpF[pFd\nF/F]gm!$6"F'F'F/FIF4F6Fh_l*(F/FIFh\nF'F4
F6Fh_l*(F/FIFc\nF'F4F6Fh_l*(,*F/FieoFfalF'FfuFjpF[pF[]nF'F4F6F/FIFh_l*(F/FIFees
F'F4F6Fh_l*(F4F6F/F8FijnF'F6FfhqFcfsFghqFcfsF^iqF[sF`iqF[sFciqF[sFdhpFfxF_ipF]g
sFg[rF^sFh[qFfzFb\rF_qFc\rFbcpFcisFipFeisFfamFfisFfam*(,*FfuFjpF[pFh_qF/"$$=!$7
"F'F'F/FIF4F6Fh_lFh`tFfam*.F4F0F7F9F/Fc`lF:F9F=F9F\oF'Ffx*.F[zF'F:F9F7FDF=F5F4F
5F/F^imFa\o*.FhyF'F:F9F7FDF/F^imF4F5F=F5FayFg]qF_qF[^qF]gsFe_tFcfsFb^qFh_l*&F/F
0,FFazF^sFgsF_qFfsF_xF`[lFcqFc[lF[sFizFbcpF\[lFbcpF[tF]tF]zF[imFdrF[imF\zF[imF
\xF_qF_sF_qF][lFcqFbrF_qFjqFaxFdqF_qFepFcqF'F'*&,FFazF_qFgsF^sFfsFcqF`[lF_xFc[l
FiwFizF[[lF\[lF[[lF[tFaxF]zFfxFdrFfxF\zFfxF\xF^sF_sF^sF][lF_xFbrF^sFjqF]tFdqF^s
FepF_xF'F/F0F6*&Fg_nF'F/F1F6*&FixF'FhvF'F'*&Fe[lF'F^^oF'F'Fc[tFdoFe[tFDFf[tF0Fj
[tF[imFa`tF[imFb`tF[imF_`rFh_lF'F'*&F.Fas,8*(,*FfuFh[sF[p!$(QF/Fd`n!$E$F'F'F/FI
F4F6Fh_l*(F/FIFa[lF'F4F6FcfsFg]qFh]oF`ctFfam*$F/FIF_gsFj[tF[sFb`tFfam*&,,FgyF^s
FepF^sFgsF_xF`\lF_xFb\lFgtF'F/F0F6*&FijnF'F/F1F6Ff_tF'*&F/F0,,FgyF_qFepF_qFgsFc
qF`\lFcqFb\lFh_lF'F'F'F'6$FEFE,RF6F'*&F3F+F/F1F[\o**F.F+FenF'F4F6F/F1FJ*(F3FEF=
F9F/F<F5*(F3F'F.F+,&F`tF'Ff]oF9F'F'*&F3F(,&F]uFccpF\uFbcpF'F'*(F3F+FAF+,&F]yF[[
lF]uFccpF'F'*(F3F+F.F+,,Fh[lF[[lFfjl#F(FecmF[\l#FVFYFcjlFejlF]_lF[[lF'F'*(FAF+F
.F+,(F[wFhnF__lFccpF\elFbcpF'F'*&F.F(,&F]]mFbcpF__lFccpF'F'*&F3FY,&F`ilFjxF_ilF
a\oF'F'*(F3FEFAF+,(FhbmFidoF`ilFjxFibmFayF'F'*(F3FEF.F+,8Fb\nFayF`\nFh]oFggo#Fc
oF\sFg\nFayF\]nF`\oFj]n#F(FjpF\^nF_ftFhgoFjxF`dpFido*&F/F1,&F`tF5Ff]oFLF'F`s*&F
iepF'F/F1FjuF'F'**F3F'FAF+F.F+,JFfdpFfamFd^pFfxF[dpF'Fj]nFa\oFherFjuFidpFfamF[e
pFjuFa]nFa\oFa^nFiwF^fpF`sF_epFfxFe_mFXFa\nFayF`epFfamFcepF`sFhjmFejlFh^pFa\oF`
\nFfamF[^nF[sF\_pFfxF'F'*(F3F'F.F(,2FhfpFa\oFd^pF`\oFjepFfamF_epFfxFdfpFfamF_fp
FfamFhepF`s**FenF'F4F6F/F1FaftF'FjuF'F'*&F3Fas,.Fd_tFd[qF_dtFa[qFe_tF_[qFahsFch
p*&FdglF'F/F1Fju*&F/F1F[uF'F`sF'F'*(F3F(FAF+,8Fe_t#FharF\`lF_dt#F'FhiqF\isFgcmF
d_tFd[qF]isFgcmF^jsFgcmF_jsF[^mF[gtF`s*&F]emF'F/F1Fju*&F/F1F\yF'F`sFjftFjuF'F'*
(F3F(F.F+,RFe[qF^cqF[^qF_ftFg[q#FjilFebl**FenF'F4F6F/F1F[uF'FjuFaipF^cqFi^tFa^p
Fj[q#F6Fh[pF\\q#F6FdelF]\qFfgtFb]qFgcmF^\qFfgtFb\qF`sF_^tF[^mF_\qFdclF`[qF[cl*&
F/F1,,Fh[lF_xFfjlF[sF[\lFj^oFcjlFbcpF]_lF_xF'F`sFd^tF[^mF\_tF[^mF^dtF^cq*(F=F9F
/F<FaftF'FLF[^tF[^mFf]tFgcm*&Fa`rF'F/F1Fju*(FiepF'F=F9F/F<FcpF'F'*(F3F+FAF(,,*(
F/FIF7F'FdfmF'F_jlFe_tF^cqF_dtFa[qFagtF`sF`gtFjuF'F'**F3F+FAF+F.F+,bsF^gpFchpFh
^qFchpF^[sFcpF_btF^_sF[gqF`\qFabtF_jlFdbtF_jlFebtF_jlFfbtF_jlFdhpF\flFfhpFchpF_
ipFd[qF^_qFa[qFbipFd[qFejpFa[qF^dtF^cqF`[qFgiqF__qFd[qFd_qFggpFj_qFggpFc`qFggpF
g`qFggpF[aqFchpFg[qF^cqFh[qFabrF]\qFchpF^\qFchpF_\qFd[qFdaq#F\dnF`jlFfaqFhpFgaq
F`\qF[bqFd[qF\bqF]\sF]bqFd[qF^bqFggp**FenF'F4F6F/F1F\yF'FjuF`bqFa[qFh\rF`sFabqF
juFbbqF`sFibqFchpFjbtF_jlF]cqFd[qFe\q#Fd`oF\^lF`cqF`\qFbcqFchpFecqFipFfcqF_jlFj
cqF_jlF`]qF'F_dqFd[qFg]q#Fi]qFh]lFidqF_jlF^eqF_jlFceqF_jlFheqFLF[^q#FjjqFh]lF\^
qF[imFb^qFa[qFbhsFa[qF`jsFa[rFc\sF`sF\fqFju*&Fe]oF'FcdpF'F'*&F\iqF'F/F1F`s*&F/F
1,6Fh[lFcqFfjlFgtF[\lF]tFcjlFcqFj[lF_xFjblFh_lF[wF_xF]elFf[mFgjlF_xFi[lFh_lF'Fj
u*$F\dpF+F'F'F'*(F3F+F.F(,R**FenF'F4F6F/F1FigtF'FjuF\[rF_jlF`cqF`\qF]cqFd[qFbiq
Fd[qF]^rFjuFb_rFggpF^jqF_jlF[gq#F6FfyF_dq#FhwFeblFjctF_jl*&FiepF'FaftF'F'Fb_sF`
sFd_rFchpFcjqF_jlF^_q#F'F\clF``rF`sFiiqFchpFdaq#F<FjpFhhqFggpFh[rF_jlFi_rFd[qFj
_rFchpFb[rF_jlF'F'*(FAF(F.F+,2F_arF[^mFg]q#FhwF`qFi`rF^cqF^]qF[clF^arFa[qFcfqF'
F\arFjuFdcrF`sF'F'*(FAF+F.F(,RFfarFgcmFb\rF[_qFh[q#FhwFh]lF\bqFacqF[gqF`\qF[arF
a[rFccrFacqFdhpFehpF`^rF'F^crFgcmFjbrF[^mFjarF[^mF\arFjuF`brFa[rFi`rF^cqFbcrF`
\qFbbrF^cqFc\rFd\rFdcrF`s*&Fj]oF'FdepF'F'Fg]qFiitF^drF`sFecrFjuFg[rF`\qF'F'*&F.
Fas,,FhcrF[^mFbbrF^cqF`brFa[rFecrFjuF^drF`sF'F'6$FEF+,D*(F3F'FAF'F/F1FJ**F3F+FA
F'F=F9F/F<F9*(FAF'F.F+,*F`tFLFatFcpF^vFLFdsFcpF'F'*(F3FEFAF',&F\uF[[lF]uFfcpF'F
'*(F3F'FAFE,&F]yFbcpF]uFfcpF'F'**F3F'FAF'F.F+,8Fh[lFbcpFi[lFfcpFj[lF[[lF[\lFhfo
FjblFfcpF[wFfnFcjlFbcpFdjlFejlFfjlFccpFgjlF[[lF]elFejlF'F'*(F3F(FAF',&F_ilFidoF
`ilFipF'F'*(F3F+FAFE,(FhbmFa\oFibmFfamF`ilFipF'F'**F3F+FAF'F.F+,ZFe_mFcdsFhjmFb
cpF`goFb]oFjgoFjxF[hoFidoFigoFjxFjjmF_qFh]nFayFe[nF_qFa]nFayFa^nF[sFe]nFayF`]nF
ayF`\nFcgsFggoF_dpFb\nFfamFg\nFfamF\]nFh]oFa\nFh_lF[^nFiwF[dpF5Fj]nFh]oFhgoFa\o
F\^nFh]oFf\nFipF^dpF`sFbftF`s*&F/F1FhzF'F`sF'F'*(FAFEF.F+,FFh^pFayF[^nFgtFa]nFa
yF[_pFiwFa^nFh_lFhjmF[imFg^pF[sF]_pF[sF\_pFiwFcepFjuFe_mF[[lFierF`sFd^pFh_lFc_p
FgtFj]nFiwF`\nFiwFjerF[sFa\nF[sF'F'*(FAF'F.F(,FFcapFiwFg^pF[sFfapFfamFhapF[sFja
pF[sFb[nFgtF\_pFiwFjjmFh_lFe_mF]oFifpFjuF^frFjuFhfpFiwFe[nFiwF[\nF[sF_frF[sFd^p
Fh_lF`frF[sFc_pFgtF'F'*(F3FYFAF',,FahsFgcmFd_tF^cqFe_tFhfrF_dtFa[rFjftF[\oF'F'*
(F3FEFAFE,4F\isFchpFe_t#"$R"F\`lF]isFchpF^jsFchpF_dtFgiqF_jsF_jlFd_tF^cqF[gtFJF
`gtF[\oF'F'**F3FEFAF'F.F+,fsF^gpF[^mFbgpFggtFhgpFdilFigpFggtF\hpF]_qF^hpFgcmFdh
pF[_qFfhpF[^mF[ipF[^mFf]tFchpF[^tF_jlF\htFL*(F=F9F/F<FhzF'FLF_ipF]_qF`ipF]_qFai
pF]hpFbipF]_qFcipFeaqFeipFjuFgipF[^mF\jpF[^mF`jpF[^mFdjpF`sF_^tF_jlFd^tF_jlFi^t
F^_sFejpFdilF^dtFd[qF\_tF_jlFfjpF[^mFjjpF[^mF^[qFhfrF`[qF_gtFc[qF^cqFe[qF]hpFf[
qF]_qFg[qFcaqFh[qFcaqFj[qF^_sF\\qFchpF]\qF^_sF^\qF^_sF_\qF`\qFa\qFLFb\qFjuFahrF
^`lFfaqF^sFc\qF\alFd\qFidoFe\q#FjelFd]lFh\qFacqFi\qF]_qFehrF`sFj\qFggtFj`rF[`lF
[grF9F`]qF5Fg]q#!$H&Fd]lFj]qF]_qF[^q#!$B$F\`lF\^qF`rF]^qFgcmFcirFjuF`^qFdilFb^q
Fa[rF[htF`s*&F/F1FdhnF'F`sF[atFdilF`jsF^`lF'F'*(F3F'FAFY,*F_htF[^mFe_tFd[qF_dtF
a[rFagtFJF'F'**F3F'FAFEF.F+,htF^gpF[^mFh^qF[^mF_btFa^pF[gqFacqFabtF[^mFdbtF[^mF
ebtF[^mFfbtF[^mF_[sF_jlFdhpF[_qFfhpF[^mF_ipFi[qF\_qF]hpF^_qFdilFbipF]_qFejpFdil
F^dtFd[qF^[qF]hpF`[qFa[qF__qF]_qF`_qF_jlFd_qFgcmFi_qFdilFj_qFgcmF^`qFb`mFc`qFgc
mFg`qFgcmF[aqF[^mF_aqF_jlFg[qF]hpFh[qFcaqF]\qF[^mF^\qF[^mF_\qF]_qFdaqFeaqFfaqF`
rFgaqFa^pFhaqF]hpF[bqF]hpF\bqF^_sF]bqF]_qF^bqFgcmF_bqF_jlF`bqF^`lFbbqFjuFcbqF]h
pFdbqF_jlFhbqFjuFibqF[^mFc\qFLFjbtF[^mFe\qFi[qFecqFiuF^]qF]coF_dqF]_qF`dqF_jlFb
dqF_jlFg]q#"$T$Fd]lFheqFcpFieqF`sF[^q#F^qF\`lF\^qF^sFb^qFgiqFbhsFdilF`jsF^`lF\f
qF`sFhhtFju*&Fe]oF'F_tF'F'*&F/F1Fg[lF'FjuFeirF9FcfqF5Fe\sF_qFf\sF`sFbcrFa^pFg\s
F_jlF[]sF_jlF^]sFb`mFccrFa^pF'F'**F3F'FAF'F.F(,fsFgfqF^`lFhfqF_jlF[gqFdclF\gqF`
sF]gqFchpFagqF]hpFbgqFchpFegqF_jlFjgqF_jlF]hqF_jlFbhqFchpFfhqF]hpFghqF]hpFhhqFg
cmF[iqFjuF]iqF^`lF^iqF_jlF`iqF_jlFbiqF]_qFciqF_jlFjctF[^mF\hpF]_qFd^sFh`nFdhpF[
_qF`ipF]_qF^_qFa[rFcipF]_sF[[rF]]pFejpFa[qFg[rFcjoF]\rF_jlF`\rFchpFf[qF]hpFh[qF
i[qFb\rFfcoFc\rF^[mFdaqFijqFg\rF`rF[bqF]hpF\bqF`\qF]bqF]hpFi\rF]hpFj\rF_jlF^]rF
chpFc]rF_jlFc\qFLFi]rFdilFd\qF^sFe\qFi[qFdcqFdilFecqFiuF_dqF]_qFg]q#"#PFb^lF`^q
Fa[rFa_sFjuF]^rF`s*&FiepF'FhzF'F'F^jrF9F`^rF5Fe\sF_qFj_sF`sFh^rFcpFb_rFgcmFd_rF
h`nFi_rF]_qFj_rF[^mF_`rF_jlFccrF`\qF]`sFjuF'F'6$F'F(,TFc[oFd[oFe[oF+Ff[oF8Fg[oF
'Fi[oF'**F3F'FAF+F.F+,`pFdpF^\oFaqF`\oFdqFa\oFgqFiuFjqFaxF\rFdwFbrFhpFdrFb\oFfr
FiuFbuF_qFbvF_qFc\oF[sF]wF_qFf\oF[sFi\oF[sF]sF]tF\xFiuF`xF[sF[]oF\]oF]]oFejlFa]
oF_x**F_uF'FenF'F4F6F/F1Fju**FhvF'FenF'F4F6F/F1F`sFepFb]oF_sFc]oFfsFJFgsF`_lFjs
Fg]o*,F4F5F7F9F/F1F:F9FcdpF'FDF[vF5F[tFh]o*,F4F5F7F9F/F1F:F9FdepF'F0FizF_xF\[lF
c_lF][lFcqF[^oFh_lF\^oFcqF_[lF`sF_^oF5Fc^oFgtFc[lFh_l*&F/F0F_fqF'F'F'F'Fd^oF'Fh
^oF'F[_oF'F__oF'*(FAF+F.F+,4FgoF^_lF_oFhnFhimFLF[oFdoFiimFcpF^oFdoFZFfn*&F/F0Fd
epF'F'F^_oF_xF'F'Fe_oF'*(F3FEFAF+,8F[qF`rFjqFLF_sFjuFdqFi_oFgqFi_oF_pF[`oFaqF[
\oF^`oF9*,F4F5F7F9F/F1F:F9F]epF'FDFbsF9FbtFjuF'F'*(F3FEF.F+,LFbuF^sFdqF`sF[vF9F
epFc`oFgqF`sFbvF^sFaqFjxFdpF_x*&F/F0Fg_lF'F'FgvFjuFc\oFiwF]wF^sFf\oFiwF_pFh_nFi
\oFiwF[tF^_lFgsF\alFjsF^_lFe`oFgtFfwF_xF_sF[sF'F'*(F3F'FAF(,<Fh`oFjuFjqFcpF_sFJ
F[qFiuFaqF`sFepF`_lFdpFc_lFdqFb\oFgqFb\oFbsF5**FctF'FenF'F4F6F/F1F`sFi`oF5F_^uF
0F'F'*(F3F'F.F(,4FgyF_qFepFiuFgsFcqF`\lFcqFb\lFh_lFc\lF`sFfsFip*&F/F0F]^mF'F'F]
aoF[sF'F'*(F3F(FAF+,`oFd`lFjuFg[mF[ilF`^lF`aoF^alFaaoFaalFO*.F:F9F/F<F7F9F=F9F4
F5F]epF'F0F]^lFcaoFc^lF^`lFfaoF9**Fb_lF'FenF'F4F6F/F1F`sFgalFcpFi\lFh]oFe]lF\bo
Fi]lF]boF_]lFfxFi_lF[`lF[_lF5Fb\mFialFc\mF0FhblF_boF]clFiflF`clF`boFeclF`boFabo
F5FiclFeelF_dlF[imFbdlFgelFcdlFc]lFfdlFhnFgdlF`boFjdlF9F_elFdbo*,F4F5F7F9F/F1F:
F9FjaqF'FDFeboF5F'F'*&F3Fas,>Fi\lFddmF_]lFedlFe]lF\coFi]lF^^lF]^lFj]lF`^lFgelF_
coFe^lFb\mFi^lF[_lF9Fa_lFjuF^coF9Fc\mFDFi_lF]coF]`lFdilF'F'*(F3F(F.F+,dpFjjlFju
F\[mFbcoF_[mFbjmFb[mFfamFccoF9Fc[mFcpFg[mF^`lFh[mF`sF`^lFcalFi[mFOFj[mF_qFecoFf
coF]^lFgcoFhalF]coFjalFhcoF`blFjcoFi\lFiflFe]lF[doFi]lFejlFf_lF0Fg^lFialF`clFea
nFeclFeanFgdlFeanFfelFaaoF]flFbcoF^glF\coFe\mF\flF[]mF9F`]mF\flFf]mFialFg]mFgel
Fh]mFc]lFi]mFi^lFj]mF_jlF^^mF\flFc^mF\flFh^mF\flF]_mF\flFhinFDFbilF[ilF]doF5F^d
oFgt*&F/F0,(Fe_mF]tFf_mF^sFd_mFfamF'F'F'F'**F3F+FAF+F.F+,dyFihmF`sFjhmF^sFfdoF5
FgdoFidoFjdoFayF]imFiwF_imFiwF`eoF9FceoFidoFeeoF^sFbimF[sF`^lFgeoFbalFiwFj[mFdh
lFecoFialFfimFjuF]^lFheoFhalFcblFjalFjeoF`blF_bnF]foFcp*.F:F9F/F<F7F9F=F9F4F5Fd
epF'FDFe]lF^foFi]lF_foF_]lFa^lF`clFe]mFeclFcblFbdlFgelFfdlFafoFgdlFcfoFaelFddmF
felFh]oFhelFe]mF]flFcblF^flFgemF`flFgemFeflFcblFjflFcblF^glFgfoFfglFcblFiglFgem
F]hlFh]o*,F4F5F7F9F/F1F:F9Fd^qF'FDFe\mFe]mF[]mF5F`]mFe]mFg]mF[imFh]mF[imFi]mFdh
lFj]mFialF^^mFe]mFc^mFe]mFh^mFe]mF]_mFe]mFhinF0F`hlFhfoFifoFf[nF[goF]goF^goFgtF
agoFf[nFdgoF5F\hoF'*&F/F0,NF`]nF[sF`\nFgtFa]nF[sFggoF^sFe]nF[sFh]nF[sFj]nFhpFa^
nFgtF\^nFhpFf\nF^sFhgoFfamFb[nFiwF]^nFiwFjjmFfamFe_mFaxF`goF_qF_^nFiwFhjmFbcpFb
^nFiwFigoFidoFjgoFidoF[hoFayF'F'*&FhvF'F]epF'F'*&F_uF'FcdpF'F'FbdmF^hoFcdmFddmF
fdmFe]mFhdmFcblFiemFcblF\fmFe]mF_hoFb`mF`fmFi^lFffmFddmFgfmFcblFbhoFe]mFd^nFeho
Fg^nFdhlF\_nFd\mFfhoFjhoF`_nFd\mF[ioFb`mFb_nFcblF_ioFaioFf_nF9FcioFb`mFi_nFjhlF
j_nFi^lF_`nFcblFgioFcblF\joF`joFe`nFi^lFi`nFcblFajoFddmF^anFcjoFdjoFe]mFgjoFjho
FijoFcblF\[pFb`mF`anFhpFaanFddmFfanFehoF`[pFfamFianFhpFjanFd\mF]bpFD*,F4F5F7F9F
/F1F:F9F_fqF'F0FehnFiwFfhnFiwFghnF[sFhhnF[sFihnFiwFjhnF[sF[inFL**FhilF'FenF'F4F
6F/F1Fju**F[[mF'FenF'F4F6F/F1F`sF'F'*(F3F+FAF(,doFbamFjuFe[pF9**Fe`lF'FenF'F4F6
F/F1F`sFg[mFdilF`^lFgeoF^alF_alF]^lFi[pFc^lFe^lFe]lFgfoFi]lF[\pF_]lFa^lFi_lFi^l
Fb\mF]coFhblF^blF]clFcblF`clFfxFeclFfxFiclFgemF_dlFfxFbdlF[imFcdlF[imFfdlFfnFgd
lFfxFjdlF5F_elF_bnF]_uF0F]\pF5F^\pF'*&FctF'F]epF'F'F`cmFd\mFccmFaioF`\pFe]mFicm
FaioF\dmF9F^dmFd\mFe_pFDF'F'*(F3F+F.F(,^oFcinF^sFdinF`sF_[mFbjmFeinFLF]^lFg\pFh
alFbjmFjalFfzF]blFbjmF`blFh\pFi\pFcpFe]lF_hlF^glF]alFg]mFgelFi]mF_hlF\^mF0Fj\pF
5*&F/F0,,F\jnFayFhjmF^sF_jnFiwFf_mF^sFe_mFfxF'F'F^bnFedlFabnF^sFhbnFe]mF]cnFi^l
FfcnFgtF_dnFi^lFaenF]]pF^]pFb`mFb]pFb`mFbjnFi^lFbenFb`mFhjnF9FjjnFayFh]pF_jlF_[
oF_xF`[oFiwF'F'*(FAF(F.F+,brF^^pF5F\[mF^[mFbalF_hlFj[mFi^lFecoF_jlFiamFialF]^lF
calFc^lFdilFhalFbcoFjalF_^pF`blFe]mFi]lF`^pFcdlFgelFfdlFa^pF]flF]coF]hlFaaoFf]m
Fi^lFg]mFc]lFh]mFgelFi]mF_qFj]mFfcoF`hlF[imFi_mF[ilFb^pFf[nF`_pF5Fa_pFf[n*&F/F0
,4Fh^pFiwF[^nFgtFa]nFiwF[_pFiwFa^nFh_lFhjmF[imFg^pF[sF]_pF[sF\_pFiwF'F'*&FixF'F
depF'F'Fc\pFDFbdmFcalFfemFgbnFhemFgbnFg_pFi^lFcfmFialFg^nFgfnF[ioFh`nFf_nF5Fi_n
F_anFj_nFialF\joF[_nFe`nFialF^anFgbnF\[pFh`nF`anFiwF]bpF0FhenF\flF]gnF\flFi_pF`
[mFj_pF_anF[`pFh`nF^`pF_anFa`pFh`nFghnFiwFihnFiwF\inF[sF\apFjuFd`pF[sFe`pFiwFcb
pF`sF'F'*&FAFas,<F`\pF\flFbdlFc]lFi]lFj`pF]^lFi`pFcdlFgelF]`lF[ilFi_lFialF\dmF5
Fc`pF`sF[apF5Fe_pF0Fb\mF[`lF_coF^`lF'F'*(FAF+F.F(,joFbalF_hlFj[mFi^lFecoF_jlFja
lFcalF]blF`[mF`blF_apFi]lF_hlFfdlFa^pF]flFbjmF^hlFcalFh]mFgelF`hlF[imF`apF5*&Fe
[lF'FdepF'F'*&F/F0,4FcapFiwFg^pF[sFfapF[sFhapF[sFjapF[sFb[nFgtF\_pFiwFjjmFh_lFe
_mF[imF'F'F]ioFDFi_nFialF^bnFc]lFabnF_qFbbnFh`nFbcnF\flF]dnFialFjdnF\flF]enFh`n
FaenFfcoF^]pFh`nFbjnFialFhjnF5Fi_pF`[mF_bpFgtF`bpFh_lFabpFiwF_[oF_qFf`pFjuFdbpF
[sFfbpF[sFgbpFiwFhbpF[sFibpF[sF'F'6$F(FE,>F]cpF[\oF^cpF'F`cpF'FdcpF'FgcpF'**F3F
EFAF'F.F',PFh]nFfamFcerFjuFjgoFipF[dpF9Fj]nFjuFe[nF^sFa]nFfamFa^nF^sF[hoFa\oFe]
nFfamFhgoFa\oFe_mF]dpFf\nFjxF`]nFfamFigoFipFhjmF[[lF`\nF^sF\^nFjuFjjmF^sF`goF_d
pF`dpFa\o*(F4F6F/F8FcdpF'F`sFggoF_dpF'F'**F3F'FAFEF.F',LFfdpFayFd^pF_qF[dpF5Fj]
nFayFherF`sFidpFayFa]nFayFa^nFh_lF^fpFjuF^epFayF_epF[imFe_mFg[pFa\nF[sF`epFayFh
jmFhfoFeepF9**F``oF'FenF'F4F6F/F1FjuFh^pFayF`\nFiwF[^nFgtF\_pFcqF'F'**F3F'FAF'F
.FE,JFd^pFcqF[epF`sFjepFayFe[nF[sFhapFayFjapFayF_epF[imFe_mFfxF_fpFayF[\nFiwFhj
mFbcpFdfpFayFgftF`sFhfpFayFjjmFgtFfapFiwFb[nFh_lF]frFjuF\_pF_qFjfpFiwF'F'**F3F(
FAF'F.F',drF^gpF_jlFbgpFggpFhgpF^`lFigpFggpF\hpF]hpF^hpFchpFdhpFehpFfhpF_jlF[ip
F_jlF_ipF]hpF`ipF]hpFaipF]hp*(F4F6F/F8Fd^qF'F`s*(F4F6F/F8FdglF'FjuFbipF]hpFcipF
dipFgipF_jlF\jpF_jlF`jpF_jlFejpF^`lFfjpF_jlFjjpF_jlF^[qF_[qF`[qFa[qFc[qFd[qFe[q
F]hpFf[qF]hpFg[qF]hpFh[qFi[qFegtF`sFj[qF[\qF\\qFchpF]\qF[\qF^\qF[\qF_\qF`\q**F4
F6F/F1F=F9FcdpF'FLFc\qFOFd\qFa\oFe\qFf\qFh\qF`\qFi\qF]hpFehrFjuFj\qFggpF]]qF^`l
F^]qF[`lF_]qF9F`]qF9Fb]qFchpFg]qFh]qFj]qF]hpF[^qFdipF\^qFa\oF]^qFchpFbirFcpFcir
F`sF_^qF^`lF`^qF^`lFa^qFdilFdirFjuFb^qFa[qF'F'**F3F+FAFEF.F',dtF^gpF[^mFh^qF[^m
F^[sFLFdhpF[_qFfhpF[^mF_ipF]hpF\_qF]_qF^_qFdilFbipF]_qFejpFdilF^[qF]_qF`[qFa[qF
__qF]_qF`_qF[^mFd_qFgcmFi_qF^`lFj_qFgcmF^`qFh`nFc`qFgcmFg`qFgcmF[aqF[^mF_aqF[^m
Fg[qF]hpFh[qFcaqF]\qF[^mF^\qF[^mF_\qF]_qFdaqFeaqFfaqF`rFgaqFdclFhaqF]_q**FcboF'
FenF'F4F6F/F1FjuF[bqFi[qF\bqFdclF]bqF]_qF^bqFgcmFchtF`sF_bqF[^mF`bqFdilFh\rFjuF
cbqF]_qFdbqF[^m*(F4F6F/F8F]emF'FjuFibqF[^mF]cqF^cqFe\qF_cqF`cqFacqFbcqFgcmFdcqF
a[qFecqFdoFfcqF[^mFjcqF[^mF^]qF[`lF^dqF9F`]qF5F_dqF]_qF`dqF[^mFbdqF[^mFg]qFgdqF
idqF[^mF^eqF[^mFceqF[^mF[^qFdipF\^qF^sFa\sF`sF_^qFdilFb^qFa[qFjeqF^`l*&F``oF'Fc
dpF'F'Fb\sF`sF[fqF'Fc\sFjuF`fqFh`nFafqF[^mFbfqFgcmFcfqF9F'F'**F3F+FAF'F.FE,jtFg
fqFdilFhfqF[^mF[gqFdclFi]sF`sF]gqF[^mFagqF]_qFbgqF[^mFegqF[^mFjgqF[^mF]hqFh`nFb
hqFgcmFfhqF]_qFghqF]_qFhhqFgcmF]iqFdilF^iqF[^mF`iqF[^mFbiqF]_q*(F4F6F/F8FjhtF'F
juFciqF[^mF\hpF]hpFdhpFehpF`ipF]hpF^_qFgiqFiiqFgcmF^jqF[^mFcjqF[^mFcipFijqF[[rF
fcoF\[rF[^mFejpFa[rFb[rF[^mFg[rF`\qFh[rF[^mF]\rFh`nF`\rF[^mFf[qF]_qFh[qFcaqFb\r
F]]pFc\rFd\rFdaqFe\rFg\rFiuF[bqF]_qF\bqFdclF]bqF]_qF`bqFdilFabqF`sFi\rF]_qFj\rF
[^mF^]rFgcmFc]rF[^mFi]rF^`lFd\qF_qF]cqF^cqFe\qFcaqF`cqFacqFecqFidoFj]rFcpF_dqFi
[qF[^rF9Fg]qF\^rF`^qFa[qFa_sF`sFb_sFju*&Fe]oF'FaftF'F'F`^rF9Fd_sFcpFc^rFh`nFj_s
FjuFi^rFh`nF\_rF[^mF^_rF[^mF`_rF[^mF^itF`sFb_rFgcmFd_rF[^mFi_rF]_qFj_rF[^mF_`rF
[^mF'F'*(FAFYF.F',8Fg]qFh`rFi`rFd[qF^]qF]coF^arFdilF_arFb`mF]arF9FdcrFJFcfqF5Fd
`rFb`mFj`rF[`lF[arF^`lF'F'*(FAFEF.FE,VF[gqFacqFfarF_jlFjarFb`mF`brFa[qFdhpF[_qF
g[rFacqFh[qFabrFb\rFehpFbbrFd[qFc\rFcbrF\bqF`\qFdbrF_jlFfbrFb`mFjbrF_jlF^crFchp
F[arF^`lFi`rFd[qFg]qFabr*$Fj]oF+F'FacrF9F`^rF5FbcrFacqFccrF`\qF\arF[\oF^arFdilF
^drFJF'F'*(FAF'F.FY,*FhcrF_jlFbbrFd[qF`brFa[qFecrF[\oF'F'6$FEF',>*.FAF'F.F'F4F5
F7F9F/F1F:F9F+**F3F'FAF'F.F',(FKF1FGF[\oFCF0F'F'**F3F+FAF'F.F',,F[oFdoF^o#FjilF
YF_oF]_oFaoF5FUF]erF'F'*(FAFEF.F',(F^oFg^oFZFhnFgnFfnF'F'*(FAF'F.FE,4F^_oFcqFZF
hnF[oF]oF_oFfnF^oF]oF\^uF6FgoFdwFhimFcpFiimFLF'F'**F3FEFAF'F.F',HFdq#FhwFarF\rF
iuFgqF`duFaqFjuFjqFcpFdpFhpFd]oF0FfsFh_nFbrFiuFitF_xFdrFiuFjtF6F_pF5Fgs#"#VFarF
jsFcpFfrFiu**FenF'F4F6F/F1F\dpF'F9*&F/F1F_]oF'F`sFdtFh_lF'F'**F3F'FAFEF.F',PFdq
#FdfoFhtFep#Fb[lFarFgqFeyFaqFjuFdpF`_lFd]oFDFfsF_q*(F\dpF'F4F6F/F8F5FbrF`r*.F=F
9F/FRF:F9F4F5F7F5FeasF'FfzFj`oF`sF[yF6F\xF`r*&F/F1F^^oF'FjuFbsF9FgsF[sFjsFLF[qF
`rFh`oFh_nF^xFcqFdtFh_lF_sF`s*.F/FRF=F9F:F9F4F5F7F5,(F[pFYF/F]hmF^]nF'F'FfzF'F'
**F3F'FAF'F.FE,\pFdp#!#`FhtFaqFh]oFdqF`rFgqF`rFjqF^sF\rF`rFbrF`rFdrF^_lFfrF`rFb
uF^sFc\oFiwFf\oFiwFi\oFiwF]sFaxF[]oF[`o*.,*FfuFguF[pFj`qF/"$O#!$O"F'F'F:F9F7F5F
/FbqF4F5F=F5F^sFgyF`r*.,*FfuF'F[pFFF/FewF<F'F'F:F9F7F5F/FbqF4F5F=F5Fcp*.,*FfuFg
uF[pFchlF/Fdfn!$K"F'F'F:F9F7F5F/FbqF4F5F=F5F^sF]]oFf[mF^]oFjuF`]oF`sFa]oFcqFfs#
FYFjoFgsF[fuFjsFXF[vF9F[tF`\oFh]uFD*,FiepF'F4F5F7F9F/F1F:F9F0FizF_xF\[lF]tF[^oF
gtF\^oF_xF`[lFcqFc[lFh_l*&F/F1FhvF'Fju*&F\dpF'F/F1F5*&FiblF'F/F0Fgt*&F\iqF'F/F0
F6F'F'**F3F(FAF'F.F',fpFb`lFfam*(F=F9F/F<F_]oF'FLF`^l#"#tFd]lFbalF]al*.Fe]oF'F:
F9F/F<F7F9F=F9F4F5FDFc^lFdilFeaoF`sFhalFi^lFjal#!%x=F\`lF]blF_boF`bl#!$R$Fd]l**
Fa]qF'FenF'F4F6F/F1F9Fi\l#FEF]qFi]l#"$4$Fd]lF_]lF[imFi_lF]coF[_lF9F`cl#FjilF\^l
FeclF_guFfdlFjaoFgdlF_guF_elFa^l*,F=F9FenF'F4F6F/F<F\dpF'F5FefoF0FaelFgemFfelFa
^lFhelFe]mF]flFialF^flFgemF`flFgemFeflFcblFjflFe]mF^gl#!$T"Fd]lFaglFi^lFcglF0Fe
glFDFfglFcblFiglFgemF]hlFa^lF^hlFbbmF]ilF6FailF^s*&F/F1F^eoF'F`s*&F/F1Fb_lF'Fju
FbilF^`lF'F'**F3F+FAFEF.F',hs*(Fa]qF'F4F6F/F8F5FeamFayFd[pF`s**FenF'F4F6F/F1Fdf
qF'F9F`^lFj`pF^alFaaoFiamF\flF]^l#!$B%Fd]lF_coFe^lFhalFi^lFjal#"$t'F\`lF]blF_bo
F`bl#"$"\Fd]lFe]l#FgflFd]lFi]l#"$P%F\clF_]lFgelFhblFbitF]clF[^mF`clF[imFecl#F8F
]qFiclFeelF_dlFgfnFcdlFfxFfdl#F^qFh]lFgdl#!#ZF\`lFjdlF9F_elFgelFefoFDFaelFeelFf
elFgelF]flFialFjflF\flF^glF_hlFaglFialF]hlFgelF^hlFbbmFahl#FRFj^lFebmFiw*(F=F9F
/F<F^^oF'FcpFailF^sFi_mFdil*&F/F1FcamF'F`sFfbmF6*&FcsF'F\dpF'F'*&Fe]oF'F]`oF'F'
*&F/F1FddoF'FjuF[jlFh_lF`cmF[^mFccmFgcmFicmFeanF^dmFiflFe_pF0FbdmFcalFcdmF]]lFe
dmFDFfdmF\flFhdmFiflF\emF0F^emFh_lFbemF[sFfemFeelFhemFeelFiemFiflFg_pFi^lF\fmF
\flF_hoFfhuF`fmF\flFcfmF\flFffmF]]lFgfmFiflF'F'**F3F+FAF'F.FE,\y*(F=F9F/F<FhvF'
FcpFjhmF^sFgdoFa\oFjdoFfamF]eoFjuFceoFa\oFeeoF_qFbimF[sF\[mFbcoFfeoF`sF`^lFj`pF
balF[sFj[mFgfnFecoFi^lFhalFbjmFjal#!$$))F\clF]blF_boF`bl#FefuF^dlFf_uF0Fi]l#"$@
&F\clF_]lFgelFhblFialF`clF\flFeclF\flFfdlF\flFgdlF\flF_elFa^lFaelFeelFfelFcjmFh
elF\flF]flF]jmF^flFeelF`flFeelFeflFiflFjflF\flF^gl#FiyF_blFfglFiflFiglFeelF]hlF
a^lF^hlF[sFe\mFh`nF[]mF9F`]mFh`nFf]mF]coFh]mFfxF^^mFh`nFc^mFh`nFh^mFh`nF]_mF\fl
F`hlFidsFifoF[[n*&,&Fe_mFbpF`goFEF'F/F0Fgt*&Fa]qF'F/F1F5*&F/F1FgimF'F`sFfjmF[[n
*&F/F1F[[mF'Fju*&F\dpF'F\vF'F'*&Fe]oF'Fe[lF'F'*&FiepF'F_]oF'F'*&,PFb\nF[sF`\nFi
wFggoF^sFg\nF[sF\]nF[imFj]nF[imF\^nF[imFhgoFfamF[^nFiwF`]nFiwFe_mFcpF`goF_qFa]n
FiwFhjmFfxFjjmFh_lFe]nFiwFe[nFh_lFh]nFiwFigoFidoFjgoFidoFf\nF_qF[hoFayFa^nF[sF'
F/F0F6F[`mFialFd`mFialFj`mFialFfho#FFFhcmF_ioFggtFi_nF\flFgioFiflFajoFa^pF^anFg
cmFgjoF_juFijoF[^mF`anFfxFaanF[^mF`[pFayFianFfxFjanF[^mF]bpF0*,F:F9,,F[p"%0TF/!
%Gc"%?GF'Ffu!%)H"Fa`mFj\mF'F4F0F/FIF7F5Fial*,,*FfuFjpF[pFidlF/F\\sFdhqF'F'F:F9F
7F5F/FIF4F5Ffam*,F:F9,*FfuFasF[pFb]rF/FbepFa]lF'F'F4F5F/FIF7F5Fhp*,F:F9,,F[p"%v
UF/!%6f"%qHF'Ffu!%J8Fa`mFj\mF'F4F0F/FIF7F5FialF^bnFdboFabnFcbl*,,*FfuFapF[pFaeu
F/"##*Fg]nF'F'F:F9F7F5F4F5F/FIF_qFbbnF[sFhbnF\flF]cnF\flFbcnF\flFdcnF]]l*,F\iqF
'F4F5F7F9F/F1F:F9FD*,F:F9,,F[p"$D)F/!%76"$S&F'Ffu!$i#Fa`mFbyF'F4F0F/FIF7F5Fh_l*
,,*FfuFbyF[pFgbqF/"$f#Fg_qF'F'F:F9F7F5F/FIF4F5Fh_lFfcnFiflFicnFeanFjcnFifl*,Fa`
rF'F4F5F7F9F/F1F:F9F0F]dnFh`nF_dnF\flFddnFh_lFjdnF\flF]enFialFaenF_jl*,F:F9,,F[
p"$b"F/!$*>FhflF'Fa`mFasFfuFe]sF'F/FIF4F0F7F5FhpFghnF[sFhhnF[sFihnFiuFjhnF[sF\i
nFgt**FenF'F4F6F/F1Fa^rF'F9F]inFiwF^inFfxF_inFiwF'F'*(FAFYF.F',>FbdlFedlFi]lFge
oFb\mF]coF_coFdilF]^l#FEF``pFcdlFa^lF`\pFb`m*(FdfqF'F4F6F/F8F5Fe_pFDF\dmF9F\apF
`sFdgmFi^lFg[mF[ilFg_pFialF'F'*(FAFEF.FE,br*(F4F6F/F8Fa^rF'F5F\[mFbcoFbalFbbmFj
[mFialFecoF[^mFiamFi^lF]^lF]alFc^lF^`lFhalF^[mFjalFgfoF`blF\flFi]l#F^rFa[mFi_lF
i^lFcdlFa^lFfdlF^_sF]flF[`lF]hlF_alFf]mFialFg]mFedlFh]mFa^lFi]mF^sFj]mF]]pF`hlF
fxFbilF[ilFi`uF6*&,&Fe_mFIFd^pFEF'F/F0Ff[n*&,&Fe_mFabmFc_pF1F'F/F0Ff[n*&FdfqF'F
/F1F5*&FdepF'F^^oF'F'Fc\pF0FbdmF]alFfemF]dlFhemF]dlFcfmFi^lF[ioFb`mFf_nF9Fi_nFj
hlFj_nFi^lF\joF`joF\[pFb`mF`anF[sF]bpFDFbbnF]dlFhenFe]mFbfnFdhlF]gnFe]mFignFi^l
Fi_pFbjmFj_pFjhlF[`pFb`mF^`pFjhlFa`pFb`mFghnF[sFihnF[sF\inFiwFc`pFjuFd`pFiwFe`p
F[sFf`pF`sF'F'*(FAF'F.FY,joFbalFbbmFj[mFialFecoF[^mFjalF]alF]blFbjmF`bl#FiyFh]l
Fi]lFbbmFfdlF^_sF]flF`[mF^hlF]alFh]mFa^lF`hlFfxFaauF6*&FdepF'FhvF'F'*&Fa^rF'F/F
1F5F]ioF0Fi_nFi^lF^bnFedlFabnF^sFbbnFb`mFbcnFe]mF]dnFi^lFjdnFe]mF]enFb`mFaenF]]
pF^]pFb`mFbjnFi^lFhjnF9Fi_pFbjmF_bpFh_lF`bpFgtFabpF[sF_[oF^sFcbpFjuFdbpFiwFfbpF
iwFgbpF[sFhbpFiwFibpFiwF'F'6$F(F(,RF6F'*(F3F+F4F6F/F8F[\o**FAF+FenF'F4F6F/F1FJ*
*F3FEF4F6F/F1F=F9F5*(F3F'FAF+,&FdsF'Ff]oF9F'F'*&F3F(,(F[wFhnF\wFccpFcwFbcpF'F'*
(F3F+FAF+,.F\\lF[[lFjblFbetF[wF]_oF]elFcetFgjlFejlF]_lF[[lF'F'*(F3F+F.F+,&Ff\lF
[[lF\wFccpF'F'*&FAF(FeetF'F'*(FAF+F.F+FgetF'F'*&F3FY,(Fe_mFcetFf_mFjxFd_mFa\oF'
F'*(F3FEFAF+,>Fb^nFayFjgoF_ftF]^nFayF[hoFjx*(F4F6F/F8F]epF'F`sFaerFjuFe_m#FjjqF
gxFigoF_ftFhjmFj^oF_^nFayFeepF'FjjmFh]oF`goF^ftF`dpFidoF'F'*(F3FEF.F+,,F\jnFido
FhjmFf[mF_jnFayFf_mFjxFe_mF`\oF'F'*(F3F'FAF(,8F^epFa\oFhjmFXF\_pF`\oFfdpFfamFe_
mFidsF_epFfxF`epFfamFidpFfamFeepF6FjauF`sF\epFjuF'F'**F3F'FAF+F.F+,HFd^pFfxF[ep
FjuFjepFfamFe[nFayFhapFa\oF^fpF`sFjapFa\oF_epFfxFe_mFh]oF_fpFfamF[\nFfamFhjmFej
lFdfpFfamFjjmF[sFb[nFiwFifpFjuF]frF`sF\_pFfxFjfpFa\oF'F'*&F3Fas,6Fe\q#Fd`oFh]lF
dfrFd[qF^]qF[clF\grFa[qFg]q#"#**Fb^lFgfrF_[qFifrFchpF_]qF'FjfrFjuFhirF`sF'F'*(F
3F(FAF+,jnFbgpFfgtFigpFfgtF_grF^cqF]iqF_gtF`grF[^mFdgrF[^mF\hpFdgtF^hpFggtFhgrF
[^mF]hrFju*(F4F6F/F8FjaqF'F`sFbhrF0Fd\qF_ftFe\qF`_sFh\qFdclFi\qF^cqFehrF`sFfhrF
cpFj\qFfgtF\]qFju**F4F6F/F1F=F9F]epF'FLF]]qFa[rFghrF[^mFjhrF[^mF]irFgcmF^]qFbit
F_]qF6F^dqF'Fb]qFgcmFg]q#!$>(Fh]lFj]qF^cqF'F'*(F3F(F.F+,JFjfrFjuFhirF`sFgfrF_[q
Fe\qFiitFdfrFd[qFiirF[^mF[[rFehpF_jrFgcmFdhpFehpF[^rF'Fd`sF`sFefrFa[rFajrFgcmFe
jrF^cqFc\rFd\rFfjrFa[qFg]q#F`yF`qFg[rF`\qFhjrFgcmF[[sFjuF'F'*(F3F+FAF(,jnF\_qFd
[qFgaqF_itFhaqFd[qFiaqFjuFi[sF_jlFdbuF`sF[bqF`itF]cqFd[qFe\qFh`rF`cqF`\qFbcqFch
pFdcqFgiqFecqFcitFfcqF_jlFjcqF_jlFj`rF[clF^dqF6FbdqFchpFg]q#F^]nFfyF`\sFa[qFidq
F_jlF^eqF_jlFceqF_jlFieqF`sFa\sFju*&F``oF'F]epF'F'*$F`^oF+F'F`fqFchpF]arF'FafqF
ggpFbfqFggpF'F'**F3F+FAF+F.F+,\tFhgpFa[rFgfqFa[qFc]sF_jlFhfqFchpFg]sF_jlF[gqF`
\qF\gqF`sFi]sFjuFj]sF_jlFagqFd[qFegqFchpFjgqFchpFbhqFggpF_grF^cqF\hpF^cqFdhpFe]
mF`ipFd[qF^_qFa[qFiiqFchpF^jqF_jlFcjqF_jlFcipFbhtF[[rF[_qF\[rF_jlFejpF_gtFb[rF_
jlFg[rFdclFh[rF_jlFf[qFd[qFh[qFabrFb\rFehpFc\rFgemFdaqFbhtFg\rFh_nFgaqF`\qF[bqF
d[qF\bqF]\sF]bqFd[qF`bqFa[qFh\rF`sFabqFjuFi\rFd[qFj\rFchpF^]rFggpFc]rFchp*(F4F6
F/F8F_fqF'FjuF__sF`sFi]rFa[rFd\qFfxF]cqFd[qFe\qFabrF`cqF`\qFecqFip*.F`^oF'F4F5F
7FDF/FFF:F9F=F5F9F_dqFd[qF[^rF6Fg]q#FdbmF`bnF`^qFa[qFghtF'FacrF'Fd_sFLFb^rFjuFc
^rFchpFe_sF_jlFg_sF_jlFj_sF`sFh^rFcpFi^rFchpF\_rFggpF[`sF_jlF^_rFggpF`_rFggpF'F
'*(F3F+F.F(,.F``sF_jlFejrF^cqFg]qFhfrFfjrFa[qFd`sF`sF[[sFjuF'F'*&FAFas,2Fg]qFfi
tFi`rF^cqFj`rFbitF[arFa[rFd`rF[^mF]arF6FdcrF`sF\arFjuF'F'*(FAF(F.F+,RFb\rF[_qF^
arFa[qFh[qFiitF\bqFacqF[gqF`\qFccrFacqFdhpFehpF^crFgcmFjbrF[^mFdbrFgcmF\arFjuF`
brFa[rFacrF6Fi`rF^cqFbcrF`\qFbbrF^cqFc\rFd\rFdcrF`sFfbrF[^mFjitF'Fg]qFiitF^drF`
sFecrFjuFg[rF`\qF'F'*(FAF+F.F(F\jtF'F'6$F'FE,>FdcuF+FecuF'FgcuF'FjcuF'*(FAF'F.F
E,4FgoFdwF_oFfnFhimFcpF[oF]oFiimFLF^oF]oFZFhnFd_oF'F^_oFcqF'F'**F3FEFAF'F.F',HF
dqF`duF\rFiuFgqF`duFaqFjuFjqFcpF^uFjuFdpFhpFg]uFDFfsFh_nFbrFiuFitF_xFdrFiu*&F/F
0FdglF'F'F_pF5FgsFaduFjsFcpFfrFiuFcduF9FdtFh_lF'F'**F3F'FAFEF.F',PFdqFgduFepFhd
uFgqFeyFaqFjuFdpF`_lFg]uF0FfsF_q*&F/F0F]emF'F'FhxF`sFiduF5FbrF`rFe^uFjuFjduFfzF
\xF`rFbsF9FgsF[sFjsFLF[qF`rFh`oFh_nF^xFcqFdtFh_lF_sF`sF\euFfzF'F'**F3F'FAF'F.FE
,\pFdpF`euFaqFh]oFdqF`rFgqF`rFjqF^sF\rF`rFbrF`rFdrF^_lFfrF`rFbuF^sFc\oFiwFf\oFi
wFi\oFiwF]sFaxF[]oF[`oFbeuF^sFgyF`rFfeuFcpFheuF^sF]]oFf[mFa]oFcqFe]uF`sFf]uFjuF
fsF[fuFgsF[fuFjsFXF[vF9F[tF`\oFi]oF0*,F4F5F7F9F/F1F:F9FaftF'FDFizF_xF\[lF]tF[^o
FgtF\^oF_xF`[lFcqFc[lFh_lF^fuF5F_fuFgt*&F/F0FjhtF'F'Fd[lF`sF'F'**F3F(FAF'F.F',f
pFb`lFfamF`^lFdfuFbalF]al*.F:F9F/F<F7F9F=F9F4F5FcdpF'F0Fc^lFdilF\_uFjuFhalFi^lF
jalFgfuF]blF_boF`blFifuF[guF9Fi\lF\guFi]lF]guF_]lF[imFi_lF]coF[_lF9F`clF_guFecl
F_guFfdlFjaoFgdlF_guF_elFa^lF`guF5FaelFgemFfelFa^lFhelFe]mF]flFialF^flFgemF`flF
gemFeflFcblFjflFe]mF^glFaguFaglFi^lFcglF0FeglFDFfglFcblFiglFgemF]hlFa^lF^hlFbbm
Fg_uFDF\ilFcpFailF^sFbilF^`l*&F/F0,&F`ilF^sF_ilFfamF'F'FeilF`sFgilFjuF'F'**F3F+
FAFEF.F',hsFgguF5FeamFayFhamFLFa`uFjuFhguF9F`^lFj`pF^alFaaoFiamF\flF]^lFiguF_co
Fe^lFhalFi^lFjalF[huF]blF_boF`blF]huFe]lF_huFi]lF`huF_]lFgelFhblFbitF]clF[^mF`c
lF[imFeclFbhuFiclFeelF_dlFgfnFcdlFfxFfdlFchuFgdlFdhuFjdlF9F_elFgelFaelFeelFfelF
gelF]flFialFjflF\flF^glF_hlFaglFialF]hlFgelF^hlFbbmFg_uF0FahlFfhuFebmFiwFailF^s
Fi_mFdilFihuF'*&FctF'FcdpF'F'FjbmF`sF]cmFju*&F/F0,(FhbmFayF`ilF^sFibmFiwF'F'F[j
lFh_lF`cmF[^mFccmFgcmFicmFeanFc\pFDF^dmFiflFbdmFcalFcdmF]]lFedmFDFfdmF\flFhdmFi
flF\emF0F^emFh_lFbemF[sFfemFeelFhemFeelFiemFiflFg_pFi^lF\fmF\flF_hoFfhuF`fmF\fl
FcfmF\flFffmF]]lFgfmFiflF'F'**F3F+FAF'F.FE,\yFjhmF^sFgdoFa\oFjdoFfamFceoFa\oFee
oF_qFbimF[sF\[mFbcoF`^lFj`pFbalF[sFj[mFgfnFecoFi^lFjimFLFhalFbjmFjalF_iuF]blF_b
oF`blFaiuF\foFDFi]lFbiuF_]lFgelFhblFialF`clF\flFeclF\flFfdlF\flFgdlF\flF_elFa^l
FaelFeelFfelFcjmFhelF\flF]flF]jmF^flFeelF`flFeelFeflFiflFjflF\flF^glFdiuFfglFif
lFiglFeelF]hlFa^lF^hlF[sFe\mFh`nF[]mF9F`]mFh`nFf]mF]coFh]mFfxF^^mFh`nFc^mFh`nFh
^mFh`nF]_mF\flF`hlFidsFifoF[[nFeiuFgtFgiuF5FfjmF[[nFjiuF'*&FhvF'FcdpF'F'F\[nF`s
F^[nFju*&F_uF'FaftF'F'*&F/F0,PFb\nFiwF`\nF[sFggoF_qFg\nFiwF\]nFfxFj]nFfxF\^nFfx
FhgoFayF[^nF[sF`]nF[sFe_mFLF`goF^sFa]nF[sFhjmF[imFjjmFgtFe]nF[sFe[nFgtFh]nF[sFi
goFa\oFjgoFa\oFf\nF^sF[hoFfamFa^nFiwF'F'F[`mFialFd`mFialFj`mFialFfhoF_juF]ioFDF
_ioFggtFi_nF\flFgioFiflFajoFa^pF^anFgcmFgjoF_juFijoF[^mF`anFfxFaanF[^mF`[pFayFi
anFfxFjanF[^mF`juFialFfjuFfamFhjuFhpFjjuFialF^bnFdboFabnFcblF`[vF_qFbbnF[sFhbnF
\flF]cnF\flFbcnF\flFdcnF]]lFd[vFh_lFj[vFh_lFfcnFiflFicnFeanFjcnFiflF]dnFh`nF_dn
F\flFddnFh_lFjdnF\flF]enFialFaenF_jlF^\vFhp*,F4F5F7F9F/F1F:F9FjhtF'F0*,F4F5F7F9
F/F1F:F9FigtF'FDFghnF[sFhhnF[sFihnFiuFjhnF[sF]`uF`sF^`uFjuF\inFgtFb\vF9F]inFiwF
^inFfxF_inFiwF'F'*(FAFYF.F',>FdgmFi^lFbdlFedlFi]lFgeoF]^lFe\vFcdlFa^lFg[mF[ilFg
_pFialF\dmF9Fc`pFjuFf\vF5Fc\pF0Fb\mF]coF_coFdilF`\pFb`mF'F'*(FAFEF.FE,brFi\vF5F
\[mFbcoFbalFbbmFj[mFialFecoF[^mFiamFi^lF]^lF]alFc^lF^`lFhalF^[mFjalFgfoF`blF\fl
Fi]lFj\vFi_lFi^lFcdlFa^lFfdlF^_sF]flF[`lF]hlF_alFf]mFialFg]mFedlFh]mFa^lFi]mF^s
Fj]mF]]pF`hlFfxFbilF[ilFe^pF'F[]vFf[nF]]vFf[nF_]vF5*&FixF'Fj]oF'F'Fe_pFDFbdmF]a
lFfemF]dlFhemF]dlFcfmFi^lF[ioFb`mF]ioF0Ff_nF9Fi_nFjhlFj_nFi^lF\joF`joF\[pFb`mF`
anF[sFbbnF]dlFhenFe]mFbfnFdhlF]gnFe]mFignFi^lFi_pFbjmFj_pFjhlF[`pFb`mF^`pFjhlFa
`pFb`mFghnF[sFihnF[sF\inFiwF\apF`sFd`pFiwFe`pF[sFcbpFjuF'F'*(FAF'F.FY,joFbalFbb
mFj[mFialFecoF[^mFjalF]alF]blFbjmF`blFc]vFi]lFbbmFfdlF^_sF]flF`[mF^hlF]alFh]mFa
^lF`hlFfxFaapF'Fe]vF5*&Fe[lF'Fj]oF'F'Fi_nFi^lF]bpFDF^bnFedlFabnF^sFbbnFb`mFbcnF
e]mF]dnFi^lFjdnFe]mF]enFb`mFaenF]]pF^]pFb`mFbjnFi^lFhjnF9Fi_pFbjmF_bpFh_lF`bpFg
tFabpF[sF_[oF^sFf`pF`sFdbpFiwFfbpFiwFgbpF[sFhbpFiwFibpFiwF'F'6$F+FE,DF_jtFJF`jt
F9FajtF'FcjtF'FejtF'FgjtF'FijtF'F[[uF'**F3F+FAF'F.F+,ZFe_mFcdsFhjmFbcpF`goFb]oF
jgoFjxF[hoFidoFigoFjxFjjmF_qFh]nFayFe[nF_qFa]nFayFa^nF[sFe]nFayF`]nFayF`\nFcgsF
ggoF_dpFb\nFfamFg\nFfamF\]nFh]oFa\nFh_lF[^nFiwF[dpF5Fj]nFh]oFhgoFa\oF\^nFh]oFf
\nFipFgauFjuF`ftFju*&F_tF'F/F1FjuF'F'*(FAFEF.F+,FFh^pFayFe_mF[[lFd^pFh_lFa]nFay
Fc_pFgtFj]nFiwF`\nFiwFjerF[sFa\nF[sF^frFjuFherF`sF[^nFgtF[_pFiwFa^nFh_lFhjmF[im
Fg^pF[sF]_pF[sF\_pFiwF'F'*(FAF'F.F(,FFhfpFiwFe_mF]oFe[nFiwFfapFfamF[\nF[sF_frF[
sFd^pFh_lF`frF[sFc_pFgtFierF`sF]frF`sFcapFiwFg^pF[sFhapF[sFjapF[sFb[nFgtF\_pFiw
FjjmFh_lF'F'*(F3FYFAF',,FahsFgcmFd_tF^cqFe_tFhfrF_dtFa[rF[gtFJF'F'*(F3FEFAFE,4F
\isFchpFe_tFh[uF]isFchpF^jsFchpF_dtFgiqF_jsF_jlFd_tF^cqFjftF[\oFagtFJF'F'**F3FE
FAF'F.F+,fsF^gpF[^mFbgpFggtFhgpFdilFigpFggtF\hpF]_qF^hpFgcmFdhpF[_qFfhpF[^mF[ip
F[^mFf]tFchpFjgtFcpF[^tF_jlF_ipF]_qF`ipF]_q*(F_tF'F=F9F/F<FcpFaipF]hpF_buFjuF`b
uF`sFbipF]_qFcipFeaqFgipF[^mF\jpF[^mF`jpF[^mF_^tF_jlFd^tF_jlFi^tF^_sFejpFdilF^d
tFd[qF\_tF_jlFfjpF[^mFjjpF[^mF^[qFhfrF`[qF_gtFc[qF^cqFe[qF]hpFf[qF]_qFg[qFcaqFh
[qFcaqFegtF`sFj[qF^_sF\\qFchpF]\qF^_sF^\qF^_sF_\qF`\qFabuFcpFahrF^`lFfaqF^sFc\q
F\alFd\qFidoFe\qF]\uFh\qFacqFi\qF]_qFj\qFggtF\]qFjuFj`rF[`lF[grF9F`]qF5Fg]qF^\u
Fj]qF]_qF[^qF`\uF\^qF`rF]^qFgcmF`^qFdilFb^qFa[rFe^qF`sFhgtFjuF[atFdilF`jsF^`l*&
,6Fh[lF_xFi[lFgtFj[lFcqF[\lFaxFjblFgtF[wFcqFcjlF_xFdjlFejlFfjlFh_lFgjlFcqF'F/F1
FjuF'F'*(F3F'FAFY,*F_htF[^mFe_tFd[qF_dtFa[rF`gtF[\oF'F'**F3F'FAFEF.F+,htF^gpF[^
mFh^qF[^mF^[sFLF_btFa^pF[gqFacqFabtF[^mFdbtF[^mFebtF[^mFfbtF[^mF_[sF_jlFdhpF[_q
FfhpF[^mF_ipFi[qF\_qF]hpF^_qFdilFbipF]_qFejpFdilF^dtFd[qF^[qF]hpF`[qFa[qF__qF]_
qF`_qF_jlFd_qFgcmFi_qFdilFj_qFgcmF^`qFb`mFc`qFgcmFg`qFgcmF[aqF[^mF_aqF_jlFg[qF]
hpFh[qFcaqF]\qF[^mF^\qF[^mF_\qF]_qFdaqFeaqFfaqF`rFgaqFa^pFhaqF]hpF[bqF]hpF\bqF^
_sF]bqF]_qF^bqFgcmFchtF`sF_bqF_jlF`bqF^`lFcbqF]hpFdbqF_jlFebuF`sFibqF[^mFc\qFLF
jbtF[^mFe\qFi[qFecqFiuF^]qF]coF_dqF]_qF`dqF_jlFbdqF_jlFg]qFg\uF[^qFi\uF\^qF^sFa
\sFjuFb^qFgiqFbhsFdilF`jsF^`lFc\sFjuFihtF`s*&FhzF'FcdpF'F'*&,,Fh[lFcqFi[lF[sFj[
lFbcpF[\lFbcpF\\lFcqF'F/F1F`sFeirF9FcfqF5Fe\sF_qFbcrFa^pFg\sF_jlF[]sF_jlF^]sFb`
m**,6Fj[lFcqF[\lF`_lF\\lF_xFi[lFgtF[wF_xFjblFh_lFcjlFcqFdjlFf[mFfjlFgtFgjlF_xF'
FenF'F4F6F/F1FjuFccrFa^pF'F'**F3F'FAF'F.F(,fsFgfqF^`lFhfqF_jlF[gqFdclFi]sFjuF]g
qFchpFagqF]hpFbgqFchpFegqF_jlFjgqF_jlF]hqF_jlFbhqFchpFfhqF]hpFghqF]hpFhhqFgcmF]
iqF^`lF^iqF_jlF`iqF_jlFbiqF]_qFibuF`sFciqF_jlFjctF[^mF\hpF]_qFd^sFh`nFdhpF[_qF`
ipF]_qF^_qFa[rFcipF]_sF[[rF]]pFejpFa[qFg[rFcjoF]\rF_jlF`\rFchpFf[qF]hpFh[qFi[qF
b\rFfcoFc\rF^[mFdaqFijqFg\rF`rF[bqF]hpF\bqF`\qF]bqF]hpFi\rF]hpFj\rF_jlF^]rFchpF
c]rF_jlFc\qFLFi]rFdilFd\qF^sFe\qFi[qFdcqFdilFecqFiuF_dqF]_qFg]qF^]uF`^qFa[rFb_s
FjuF^^rF`s*&F_tF'FaftF'F'F^jrF9F`^rF5Fe\sF_qFd_sFLFb^rFjuFb_rFgcmFd_rFh`nFi_rF]
_qFj_rF[^mF_`rF_jlFccrF`\q**FidvF'FenF'F4F6F/F1F`sF'F'6$F+F(,DFadrFJFbdrF9FcdrF
'FedrF'FgdrF'FidrF'F[erF'**F3F+FAF+F.F',ZFe_mF`vFhjmF`erF`goF_dpFb^nFfamFjgoFip
F]^nFfamF[hoFa\oFigoFipF_^nFfamFjjmFidoFh]nFayFe[nFh_lFa]nFayFa^nF_qFe]nFayF`]n
FayF`\nF_qFggoFb]oF[\nFgtFb[nF[sFeepF5Fj]nF`sFhgoFidoF\^nF`sFi^vFjuFf\nFip*(Fhz
F'F4F6F/F8FjuFbdpFjuF'F'FderF'*(FAF(F.F',FFh^pFfamFe_mFbcpFd^pFgtFa]nFfamFc_pFh
_lFj]nF[sF`\nF[sFjerFiwFa\nFiwF^frF`sFcepF`sF[^nFh_lFhjmFfxFg^pFiwFa^nFgtF[_pF[
sF\_pF[sF]_pFiwF'F'*(FAF+F.FE,FFhfpF[sFe_mFdoFe[nF[sFfapFayF[\nFiwF_frFiwFd^pFg
tF`frFiwFc_pFh_lFierFjuFifpF`sFcapF[sFg^pFiwFb[nFh_lF\_pF[sFhapFiwFjapFiwFjjmFg
tF'F'*(F3FYF.F',:FifrFgcmFe\qFcfrFdfrF^cqFg]qFffrFgfrFhfrF^]qF]coF\grFdilF[grF9
FhirFJF_]qF5Fj`rF[`lFefrF^`lF'F'**F3FEFAF+F.F',jsF^gpF[^mFbgpFggpFhgpF^`lFigpFg
gpF_grFd[qF]iqFa[rF`grF_jlFdgrF_jlF\hpFcaqF^hpFchpFhgrF_jlFh_vFjuFdhpF[_qFfhpF[
^mF[ipF[^m*(FbevF'F4F6F/F8FjuF_ipF]_qF`ipF]_qFaipF]_qF`buF`sFbipF]_qFcipFeaqFfi
pFcpFgipF[^mF\jpF[^mF`jpF[^mFejpFdilFfjpF[^mFjjpF[^mF^[qFhfrF`[qFa[rFc[qF^cqFe[
qF]_qFf[qF]_qFg[qF]_qFh[qFcaqFegtFjuFj[qF_hrF\\qFgcmF]\qF_hrF^\qF_hrF_\qFacqFg
\rF_qFahrFdil**FhzF'F4F6F/F1F=F9FcpFbhrF\alFd\qFezFe\qFchrFh\qF`\qFi\qF]hpFj\qF
ggpF\]qF`sFi_vFcpFghrF_jlFjhrF_jlF]irFchpFj`rF]coF[grF5F^dqF5Fg]qF`irFj]qF]hpF[
^qFeaqF\^qFidoF]^qFgcmF_^qFdilF`^qFdilFa^qF^`lFb^qFa[rFc^qFjuFe^qF`sFeirF9F'F'*
(F3FEF.FE,JFjfrF[\oFgfrFhfrFe\qFabrFdfrF^cqFiirF_jlF^jrF9F[[rF[_qF_jrFchpF\grFd
ilFdhpF[_qF[^rF5Fd`sFJFefrF^`lFajrFchpFejrFd[qFc\rF^[mFfjrFa[rFg]qFgjrFg[rFcjoF
hjrFchpF'F'**F3F'FAF(F.F',hsF^gpF_jlFh^qF_jlF_[sF[^mFc[sFh`nFdhpFehpFfhpF_jlF_i
pF]_qF\_qF]_qF^_qF^`lFbipF]hpFejpF^`lF^[qF]hpF`[qFa[rF__qF]hpF`_qF[^mFd_qFchpFj
_qFchpF^`qFh`nFc`qFchpFg`qFchpF[aqF_jlF_aqF_jlFg[qF]_qFh[qFi[qF]\qF_jlF^\qF_jlF
_\qF]hpFdaqFdipFfaqFiuFgaqFacqFhaqF]_qFi[sFh`nF[bqF]_qF\bqF]\sF]bqF]hpF^bqFchpF
chtFjuF_bqF_jlF`bqFdilFcbqF]hpFdbqF_jlFebuF`sFibqF_jlFbhrFLFe\qFcaqFecqF`rFj`rF
]coF_dqF]hpF`dqF_jlFbdqF[^mFg]qF^\sF`\sFdilFheqFLFieqFjuF[^qFeaqF\^qF_qF_^qF^`l
Fb^qFa[rFjeqFdilF\fqFjuF^fqF`s*&FhzF'F]epF'F'FeirF5F]arF5Fe\sF^sFbcrFacqFg\sF[^
mF[]sF[^mF^]sFh`nFaevF`sF'F'**F3F'FAF+F.FE,^uFhgpF^`lFgfqFdilFc]sF[^mFhfqF[^mFg
]sF[^mF[gqF`\qF\gqFjuFj]sF[^mF]gqFgcmFagqF]_qFbgqFgcmFegqF[^mFjgqF[^mF]hqF[^mFb
hqFgcmF\^sFh`n*(F`evF'F4F6F/F8F`sF^^sFh`nFa^sFh`nFfhqF]hpF_grFd[qFghqF]hpFhhqFc
hpF^iqF_jlF`iqF_jlFbiqF]hpFciqF_jlF\hpF]hpFd^sFb`mFdhpFehpF`ipFi[qF^_qFa[qFcipF
j^sF[[rFfcoFejpFa[rFg[rF\_sF]\rF[^mF`\rFgcmFf[qF]_qFh[qFcaqFb\rF]]pFc\rFbcoFdaq
F]_sFg\rFiuFgaqF^_sF[bqF]_qF\bqFa^pF]bqF]_qFi\rF]_qFj\rF[^mF^]rFgcmFc]rF[^mFbhr
FLFf`vF`sFi]rF^`lFd\qF_qFe\qFcaqFdcqF^`lFecqF`rF_dqF]hpFg]qF`_sF`^qFgiqF]^rFjuF
^^rF`s*&F_tF'FcdpF'F'F^jrF5FacrF5Fe\sF^sFb^rF`sFe_sFh`nFg_sFh`nFh^rFLF[`sFh`nFb
_rFchpFd_rFb`mFi_rF]hpFj_rF_jlF_`rF_jlFbcrF^_sFccrF^_sFfevFjuF'F'*(F3F'F.FY,,F`
`sF[^mFejrFd[qFg]qF_[qFfjrFa[rF[[sF[\oF'F'6$F+F',JF-F'F2F8F;F>F@F'FMF'FSF'FinF'
FeoF'F]pF'**F3F+FAF+F.F',TF_pFhpFdpFipF[qF_qFaqFcqFdqFfqFgqFfqFjqF_qF\rF`rFbrF`
rFdrF`rFfrF`rFgrF[sF]sF^sF_sF`sFbsF5FfsFhpFgsFhsFjsF_qF[tF]tFgzF0F\`oFjuFdtFgtF
itFcqFdduFjuFfavF6F'F'*(F3F+F.FE,DFbuFiuFdqFjuF[vF5FepF`vFgqFjuFbvFiuFdpFfvFb^u
F6Fc\lFjuFivFgtF]wFiuF_pFhpF[tFdwFgsFOFjsFdwFfwFcqF_sFiwF'F'*(FAF(F.F',HF\xFiuF
epFjxFjsF^sFbrFiuF]sF_qFdqF[sFgsFiwF^yFayFiavF6FgzFDF[euF`sFfsF^sF^xF_xFdtFgtF`
xF_qF_sF_xF[tFaxFbxFfxFjqF]tF'F'*(FAF+F.FE,VFdqF`rFjqF]tFbrF`rFdrFeyF]sF_qF\xF`
rFgyF[sFjyFayF\zFfxF]zFfxFazF_qFepFaxF_sF^sFfsFezFgsFfzFjsF^sF[tFaxF^tF0FizF[[l
F\[lF[[lF][lF_xF]^oF`sF`[lF_xFc[lFiwF]fuF`s*&F`evF'F/F0F6F'F'*&F.FY,0FgyF`rFgsF
_\lFepF`rFh^uF6FgvF`sF`\lF_xFb\lFgtF'F'*(F3FYF.F',>F_]lFc]lFe]lFf]lFi_lF[`lF]`l
F^`lFi]lFj]lF]^lF^^lF`^lFa^lFi\lF]]lFd_lF9Fc\mF0F[_lF5Fh[mFjuFc^lFe^lFg^lFi^lF'
F'**F3FEFAF+F.F',drFb`lFayFcfuFcpFi`lF5Fj`lF9F`^lF]alF^alF_alFaalF\alFbalFcal*.
FhzF'F:F9F/F<F7F9F=F9F4F5FDF]^lFealF[boFcpFhalFialFjalF[blF]blF^blF`blFablFi\lF
cblFe]lFdblFi]lFfblFc\mFDFg^lFialFhblF[clF]clFgtF`clFdclFeclFdclFiclF]dlF_dlFad
lFbdlFa^lFcdlFedlFfdlFdoFgdlFdclFjdlF5F_elFa^lFaelFeelFfelFgelFhelF\flF]flFi^lF
^flFeelF`flFeelFeflFiflFjflF\flF^glF_glFaglFi^lFcglFDFeglF0FfglFiflFiglFeelF]hl
FgelF^hlF_hlF`hlFcq*,FbevF'F4F5F7F9F/F1F:F9F0FahlFdhlFehlFjhlF]`lF[ilFgboFjuFai
lF_qFcguFjuFdguF`sFbilFdilFabvF6F[jlF_jlF'F'*(F3FEF.FE,hpFdinFjuF\[mF^[mF_[mF`[
mFb[mFayFeinFcpFd[mF9Fg[mFdilF`^lF]alFi[mF\alFj[mF]alF]^lF[\mFhalF[`lFjalF]\mF`
blF_\mFi\lFcblFe]lF`\mFi]lFf[mFf_lFDFb\mFialF`clFd\mFeclFd\mFgdlFd\mFfelF_alF]f
lF^[mF^glFf]lFe\mFi^lF[]mF5F`]mFe]mFf]mFi^lFg]mFa^lFh]mFedlFi]mFialFj]mF[^mF^^m
Fe]mFc^mFi^lFh^mFi^lF]_mFe]mFhinF0Fa_lF`sFb_uF6Fg_mFgtFi_mF[ilFj_mF5F[`mFb`mFd`
mFb`mFj`mFb`mF'F'**F3F'FAF(F.F',\sFc[pFjuFeamFfamFgamF5Fg[mF^`lFaalFLFiamFe]mF]
^lFjamFhalFialFjalF\bmF]blF^blF`blF^bmFe]lFcalFb\mF[`lFeclFe]mFbdlFfxFfdlF`bmFg
dlFe]mF_elFgelFaelFjhlFfelFa^lF]flFi^lFjflFb`mF^glFbbmFaglFialF]hlFa^lF^hlF_hlF
`hlFcbmFchvFDFebmF[sFghuFLFailF_qFi_mF^`lFhhuFjuF[iuF`sFfbvF6*&FhzF'F]`oF'F'F`c
mF[^mFccmFgcmFicmFgcmF\dmF5F^dmFiflFbdmF]alFcdmFddmFedmF0FfdmFb`mFhdmF_jlF\emFD
F^emFh_lFbemF[sFfemFgemFhemFgemFiemFcblF\fmFb`mF`fmFe]mFcfmFe]mFffmFddmFgfmFcbl
FjfmFgtF_gmFi^lFdgmF\flFhgmF[sF[hmF]dlF^hmFi^lFbhmFi^lF'F'**F3F'FAF+F.FE,\yF^iu
FLFbdoFjuFjhmF[imFcdoF`sF\imF5F]imF[sF_imF[sFbeoFLFbimFayF\[mF^[mFaalFLFi[mFLF]
^lF[jmFhalF]jmFjalF^jmF]blF^blF`blF_jmFe]lFajmFhblFi^lFeclF\flFbdlFa^lFfdlF`bmF
gdlF\flF_elFgelFaelFeelFfelFa^lF]flFbjmFjflF\flF^glFajmF]hlFcjmF^hlFiwFf]mF[`lF
g]mFfxFi]mFejmFj]mF_jlFhinFDF`hlFcbmFhiuFjuFfjmF[[nFiiuF`sF`[nF[[nFc[nFf[nFh[nF
5*&,PF`\nFh_lFa\nFgtFb\nFiwFf\nFfxFg\nFiwFhjmFfxFb[nFiwF\]nFfxF`]nFfamFa]nFfamF
e]nFfamFh]nFfamFj]nFfamF[^nF[sF\^nFfamFe[nFgtFe_mF^sF[\nFh_lFjjmF[sF]^nFiwF_^nF
iwFa^nFiwFb^nFiwF'F/F0F6*&F_tF'F_]oF'F'Fi[nFf[n*&FhzF'Fe[lF'F'FbdmFc^nFcdmF]]lF
fdmF\flFhdmFiflFiemFiflF\fmF\flF`fmF\flFffmF]]lFgfmFiflFd^nFf^nFg^nF[_nF\_nFgcm
F`_nFgcmFb_nF[^mFf_nF5Fi_nFe]mFj_nF\flF_`nFh_lFe`nFh`nFi`nFiflF^anF_anF`anFayFa
anFeanFfanFf^nFianFayFjanF[^mF^bnF_bnFabnFiflFbbnFgbnFhbnFe]mF]cnFe]mFbcnFe]mFd
cnFddmFfcnFcblFicnFd\mFjcnFcblF]dnFb`mF_dnFb`mFddnFh_lFjdnFe]mF]enFi^lFaenF[^mF
benFi^lFhenF\flF]fnF[^mFbfnFgfnFhfnF[sF]gnF\fl*,F`evF'F4F5F7F9F/F1F:F9FDFbgnFJ*
,FidvF'F4F5F7F9F/F1F:F9F0FegnFh_lFignFialF]hnF[sFehnF[sFfhnF[sFghnFayFhhnFayFih
nFgtFjhnFayF\inFh_lF]inF[sF^inF[imF_inF[sF`inFiwF'F'*(F3F'F.FY,fnFcinF_qFjjlF`s
F_[mF`[mFc[mFLFi[mFLF]^lFfinFhalF`[mFjalFezF]blF`[mF`blFginFe]lFbbmF^glFcalFg]m
Fa^lFi]mFbbmF\^mFD*&,*Fe_mF_xF\jnFayFf_mF^sF_jnFiwF'F/F0F6FiinF5F^bnFc]lFabnFca
lFhbnF\flF]cnF\flFfcnF[^mF_dnF\flFbjnF\flFhjnF5FjjnFfamF[[oFh_lF_[oFcqF`[oF[sF'
F'6$F+F+,RF6F'*&FAF+F/F1F[\o*(F.F+F4F6F/F8F[\o**F3F'FAF+F=F9F/F<F5*,F3F'F.F+F4F
6F/F1F=F9F5*(F3F+FAF+F]etF'F'*(F3F+F.F+F^^vF'F'*&FAF(F_etF'F'*(FAF+F.F+,,Fh[lF[
[lFi[l#F<FecmFj[lFf[mF[\lFf[mF\\lF[[lF'F'*&F.F(Fb^vF'F'*(F3FEFAF+FietF'F'*(F3FE
F.F+Ff^vF'F'*(F3F'FAF(F[ftF'F'**F3F'FAF+F.F+,XFe_mFf[mFhjmF`\oFb^nFayF]^nFayF_^
nFayFjjmFfamFh]nFa\oFe[nFiwFa]nFa\oFa^nFayFe]nFa\oF`]nFa\oF`\nF[sFb\nFayFg\nFay
F\]nF`\oF[\nF[sFb[nFayFa\nFiwF[^nFfamFj]nFa\oF\^nFa\oFf\nF_ftFberFjuF[fvF`sF_[u
FjuF\dvF`sF'F'*(F3F'F.F(,*Fe_mFhnF\jnFidoFf_mFjxF_jnFayF'F'*(F3F(FAF+FiftF'F'*(
F3F(F.F+,6FifrFchpFe\qFc_vFdfrFd[qFg]qFd_vFgfrF_[qFj`rFbitFefrFa[rF[grF6FhirF`s
FjfrFjuF'F'*(F3F+FAF(F]gtF'F'**F3F+FAF+F.F+,\sF^gpFchpFhgpFa[rF_grF^cqF`grF[^mF
dgrF[^mF\hpF^cqFhgrF[^mFdhpF\flFfhpFchpF[ipFchpFf]tFgcmF[^tF[^mFdfvF`sF\\uFcpF_
ipFd[qF`ipFd[qFgdvFLF^hrFjuF`buFjuFbipFd[qFcipFbhtFeipF`sFgipFchpF\jpFchpF`jpFc
hpF_^tF[^mFd^tF[^mFi^tFa^pFejpFa[qF^dtF^cqF\_tF[^mFfjpFchpFjjpFchpF^[q#FcoF`bnF
`[qFa[rFc[qF`itFf[qFd[qFg[qF^cqFh[qFabrFj[qFchpF]\qFchpF^\qFchpFg\rFfxF`hrFcpFe
fvFLFfaqF[imFd\qFh_nFe\qFiitFghrF[^mFjhrF[^mF]irFgcmFg]q#FbfmF`bnF[^qFfhtF\^qFh
pF]^qFggpFcirF`sF`^qFa[qFb^qF_gtFe^qFjuFb\uFjuF[atFa[qF`jsFa[rFhdvF`sFeirF6F'F'
*(F3F+F.F(,HFjfrFjuFhirF`sFgfrF_[qFe\qFiitFdfrFd[qFiirF[^mF^jrF6F[[rFehpF_jrFgc
mF\grFa[qFdhpFehpFd`sF`sFajrFgcmFejrF^cqFfjrFa[qFg]qF^`vFg[rFiitFhjrFgcmF[[sFju
F'F'*&FAFasF^htF'F'*(FAF(F.F+,XF_btF^_sF[gqF`\qFabtF_jlFdbtF_jlFebtF_jlFfbtF_jl
Fc[sF_jlF_ipF`itF^dtF^cqF^[qF^cqF_aqFgcmF\bqFacqF_bqFgcmFcbqF^cqFdbqFgcmFebuFju
FhbqF`sFjbtF_jlF`dqFgcmFg]qFhfrF[^qF`itFb^qFbitF[]uF`sF_evFju*&FhzF'F_tF'F'Fbcr
F`\qFccrFacqF'F'*(FAF+F.F(,XFc]sF_jlFg]sF_jlF[gqF`\qFj]sF_jlF\^sF_jlF]gvFjuF^^s
F_jlFa^sF_jlFc^sF`sFfhqF^cqF_grF^cqFghqF^cqF^iqFgcmF`iqFgcmFciqFgcmFjctF_jlF`ip
F`itFcipF`itF\bqFacqFg]q#Fb[lF`bnF`^qFbitFa_sF`sF^^rFjuFf[wF'F_`rFgcmFbcrF`\qFc
crFacqF'F'*&F.FasFj`vF'F'F$
